### ISSUE TITLE
GitHub Provider creates repository but returns error

### ISSUE THREAD

**Issue by KylePeterDavies** [integrations/terraform-provider-github#1001]
### Terraform Version
```
Terraform v1.0.7
on darwin_amd64
+ provider registry.terraform.io/gitlabhq/gitlab v3.8.0
+ provider registry.terraform.io/integrations/github v4.18.2
```
### Affected Resource(s)
`github_repository`

.### Terraform Configuration Files
```hcl

module "github_repository" {
  source      = "../github/github_repository"
  name        = "Kyles Repository"
}
```

```hcl 
variable "auto_init" {
  type    = bool
  default = true
}

variable "name" {
  type = string
}
```

```hcl
resource "github_repository" "repository" {
  name                   = var.name
  auto_init              = var.auto_init
}
```

### Debug Output

[Debug Log Output](https://gist.github.com/KylePeterDavies/33bffe007cf247b56f1c5a74eeed1571)

### Expected Behavior
GitHub / Terraform should create a repository without returning an error code.

### Actual Behavior
GitHub returned an error without specifying the error, However, it did create the repository 

```
│ Error: PATCH https://api.github.com/repos/KylePeterDavies/Kyles-Repository: 422 Validation Failed []
 
   with module.github_repository.github_repository.repository,
   on ../github/github_repository/module.tf line 1, in resource "github_repository" "repository":
    1: resource "github_repository" "repository" {

```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:

```bash
terraform init
terraform plan
terraform apply
```

**Comment by omgaz** [comment]
Seems like a duplicate of my long-unanswered issue https://github.com/integrations/terraform-provider-github/issues/850
