### ISSUE TITLE
Add support to Allow specified actors to bypass pull request requirements

### ISSUE THREAD

**Issue by jtyr** [integrations/terraform-provider-github#1005]
The provider is missing option to "Allow specified actors to bypass pull request requirements" in the branch protection rule settings.

```
# Settings -> Branches -> <ProtectionRule> -> Protect matching branches:

|X| Require a pull request before merging
    |X| Allow specified actors to bypass pull request requirements
        <ListOfTeamsOrUsers>
```

**Comment by jtyr** [comment]
There is no support for this in the [google/go-github](https://github.com/google/go-github/blob/master/github/repos.go#L887-L930) package and neither this feature is documented in the official [GitHub REST API](https://docs.github.com/en/rest/reference/repos#update-branch-protection) :disappointed:

**Comment by majormoses** [comment]
It looks like they added support for it in GraphQL API: https://docs.github.com/en/graphql/reference/input-objects#updatebranchprotectionruleinput it looks as if we need to pass `bypassPullRequestActorIds` with an array of ids.

**Comment by jtyr** [comment]
As soon as the [`githubv4`](https://github.com/shurcooL/githubv4) package supports this feature, we will be able to add it into this provider. I guess the author of `githubv4` must regenerate the code from the latest GitHub GraphQL schema.

**Comment by jtv8** [comment]
https://github.com/integrations/terraform-provider-github/pull/1030 is now merged and looks to be available as `pull_request_bypassers` in the provider: https://registry.terraform.io/providers/integrations/github/latest/docs/resources/branch_protection#required-pull-request-reviews

**Comment by chenshap** [comment]
is it planned to be added to github_branch_protection_v3?
https://registry.terraform.io/providers/integrations/github/latest/docs/resources/branch_protection_v3

**Comment by kfcampbell** [comment]
I'm going to close this issue as pull request bypassers are implemented in the non-v3 resource. @chenshap it's still an outstanding need to add this functionality to the v3 version of the resource, though it's still not available in google/go-github. It is, however, exposed in the [REST API](https://docs.github.com/en/rest/branches/branch-protection?apiVersion=2022-11-28#update-pull-request-review-protection). Please feel free to create another issue to track that work if you'd like!
