### ISSUE TITLE
Add support for Dependabot secrets

### ISSUE THREAD

**Issue by gnarea** [integrations/terraform-provider-github#1006]
### Terraform Version

0.14.5

### Affected Resource(s)

None that already exists.

### Expected Behavior

I can create secrets for Dependabot.

### Actual Behavior

I can't create secrets for Dependabot.

### Steps to Reproduce

1. Try to create a secret for Dependabot.

### Important Factoids

These secrets can be set at the organisation- or project-level. I'd need both ideally.

### References

https://github.blog/changelog/2021-11-30-github-actions-workflows-triggered-by-dependabot-receive-dependabot-secrets/

**Comment by kfcampbell** [comment]
This feature would be awesome! It's currently blocked by [lack of API support](https://github.com/dependabot/dependabot-core/issues/3297), but there appears to be a lot of interest in doing so. As soon as the team implements this public API (and either makes it available in `go-github` or `githubv4`), we can pick this up!

**Comment by jurre** [comment]
FWIW this API is now available: https://docs.github.com/en/rest/reference/dependabot

**Comment by liath** [comment]
Working on getting this supported upstream! (Is "upstream" the right term here? Feels a little off)
https://github.com/google/go-github/pull/2248 :D

**Comment by liath** [comment]
The above changes are released in v42.0.0 of https://github.com/google/go-github/pull/2253.

**Comment by hitmands** [comment]
Is there an ETA to provision dependabot secrets via terraform?

https://registry.terraform.io/providers/integrations/github/latest/docs/resources/actions_organization_secret

**Comment by kfcampbell** [comment]
@hitmands There's no specific ETA available. However, this is at the top of my radar after the EMU external groups feature merges (#1094). If you're interested in submitting a PR or reworking the PR started in #1036, please feel free!

**Comment by liath** [comment]
Reworking? There was a merge conflict but it should be ready to go

**Comment by gnarea** [comment]
How does one use the new resource(s)? I don't think it's documented.

**Comment by srgustafson8** [comment]
@gnarea my PR above adding documentation has been merged, so hopefully that helps!
