### ISSUE TITLE
Implement data source to retrieve GitHub apps

### ISSUE THREAD

**Issue by gnarea** [integrations/terraform-provider-github#1009]
### Terraform Version

1.1.0

### Expected Behavior

A data source to retrieve the `node_id` of a GitHub app, so that I can use it in the `github_branch_protection` resource.

### Actual Behavior

There's no such data source. I have to manually query the GitHub API to get the `node_id`; e.g.: https://api.github.com/apps/github-actions

### References

https://github.com/integrations/terraform-provider-github/pull/615#issuecomment-769910688

**Comment by g-chouzadjian** [comment]
I've had a crack here: https://github.com/integrations/terraform-provider-github/pull/1268

**Comment by patrickmarabeas** [comment]
Confirmed by GitHub that private Apps can only be queried by the App itself, and not others.

**Comment by kfcampbell** [comment]
Closing via #1268.
