### ISSUE TITLE
github_repository_environment not working with github app auth

### ISSUE THREAD

**Issue by nitrotm** [integrations/terraform-provider-github#1011]
### Terraform Version
v1.0.4 with github provider v4.18.2

### Affected Resource(s)
- github_repository_environment

### Terraform Configuration Files
```hcl
provider "github" {
  owner = var.github_organisation

  app_auth {
    id              = var.github_app_id
    installation_id = var.github_install_id
    pem_file        = file(var.github_private_key)
  }
}

resource "github_repository_environment" "test" {
   repository  = data.github_repository.test.name
   environment = "test"
}
```

### Debug Output
```
github_repository_environment.test: Creating...
╷
│ Error: PUT https://api.github.com/repos/ORG/test/environments/test: 403 Resource not accessible by integration []
│ 
│   with github_repository_environment.test,
│   on github.tf line 51, in resource "github_repository_environment" "test":
│   51: resource "github_repository_environment" "test" {

```

### Expected Behavior
We expect the environment to be created.

### Actual Behavior
The API forbid this request (probably due to github oAuth scope issue?). We checked and gave proper permissions to the org application and the organization is an enterprise account.

### Steps to Reproduce
1. `terraform apply`

### Notes
It seems possible to request specific permissions while requesting an oAuth access token:
https://docs.github.com/en/rest/reference/apps#create-an-installation-access-token-for-an-app

Should `environments` be explicitly requested for this request to succeed?

**Comment by Satak** [comment]
We are having the same issue. I'm running this from Terraform cloud and I have set all environment variables via variable set:
```
GITHUB_APP_ID
GITHUB_APP_INSTALLATION_ID
GITHUB_APP_PEM_FILE (this is single string where new lines replace by \n)
GITHUB_OWNER
```

```terraform
terraform {
  cloud {
    organization = "our-tf-cloud-org"

    workspaces {
      name = "our-workspace-name"
    }
  }

  required_providers {
    github = {
      source  = "integrations/github"
      version = "~> 4"
    }
  }
}

provider "github" {
  app_auth {}
}

data "github_repository" "repo" {
  name = "our-private-repository-name"
}

output "repo_node_id" {
  value = data.github_repository.repo.node_id
}
```

error:
```
GET https://api.github.com/repos/<org>/<repo-name>/branches: 403 Resource not accessible by integration []
```
