### ISSUE TITLE
[Feature Request] Add user to an organisation as outside collaborator

### ISSUE THREAD

**Issue by dgteixeira** [integrations/terraform-provider-github#1015]
##Description

Would be great to improve the existent `github_membership` resource and add `external` to the possible list of roles.

Link to GitHub documentation: [GitHub API Outside Collaborator](https://docs.github.com/en/rest/reference/orgs#convert-an-organization-member-to-outside-collaborator).

### Terraform Version
`➜ tf version
Terraform v1.1.0
on linux_amd64
+ provider registry.terraform.io/integrations/github v4.19.0`

### Affected Resource(s)
Please list the resources as a list, for example:
- github_membership

Documentation: https://registry.terraform.io/providers/integrations/github/latest/docs/data-sources/membership

### Possible declaration
```
resource "github_membership" "external" {
  username = "dgteixeira"
  role     = "external"
}
```

### Possible access to data

These users could be accessed if the issue #1014 could be implemented.

**Comment by thazelart** [comment]
👋 Hey,

I think this should be prioritized. 

Best,
