### ISSUE TITLE
[Feature request] Drift detection github_repository_collaborator

### ISSUE THREAD

**Issue by Esysc** [integrations/terraform-provider-github#1018]
### Terraform Version
Terraform v1.0.11
on linux_amd64
+ provider registry.terraform.io/integrations/github v4.19.0

### Context
We are managing hundreds of repositories and for each of them Terraform configuration describes the list of "collaborators" with relative permissions. It turns out that if a new collaborator is added out of band, Terraform doesn't detect the drift, simply because cannot know what is not in his state. This is a potential security problem, since the out of band operation would grant read/write (or more: admin) access to untracked entities. 

### Expected Behavior
`terraform plan` should propose to destroy the unknown entity , leaving the choice to the user to update the configuration and import the new resource or destroy. 

### Actual Behavior
Terraform plan is no-ops

### Steps to Reproduce
1. Assuming `terraform plan` is no-ops for repo A
2. Go in GitHub UI and add 1 or more collaborators for repo A
3. Run `terraform plan`
4. Result is no-ops

### Proposal
The provider can already retrieve a collection of collaborators https://registry.terraform.io/providers/integrations/github/4.13.0/docs/data-sources/collaborators. Having the real lists, it could compare with the configuration and finally detect the drift.

### Possible Duplicates
- #979

**Comment by aliculPix4D** [comment]
@jcudit I am a coworker of @Esysc and we are considering in our team to contribute a PR for this issue. Would you be interested?

**Comment by kfcampbell** [comment]
@aliculPix4D @Esysc I'd definitely be receptive of a PR, but would probably prefer doing an additive change in the form of a new resource like the difference between github/resource_github_team_members.go and github/resource_github_team_membership.go. Thoughts?

**Comment by odormond** [comment]
This is related to #1060 and a PR for authoritative repository collaborators is available: https://github.com/integrations/terraform-provider-github/pull/1121

**Comment by Esysc** [comment]
Closing, since https://github.com/integrations/terraform-provider-github/releases/tag/v5.20.0 the issue has been addressed.
