### ISSUE TITLE
List repository tags

### ISSUE THREAD

**Issue by CyberShadow** [integrations/terraform-provider-github#1021]
There is a way to list repository branches (`github_repository.name.branches`), but there doesn't seem to be an equivalent for tags.

More generally perhaps [listing refs](https://docs.github.com/en/rest/reference/git#list-matching-references) would be better.

**Comment by CyberShadow** [comment]
I cannot add labels.

**Comment by armantur** [comment]
This feature is much needed. Maybe there is an existing way to fetch all tags from the repository?
