### ISSUE TITLE
github_repository_environment causes provider to panic

### ISSUE THREAD

**Issue by iwarapter** [integrations/terraform-provider-github#1025]
### Terraform Version

```
terraform version
Terraform v1.1.2
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.70.0
+ provider registry.terraform.io/integrations/github v4.19.1
```
(Also tested with v4.19.0)

### Affected Resource(s)

- `github_repository_environment`

### Terraform Configuration Files
```hcl
resource "github_repository_environment" "apply" {
  environment  = "apply"
  repository   = github_repository.this.name
  reviewers {
    teams = [data.github_team.aws_core_infra.id]
  }
  deployment_branch_policy {
    protected_branches     = true
    custom_branch_policies = false
  }
}
```

### Debug Output
Please provide a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output

https://gist.github.com/iwarapter/559140ddc7b4d89ca9959af521ceb822

### Expected Behavior

Resource is created.

### Actual Behavior

Resource is created, state is left incorrect provider dies.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by iwarapter** [comment]
This is caused by the error handling - https://github.com/integrations/terraform-provider-github/blob/main/github/resource_github_repository_environment.go#L115

I was getting  `403 Resource not accessible by integration []` error but the current implementation ONLY handles a single error type, resulting in the nil panic when `env` is `nil`

**Comment by iwarapter** [comment]
Im using a github app auth with permissions r/w on both environments and deployments - https://docs.github.com/en/rest/reference/deployments#get-an-environment and its covered by the docs, interestingly PUT works not GET

**Comment by grelland** [comment]
Any progress on this? Currently running into this on `4.28.0`, using app_auth and a `read/write` scope on repos - the workaround of limiting to `read` scope is not a proper solution as I'm relying on being able to do `PUT` as well.

**Comment by kurianoff** [comment]
There is another issue that exists on the same topic #1146 

The advice provided by user @courentin helped resolve the issue in my case. Here is what he's [saying](https://github.com/integrations/terraform-provider-github/issues/1146#issuecomment-1143393054): "...on my side granting a read-only permission on repository Actions to my Github app fixed the issue".

**Comment by kfcampbell** [comment]
I like that workaround, and thanks for making the connection! It would be better if the provider handled the error more gracefully and didn't panic as well.

**Comment by nexocentric** [comment]
I am currently dealing with the same issue. I don't understand what is meant by granting a read-only permission on repository Actions? Where do I set this?

**Comment by nexocentric** [comment]
Right now, the thing that I'm not understanding is, the plugin seems to work, and then it dies right in the middle before going on to other steps.
