### ISSUE TITLE
resource "github_team_sync_group_mapping" getting the error "403 This team is not externally managed"

### ISSUE THREAD

**Issue by DaveKLloyd** [integrations/terraform-provider-github#1041]
### Terraform Version
We are using Terraform Cloud v1.1.3 I have also tested and got the same result running locally on v1.0.6

### Affected Resource(s)
Please list the resources as a list, for example:
- github_team_sync_group_mapping

### Terraform Configuration Files
```provider "registry.terraform.io/integrations/github" {
  version     = "4.14.0"
  constraints = "4.14.0"
  hashes = [
    "h1:8WTbHPIb7hzfNgZv72piPkpPB8zX3mfJHZdCAPnij8k=",
    "zh:1c675ce700c0ebfc7ef437443fb25f912a62717b7bca60071bf9733d23db9576",
    "zh:242362cc1b4932b80333f3f9b4dab6edfc84fd4cb9811bad81872939cf088b5a",
    "zh:25bc76d0e8cce0b8bcee45a88810d655e1253c9001533b087f57fd223dc4881c",
    "zh:3bce5f98e087796866ade17cfaa8b3f70018b53e8cff3cae32dac0a910d060a8",
    "zh:3dda969761bb60c1721dac6901450be08b2d7501eda21146ba9dc172fcc05723",
    "zh:5bf6b85ce208a113b54d70b973f81e7c7a7ea9a3f6d2b30eaa41ea641333ab25",
    "zh:81b75b38332affb15bc9004c8c6aa746595b0879f779c4886899aef3db434645",
    "zh:8a2310d85ecd60c079ec2db14ed338296f83b77857ae68e48b1a7a8a946a260c",
    "zh:a9f1d55cee031c883ead6420896225806fda239374d730ed2d7446bee3224564",
    "zh:caa1cf690c4e208847b026071567a7ee8b2e55dbc75649e7de393b5502a2418b",
    "zh:e4a077b84a01d3c50ab0de1eb70122912c340f89be995177fb4ab0635f11527e",
    "zh:e9e40b34915e1cfae711218976f398e3dae5c96682516dab870fc97e8048f416",
    "zh:fadf11408f16ddf1605419a357ac53cf2dde6cc769757eacc9ae804a21c8d71e",
  ]
}
```

### Expected Behavior
The GitHub Team should have been mapped to the AAD Group. 

### Actual Behavior
We get this error
```
Error: PATCH https://api.github.com/orgs/********/teams/test/team-sync/group-mappings: 403 This team is not externally managed. Learn more at https://docs.github.com/articles/synchronizing-teams-between-your-identity-provider-and-github []
│
│   with github_team_sync_group_mapping.example_group_mapping,
│   on Team.tf line 9, in resource "github_team_sync_group_mapping" "example_group_mapping":
│    9: resource "github_team_sync_group_mapping" "example_group_mapping" {
```

### Steps to Reproduce
```
#Run this against a Github Enterprise with EMU enabled. 

resource "github_team" "team" {
  name        = "test"
  description = "Test Team"
  privacy     = "closed"
}

resource "github_team_sync_group_mapping" "example_group_mapping" {
  team_slug        = github_team.team.slug
  group {
        group_id          = "<AAD Group ID>"
        group_name        = "<AAD Group Name>"
        group_description = ""
        }
 }
```

### Important Factoids
This is running on GitHub Enterprise with Enterprise Standard Users enabled.

**Comment by DaveKLloyd** [comment]
After further investigation. It seems github_team_sync_group_mapping does not work for EMU enabled Enterprises. This would be using this [Create or update IdP group connections](https://docs.github.com/en/enterprise-cloud@latest/rest/reference/teams#create-or-update-idp-group-connections)

I was able to do what I needed using the API call [/orgs/{org}/teams/{team_slug}/external-groups](https://docs.github.com/en/enterprise-cloud@latest/rest/reference/teams#update-the-connection-between-an-external-group-and-a-team)

However this does not seem to be supported in the GitHub Provider for Terraform.

**Comment by malirezai** [comment]
Hi @DaveKLloyd 

Thanks for the update here. 

So to confirm - are you also using Terraform to create the actual TEAM on the GitHub side too? Or just to create the group mapping to the IDP group?

**Comment by malirezai** [comment]
Hi @DaveKLloyd 

So - team sync is **intentionally not supposed to work with EMUs**. The IdP groups are provisioned through **group SCIM** and there is the separate API that you use to access and add them to the team. 

The only parst of the terraform provider that won't work are the Team sync and user provisioning ones, as its supposed to be run out of the IDP.

**Comment by DaveKLloyd** [comment]
@malirezai we are using terraform to create the GitHub Team and AAD group.

We would like to also do the mapping between them. 

Dave

**Comment by malirezai** [comment]
@DaveKLloyd is that not possible with the API you have identified then, under PATCH? 

https://docs.github.com/en/enterprise-cloud@latest/rest/reference/teams#update-the-connection-between-an-external-group-and-a-team

**Comment by DaveKLloyd** [comment]
@malirezai yes it is. But then it's nice to managed by Terraform. It would not be stored in Terraform state.

Dave

**Comment by kfcampbell** [comment]
@jcudit and I talked about this a little bit today! We believe we would want to offer a new resource (to allow compatibilty with the existing (deprecated?) team-sync functionality) that wraps [this GitHub EMU API](https://docs.github.com/en/enterprise-cloud@latest/rest/reference/teams#external-groups). This functionality is present in the `go-github` library in a version that's already imported into the Terraform provider project. Implementation of such a feature is unblocked.

**Comment by malirezai** [comment]
@kfcampbell fantastic! The API is not deprecated, just not used for GitHub EMU Enterprises. GitHub EMU Enterprises use group SCIM and not the team sync functionality, they work in different ways.

**Comment by kfcampbell** [comment]
@AlexandreODelisle I'm working on it! The PR is [here](https://github.com/integrations/terraform-provider-github/pull/1094) right now if you'd like to follow along.

**Comment by malirezai** [comment]
@DaveKLloyd ^^ fyi 😀

**Comment by bryantson** [comment]
Awesome job :D

**Comment by juanmiguelRuaDev** [comment]
Thank you very much @kfcampbell
