### ISSUE TITLE
[Feature request] Allow for retrieving latest release marked "prerelease"

### ISSUE THREAD

**Issue by youcandanch** [integrations/terraform-provider-github#1050]
### Description
Being able to retrieve the latest release from a given repository is awesome, but there's circumstances in which it'd be beneficial to grab the latest *prerelease*. In a continuous deployment workflow where there's a "prerelease" like environment (staging, preproduction, prerelease, rc, etc.) it'd be great to be able to pull the tag information directly from the provider, rather than having to skip out to the API to do it. 

### Terraform Version
Terraform v1.1.4 on linux_amd64
registry.terraform.io/integrations/github ~> 4.0

### Affected Resource(s)
Please list the resources as a list, for example:
- github_release

### Possible declaration
```terraform
resource "github_release" "latest_prerelease" {
    prerelease = "true"
    owner = "integrations"
    repository = "terraform-provider-github"
    retrieve_by = "latest"
}
```

I realize this might be a bit of a hassle, because the API itself doesn't expose a prerelease flag, which means one would have to list through all the releases in a given repository and selectively pluck out the prereleases, then do the datetime comparison to grab the latest. There's similar code in Hub for the filtering aspect that could serve as inspiration.

If this is something that y'all would be interested in, I'd be happy to take a stab at it!

**Comment by youcandanch** [comment]
Started this in https://github.com/integrations/terraform-provider-github/pull/1066.

**Comment by rotilho** [comment]
Not sure if it's possible but It would be also nice to have a way to get the latest tag regex instead of introduce a new retrieve type.

In this way we are able to support many more use cases.

**Comment by aluxian** [comment]
+1, this would be super useful for us at https://proptee.io/

We rely on terraform and GitHub releases for CI/CD. The workflow is:
1. push commits / merge PRs
2. create a new GitHub release targeting the commit we want to release
3. apply terraform project -> this retrieves the latest release and updates a K8s deployment

At the moment, step 3 works only for prod releases. Being able to retrieve the latest pre-release would make adding a test environment super easy for us.
