### ISSUE TITLE
[Feature request] Manage repository collaborators in a single resource

### ISSUE THREAD

**Issue by m-adawi** [integrations/terraform-provider-github#1060]
Hi everyone.

I have been using this provider for a while and I had this problem. The problem is that I can't manage all repo collaborators in a single resource. Which means, if someone adds a collaborator to a repo using GitHub's interface, terraform won't detect the remote changes because no resources have actually changed. 

The current repository collaborator resource looks like this:
```hcl
resource "github_repository_collaborator" "a_repo_collaborator" {
  repository = "our-cool-repo"
  username   = "SomeUser"
  permission = "admin"
}
```  

I think it would be great if there was a resource to manage all repository collaborators like this:

```hcl
resource "github_repository_collaborators" "repo_collaborators" {
  repository = "our-cool-repo"
  collaborator {
    username   = "SomeUser"
    permission = "admin"
  }
  collaborator {
    username   = "AnotherUser"
    permission = "push"
  }
 .
 .
 .
}
```

This will enable us to manage all of the collaborators in single place and if someone goes to GitHub and manually adds a collaborator using the web interface, the next terraform plan command will show that remote changes occurred which will enable us to override the changes or add them to code.

Same goes for these resources (and maybe others):
- github_membership
- github_team_repository

**Comment by foosinn** [comment]
Can you please add the label? For us the terraform module is useless since execution is very slow (>10 minutes)

**Comment by kfcampbell** [comment]
We have prior art for authoritative resources as described in the issue body, like [this one](https://github.com/integrations/terraform-provider-github/blob/main/github/resource_github_team_members.go) for team memberships. 

If anyone is interested in opening up a PR for this, I'd be happy to review it!

**Comment by odormond** [comment]
Apparently there is already a PR open to implement authoritative repository collaborators: https://github.com/integrations/terraform-provider-github/pull/1121

**Comment by pascal-hofmann** [comment]
This issue can be closed. There is `github_repository_collaborators` now.
