### ISSUE TITLE
[Feature Request] Support Github Organization "Member Privileges"

### ISSUE THREAD

**Issue by danielpops** [integrations/terraform-provider-github#1062]
Doesn't look like the provider supports organization-level member privileges, like the ability to fork private repositories.

![image](https://user-images.githubusercontent.com/10519220/153507913-c517f488-e47b-4c43-b2a9-7028b1ce9283.png)

I would like to manage these configuration options with the provider rather than the status quo of clicking around in the UI and hoping I did everything correctly :)

**Comment by lucas-bsq** [comment]
Any chance of reopening this issue?
