### ISSUE TITLE
[Feature Request] Orgainzation Invitation

### ISSUE THREAD

**Issue by j3ffrw** [integrations/terraform-provider-github#1065]
Hi, I'd to request to add support for organization invitation, specifically using email to send the invitation.
https://docs.github.com/en/rest/reference/orgs#create-an-organization-invitation

**Comment by batizar** [comment]
This would be very helpful as not everybody in our org already has GitHub account and we could invite them with their email first similar to how it works on GitHub.

**Comment by joerg** [comment]
Another use case are enterprises where you know their enterprise EMail address but users can link that to their personal github username. Not knowing their username to be but only their EMail requires us currently to invite them.
