### ISSUE TITLE
[Feature Request] GitHub Custom Repository Role resource

### ISSUE THREAD

**Issue by batizar** [integrations/terraform-provider-github#1069]
Hi,
I'd like to request the resource for creating custom repository roles.

https://docs.github.com/en/enterprise-cloud@latest/organizations/managing-peoples-access-to-your-organization-with-roles/managing-custom-repository-roles-for-an-organization

Thanks

**Comment by josh-symplr** [comment]
or the ability as well to reference custom repository roles in team permissions with `github_team_repository`

https://registry.terraform.io/providers/integrations/github/latest/docs/resources/team_repository

**Comment by josh-symplr** [comment]
seems to me its more of an 'issue' as you are limited in the `github_team_repository` to use only the 'off the shelf' roles that are given.   Once custom roles created (and they are needed, in order to give the right access to teams for 'security alerts'), you cannot manage this in terraform anymore.

**Comment by dgteixeira** [comment]
Hello all, how are you? :)

Any update on this topic? 

Thanks!

**Comment by joshuahancox** [comment]
I raised a PR here, based on another - could anyone help in getting this reviewed/merged? 😃

https://github.com/integrations/terraform-provider-github/pull/1113

**Comment by fproulx-boostsecurity** [comment]
Any updates on this...

**Comment by kfcampbell** [comment]
Our team's attention has been focused elsewhere unfortunately. We are very encouraging of PR submissions though!

**Comment by cailen** [comment]
I submitted a PR to add this resource and data source.
