### ISSUE TITLE
[Pull Requests] less `Always suggest updating pull request branches` avariable for the repository.

### ISSUE THREAD

**Issue by sungaohui** [integrations/terraform-provider-github#1072]
Hi,
I'd like to request the resource for github-repository less  `Always suggest updating pull request branches`.
https://docs.github.com/en/enterprise-cloud@latest/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-suggestions-to-update-pull-request-branches

### Terraform Version
The latest version
### Affected Resource(s)
- resource_github_repository

**Comment by pmjacinto** [comment]
Also interested in having this.

It doesn't seem to be documented yet, but there is an `allow_update_branch` field in the REST Repo API.

`gh api -X PATCH --raw-field allow_update_branch=true repos/my-org/my-repo`

**Comment by strantalis** [comment]
I was looking for the ability to set this the other day so I opened up a pull request to add it but it needs to wait on #1138 as that is when the feature was added.
