### ISSUE TITLE
Support for team icons

### ISSUE THREAD

**Issue by nikolay** [integrations/terraform-provider-github#1073]
It would be *really* nice if we can programmatically set/update/remove the team's icon.

**Comment by kfcampbell** [comment]
@nikolay I don't believe this is possible until it's supported by the API. It's not supported in the [Teams REST API](https://docs.github.com/en/rest/teams/teams?apiVersion=2022-11-28) spec and I don't believe it's supported by GraphQL either, unfortunately.
