### ISSUE TITLE
Can't create labels for organisation repos

### ISSUE THREAD

**Issue by rikkit** [integrations/terraform-provider-github#1075]
### Terraform Version
1.0

Provider version 4.2.0

### Affected Resource(s)

- github.github_issue_label

### Terraform Configuration Files
```hcl
variable "token" {
}

provider "github" {
  token = var.token
}

data "github_repository" "ui" {
  full_name = "travellocal/ui"
}

locals {
  repos = [
    data.github_repository.ui,
  ]

  repo_names = toset([for repo in local.repos : repo.full_name])
}

resource "github_issue_label" "bug" {
  for_each   = local.repo_names
  repository = each.key
  name       = "bug"
  color      = "cc0000"
}

```

### Debug Output
Sorry,  we use a wrapper script that makes it diffcult to get debug output. Here is the api call that fails when running `terraform apply`.

```
╷
│ Error: POST https://api.github.com/repos/rikkit/travellocal/ui/labels: 404 Not Found []
│
│   with module.github.github_issue_label.bug,
│   on modules/github/labels.tf line 3, in resource "github_issue_label" "bug":
│    3: resource "github_issue_label" "bug" {
│
╵
```

### Expected Behavior

The `bug` label is created in the `travellocal/ui` repo. (the API call should be to `https://api.github.com/repos/travellocal/ui/labels`)

### Actual Behavior

The repo string `travellocal/ui` isn't parsed and an API call is made using the owner of the personal access token. 

### Steps to Reproduce

1. `terraform apply`

### Important Factoids
n/a

### References

This seems like the relevant bit of code:

https://github.com/integrations/terraform-provider-github/blob/main/github/resource_github_issue_label.go#L62-L65

**Comment by amy-hashi** [comment]
You need to set the owner either in your provider block or in your environment variables (GITHUB_OWNER).

**Comment by rikkit** [comment]
Hi @amy-hashi, thanks for the pointer. I tried it out and the URL is still not being built properly. 

I added the `owner` property to as follows

```
provider "github" {
  token = var.token
  owner = "travellocal"
}
```

And I still get this error. As you can see `travellocal/travellocal/ui` is used.

```
╷
│ Error: POST https://api.github.com/repos/travellocal/travellocal/ui/labels: 404 Not Found []
│
│   with module.github.github_issue_label.from_support["travellocal/ui"],
│   on modules/github/labels.tf line 38, in resource "github_issue_label" "from_support":
│   38: resource "github_issue_label" "from_support" {
│
╵
```

I switched my config from `full_name` to `name` 

```
data "github_repository" "ui" {
  name = "ui"
}
```

And the same error is generated - 

```
╷
│ Error: POST https://api.github.com/repos/travellocal/travellocal/ui/labels: 404 Not Found []
│
│   with module.github.github_issue_label.from_support["travellocal/ui"],
│   on modules/github/labels.tf line 38, in resource "github_issue_label" "from_support":
│   38: resource "github_issue_label" "from_support" {
│
╵
``` 

As you can see `travellocal/travellocal/ui` is still used.

**Comment by rikkit** [comment]
Not stale
