### ISSUE TITLE
Add support to allow specifying who can force push for branch protection rules

### ISSUE THREAD

**Issue by evgeny-myasishchev** [integrations/terraform-provider-github#1085]
As of now github_branch_protection  resources doesn't allow specifying option below:

`Allow force pushes` => `Specify who can force push` => [list of people or teams]

The graphql API seems to already have a support for this property: https://docs.github.com/en/graphql/reference/objects#branchprotectionrule

**Comment by kfcampbell** [comment]
Hmm...this seems somewhat popular based upon the number of reactions to the issue. Perhaps it's worth keeping around.

**Comment by apujari-hippo** [comment]
Do we have an ETA on when it will be merged?
