### ISSUE TITLE
[Feature Request] Grant single GitHub user permission to GitHub repository

### ISSUE THREAD

**Issue by EricCrosson** [integrations/terraform-provider-github#1088]
### Current Version

```
4.20.1
```

### Use-cases

I'm trying to grant myself (a single GitHub user) access to a GitHub repository whose visibility is `private`. In the past I've used [github_team_repository](https://registry.terraform.io/providers/integrations/github/latest/docs/resources/team_repository) to grant a GitHub _team_ access to a GitHub repository, but I can't find the analogous way to grant access to a single user.

### Attempted Solutions

I could make a one-man GitHub team and grant that team access to the GitHub repository, but that seems suboptimal.

### Proposal

If I'm not overlooking something that already exists, we could make use of a `github_user_repository` resource. It could take the user's id, repository, and permission, just like the `github_team_repository` does.

### References

This section intentionally left blank.

**Comment by HorizonNet** [comment]
Could it be that you're looking for [github_repository_collaborator](https://registry.terraform.io/providers/integrations/github/latest/docs/resources/repository_collaborator)? There you're granting a specific set of permissions to a given user to a given repository.

**Comment by EricCrosson** [comment]
That's exactly what I'm looking for. Many thanks, @HorizonNet!
