### ISSUE TITLE
Error: Field 'bypassPullRequestAllowances' doesn't exist on type 'BranchProtectionRule'

### ISSUE THREAD

**Issue by djaboxx** [integrations/terraform-provider-github#1090]
### Terraform Version
0.14.7

### Affected Resource(s)
Please list the resources as a list, for example:
- github_branch_protection

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl

# https://registry.terraform.io/providers/integrations/github/latest/docs/resources/branch_protection
resource "github_branch_protection" "main" {
  count             = var.github_create_repo ? 1 : 0
  enforce_admins    = var.github_enforce_admins_branch_protection
  pattern           = data.github_repository.repo_lookup.default_branch
  push_restrictions = []
  repository_id     = github_repository.repo[0].node_id
  required_pull_request_reviews {
    dismiss_stale_reviews           = var.github_dismiss_stale_reviews
    require_code_owner_reviews      = var.github_require_code_owner_reviews
    required_approving_review_count = var.github_required_approving_review_count
  }
  required_status_checks {
    contexts = [
      "Terraform Enterprise/${var.organization}/${var.name}",
      "sentinel/${var.organization}/${var.name}"
    ]
    strict = true
  }
  depends_on = [
    # first let the automation create the codeowners and backend file then only create branch protection rule
    # if branch protection rule is created first, codeowners will fail
    github_repository_file.codeowners,
    github_repository_file.backend
  ]
}

```

### Debug Output
Please provide a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
This configuration was working properly, prior to latest version of provider. We are using on-prem TFE. 

### Actual Behavior
What actually happened?
Error: Field 'bypassPullRequestAllowances' doesn't exist on type 'BranchProtectionRule'

**Comment by carocad** [comment]
From what I can this was introduced in v4.21.0 with this PR: https://github.com/integrations/terraform-provider-github/pull/1030

**Comment by carocad** [comment]
@djaboxx are you also using Github Enterprise? My guess is that the GraphQL schema on our instances doesnt include that field but public github does 😞

**Comment by kfcampbell** [comment]
What version of GitHub Enterprise are you using? In the meantime, can you use [v4.20.1](https://github.com/integrations/terraform-provider-github/releases/tag/v4.20.1) as a workaround?

**Comment by carocad** [comment]
> GitHub Enterprise Server 3.2.10

**Comment by alexbde** [comment]
I can confirm this issue exists with GHES 3.2.10 and is resolved downgrading to provider v4.20.1.

**Comment by reedloden** [comment]
https://studio.apollographql.com/public/github/changelog/version/1a2df624-a755-40b1-905a-aab34e4fb9ad?variant=current

You need GHES 3.4.0 for this feature, as per https://docs.github.com/en/enterprise-server@3.4/admin/release-notes#3.4.0

**Comment by djaboxx** [comment]
When will a fix be provided for this issue?

**Comment by kfcampbell** [comment]
@djaboxx I can't offer a specific date that we could implement something to work around this, but we're always encouraging of contributions if you'd like to submit! Perhaps we could implement a `GHES_VERSION` environment variable that could be checked before constructing the GraphQL query.

**Comment by djaboxx** [comment]
Will this provider ever work with Github Enterprise again?
