### ISSUE TITLE
github_repository_file issue with orphaned file

### ISSUE THREAD

**Issue by bmurray3** [integrations/terraform-provider-github#1091]
### Terraform Version
Terraform version is 1.0.1.
Github provider version is 4.16.0.

### Affected Resource(s)
- github_repository_file

### Terraform Configuration Files
```hcl
resource "github_repository_file" "managed_files_one_time" {
  depends_on          = [github_branch.tenant_workspace_branch_dev]
  for_each            = fileset("${path.module}/github-files-no-override", "**")
  repository          = github_repository.terraform_workspace_repository.name
  branch              = "dev"
  file                = replace(each.value, ".tpl", "")
  content             = file("${path.module}/github-files-no-override/${each.value}")
  commit_message      = "Managed by Terraform"
  overwrite_on_create = true
  lifecycle {
    ignore_changes = [
      file, content, commit_message, commit_author, commit_email,
    ]
  }
}
```

### Debug Output
https://gist.github.com/bmurray3/3738566450e5868940a7a71ff2c1f062

### Expected Behavior
Based on lifecycle, content changes once the file is created should be ignored. 

### Actual Behavior
When the file is modified by another commit, subsequent runs will either delete or create the file again, even when the terraform runs were the creators of the file on a previous run. Each run will switch between creating or deleting the file based on its existence.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Stage files to be created.
2. `terraform apply`
3. modify staged file outside terraform
4. `terraform apply`
5. `terraform plan`
6. review plan

### Important Factoids
Not all modified files outside terraform exhibit this behavior. It is unclear why the .gitignore file is being marked as an orphan, which triggers this switch from create / delete / create / delete / etc.

**Comment by bmurray3** [comment]
Is there anything else I can provide to help with this issue?

**Comment by ghostsquad** [comment]
Why are you using `overwrite_on_create = true`?

**Comment by bmurray3** [comment]
The script is part of a project builder, and not every repository was started with an empty shell. At this point it is not necessary, and we removed overwrite_on_create attribute but it had no effect.

**Comment by amexboy** [comment]
@bmurray3 Were you able to find a good solution? I am facing a similar issue where if we delete the branch (after merging the PR) the state will be left unstable

**Comment by bmurray3** [comment]
@amexboy Unfortunately we have not had any success with using this resource in a stable manner, and are now looking at alternatives which do not include the github provider. 
We added sha and commit_sha to the lifecycle changes as well, there is nothing in state file to indicate why it is triggering these delete and recreate events.

**Comment by ghostsquad** [comment]
It feels as though the terraform "abstraction" is not well suited for something like a file or commit.
