### ISSUE TITLE
Error: This resource can only be used in the context of an organization, "" is a user.

### ISSUE THREAD

**Issue by te-ak** [integrations/terraform-provider-github#1100]
### Terraform Version
idk but it is running through atlantis

### Affected Resource(s)
- github_team

### Terraform Configuration Files
```
terraform {
  required_providers {
    github = {
      source  = "integrations/github"
      version = "~> 4.0"
    }
  }
}
provider "github" {
    owner = orgname
    token    = data.aws_s3_object.github_token.body
}
```

### Expected Behavior
Terraform should print that it is not going to use an org for the request. Or maybe it can still try to use the owner, since that was defined. Then maybe there would be an API request error on the apply step and you can troubleshoot this better.

### Actual Behavior
Terraform gave me this error: "Error: This resource can only be used in the context of an organization, "" is a user."
My tf code was fine, but what actually happened was I had the wrong mime-type set in my S3 bucket. After setting the bucket to plain text I was able to apply my plan.

### Steps to Reproduce
1. `terraform plan`

**Comment by kroussou** [comment]
I've got similar error message when github token has expired. So I guess this is rather misleading error message for authentication failure

**Comment by monstermp87** [comment]
Thanks @kroussou , It was the same issue for me about authentication. I was using IDE Terminal and had to again export GITHUB_TOKEN= **** on that terminal session to get it worked. The error is for sure misleading.

**Comment by devops-corgi** [comment]
I'm running into this issue when I use a PAT.  I have the token set as an environment variable (both local and in CI), though for different users.

If I set GITHUB_OWNER environment variable, it works.  But if I just pass in via Terraform provider, it doesn't.

IE, this fails.

```
provider "github" {
  owner = "tractionguest"
}
```

If I `export GITHUB_OWNER=octocat`, it works.
