### ISSUE TITLE
Main not Master

### ISSUE THREAD

**Issue by wellingk** [integrations/terraform-provider-github#1101]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
-14.6

### Affected Resource(s)
Please list the resources as a list, for example:
github_repository

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```
resource "github_repository" "repo" {
  name        = "repo-name"
  description = "repo description"
  visibility  = "private"
}
```

### Debug Output
N/a

### Panic Output
N/a

### Expected Behavior
repo created with 1 branch called main

### Actual Behavior
repo created with 1 branch called master

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply` 

### Important Factoids
N/a

### References
If you create a branch in the console the default branch name by defulat is main to remove any offence caused by using master.  Please can this be resolved.

**Comment by kroussou** [comment]
Default branch name is defined in user or organization settings ([ref](https://github.blog/changelog/2020-10-01-the-default-branch-for-newly-created-repositories-is-now-main/)). IMHO your issue is not related to `github_repository` resource.
