### ISSUE TITLE
[Feature Request] GitHub Advanced Security

### ISSUE THREAD

**Issue by tjcorr** [integrations/terraform-provider-github#1104]
Support for GitHub Advanced Security and Secret Scanning. 

The current repository resource does not support the parameter: `security_and_analysis` which is used to enable both GHAS and secret scanning on a repository:

> Specify which security and analysis features to enable or disable. For example, to enable GitHub Advanced Security, use this data in the body of the PATCH request: {"security_and_analysis": {"advanced_security": {"status": "enabled"}}}. If you have admin permissions for a private repository covered by an Advanced Security license, you can check which security and analysis features are currently enabled by using a GET /repos/{owner}/{repo} request.

This parameter is already supported in the go library with https://github.com/google/go-github/issues/2132 .

**Comment by cfisher281** [comment]
+1
I could use this now.

**Comment by skumarnara** [comment]
BUMP..........

**Comment by andrew-lethbridge-vgh** [comment]
Could also really use this.

**Comment by jwfh** [comment]
This would be a useful feature.

**Comment by Dilfer** [comment]
Would really like this feature. Right now our repo creation process is not fully automatable without this change to the provider.

**Comment by kuhlman-labs** [comment]
https://github.com/integrations/terraform-provider-github/pull/1298 allows us to set the GHAS settings on an org level. I will investigate how to implement this at the repo level.

**Comment by kuhlman-labs** [comment]
There was an additional field added to the Security and Analysis block to configure secret scanning push protection. I have a PR open https://github.com/google/go-github/pull/2476 to add the field and then I can configure the repository resource.

**Comment by kuhlman-labs** [comment]
PR has been submitted:
https://github.com/integrations/terraform-provider-github/pull/1304

**Comment by Luis-3M** [comment]
Looking forward to this one 🚀

**Comment by kuhlman-labs** [comment]
This feature has been merged, @kfcampbell this Issue can be closed.
