### ISSUE TITLE
[Bug] Omitting optional members argument for github_team_members produces error

### ISSUE THREAD

**Issue by kroussou** [integrations/terraform-provider-github#1105]
According to the docs `members` argument is optional but in fact it is not.
Given the purpose of `github_team_members` resource to manage team membership explicitly there should be the way to ensure that managed team has no members. 

### Terraform Version
```
Terraform v1.1.7
on darwin_amd64
+ provider registry.terraform.io/integrations/github v4.23.0
```

### Affected Resource(s)
- github_team_members

### Terraform Configuration Files
```hcl
resource github_team "empty" {
    name = "empty"
}

resource github_team_members "empty" {
    team_id = github_team.empty.id
}
```

### Expected Behavior
Empty team created.

### Actual Behavior
```
│ Error: Insufficient members blocks
│
│   on bug.tf line 14, in resource "github_team_members" "empty":
│   14: resource github_team_members "empty" {
│
│ At least 1 "members" blocks are required.
```

### Steps to Reproduce
1. `terraform apply`

**Comment by stawik-mesa** [comment]
@kroussou I think this is a bug or wrong documented. I haven't thought about having a team without members, so I added a check to verify that at least one members block must be specified. The field description should be required and not optional.

**Comment by kroussou** [comment]
@stawik-mesa Thanks a lot for fast reply! What do you think will be better fix:
- update the docs
- remove check so it would be possible to create empty teams?

**Comment by kroussou** [comment]
I'll go for a documentation update. 
There is simple workaround to ensure that team has no members: just delete `github_team_members` respective resource
