### ISSUE TITLE
Ref data source contains incomplete code

### ISSUE THREAD

**Issue by youcandanch** [integrations/terraform-provider-github#1108]
### Terraform Version
1.1.8

### Affected Data Source
- ref

### Terraform Configuration Files
```hcl
provider "github" {}
data "github_ref" "this" {
  owner      = "integrations"
  repository = "terraform-provider-github"
  ref        = "tags/v4.23.0"
}
```

### Expected Behavior
Should get back ref information on the branch/tag.

### Actual Behavior

```
│ Error: Missing required argument
│
│   on github.tf line 46, in data "github_ref" "this":
│   46: data "github_ref" "this" {
│
│ The argument "branch" is required, but no definition was found.
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Grab the snippet above, and throw it in a Terraform file.
2. Try a `terraform plan`.

### Important Factoids
It looks like when I introduced this data source in https://github.com/integrations/terraform-provider-github/pull/1084, the last commit on the branch was from an older working version. I'm going to open a PR to fix this, but also going to eye the unit tests from that PR, as I'm a little bit perplexed as to how tests ended up passing.

### References
- https://github.com/integrations/terraform-provider-github/pull/1084

**Comment by youcandanch** [comment]
@kfcampbell just want to make sure I understand something about workflow with this repo -- are tests supposed to run on push? It looks like they're in the CI file, but not actually running. This is the most recent build (as of right now) on main:

https://github.com/integrations/terraform-provider-github/runs/5890079414?check_suite_focus=true

...and it looks like the test step finishes in anywhere from 10-15s, with this as the output:

![image](https://user-images.githubusercontent.com/448732/162586341-e644102e-1f73-4c82-925f-3020ca4eb8cb.png)

If this is intentional that's totally fine, but if it's not I'll open a separate issue for that.

**Comment by kfcampbell** [comment]
@youcandanch our testing situation is a little goofy right now. We're running unit tests on push, which are executing quite quickly as you've pointed out. Integration tests are run [weekly](https://github.com/integrations/terraform-provider-github/blob/main/.github/workflows/dotcom-acceptance-tests-all.yml), although they've been reliably failing for some time and aren't currently bringing much value to the product. 

Once a few immediate fires are put out (EMU support, Dependabot secrets, authorization fixes) I would love to find some time to put towards our testing strategy to gain more confidence with releases.

**Comment by youcandanch** [comment]
@kfcampbell _totally_ understood, only so many hours in the day. Happy to help where I can!

**Comment by youcandanch** [comment]
Using this in a project now totally smoothly, so gonna close this out as resolved.
