### ISSUE TITLE
Unable to import github_actions_environment_secret

### ISSUE THREAD

**Issue by guilhermeblanco** [integrations/terraform-provider-github#1124]
### Affected Resource(s)

Please list the resources as a list, for example:
- github_actions_environment_secret

### Terraform Configuration Files
```hcl
terraform {
  required_version = "~> 1.0"

  required_providers {
    github = {
      source  = "integrations/github"
      version = "~> 4.23.0"
    }
  }
}

provider "github" {
  token = module.github_secrets.secret_value["access_token"]
  owner = "XXXX"
}

resource "github_actions_environment_secret" "remote_host" {
  environment     = github_repository_environment.prod.environment
  repository      = data.github_repository.this.name
  secret_name     = "REMOTE_HOST"
  plaintext_value = module.prod_secrets.secret_value["host"]
}
```

### Expected Behavior
What should have happened?

Terraform should have imported the resource

### Actual Behavior
What actually happened?

Currently unable to import github_actions_environment_secret.

```bash
❯ terraform import 'github_actions_environment_secret.remote_host' REMOTE_HOST
github_actions_environment_secret.remote_host: Importing from ID "REMOTE_HOST"...
╷
│ Error: resource github_actions_environment_secret doesn't support import
│ 
```

While in the documentation it is stated that:

![Screenshot from 2022-04-21 22-46-10](https://user-images.githubusercontent.com/208883/164586190-f8e9c365-85a6-433f-a77d-21659d688433.png)

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform import 'github_actions_environment_secret.remote_host' REMOTE_HOST`

**Comment by shailygupta** [comment]
We are seeing this behavior as well.

Terraform Version: 1.1.6
Github Provider Version: 5.4.0

**Comment by kfcampbell** [comment]
Hmm...it looks like this behavior was introduced in #805 and never actually supported import. I'll open a quick PR to change the docs. In the meantime, is this a behavior you would consider opening a PR to fix?

**Comment by kfcampbell** [comment]
cc @nadenf for visibility. Is that something you're interested in?
