### ISSUE TITLE
The repository_file data source throws an error when trying to access a non-existent file

### ISSUE THREAD

**Issue by galargh** [integrations/terraform-provider-github#1131]
### Affected Resource(s)
Please list the resources as a list, for example:
- `data.github_repository_file`

### Expected Behavior
The `repository_file` data source allows checking if a specific file exists in a repository. The same way that `branch`data source, for example, does (see: https://github.com/integrations/terraform-provider-github/blob/main/github/data_source_github_branch.go#L52).

### Actual Behavior
The `repository_file` data source throws an error when trying to get a file which does not exist (see: https://github.com/integrations/terraform-provider-github/blob/main/github/data_source_github_repository_file.go#L82).

### References
- https://github.com/integrations/terraform-provider-github/pull/1129

**Comment by mwos-sl** [comment]
I need similar thing, to basically have an ability to check if a file exists in a given repo.

**Comment by galargh** [comment]
AFAIK, it's still applicable.
