### ISSUE TITLE
Error - Can't import github_organization_webhook

### ISSUE THREAD

**Issue by lucas481516** [integrations/terraform-provider-github#1140]
Hi there,

### Terraform Version
Version : v1.1.0

### Affected Resource(s)
List the resources : 
- github_organization_webhook

### Actual Behavior

github_organization_webhook.github_webhook: Importing from ID my_ID...
github_organization_webhook.github_webhook: Import prepared!
  Prepared github_organization_webhook for import
github_organization_webhook.github_webhook: Refreshing state... [id=my_id]

Error: This resource can only be used in the context of an organization, "" is a user.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
0 . The webhook was created on Org lvl
1.  terraform import github_organization_webhook.github_webhook ID

Thank you for your time 🙂

**Comment by DI-DaveGoodine** [comment]
I can reproduce this with:
```
davegoodine@HOU-L9452: github-org-webhooks (master)$ terraform version
Terraform v1.2.9
on darwin_amd64
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/hashicorp/vault v3.12.0
+ provider registry.terraform.io/integrations/github v4.31.0
```

code:
```
provider "github" {
  token = data.vault_generic_secret.gh_token.data["token"]
  owner = "myorg"
  alias = "myorg"
}

resource "github_organization_webhook" "myorg" {
  configuration {
    url          = var.url
    content_type = "json"
    insecure_ssl = false
    secret       = random_password.shared_secret.result
  }

  active = true

  events = [
    "issue_comment",
    "pull_request",
    "pull_request_review",
    "pull_request_review_comment",
    "push"
  ]
  provider = github.myorg

}
```

**Comment by DI-DaveGoodine** [comment]
After further testing, the error is caused by an expired github api token.
