### ISSUE TITLE
Support `Default to PR titles for squash merge commit messages`

### ISSUE THREAD

**Issue by Blacksmoke16** [integrations/terraform-provider-github#1150]
### Terraform Version

```sh
Terraform v1.1.9
on linux_amd64
+ provider registry.terraform.io/integrations/github v4.24.1
```

### Affected Resource(s)

Please list the resources as a list, for example:
- github_repository

See https://github.blog/changelog/2022-05-11-default-to-pr-titles-for-squash-merge-commit-messages/. Based on https://github.com/integrations/terraform-provider-github/pull/1143 this is probably blocked until `go-github` adds this feature, and the provider is upgraded to it.

**Comment by emmabindi** [comment]
+1 Our team would appreciate the ability to set use_squash_pr_title_as_default for our repo

**Comment by chaosaffe** [comment]
I think this may be closed by https://github.com/integrations/terraform-provider-github/pull/1263
