### ISSUE TITLE
github_repository_file adds additional author and committer information when editing a file resulting in unsigned commits

### ISSUE THREAD

**Issue by pawnu** [integrations/terraform-provider-github#1152]
### Terraform Version
Terraform v1.1.9

### Affected Resource(s)
- github_repository_file

### Debug Output
https://gist.github.com/pawnu/51b1d43ce618692446316515dc25fa8a

### Expected Behavior
When a file is edited without committer or author name and email information, the PUT request to edit file should not have committer or author information specified. This will allow github to sign the commit for you with your user/bot token.

### Actual Behavior
The PUT request adds author and committer name and email when editing the file. This results in unsigned commit as github will expect the author to sign the commit also.

See https://gist.github.com/pawnu/51b1d43ce618692446316515dc25fa8a#file-terraform_edit_file-txt line 235 vs https://gist.github.com/pawnu/51b1d43ce618692446316515dc25fa8a#file-terraform_create_file-txt line 282

### Steps to Reproduce
```
resource "github_repository_file" "tftestfile1" {
  repository          = data.github_repository.py-selenium-docker.name
  branch              = "main"
  file                = "tftestfile1"
  content             = "test file via terraform provider edit"
  commit_message      = "Managed by Terraform provider"
  overwrite_on_create = true
}
```

1. Create a file with github_repository_file resource without specifying `commit_author` and `commit_email`, and run apply. The commit which created the file is signed by your Github App/user and verified.
2. Make change to the same file content, and run apply again. The commit which edited the file is from `web-flow` user and unsigned. https://github.com/web-flow

I ran PUT requests with raw github API to create and edit file without committer and author information, and both result in signed commit.

CREATE
```
curl -i -X PUT   -H "Authorization: token ghs_y[...redacted...]"   -H "Accept: application/vnd.github.v3+json"   https://api.github.com/repos/pawnu/py-selenium-docker/contents/.github/workflows/testcreatefile   -d '{"message":"Create new file","content":"bXkgbmV3IGZpbGUgY29udGVudHM="}'
```
https://gist.github.com/pawnu/51b1d43ce618692446316515dc25fa8a#file-rest_api_create_file-txt

EDIT
```
curl -i -X PUT   -H "Authorization: token ghs_y[...redacted...]"   -H "Accept: application/vnd.github.v3+json"   https://api.github.com/repos/pawnu/py-selenium-docker/contents/.github/workflows/testcreatefile   -d '{"message":"Create new file","content":"bXkgbmV3IGZpbGUgY29udGVudCBlZGl0Cg==","sha":"0d5a690c8fad5e605a6e8766295d9d459d65de42"}'
```
https://gist.github.com/pawnu/51b1d43ce618692446316515dc25fa8a#file-rest_api_edit_file-txt

The issue doesn't seem to be within Github API.

**Comment by pawnu** [comment]
I have tested this out with go-github, and editing file with CreateFile and UpdateFile methods both work as expected i.e. the  commits are signed when no author or committer details are provided.

**Comment by pawnu** [comment]
@kfcampbell @joshuahancox Sorry to bother you guys but would you be able to review this please as this bug is a massive blocker for centrally managing (editing) files like github workflows due to unverified commits..

**Comment by joshua-hancox** [comment]
The change LGTM, but I don't think I have permission to provide an approving review. Sorry.
