### ISSUE TITLE
Set/read organization repository default branch

### ISSUE THREAD

**Issue by mengesb** [integrations/terraform-provider-github#1154]
Came across an interesting edge case with making modules using the github provider. Unfortunately I think this also will require some action on GitHub's side, because I'm not seeing the requisite stuff in the GH API (REST or GraphQL) - briefly checked both organization and repository APIs.

In an organization, on GitHub (GH) or GitHub Enterprise Server (GHES), you can set default branch for newly auto-initialized repositories. Now-a-days this typically defaults to `main`, whereas previously it use to be `master`. In some circumstances, organizations don't use either and have their own special brand of default branch. I tried searching the two APIs available however couldn't find anything that allows you to set this on organization creation, update after, or read after creation. You can definitely update it in the UI. I'm guessing either client libraries don't pull this information, or worse yet the APIs available don't report or allow definitions of this information on create/read. What follows below would be a feature request to be able to set this at an organization level. In looking at the resulting `repository` resources, I noticed that `default_branch` per the terraform resource is "deprecated" in favor of the resource `github_branch_default` - which I'm not sure is the right place because if you do not set `auto_init = true` on the repository creation, you cannot create a branch (because there's no `ref` to source the branch create from).

- set an organizations default repository branch upon auto-initialization
- read an organizations default repository branch

### Terraform Version
N/A

### Affected Resource(s)
- github_organization
- data.github_organization

### Terraform Configuration Files
```hcl
locals {
  # Make a list of branches, with the first branch being the default branch for the repository (even if it's "main" ... we'll address this in the resource ; we address any duplication here if var.branch_default is included in var.branches)
  branches = distinct(compact(concat([var.branch_default], var.branches)))
}

data "github_organization" "o" {
  name = var.organization
}

resource "github_repository" "r" {
  ...
  auto_init = true
  ...
}

# If we auto_init, create branches keyed on branch name except for the repository default branch
resource "github_branch" "b" {
  for_each   = { for k in local.branches : k => k if k != data.github_organization.o.repository_default_branch && github_repository.r.auto_init }
  repository = github_repository.r.name
  branch     = each.key
}

# If we auto_init, set the default branch if it's different from the repository default branch
resource "github_branch_default" "b" {
  for_each   = { for k in [local.branches[0]] : k => k if k != data.github_organization.o.repository_default_branch && github_repository.r.auto_init }
  repository = github_repository.r.name
  branch     = github_branch.b[each.key].branch
}

```

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
- Branches are created that don't match the organizations default branch
- If the user wants a different default branch for the repo, it would be set

### Actual Behavior
N/A

### Steps to Reproduce
N/A

### Important Factoids
Ideally this would work in both GHE and GHES if the organization repository default branch field is setable (`github_organization` resource or data source readable)

### References
N/A

**Comment by mengesb** [comment]
So currently my workaround isn't quite a good workaround, and a resource or data source for setting this would work out better.

I've defined a `repository_default_branch` variable which I'll require it to be a value through validation, however this is per-repository as this is where my module functions. If the organization defines a set branch, and the user wants a different set of branches and a different `branch_default`, then my code would still create this `repository_default_branch` branch. Ideally reading this from a data source would be preferred.

**Comment by giner** [comment]
This is still relevant and very much needed, especially data source to get the default branch as this is needed for `source_branch` in `github_branch` resource
