### ISSUE TITLE
Owner Missing in the Path in API Calls for github_branch_default Resources?

### ISSUE THREAD

**Issue by cooperwalbrun** [integrations/terraform-provider-github#1164]
I am observing errors reading `github_branch_default` resources where it appears the `owner` is not being properly injected into the path in the GitHub API call (see below).

### Terraform Version

1.1.9

### Provider Version

4.25.0

### Affected Resource(s)

`github_branch_default`

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    github = {
      source  = "integrations/github"
      version = "~> 4.0"
    }
  }

  ...
}

provider "github" {
  token = var.github_token
  owner = "cooperwalbrun" # This error occurs regardless of whether I specify this argument on the provider
}

resource "github_repository" "repository" {
  name = "scala-giter8"
  ...
}

resource "github_branch_default" "master" {
  repository = github_repository.repository.name
  branch     = "master"
}
```

### Expected Behavior

The Terraform should plan successfully without errors.

### Actual Behavior

The following error is output. Note the `//` in the API path where it should instead be `/cooperwalbrun/`. Also note that this is happening on all of my `github_branch_default`, not just this one in particular.

```
│ Error: GET https://api.github.com/repos//scala-giter8: 404 Not Found []
│ 
│   with github_branch_default.master,
│   on main.tf line 45, in resource "github_branch_default" "master":
│   45: resource "github_branch_default" "master" {
```

### Steps to Reproduce

The error happens during the plan step, so issuing `terraform plan` reproduces it. I am not sure if it is relevant, but this happened on a `github_branch_default` resource that was already provisioned successfully in a prior Terraform run - the only thing I changed today was that I updated the `provider` block to specify the `token` argument; previously, I was using the `GITHUB_TOKEN` environment variable without any issues.

**Comment by cooperwalbrun** [comment]
I have figured out what was causing this. It turned out that my statefile somehow kept getting references to the `hashicorp/github` variant of the provider (as opposed to the `integrations/github` variant), and the `github_branch_default` resources were among those being impacted. I cannot explain why my code worked fine prior to the `token`/`GITHUB_TOKEN` change, but I will choose not to dwell on it.

I also noticed that, even after running the `terraform state replace-provider hashicorp/github integrations/github` command, resources in one of my repository-local modules were still causing `hashicorp/github` to be pulled in during `terraform init`. In order to fix this part, I had to add

```
terraform {
  required_providers {
    github = {
      source  = "integrations/github"
      version = "~> 4.0"
    }
  }
}
```

to the code within the module itself in order to stop it from pulling in the `hashicorp/github` variant. After I did that, every resource in my repository began working properly again.

**Comment by martibosch** [comment]
Hello,

I am also running into this error when using environment secrets for my repo (see https://github.com/martibosch/doge-test/pull/2#issuecomment-1180459244), even though I am explicitly setting the source of the github provider as `integrations/github` in both the base setup (https://github.com/martibosch/doge-test/blob/develop/terraform/providers.tf) and modules (https://github.com/martibosch/doge-test/blob/develop/terraform/modules/base/providers.tf and https://github.com/martibosch/doge-test/blob/develop/terraform/modules/env/providers.tf).

Any clues on why this is happening?

Thank you. Best,
Marti
