### ISSUE TITLE
Set branch pattern for deployment_branch_policy of github_repository_environment

### ISSUE THREAD

**Issue by aminzar-access** [integrations/terraform-provider-github#1165]
Hi,
I can't see anything in documentation on how set branch pattern for deployment_branch_policy of github_repository_environment module.

https://registry.terraform.io/providers/integrations/github/latest/docs/resources/repository_environment#custom_branch_policies

Any help is appreciated.

**Comment by KyleKotowick** [comment]
I think this is a duplicate of #922.
