### ISSUE TITLE
Option to "Always suggest updating pull request branches" in github_repository

### ISSUE THREAD

**Issue by aminzar-access** [integrations/terraform-provider-github#1168]
Hi there,
The option to "Always suggest updating pull request branches" is missing from github_repository resource.

![image](https://user-images.githubusercontent.com/77307027/171369012-bbddbe77-175c-42f6-a03e-e1a877df93e0.png)

Thank you for looking into it.

### Affected Resource
- github_repository

**Comment by douglascayers** [comment]
Still relevant

**Comment by douglascayers** [comment]
Actually, looks like this was implemented in https://github.com/integrations/terraform-provider-github/pull/1143
