### ISSUE TITLE
Resource to manage Repository Action settings

### ISSUE THREAD

**Issue by aminzar-access** [integrations/terraform-provider-github#1169]
Hi there,
We need a resource to manage Actions settings of the repositories .

![image](https://user-images.githubusercontent.com/77307027/171370298-92f91f89-8040-4a01-9051-526184a1e3ab.png)

Thanks for your help.

**Comment by davidh-unmind** [comment]
anyone want to pick this up or already started on this?

**Comment by iiro** [comment]
Hi,

I guess this was just released...? https://registry.terraform.io/providers/integrations/github/latest/docs/resources/actions_repository_permissions & https://github.com/integrations/terraform-provider-github/releases/tag/v5.9.0

**Comment by kfcampbell** [comment]
Yep! This is closed as of #1339's release as @iiro noted.
