### ISSUE TITLE
Dependabot secrets resource documentation

### ISSUE THREAD

**Issue by srgustafson8** [integrations/terraform-provider-github#1171]
Dependabot secrets for both organisation and repository were added in version 4.26.0, but currently don't include any documentation on how to use them. Docs should be added for the new resources.

### References

- #1006 
- #1036

**Comment by srgustafson8** [comment]
Happy to do this myself, i'll raise a PR either today or tomorrow.

**Comment by SiavoshZarrasvand** [comment]
@srgustafson8 Hey! Need a hand with this one? I was trying to do this today found my way over here :)

**Comment by srgustafson8** [comment]
> raise a PR either today or tomorrow.

> commented 6 days ago

Oops. Thanks for the bump @SiavoshZarrasvand - i'm half way through so i'll finish it off and raise the PR today!
