### ISSUE TITLE
 Restrict pushes that create matching branches 

### ISSUE THREAD

**Issue by james-callahan** [integrations/terraform-provider-github#1172]
### Terraform Version
```
Terraform v1.2.1
on linux_amd64
```

### Affected Resource(s)
- github_branch_protection

### Expected Behavior

Should be able to tick the "Restrict pushes that create matching branches" box
![image](https://user-images.githubusercontent.com/35791147/171774461-d6ac6e82-9d5f-4e5e-a02e-289b98be1a76.png)

This is step 14 in https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule#creating-a-branch-protection-rule

### Actual Behavior

Option is not adjustable via the terraform provider

**Comment by joshdk** [comment]
What this issue does not mention is the failure case that results when configuring a repo without this property;

We are using this provider to provision some private repos that attempt to enforce a forking model (even for users with write access) by having a branch protection rule for `**/*`. 

Unfortunately, the resulting repository ends up being stuck in an awkward middle-ground where users can create new in-repo branches, but cannot subsequently force push to them (after squashing/amending/rebasing/etc). 

We then need to shepard them to fork the repo/configure remotes/re-open their original PR/etc which is a heavy-friction process.

If #1174 is released then this use case will be enabled and users will be immediately blocked when they push to in-repo branches. Remediation here is a lot easier than needing to throw out a potentially large amount of (un-updatable) PR work.

Thank you, cheers!
