### ISSUE TITLE
Allow specifying the order of branch protection rules

### ISSUE THREAD

**Issue by spangaer** [integrations/terraform-provider-github#1189]
When specifying glob branch protection rules, the globs are evaluated in order and the first glob to match is the rule that applies.

That means that (in case of overlapping globs) the order needs to be deterministic hence specifiable.

Some (optional) numeric priority or so?

**Comment by jtamagnan-delphix** [comment]
I see a few possibilities regarding this request:

 1. This is worth fixing at the Terraform provider level
   a. Maintainers *are* interested in fixing this
   b. Maintainers *are not* interested in fixing this but *PRs are welcome* 
 2. This is only worth fixing if there is support from GitHub as in https://github.com/community/community/discussions/39197
   a. Maintainers are interested in fixing this
   b. Maintainers *are not* interested in fixing this but *PRs are welcome*
 3. This is not worth fixing regardless
 
I'm fine with this issue being closed but would love to know which of the 5 scenarios we live in. @kfcampbell would you be the right person to ask for a statement on the future of this request?

**Comment by kfcampbell** [comment]
Is there API support for doing this? I'm not seeing anything about this [here](https://docs.github.com/en/rest/branches/branch-protection?apiVersion=2022-11-28) but maybe I'm missing something. If there's API support, I'd definitely welcome PRs to add it to the provider.
