### ISSUE TITLE
TF tries to remove members of the subteam from the parent team even though they dont exist in it.

### ISSUE THREAD

**Issue by cuotos** [integrations/terraform-provider-github#1193]
### Terraform Version
```
Terraform v1.2.3
on darwin_amd64
```

### Affected Resource(s)
Please list the resources as a list, for example:
- github_team_members

### Terraform Configuration Files
```hcl
resource "github_team" "parent" {
  name    = "parent_team"
  privacy = "closed"
}
resource "github_team_members" "parent" {
  team_id = github_team.parent.id
  members {
    username = "userA"
    role     = "maintainer"
  }
}
resource "github_team" "child" {
  name           = "child_team"
  parent_team_id = github_team.parent.id
  privacy        = "closed"
}
resource "github_team_members" "child" {
  team_id = github_team.child.id
  members {
    username = "userB"
    role     = "maintainer"
  }
}  
```

### Expected Behavior
after apply, no changes are required

### Actual Behavior
```hcl
  ~ resource "github_team_members" "parent" {
        id      = "xxxx"
        # (2 unchanged attributes hidden)

      - members {
          - role     = "maintainer" -> null
          - username = "userB" -> null
        }
        # (1 unchanged block hidden)
    }
 ```
 
 User B is not in the parent team, only the sub team, but TF wants to remove it from the parent which cannot be done and the apply times out. The Github api returns a list of all sub team members when you request all users in the parent team.
 
 https://docs.github.com/en/rest/teams/members#list-team-members
 `Team members will include the members of child teams.`

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by cuotos** [comment]
Related issue regarding the actual API provided by Github

https://github.com/github/docs/discussions/18926

**Comment by mickem** [comment]
I would say it is not really related to the API.
In the scripts I wrote before going to terraform I solved this by using the graphQL APIs which returns the correct information.
So switching to that API for reading members would solve this issue without any changes in the GitHub APIs.

**Comment by strongishllama** [comment]
@nickfloyd Thinking of taking a stab at this. I've written a bit of Go, so I think I have a pretty good idea what is required, but I've never done anything on the provider side of Terraform, so if you could double-check my line of thinking isn't too far of course that would be great!

1. Update the `resource_github_team_members` resource to have a `_v3` suffix, similar to `resource_github_branch_protection_v3`.
2. Update any of the existing tests if required.
3. Create a new `resource_github_team_members` resource that will use the GitHub GraphQL Go SDK under the hood.
4. Create new tests for the newly created `resource_github_team_members` resource.

**Comment by kfcampbell** [comment]
@strongishllama the `v3` thing is an artifact of issues the provider has had swapping between the GraphQL and REST APIs in the past. I would like to avoid future instances of it if possible. 

Ideally, the change doesn't require any schema updates and can be made transparently to the end user. In that case, we could use the same resource and wouldn't require a major version bump.
