### ISSUE TITLE
Feature Request: Organization Settings

### ISSUE THREAD

**Issue by HariSekhon** [integrations/terraform-provider-github#1200]
Please support more Organization level settings, such as:

- disabling repo creation by members
- enabling Dependabot on all new repos
- enabling GitHub Advanced Security on all new repos
- enabling Secret Scanning on all new repos
- organization level secrets (to chain from a cloud provider's Secrets Manager such as AWS or GCP)
- GitHub Actions workflows permissions to set read-only unless specifically elevated
- Billing spending limits

related to #1199

**Comment by HariSekhon** [comment]
GitHub Enterprise support have confirmed the Rest API is deficient, so have raised a public discussions feature request here to track this publicly:

https://github.com/github-community/community/discussions/19569

**Comment by joshua-hancox** [comment]
Hey @HariSekhon, I already raised a similar request here - could you help with upvoting it?

#1125

**Comment by kfcampbell** [comment]
Can this be closed now that #1298 has been merged and will be released shortly?

**Comment by elsmorian** [comment]
+1 here for ability to set spending limits for eg. Actions - that was not included in #1298 . Maybe we should have a separate issue for it?

**Comment by kfcampbell** [comment]
@elsmorian that sounds reasonable to me; please feel free to do so!

**Comment by elsmorian** [comment]
@kfcampbell Okedoke, you can find it here: https://github.com/integrations/terraform-provider-github/issues/1428 :)

**Comment by kfcampbell** [comment]
Thank you @elsmorian! I'll close this issue now and further discussion can happen on #1428.
