### ISSUE TITLE
[Feature Request] support for the Github "Security Managers" feature 

### ISSUE THREAD

**Issue by Svetlanko** [integrations/terraform-provider-github#1210]
are there plans to add support for a Github "Security Managers" feature? 
https://docs.github.com/en/organizations/managing-peoples-access-to-your-organization-with-roles/managing-security-managers-in-your-organization

we've been configuring it manually via Github UI but would love to have it terraformed. 

thank you!

**Comment by SolomonHD** [comment]
Yes, this would be a great feature.

**Comment by jeremyhayes** [comment]
This will need support for the [security managers API](https://docs.github.com/en/rest/orgs/security-managers). Created https://github.com/google/go-github/issues/2529 to track.

I'm happy to pick this up too. 👍

**Comment by kfcampbell** [comment]
Thank you @jeremyhayes! You rock. Please let me know if you'd like my eyes, assistance, etc.

**Comment by jeremyhayes** [comment]
Quick status update. The necessary change in the underlying API client was merged.
- https://github.com/google/go-github/pull/2530

Now waiting on a release of that lib and for it to get updated here.

**Comment by kfcampbell** [comment]
Thanks for the update! Still waiting on a release of go-github unfortunately.

**Comment by SolomonHD** [comment]
Love seeing the progress @jeremyhayes! When this is added where will this option be controlled from, github_organization_settings? Or will a new resource be created?

**Comment by jeremyhayes** [comment]
> Love seeing the progress @jeremyhayes! When this is added where will this option be controlled from, github_organization_settings? Or will a new resource be created?

My WIP has it as a new resource: `github_organization_security_manager`. But certainly that's up for debate when the PR opens! 😅

**Comment by jeremyhayes** [comment]
[go-github v48.1.0](https://github.com/google/go-github/releases/tag/v48.1.0) has released with the needed API support.

@kfcampbell what's the preferred update path here? Looks like we're still on v47.

**Comment by nickfloyd** [comment]
Hey @jeremyhayes, I'm on it... I'll update the dep and drop a PR (reference it here).

**Comment by nickfloyd** [comment]
For reference: go-github version update [PR](https://github.com/integrations/terraform-provider-github/pull/1366)

**Comment by Svetlanko** [comment]
thank you for getting this feature out 🔥
