### ISSUE TITLE
Drift on `github_repository_collaborator` permission: push vs write

### ISSUE THREAD

**Issue by lra** [integrations/terraform-provider-github#1221]
### Terraform Version

```
Terraform v1.2.5
on darwin_arm64
+ provider registry.terraform.io/integrations/github v4.27.0
```

### Affected Resource(s)
- github_repository_collaborator

### Terraform Configuration Files
```hcl
resource "github_repository_collaborator" "test" {
  repository = "repository"
  username   = "username"
  permission = "push"
}
```

### Expected Behavior

After `terraform apply`, a `terraform plan` should show no changes:
```
No changes. Your infrastructure matches the configuration.
```

### Actual Behavior

After a few hours, a terraform drift is showing up while planning:
```
  # github_repository_collaborator.dotcom["ssjoberg@seismic.com"] must be replaced
-/+ resource "github_repository_collaborator" "test" {
      ~ id                          = "repo:user" -> (known after apply)
      ~ invitation_id               = "123456789" -> (known after apply)
      ~ permission                  = "write" -> "push" # forces replacement
        # (3 unchanged attributes hidden)
    }
```

And if we set the permission to "write" in the resource, we get a 500 from the github api:
```
│ Error: PUT https://api.github.com/repos/org/repo/collaborators/username: 500  []
│ 
│   with github_repository_collaborator.test,
│   on users.tf line 110, in resource "github_repository_collaborator" "test":
│  110: resource "github_repository_collaborator" "test" {
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

**Comment by HorizonNet** [comment]
As an additional information: It not just happens with `push` and `write`, but also with `pull` and `read`, leading to the same situation.

**Comment by HorizonNet** [comment]
@lra I just gave 4.27.1 a try. It seems to be fixed there.

**Comment by lra** [comment]
Thanks, I'll give it a shot.
