### ISSUE TITLE
Use GetRoleName() instead of permission mapping not backward compatible.

### ISSUE THREAD

**Issue by schans** [integrations/terraform-provider-github#1222]
Hi there,

### Terraform Version
4.27.0

### Affected Resource(s)
- resource_github_team_repository

### Expected Behavior
Things keep working as in <4.27.0

### Actual Behavior
Non-custom roles are broken as the naming is different. read vs pull, write vs push etc.
For a lot more info see: https://github.com/integrations/terraform-provider-github/pull/1192

### Steps to Reproduce
Upgrade from <4.27.0 to 4.27.0 and run tf apply

### Important Factoids
Seems a bit of a mess due to historic reasons as Github? https://github.community/t/is-the-api-insane-with-respect-to-collaborators-or-am-i-confused/253696

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1192

**Comment by Luis-3M** [comment]
Many thanks @kfcampbell.
Given that we've successfully reverted PR #1992, should we close this issue and open a new one regarding the original broken behaviour when using custom roles?

**Comment by kfcampbell** [comment]
That sounds good to me! I've chosen to reopen #1183.
