### ISSUE TITLE
Terraform validate fails when using app_auth with environment variables

### ISSUE THREAD

**Issue by hollow** [integrations/terraform-provider-github#1239]
When using GitHub App authentication via environment variables `terraform validate` fails:

```
provider "github" {
  app_auth {}
}
```

```
Validation failed: .
╷
│ Error: Missing required argument
│ 
│   on main.tf line 3, in provider "github":
│    3:   app_auth {}
│ 
│ The argument "id" is required, but no definition was found.
╵
╷
│ Error: Missing required argument
│ 
│   on main.tf line 3, in provider "github":
│    3:   app_auth {}
│ 
│ The argument "installation_id" is required, but no definition was found.
╵
╷
│ Error: Missing required argument
│ 
│   on main.tf line 3, in provider "github":
│    3:   app_auth {}
│ 
│ The argument "pem_file" is required, but no definition was found.
```

**Comment by edwardgronroos** [comment]
Just did this and it worked fine, but make sure you've set the environment variables in the workflow/environment where you run the `terraform validate`.

On my first go I just set them on the step running `terraform plan` and got the same issue as you here on validate.

**Comment by hollow** [comment]
`terraform validate` should not need these environment variables to be set at all, since no API calls are made.

We have mitigated this issue with the following snippet in our `.envrc`:

```
export GITHUB_APP_ID=${GITHUB_APP_ID:-placeholder}
export GITHUB_APP_INSTALLATION_ID=${GITHUB_APP_INSTALLATION_ID:-placeholder}
export GITHUB_APP_PEM_FILE=${GITHUB_APP_PEM_FILE:-placeholder}`
```

**Comment by hollow** [comment]
The labels `Type: Support` and `Status: Needs info` should be removed as this is a bug and the mitigation and solution has been posted above.

**Comment by kfcampbell** [comment]
@hollow I'll close this issue in that case; please reopen if you feel there are additional items to address here.

**Comment by robinbowes** [comment]
This is still an issue, IMO. At the very least, you should include the workaround in the docs.

**Comment by lkanerv** [comment]
I agree with Robin, this issue seems like it should be re-opened, since the documented `app_auth {}` causes validate errors. 

Additionally, falling through to env vars prefixed with `GITHUB_` seems to break in GHA workflows, since those appear to be protected variable prefixes. See https://github.com/integrations/terraform-provider-github/issues/2375
