### ISSUE TITLE
changelog no longer updating

### ISSUE THREAD

**Issue by devopsrick** [integrations/terraform-provider-github#1240]
It seems the changelog has stopped updating with releases.  The last entry is 4.24.0 (Apr 28, 2022)

https://github.com/integrations/terraform-provider-github/blob/main/CHANGELOG.md

**Comment by kfcampbell** [comment]
Good observation! I switched to keeping track of the changelog using the fancy new "Autogenerate release notes" feature (example [here](https://github.com/integrations/terraform-provider-github/releases/tag/v4.26.1)). The previous process was manual and error-prone. I don't want to remove the changelog entirely, but I'd like to add a note at the top for how to access new changelog information. I'll open a PR to do that shortly!
