### ISSUE TITLE
Feature request: Set multiple issue labels for repository

### ISSUE THREAD

**Issue by parviste** [integrations/terraform-provider-github#1247]
We manage a quite large number of github repositories through terraform. We want to ensure that all the repositories have the same issue labels. Currently, for each repo, we have to loop over each label, and create a `github_issue_label`. This is slowing down the terraform apply by a lot, since the state of each label has to be checked individually.

It would be much more efficient for us if we could have a single resource that set multiple issue labels at once.

**Comment by kfcampbell** [comment]
This issue should stay open; it's still very much valid.
