### ISSUE TITLE
GitHub Tag Protection

### ISSUE THREAD

**Issue by nikwotton** [integrations/terraform-provider-github#1250]
This is not a bug but a feature request - I don't see where best to put this other than in Issues. If I am in the wrong place, please let me know and I will move it

The feature I am requesting is being able to manage [GitHub Tag Protection Rules](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/configuring-tag-protection-rules) through terraform. As far as I can tell reading through the documentation, this feature does not exist yet. I also don't see any Issues or Pull Requests currently for it, though I could've missed it. Not sure what other information to provide that would be helpful, but I will answer any questions asked of my on this Issue. 

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.
```
Terraform v1.2.6
on darwin_amd64
```

GitHub Provider Version:
```
4.28.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
GitHub Provider

**Comment by jpbelangerupgrade** [comment]
We contributed to go-github to add the code to be able to access tag protection API. It would be part of the next release (v45.2.1 most probably). 
ref: https://github.com/google/go-github/pull/2424

**Comment by nikwotton** [comment]
It looks like the code was added to go-github in [version 46.0.0](https://github.com/google/go-github/releases/tag/v46.0.0) which was merged into this repo in [version 4.31.0](https://github.com/integrations/terraform-provider-github/releases/tag/v4.31.0). I'm not familiar enough with this repo to know what the next steps are, just updating this issue

**Comment by jfengupgrade** [comment]
forked and working on the new feature

**Comment by kuhlman-labs** [comment]
PR Opened #1283

**Comment by kfcampbell** [comment]
Fixed by #1283!
