### ISSUE TITLE
Support Autolinks with alphanumeric or numeric IDs

### ISSUE THREAD

**Issue by douglascayers** [integrations/terraform-provider-github#1270]
GitHub updated their [autolink feature](https://github.blog/changelog/2022-08-31-autolinks-with-alphanumeric-or-numeric-ids/) to support either alphanumeric or numeric IDs.

This is a request to update the [github_repository_autolink_reference](https://registry.terraform.io/providers/integrations/github/latest/docs/resources/repository_autolink_reference) resource to support the new `is_alphanumeric: boolean` argument, which indicates whether this autolink reference matches alphanumeric characters. If false, this autolink reference is a legacy autolink that only matches numeric characters.

Example API Payload:
```json
{
  "id": 1,
  "key_prefix": "TICKET-",
  "url_template": "https://example.com/TICKET?query=<num>",
  "is_alphanumeric": true
}
```

---

I'm interested in working on adding this feature, and I've already submitted https://github.com/google/go-github/pull/2450 to add this feature into **go-github** lib so that we can make use of it in this terraform plugin.

I'm a complete `go` novice, so I'm thankful 99% of the work for calling this API is already done 😅 

Thanks!

**Comment by Djiit** [comment]
Hey team,

Interested in this too. Happy to pair/collaborate on it; but same, would need a bit of guidance to start.
