### ISSUE TITLE
GitHub Apps Authentication Requires GITHUB_OWNER to work

### ISSUE THREAD

**Issue by Aya-Inocentes** [integrations/terraform-provider-github#1287]
Hello, I've been trying to authenticate my terraform-github and as per documentation you'll need only the following variables when authenticating using GitHub Apps:
provider "github" {
  app_auth {
    id              = var.app_id              # or `GITHUB_APP_ID`
    installation_id = var.app_installation_id # or `GITHUB_APP_INSTALLATION_ID`
    pem_file        = var.app_pem_file        # or `GITHUB_APP_PEM_FILE`
  }
```hcl
provider "github" {
  app_auth {
    id              = var.app_id              # or `GITHUB_APP_ID`
    installation_id = var.app_installation_id # or `GITHUB_APP_INSTALLATION_ID`
    pem_file        = var.app_pem_file        # or `GITHUB_APP_PEM_FILE`
  }
}
```

But I've been an error:
```hcl
 Error: GET https://api.github.com/user: 403 Resource not accessible by integration []
│
│   with provider["registry.terraform.io/integrations/github"],
│   on providers.tf line 14, in provider "github":
│   14: provider "github" {
```

Only when I've set the environment variable: `export GITHUB_OWNER="owner"` then it works.

### Terraform Version
Terraform v1.0.1

### Affected Resource(s)
provider registry.terraform.io/integrations/github v4.31.0

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    github = {
      source  = "integrations/github"
      version = "4.31.0"
    }
  }
}

provider "github" {
  app_auth {
    id="<ommited>"
    installation_id="<ommited>"
    pem_file=file("<ommited>")
  }
}
```
### Expected Behavior
```
provider "github" {
  app_auth {
    id              = var.app_id              # or `GITHUB_APP_ID`
    installation_id = var.app_installation_id # or `GITHUB_APP_INSTALLATION_ID`
    pem_file        = var.app_pem_file        # or `GITHUB_APP_PEM_FILE`
  }
}
```
Should be working but I'm getting an error

### Actual Behavior
```
 Error: GET https://api.github.com/user: 403 Resource not accessible by integration []
│
│   with provider["registry.terraform.io/integrations/github"],
│   on providers.tf line 14, in provider "github":
│   14: provider "github" {
```

### Steps to Reproduce
1. `terraform apply`

**Comment by eliasnorrby** [comment]
I stumbled upon this as well, but I don't think it's a bug. The [docs](https://registry.terraform.io/providers/integrations/github/latest/docs#argument-reference) mark the `owner` parameter as optional, but only when the owner can be derived from an available token. When using `app_auth`, there is no token, so `owner` must be specified.

> [owner](https://registry.terraform.io/providers/integrations/github/latest/docs#owner) - (Optional) This is the target GitHub organization or individual user account to manage. For example, torvalds and github are valid owners. It is optional to provide this value and it can also be sourced from the GITHUB_OWNER environment variable. When not provided and a token is available, the individual user account owning the token will be used. **When not provided and no token is available, the provider may not function correctly.**

**Comment by x-yuri** [comment]
@eliasnorrby It's likely not the provider's bug, but at least it's a documentation bug.

The documentation gives the following example:

```
provider "github" {
  app_auth {
    id              = var.app_id              # or `GITHUB_APP_ID`
    installation_id = var.app_installation_id # or `GITHUB_APP_INSTALLATION_ID`
    pem_file        = var.app_pem_file        # or `GITHUB_APP_PEM_FILE`
  }
}
```

There's no token, as such there should be the `owner` argument.

**Comment by x-yuri** [comment]
I don't see the `owner` argument in the [docs' example][a]. What's completed about this task?

[a]: https://registry.terraform.io/providers/integrations/github/latest/docs#github-app-installation

**Comment by Aya-Inocentes** [comment]
reopening this issue. Waiting for admins to update the documentation based on this.

**Comment by kfcampbell** [comment]
@Aya-Inocentes the file to update is [here](https://github.com/integrations/terraform-provider-github/blob/main/website/docs/index.html.markdown#github-app-installation). Do you have the inclination to submit a PR for this docs change?

**Comment by Aya-Inocentes** [comment]
Hi @kfcampbell , Issue already resolved on my side, Just needed to implicitly add an `owner` argument for this to work. Won't be creating a PR.

Closing this issue.

Thanks,
