### ISSUE TITLE
FEATURE REQUEST: Dependabot security updates flag for repositories

### ISSUE THREAD

**Issue by sidekick-eimantas** [integrations/terraform-provider-github#1301]
### Terraform Version
Terraform v1.3.0
on darwin_arm64
+ provider registry.terraform.io/integrations/github v5.3.0

### Affected Resource(s)
- github_repository

Would be great if the following were supported:
<img width="801" alt="image" src="https://user-images.githubusercontent.com/111279287/192145594-f57d6bdb-6ce9-413a-b1f0-8df33c5fffe1.png">

Right now this can be enabled on repo creation only through the new `github_organization_settings` resource

**Comment by Serneum** [comment]
I am using version 5.12.0 of the GitHub provider and it looks like this is still missing. Tossing in my support for this feature request

**Comment by ViacheslavKudinov** [comment]
Same with 5.14.0.
Will be great to get it.

**Comment by gustavodaltoe** [comment]
Still no updates?

**Comment by kfcampbell** [comment]
I don't see any API support for this, unfortunately. Can someone provide a link to the docs of the API if it does exist?

**Comment by ViacheslavKudinov** [comment]
Yes, it is.
I've tested this API endpoint and one enables UI feature "Dependabot security updates".
Pre-req is that "Dependabot alerts" has to be enabled before. Otherwise it will return error:
```
{
  "message": "Vulnerability alerts must be enabled to configure automated security fixes.",
  "documentation_url": "https://docs.github.com/rest/reference/repos#enable-automated-security-fixes"
}
```

**Comment by grahamhar** [comment]
I have just started looking at making a contribution for this and I think I might have found the reason why this is not implemented before. There is only a REST API to enable or disable the setting with nothing available to get the current status. This means that each time a plan is performed this would always need to be flagged as a change and result in an apply needing to be run as the current state can't be checked during the plan.

I will try to look at the GraphQL docs to see if there is scope to use that instead. 

If any of the maintainers could comment on having a resource in a perpetual state of diff would be acceptable?

**Comment by kfcampbell** [comment]
We've ended up in situations with perpetual diffs occasionally (like #881) but they've always been bug cases. Ideally we'd avoid a situation in which that is the default and intended behavior.

**Comment by grahamhar** [comment]
@kfcampbell Is there a way we can get a GET method added to the rest endpoint (I couldn't find anything in graphql either)?

I tried making a GET request and I got strange behaviour of getting a 204 empty response irrespective of if it was enable or not. I would have expected a 501 not implemented as the docs have no mention of support for GET, the below example is against a repo with it disabled.


```
> GET /repos/grahamhar/aws-rotate/vulnerability-alerts HTTP/2
> Host: api.github.com
> user-agent: curl/7.88.1
> accept: application/vnd.github+json
> authorization: Bearer <redacted>
> x-github-api-version: 2022-11-28
> 
< HTTP/2 204 
< server: GitHub.com
< date: Fri, 14 Jul 2023 06:33:40 GMT
< x-oauth-scopes: gist, read:org, repo, workflow
< x-accepted-oauth-scopes: repo
< x-github-media-type: github.v3; format=json
< x-github-api-version-selected: 2022-11-28
< x-ratelimit-limit: 5000
< x-ratelimit-remaining: 4997
< x-ratelimit-reset: 1689319623
< x-ratelimit-used: 3
< x-ratelimit-resource: core
< access-control-expose-headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset
< access-control-allow-origin: *
< strict-transport-security: max-age=31536000; includeSubdomains; preload
< x-frame-options: deny
< x-content-type-options: nosniff
< x-xss-protection: 0
< referrer-policy: origin-when-cross-origin, strict-origin-when-cross-origin
< content-security-policy: default-src 'none'
< vary: Accept-Encoding, Accept, X-Requested-With
< x-github-request-id: C478:B976:BCF40F:BF5E90:64B0EC43
< 
* Connection #0 to host api.github.com left intact
```

**Comment by kfcampbell** [comment]
@grahamhar I don't have any particular cachet with the API team. The best way to request changes is by starting a discussion [here](https://github.com/orgs/community/discussions/categories/api-and-webhooks).

**Comment by Luttik** [comment]
If anybody did that 👆 already, could the link be shared so we can upvote it?

**Comment by grahamhar** [comment]
@kfcampbell is this issue also a duplicate of https://github.com/integrations/terraform-provider-github/issues/272?

**Comment by kfcampbell** [comment]
@grahamhar it is, but let's keep this open as well to keep the discussion that's been happening visible.

**Comment by grahamhar** [comment]
I have opened a PR in the SDK see [PR](https://github.com/google/go-github/pull/2842)

**Comment by grahamhar** [comment]
@kfcampbell #1851 opened to try and implement this feature, this is my first contribution to this provider so I would appreciate any guidance you can give me on the PR.

**Comment by ViacheslavKudinov** [comment]
Hi,
i couldn't find `github_repository_dependabot_security_updates` on doc for the release  v5.34.0 https://registry.terraform.io/providers/integrations/github/latest/docs
It looks like it is missed?!

**Comment by h-rasi** [comment]
Same here. Not able to find it in the new release!

**Comment by ViacheslavKudinov** [comment]
Hi @kfcampbell 
There is 5.35.0, but still nothing about this resource https://registry.terraform.io/providers/integrations/github/latest/docs
Any updates about this "new" resource? 
![Screenshot_20230911-072557_Chrome](https://github.com/integrations/terraform-provider-github/assets/56436734/b5cccf27-70f7-46ba-83dd-eb0f0b22994c)
