### ISSUE TITLE
Renaming github_repository doesn't taint full_name attribute

### ISSUE THREAD

**Issue by MajorBreakfast** [integrations/terraform-provider-github#1305]
### Terraform Version

0.14.11

### Affected Resource(s)

- github_repository

### Terraform Configuration Files
```hcl
resource "github_repository" "example" {
  name        = "example" # Rename the repo later, e.g. into example2
  ...
}
```

### Expected Behavior
When renaming a repository, the provider should mark the `full_name` field (which is `<owner>/<repo-name>`) as changed, so that further resources that depend on it can be updated in the same plan.

### Actual Behavior
The changed `full_name` field is only discovered by the state refresh in a subsequent plan after having the name change applied.

**Comment by KenSpur** [comment]
In resource_github_repository.go 

func resourceGithubRepository()

```go
func resourceGithubRepository() *schema.Resource {
	return &schema.Resource{ 
            ...
            Schema: map[string]*schema.Schema{
            ...
            },
            CustomizeDiff: customDiffFunction, // < add this 
            ...
```

and implement customDiffFunction as 

```go
func customDiffFunction(diff *schema.ResourceDiff, v interface{}) error {
	if diff.HasChange("name") {
		diff.SetNewComputed("full_name")
	}
	return nil
}
```

It will force the (known after apply) on the full_name.

Ill open a PR on friday, though feel free to open one before me.
