### ISSUE TITLE
Cannot create organizations from null_resources because provider checks fail to configure correctly

### ISSUE THREAD

**Issue by joestump** [integrations/terraform-provider-github#1309]
### Terraform Version
1.2.0+

### Affected Resource(s)
The `provider.go` bootup. Effects any resource that uses `owner.IsOrganization` check.

### Terraform Configuration Files

```hcl
resource "null_resource" "new_org" {
  # Use local-exec to provision an org using the GHE site admin API.
}

resource "github_repository" "test" {
  provider = github.new_org
  # Repository attributes here
  depends_on = ["null_resource.new_org"]
}

provider "github" {
  alias = "new_org"
  owner = "new_org"
}
```

### Debug Output

```
Error: this resource can only be used in the context of an organization, "new_org" is a user
```

### Expected Behavior

Organization is created via `local-exec` and then `github_repository.test` is created.

### Actual Behavior

In [`config.go`](https://github.com/integrations/terraform-provider-github/blob/cb52c618c12d73845b0a83653d3a621635a5e293/github/config.go#L112) the provider checks to see if the organization is real or not. When creating organizations from the same `terraform apply` via a `null_resource`, this check fails and [`owner.IsOrganization`](https://github.com/integrations/terraform-provider-github/blob/cb52c618c12d73845b0a83653d3a621635a5e293/github/config.go#L116) remains set to `false`. 

### Steps to Reproduce

Create an org from a `null_resource` in the same `apply` you try to use the provider configured with that as an `owner`. 

### Important Factoids

* When you call the create org API endpoint (see below for an example), you specify a user that is admin. This is the first new member. 
* The `$GITHUB_TOKEN` `user_terraform_runs_as` has `site_admin` scope. It is also set as the 1 sole admin of `new_org` when it's created via the API.
* We added a `sleep 30` to our `null_resource` to rule out a race condition on eventually consistent issue on the GHE side.

```sh
curl --location --request POST 'https://github.my-company.com/api/v3/admin/organizations' \
--header "Authorization: Bearer $GITHUB_TOKEN" \
--header 'Content-Type: application/json' \
--data-raw '{"login":"new_org","admin":"user_terraform_runs_as"}'
```

### References

https://docs.github.com/en/enterprise-server@3.6/rest/enterprise-admin/orgs#create-an-organization

**Comment by ehuizar1028** [comment]
I'm getting the same issue, I have a very similar setup where I'm using a null_resource to execute the API call to create the Org.

Curious what your logic is in the null_resource? In an effort to not print out our API keys in the null_resource, i just create a tmp file, run it, then remove it. But im looking for a better way to run this (once we get past the initial error, it seems that subsequent runs for me works)

It looks something like this:
```
resource "local_file" "file" {
    content = templatefile("./MyTemplate.tfpl", {token = data.vault["MyToken"]})
    filename = "./myScript.sh"
}

resource "null_resource" "org" {
  provisioner "local-exec" {
    command = "./myScript.sh"
  }
  depends_on = [local_file.file]
}

**Comment by joestump** [comment]
@ehuizar1028 the way ours works is we have a YAML file that teams PR when they want an organization. When TF kicks off on merge we enumerate over that YAML file and use `curl` to hit the API to create the organization if the organization's URL 404s. 

In general, we've found this provider to be painful to work with across multiple organizations in a single root module. My team has wasted at least 8 hours across 3 separate bug reports because of [this hack](https://github.com/integrations/terraform-provider-github/blob/main/github/provider.go#L215-L229) made in the name of backwards compatibility.

For anyone looking to learn from our pain, here are some tips:

* Do not set `GITHUB_OWNER` in the environment and `owner` at the same time. `owner` will be ignored and Terraform will fail. 
* Create automation outside of Terraform for creating your organizations.
* GHEC has functionality for managing/automation orgs/teams (I think it's called EMU?). If you're automating orgs, you're probably on GHE already. We are looking to move to that and then drive the rest of our GitHub automation as usual with this provider.

**Comment by joestump** [comment]
@ehuizar1028 security tip, if you set `GITHUB_TOKEN` and `GH_TOKEN` in the environment you run `terraform` in you don't have to pass `token` around (assuming that is what it is).
