### ISSUE TITLE
github_actions_runner_group is not correctly refreshing selected_repository_ids

### ISSUE THREAD

**Issue by jkasarherou** [integrations/terraform-provider-github#1310]
Hi,
I have found an issue with the resource `github_actions_runner_group`. From my tests it seems the resource is not correctly refreshing `selected_repository_ids`.
Looking at the terraform debug output, it seems that the GitHub API returns `304 Not Modified` based on the stored ETag when the provider attempts to refresh the action runner group resource.

This seems to be caused by this https://github.com/integrations/terraform-provider-github/blob/6773d80600f761bf50b695f475c2d457d1151ee5/github/resource_github_actions_runner_group.go#L146

I am not sure if this problem can be considered a bug with GitHub API itself and be reported as such, but for our usage this is making this resource unreliable with the terraform provider.

### Terraform Version

```
terraform -v
Terraform v1.2.6
on darwin_arm64
+ provider registry.terraform.io/integrations/github v5.3.0
```

### Affected Resource(s)
- `github_actions_runner_group`

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    github = {
      source = "integrations/github"
      version = "= 5.3.0"
    }
  }
}

resource "github_actions_runner_group" "group" {
  name        = "test"
  visibility  = "selected"

  selected_repository_ids = []
}

```

### Debug Output

https://gist.github.com/jkasarherou/7445669986a1f794526f7347762b92df

Extract of debug output (redacted sensitive values).

### Panic Output
n/a
### Expected Behavior

The terraform plan should show a diff for `selected_repository_ids`.

### Actual Behavior

The terraform plan does not show a diff for `selected_repository_ids`.

### Steps to Reproduce

1. `terraform apply` - This creates the test runner group.
2. Add a selected repository to the created test runner group manually (outside of terraform).
3. `terraform plan` - No diffs in the plan.

### Important Factoids
n/a
### References
n/a

**Comment by bchen-nydig** [comment]
running into the same issue

**Comment by kfcampbell** [comment]
Hmm...do either of you have thoughts on what more appropriate behavior from the provider might be in this situation?

**Comment by jkasarherou** [comment]
@kfcampbell I am thinking the provider can not rely on the `StatusNotModified` from the API, and refresh the list of repositories every time.

**Comment by kfcampbell** [comment]
Do you have any interest in opening up a PR for this behavior?

**Comment by jkasarherou** [comment]
@kfcampbell I can give it a try
