### ISSUE TITLE
github_repository_deploy_key replacement with same SSH-key fails

### ISSUE THREAD

**Issue by spr-mweber3** [integrations/terraform-provider-github#1316]
Hey there, I've noted a problem when switching a deploy keys read_only attribute and having the same SSH-key in place. 

I understand that the deploy_key needs to be replaced. What I don't understand is why the resource tries to create the new one before it destroys the old one even though `create_before_destroy` was not set to `true` explicitly be my on that resource. The default behavior of Terraform is to destroy first in that case. That's why I suggest it's explicitly defined in the provider. I even tried setting `create_before_destroy` explicitly to false which didn't help.

What would be perfect? Having the option to flip a deploy key from read-only to read-write without the need for a replace.

### Terraform Version
+ v1.2.9
+ provider.github v5.3.0

### Affected Resource(s)
- github_repository_deploy_key

### Expected Behavior
The old deploy_key should have gotten destroyed before an attempt is made to create the new one with the same SSH-key.

### Actual Behavior
The new deploy_key is tried to be created before the old one got deleted, which obviously isn't going to work because one signe SSH-key can only be used in one deploy_key.

**Comment by spr-mweber3** [comment]
This issue still exists in v5.5.0 - I'd like to understand if I'm trying to do something special here - and/or - how to approach my goal of being able to flip a deploy key from read-only to read-write differently.

**Comment by kfcampbell** [comment]
Would you mind providing an HCL snippet to help me reproduce the issue?
