### ISSUE TITLE
github_repository_webhook documentation is wrong

### ISSUE THREAD

**Issue by jrobison-sb** [integrations/terraform-provider-github#1318]
### Terraform Version
```
$ terraform -v
Terraform v1.2.0
on darwin_arm64
+ provider registry.terraform.io/integrations/github v5.3.0
```
### Affected Resource(s)
- github_repository_webhook
- github_organization_webhook

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

The documentation lists a `name` attribute [in the examples](https://registry.terraform.io/providers/integrations/github/latest/docs/resources/repository_webhook#example-usage) and [in the attribute list](https://registry.terraform.io/providers/integrations/github/latest/docs/resources/repository_webhook#name). But [the name attribute was removed](https://github.com/integrations/terraform-provider-github/pull/226) and is no longer valid. If you try to specify a `name` attribute, you'll get an error:

```
resource "github_repository_webhook" "default" {
  name = "web"
  ...
}

Error: "name": [REMOVED] The `name` attribute is no longer necessary
```

The docs should be updated to reflect this removal.

**Comment by jrobison-sb** [comment]
.

**Comment by kfcampbell** [comment]
@jrobison-sb do you have any inclination to open up a PR for this behavior?

**Comment by jrobison-sb** [comment]
Looks like the `name` attribute has already been removed from the docs.
