### ISSUE TITLE
github_organization_settings erroring on update for "team" plan

### ISSUE THREAD

**Issue by chrislittera** [integrations/terraform-provider-github#1324]
### Terraform Version
Terraform v1.3.0
on linux_amd64
+ provider registry.terraform.io/hashicorp/github v5.3.0
+ provider registry.terraform.io/integrations/github v5.3.0

### Affected Resource(s)
- github_organization_settings

### Terraform Configuration Files
```hcl
resource "github_organization_settings" "something" {
  advanced_security_enabled_for_new_repositories               = false
  billing_email                                                = "example@example.com"
  blog                                                         = "www.github.com"
  default_repository_permission                                = "write"
  dependabot_alerts_enabled_for_new_repositories               = true
  dependabot_security_updates_enabled_for_new_repositories     = true
  dependency_graph_enabled_for_new_repositories                = true
  has_organization_projects                                    = false
  has_repository_projects                                      = false
  members_can_create_pages                                     = false
  members_can_create_private_pages                             = false
  members_can_create_private_repositories                      = false
  members_can_create_public_pages                              = false
  members_can_create_public_repositories                       = false
  members_can_create_repositories                              = false
  members_can_fork_private_repositories                        = false
  name                                                         = "Some Great Org"
  secret_scanning_enabled_for_new_repositories                 = false
  secret_scanning_push_protection_enabled_for_new_repositories = false
  web_commit_signoff_required                                  = false
}
```

### Expected Behavior
A change to the configurations should properly apply.

### Actual Behavior
```
2022-10-12T16:31:39.097-0400 [DEBUG] provider.terraform-provider-github_v5.3.0: {
2022-10-12T16:31:39.097-0400 [DEBUG] provider.terraform-provider-github_v5.3.0:  "message": "Validation Failed",
2022-10-12T16:31:39.097-0400 [DEBUG] provider.terraform-provider-github_v5.3.0:  "errors": "This organization does not support internal repositories.",
2022-10-12T16:31:39.097-0400 [DEBUG] provider.terraform-provider-github_v5.3.0:  "documentation_url": "https://docs.github.com/rest/reference/orgs#update-an-organization"
2022-10-12T16:31:39.097-0400 [DEBUG] provider.terraform-provider-github_v5.3.0: }
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
[In the code](https://github.com/integrations/terraform-provider-github/blob/main/github/resource_github_organization_settings.go#L221-L228) you take into account both `free` and `enterprise` plans but miss the [teams plan option](https://github.com/pricing). 

The plan data looks like this:
```
2022-10-12T16:31:37.977-0400 [DEBUG] provider.terraform-provider-github_v5.3.0:  "plan": {
2022-10-12T16:31:37.977-0400 [DEBUG] provider.terraform-provider-github_v5.3.0:   "name": "team",
2022-10-12T16:31:37.977-0400 [DEBUG] provider.terraform-provider-github_v5.3.0:   "space": 1234,
2022-10-12T16:31:37.977-0400 [DEBUG] provider.terraform-provider-github_v5.3.0:   "private_repos": 1234,
2022-10-12T16:31:37.977-0400 [DEBUG] provider.terraform-provider-github_v5.3.0:   "filled_seats": 100,
2022-10-12T16:31:37.977-0400 [DEBUG] provider.terraform-provider-github_v5.3.0:   "seats": 100
2022-10-12T16:31:37.977-0400 [DEBUG] provider.terraform-provider-github_v5.3.0:  },
```
I don't know what other options aren't available in the "team" plan and am happy to work with you on testing if needed to help get it done right.

Thanks!

**Comment by chrislittera** [comment]
After reading https://docs.github.com/rest/reference/orgs#update-an-organization

It says:
```
The new input parameters are `members_can_create_public_repositories`, `members_can_create_private_repositories` for all organizations and `members_can_create_internal_repositories` for organizations associated with an enterprise account using GitHub Enterprise Cloud or GitHub Enterprise Server 2.20+.
```
so it seems like that is the only one that needs adjusting.

**Comment by kfcampbell** [comment]
@chrislittera thanks for reporting this! Do you have any interest in opening up a PR to help fix this behavior?

**Comment by rwblokzijl** [comment]
`members_can_create_internal_repositories` are also passed if the billing plan is "enterprise". This  is also incorrect as internal repos are only for "GitHub Enterprise Cloud with an enterprise account". [Not all enterprise organisations](https://github.com/integrations/terraform-provider-github/blob/main/github/resource_github_organization_settings.go#L228). 


> [Note](https://docs.github.com/en/enterprise-cloud@latest/repositories/creating-and-managing-repositories/about-repositories#about-internal-repositories): You can only create internal repositories if you use GitHub Enterprise Cloud with an enterprise account. An enterprise account is a separate type of account that allows a central point of management for multiple organizations. For more information, see "[Types of GitHub account](https://docs.github.com/en/enterprise-cloud@latest/get-started/learning-about-github/types-of-github-accounts)."

**Comment by kuhlman-labs** [comment]
@sebmck Can you tell me a bit more about what plan you are on?

**Comment by sebmck** [comment]
@kuhlman-labs We (@rome) are using Enterprise Cloud without an Enterprise account.

**Comment by jrdnbradford** [comment]
Expect same issue here as described by @chrislittera. We have an organization account on the GitHub Team plan.

**Comment by kuhlman-labs** [comment]
@chrislittera @jrdnbradford #1362 Should fix the issue for Team plans

**Comment by propyless** [comment]
Encountering the same issue here as well. Don't have internal repos with an Enterprise Plan. Its only supported with Enterprise Account.

**Comment by jrdnbradford** [comment]
As of release `5.9.0` `github_organization_settings` is working for our team plan.

**Comment by chrislittera** [comment]
@jrdnbradford I've confirmed this works in `5.9.2`, thanks!
