### ISSUE TITLE
5.4.0 is much slower

### ISSUE THREAD

**Issue by bootswithdefer** [integrations/terraform-provider-github#1328]
5.3.0 plan/apply takes ~25 minutes
5.4.0 plan/apply takes ~65 minutes

### Terraform Version
Terraform v1.3.2
on linux_amd64
+ provider registry.terraform.io/integrations/github v5.4.0

### Affected Resource(s)
Suspicions that it's github_branch_protection

### Terraform Configuration Files
Confidential, will provide if needed

### Debug Output
Will provide if needed

### Panic Output
N/A

### Expected Behavior
Plan takes 25 minutes

### Actual Behavior
Plan takes 65 minutes

### Steps to Reproduce
Both plan and apply take longer.

### Important Factoids
We have 3848 resources in our state, consisting of these types:
github_actions_organization_secret
github_branch_protection
github_membership
github_repository
github_repository_collaborator
github_repository_webhook
github_team
github_team_members
github_team_membership
github_team_repository

### References
#1020  may be the issue?

**Comment by kfcampbell** [comment]
@dion-gionet do you have thoughts on potentially reducing the impact of the nested `for` loops introduced in #1020? I'm thinking it would be best to revert the PR for the incoming v5.5.0 release which would remove the immediate cause of the performance regression for the time being.

**Comment by dion-gionet** [comment]
@kfcampbell mm, I'll have to look into it and come back to you. I'll make another PR when I have a solution

**Comment by dion-gionet** [comment]
@kfcampbell I've opened https://github.com/integrations/terraform-provider-github/pull/1331 which should fix this whenever you have time to check it out!

**Comment by kfcampbell** [comment]
@bootswithdefer I'm going to merge #1331 and cut a v5.7.0 release soon. If you get a chance, would you mind pulling in the latest version once it's out and retrying your plan?

**Comment by bootswithdefer** [comment]
@kfcampbell 5.7.0 runs at the same speed as 5.3.0, thanks!
