### ISSUE TITLE
Feature Request: Support Custom Roles for Users

### ISSUE THREAD

**Issue by alexlo03** [integrations/terraform-provider-github#1334]
Teams allow custom role assignment: https://github.com/integrations/terraform-provider-github/pull/1038 (see also https://github.com/integrations/terraform-provider-github/issues/988)
Users (Collaborators) do not: 
https://github.com/integrations/terraform-provider-github/blob/05a8875f0a3912d7231b06cfe5dc5d55bbc1dccc/github/resource_github_repository_collaborator.go#L42

Thanks

**Comment by kfcampbell** [comment]
@alexlo03 does that cover the functionality for custom roles described in the docs [here](https://docs.github.com/en/enterprise-cloud@latest/organizations/managing-peoples-access-to-your-organization-with-roles/managing-custom-repository-roles-for-an-organization)?

**Comment by alexlo03** [comment]
@kfcampbell This impacts the ability to assign the role.
With terraform now it is possible to set MY_CUSTOM_ROLE on SOME_TEAM.
It is NOT possible to set MY_CUSTOM_ROLE on SOME_PERSON.

**Comment by kfcampbell** [comment]
@alexlo03 I think I understand that. Will removing the `ValidateFunc` you linked allow custom roles as described in the docs link above? Is that something you'd like to try submitting a PR for?

**Comment by alexlo03** [comment]
Sorry I am unable to do a PR any time soon. Feel free to close.

**Comment by kfcampbell** [comment]
I think it's still worth keeping the issue open for now in case another community members wants to give it a shot!
