### ISSUE TITLE
Create a repository with github_repository return 404

### ISSUE THREAD

**Issue by georgef-dev** [integrations/terraform-provider-github#1335]
Hello!

When trying to create a new repository using `github_repository` I'm receiving "404 Not Found" and I believe the API is calling the wrong URL.

### Terraform Version
Terraform v1.3.2
+ provider registry.terraform.io/integrations/github v5.5.0

### Terraform Configuration Files
```hcl
# providers.tf

terraform {
  required_providers {
    github = {
      source  = "integrations/github"
      version = "5.5.0"
    }
  }

# main.tf

resource "github_repository" "repository" {
  name        = "created-by-terraform"
  description = "Createbd by Terraform"

  visibility = "internal"

  template {
    owner      = "OurOrg"
    repository = "created-by-terraform"
  }
}

resource "github_branch" "main" {
  repository = github_repository.repository.name
  branch     = "main"
}

resource "github_branch_default" "default"{
  repository = github_repository.repository.name
  branch     = github_branch.main.branch
}
```

### Terraform Apply Output
```bash
github_repository.repository: Creating...
╷
│ Error: POST https://api.github.com/repos/OurOrg/created-by-terraform/generate: 404 Not Found []
│
│   with github_repository.repository,
│   on main.tf line 39, in resource "github_repository" "repository":
│   39: resource "github_repository" "repository" {
│
```

### Expected Behavior
Succeed.

### Steps to Reproduce
1. `terraform init`
1. `terraform apply`

### References
I believe the API should call `https://api.github.com/orgs/ORG/repos` rather than `https://api.github.com/repos/OurOrg/created-by-terraform/generate`
[Reference documentation](https://docs.github.com/en/rest/repos/repos#create-an-organization-repository)

**Comment by dion-gionet** [comment]
Are you trying to create a template repository `created-by-terraform` ? If so, you should use the `is_template` argument instead of the `template` block. The template block specifies a template repo to create the `github_repository` **from** so in this case `created-by-terraform` doesn't exist to base the repo on so it returns a 404.

[github_repository](https://registry.terraform.io/providers/integrations/github/latest/docs/resources/repository#template)
> [template](https://registry.terraform.io/providers/integrations/github/latest/docs/resources/repository#template) - (Optional) Use a template repository to create this resource. See [Template Repositories](https://registry.terraform.io/providers/integrations/github/latest/docs/resources/repository#template-repositories) below for details.

**Comment by kfcampbell** [comment]
I agree with @dion-gionet! If you're looking to create a template repo, use the `is_template` argument. If you're trying to create a repo _from_ a template, use the template block.

**Comment by dion-gionet** [comment]
@mlitvinav Have you made sure the template repository (in this case `repository-a`) has the `Template repository` option turned on in repository settings? If it's off and the repo exists, the endpoint will indeed return a 404. Just tested it on my side and it works for me

![Screenshot 2023-03-09 at 10 26 27 AM](https://user-images.githubusercontent.com/29441318/224071533-0106c88b-c2a3-4139-862f-330c6fc961c6.png)

**Comment by mlitvinav** [comment]
Okay this is now a little bit emberassing. You are right @dion-gionet ! I have asked someone with access to the settings to check and it is not marked as a tempate anymore...
Thank you for the `is_template` flag. This should reapply it, in the case someone removes it again.

**Comment by rmvangun** [comment]
I'm having the same issue, though not related to a template repository I believe.

```
terraform version
Terraform v1.5.3
on darwin_amd64
+ provider registry.terraform.io/carlpett/sops v0.7.2
+ provider registry.terraform.io/hashicorp/aws v5.11.0
+ provider registry.terraform.io/integrations/github v5.32.0
```

In the `terraform plan`:

```
  # module.release_repo["my-repository"].github_repository.this will be created
  + resource "github_repository" "this" {
      + allow_auto_merge            = false
      + allow_merge_commit          = false
      + allow_rebase_merge          = false
      + allow_squash_merge          = true
      + allow_update_branch         = true
      + archived                    = false
      + default_branch              = (known after apply)
      + delete_branch_on_merge      = true
      + description                 = "A repo containing terraform for platform distribution"
      + etag                        = (known after apply)
      + full_name                   = (known after apply)
      + git_clone_url               = (known after apply)
      + has_downloads               = false
      + has_issues                  = true
      + has_projects                = false
      + has_wiki                    = false
      + html_url                    = (known after apply)
      + http_clone_url              = (known after apply)
      + id                          = (known after apply)
      + is_template                 = false
      + merge_commit_message        = "PR_TITLE"
      + merge_commit_title          = "MERGE_MESSAGE"
      + name                        = "my-repository"
      + node_id                     = (known after apply)
      + private                     = (known after apply)
      + repo_id                     = (known after apply)
      + squash_merge_commit_message = "COMMIT_MESSAGES"
      + squash_merge_commit_title   = "COMMIT_OR_PR_TITLE"
      + ssh_clone_url               = (known after apply)
      + svn_url                     = (known after apply)
      + visibility                  = "private"
      + vulnerability_alerts        = true

      + security_and_analysis {
          + advanced_security {
              + status = "enabled"
            }
          + secret_scanning {
              + status = "enabled"
            }
          + secret_scanning_push_protection {
              + status = "enabled"
            }
        }

      + template {
          + include_all_branches = false
        }
    }
```

And getting this error:

`Error: POST https://api.github.com/repos///generate: 404 Not Found []`

Other resources are created correctly, so it's just the `github_repository` resource having problems. I've configured `token` and `owner` on the provider block, and also have tried setting `GITHUB_TOKEN` and `GITHUB_OWNER`, which often cause problems when querying private repos.
