### ISSUE TITLE
Create a repository from a template and include branches

### ISSUE THREAD

**Issue by peter-murray** [integrations/terraform-provider-github#1337]
The GitHub Rest API now has support for including the branches in a template repository using the `include_all_branches` parameter in the request; https://docs.github.com/en/rest/repos/repos#create-a-repository-using-a-template

I would like to request support be added to the `github_repository` resource to be able to specify this parameter when create a repository based off a template repository, so that the newly create repository has all the branches from the template instead of only the default branch.

**Comment by kfcampbell** [comment]
PR #1120 will close this issue.

**Comment by kfcampbell** [comment]
Closing via #1353.
