### ISSUE TITLE
Feature Request: New Branch Protections: Last Pusher and Locked Branch

### ISSUE THREAD

**Issue by drmaciej** [integrations/terraform-provider-github#1341]
Recently released: https://github.blog/changelog/2022-10-20-new-branch-protections-last-pusher-and-locked-branch

**Comment by kfcampbell** [comment]
Ooh, nice! This would be great to have in the provider. It looks like [GitHub API support](https://docs.github.com/en/rest/branches/branch-protection) is available. I'm not sure if the graphQL schema has been updated to pull in this new behavior yet for the github_branch_protection resource. 

For the github_branch_protection_v3 resource, we'd need support from google/go-github, which doesn't appear to have this functionality yet. We can add it once it does, though!
