### ISSUE TITLE
Upgrading to v5 is not seamless

### ISSUE THREAD

**Issue by maroux** [integrations/terraform-provider-github#1343]
### Terraform Version
```
→ tf version
Terraform v1.1.3
on darwin_amd64
+ provider registry.terraform.io/integrations/github v5.5.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- `github_repository`

### Terraform Configuration Files
```hcl
resource "github_repository" "repo" {
  name = "foobar"
}
```

### Debug Output
Please provide a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create a repo with v4 provider
2. Upgrade to v5 provider version
3. Run `terraform init -upgrade`
4. Run `terraform plan`
5. Fails

### Actual Behavior
Fails with error:
```
│ Error: Failed to decode resource from state
│ 
│ Error decoding "github_repository.repo" from previous state: unsupported attribute "branches"
```

### Expected Behavior
- Should work fine.

### Important Factoids
I understand `branches` was removed in this PR: #1117, but the upgrade to v5 should be seamless if you're not using `branches` in the config no?
I'm having to muck around with state file manually to upgrade to v5 which is error-prone and annoying.

### References
- #1117

**Comment by kfcampbell** [comment]
@maroux this is an expected change; v4 state will not work with v5 resources in this manner.

**Comment by mbarany** [comment]
This is affecting us as well. We have hundreds of repos in TF. I love that `branches` is no longer in that resource, but I would think there would be a more seamless way to upgrade from v4 to v5 without removing state. In lieu of that that seamless upgrade is there at least some information on how to fix the state to be v5 compatible?

**Comment by kfcampbell** [comment]
@mbarany Do you know what other providers do for breaking changes like this? Looking at some of Hashicorp's documentation [here](https://developer.hashicorp.com/terraform/plugin/hashicorp-provider-design-principles#consider-state-and-versioning), maybe what we should've done is maintain a version of `github_repository` with `branches` and also include it as its own resource, though I'm not sure how conflict resolution would be done there.

**Comment by mbarany** [comment]
@kfcampbell I do not, but a quick Google search yields something about a state file migration
https://github.com/hashicorp/terraform/issues/16809#issuecomment-383954621

**Comment by kfcampbell** [comment]
Oh interesting. I wonder if that would work if we implemented it this late.

**Comment by mbarany** [comment]
I'm not a Go expert but this looks pretty straightforward. Looking at [this state migration PR](https://github.com/integrations/terraform-provider-github/pull/133) for `resource/github_repository_webhook`. Seems like we just need to bump the `SchemaVersion` and write a migration to delete `branches`

**Comment by mbarany** [comment]
@kfcampbell I've put in a PR that I think should fix this
https://github.com/integrations/terraform-provider-github/pull/1434

**Comment by jvaliente-uz** [comment]
Hi there! We are experiencing the same issue already mentioned. While trying to update the provider version from `4.28.0` to `5.0.0` the same error (i.e. `unsupported attribute "branches"`) is raised 😢 

The steps I followed were the very standard ones:
* Update the provider version from `4.28.0` to `5.0.0` on the `terraform.tf` file
* Run `terraform init -upgrade`
* Run `terraform plan` -> where the error is raised

Already read all the PRs mentioned here, didn't succeed anyway. Are we missing anything else 🤔 ??

**Comment by mbarany** [comment]
@jvaliente-uz the migration was added in [5.13.0](https://github.com/integrations/terraform-provider-github/releases/tag/v5.13.0) so you'll have to go straight to that version

**Comment by jvaliente-uz** [comment]
> @jvaliente-uz the migration was added in [5.13.0](https://github.com/integrations/terraform-provider-github/releases/tag/v5.13.0) so you'll have to go straight to that version

Thanks Michael! The upgrade was smooth after that, appreciate it!
