### ISSUE TITLE
How to add commit-msg hook to the repository

### ISSUE THREAD

**Issue by pbn4** [integrations/terraform-provider-github#1344]
### Terraform Version
1.3.3

### Affected Resource(s)
- github_repository_file

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    github = {
      source  = "integrations/github"
      version = "~> 4.0"
    }
  }
}

data "github_user" "current" {
  username = ""
}

resource "github_repository" "this" {
  name        = "my-test-repository-name"
  description = ""

  visibility = "private"

  auto_init = true
}

data "local_file" "initial_file" {
  filename = "${path.module}/commit-msg"
}

resource "github_repository_file" "initial_files" {
  repository          = github_repository.this.name
  branch              = "main"
  file                = ".git/hooks/commit-msg"
  content             = data.local_file.initial_file.content
  commit_message      = "Add commit-msg hook"
  commit_author       = data.github_user.current.username
  commit_email        = data.github_user.current.email
  overwrite_on_create = true
}
```

### Debug Output
https://gist.github.com/pbn4/5ad874ad5d13112c6f6c8c2c39ad6ae8

### Expected Behavior
A `.git/hooks/commit-msg` file should be created

### Actual Behavior
API responds with
```
422 path contains a malformed path component [{Resource:Commit Field:path Code:invalid Message:}]
```

### Steps to Reproduce
0. Create a file `commit-msg` in your CWD
1. Put HCL into main.tf
2. `terraform apply`

**Comment by kfcampbell** [comment]
I'm seeing this issue too. It looks like the GET call to `GET /repos/kfcampbell-terraform-provider/my-test-repository-name/contents/.git/hooks/commit-msg?ref=main` (in my case) is 404ing. Do you think explicitly creating the directory first would resolve the issue?

**Comment by pbn4** [comment]
@kfcampbell It's not possible to commit anything under .git, I ended up using 

```
git config --local core.hooksPath .git-hooks/
```

to install hooks from custom .git-hooks directory. If you want to enforce anything on developers you should create a github action e.g. linter check and configure repository to no allow pull request merges if this check is not green.
