### ISSUE TITLE
Perpetual updates in github_repository_file

### ISSUE THREAD

**Issue by yafanasiev** [integrations/terraform-provider-github#1345]
When upgrading from provider version 5.3.0 to 5.6.0, Terraform shows diff for all `github_repository_file` resources to remove `commit_author` and  `commit_email` from resource. After successful apply, next plan operation shows the same diff again. Reverting back to 5.3.0 solves the problem. Issue can be reproduces on 5.5.0 as well.

Tried removing resource from state and importing it back again - no luck.
Provider is initialised using a PAT token of separate service user in organisation.

### Terraform Version
Terraform v1.3.3
on darwin_arm64

### Affected Resource(s)
- github_repository_file

### Terraform Configuration Files
```hcl
resource "github_repository_file" "kustomize" {
  repository = local.fluxcd_config.github_main_repository_name
  file       = data.flux_sync.main.kustomize_path
  content    = local.kustomize_file
  branch     = local.fluxcd_config.github_main_repository_branch
}
```

### Expected Behavior
Changes to resource should be successfully applied.

### Actual Behavior
Changes are applied successfully and new empty commit is created. Next plan operation shows the diff again.

```hcl
  # module.eks.github_repository_file.kustomize will be updated in-place
  ~ resource "github_repository_file" "kustomize" {
      - commit_author       = "<REDACTED>" -> null
      - commit_email        = "<REDACTED>" -> null
        id                  = "<REDACTED>"
        # (8 unchanged attributes hidden)
    }
```

### References
This behaviour is most likely introduced in https://github.com/integrations/terraform-provider-github/pull/1179.

**Comment by kfcampbell** [comment]
Good find! Is this something you'd be interested in opening a PR to fix?

**Comment by yafanasiev** [comment]
@kfcampbell I don't have a lot of experience with Terraform providers. I might give it a chance some time later this week, but can't guarantee anything.

**Comment by spr-mweber3** [comment]
Experiencing the same. This is clearly a bug. Unfortunately I can't help with an PR here as well. Mitigated by pinning to v5.3.0 of the provider for now.

**Comment by kfcampbell** [comment]
Hmm... @pawnu are you seeing this as well after #1179 has merged? Do you have thoughts on how we might mitigate the issue?

**Comment by kfcampbell** [comment]
I'm a little hesitant to revert #1179 as there was some interest in that feature from folks using GitHub Apps to authenticate. I support setting an author/email on the file if that works around the issue. I'd be receptive of a PR that would attempt to handle this appropriately without specific user input as well.
