### ISSUE TITLE
[FEAT]: Add a means to provision a Personal Access Token through Terraform

### ISSUE THREAD

**Issue by jamietanna** [integrations/terraform-provider-github#1360]
### Describe the need

With the release of [Fine-Grained Personal Access Tokens](https://github.blog/changelog/2022-10-18-introducing-fine-grained-personal-access-tokens/), it'd be handy to be able to provision these with Terraform, i.e. so automation can interact with GitHub more appropriately.

These are still in beta, so not sure if we want to provide a resource until it's fully finalised, or if we'd be happy iterating over it as appropriate.

As I'm writing this, one thing that may make this not-super-helpful is that they are bound to the user who creates them, so we may want some way of providing a separate `token` to allow switching which user the token is created for?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sbkg0002** [comment]
Is there any work being done on this one?

**Comment by kfcampbell** [comment]
I actually don't believe this is possible. Personal access tokens of any kind can't be created through the API as far as I'm aware.

**Comment by DavidS-ovm** [comment]
Indeed: https://docs.github.com/en/rest/orgs/personal-access-tokens?apiVersion=2022-11-28#update-the-access-to-organization-resources-via-fine-grained-personal-access-tokens

Pretty disappointing gap in microsoft's offering there.
