### ISSUE TITLE
[DOCS]: more detailed info on how to authenticate

### ISSUE THREAD

**Issue by tatutoivio-bf4d** [integrations/terraform-provider-github#1361]
### Describe the need

When using `gh` for authentication to GitHub, how should the authentication exactly be done?

Attempt 1:
Adding empty `app_auth` block to the provider block
-> Missing `id`, `installation_id`, and `pem_file` – where to find these from?

Attempt 2:
Running `export GITHUB_TOKEN=$(gh auth token)`, and then adding `token = "GITHUB_TOKEN"` to the provider block
-> Bad credentials upon `terraform apply`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tatutoivio-bf4d** [comment]
@oliver-sentianse I understood that the PEM file would be a file generated by the `gh` CLI. I'd rather not create any extra authentication-related files if possible, as I'm already authenticated with the CLI.

**Comment by x-yuri** [comment]
There are different ways to authenticate:

* Via [personal tokens][a]. There are fine-grained and classic tokens.
* Via [GitHub apps][b].
* Via OAuth apps.

Classic tokens and OAuth apps are to be avoided if possible. AFAICT.

[Here][c] I briefly described how to access GitHub API from command line via a GitHub app. If you need to access a private repository, you need to install the app in the account that owns the repository. For authenticating with `terraform` most of the steps are needed. Particularly you need to activate your device at https://github.com/login/device. Whatever that means. Activation will probably occasionally expire. I'm not sure. I don't have much experience yet. You probably don't need to get an access token. And you obviously don't need to make API requests.

If you need to access repositories owned by your personal account, a personal token should suffice. In case of organization repositories you likely need a GitHub app.

[a]: https://registry.terraform.io/providers/integrations/github/latest/docs#oauth--personal-access-token
[b]: https://registry.terraform.io/providers/integrations/github/latest/docs#github-app-installation
[c]: https://gist.github.com/x-yuri/9d4e7e9daa0ef3eaaf50fe8b017c16ba
