### ISSUE TITLE
[FEAT]: Resource for creating an Enterprise Organization

### ISSUE THREAD

**Issue by kuhlman-labs** [integrations/terraform-provider-github#1365]
### Describe the need

Customers would like the ability to automate the creation of Orgs within their Enterprise Instance. Today that is achievable using some GraphQL queries and mutations but many Enterprises would like to be able to automate and track these changes with Terraform.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment]
Agreed that this would be useful!
