### ISSUE TITLE
[BUG]: projects enabled when `has_project` has been set to `false`

### ISSUE THREAD

**Issue by johankees** [integrations/terraform-provider-github#1380]
### Describe the need

Given the following code:

```terraform
resource "github_repository" "example" {
  name        = "example"
  description = "Repository should be created without project"

  visibility = "public"

  has_projects = false
}
```

A project should be created without projects enabled, however `Projects` is enabled in the Features settings.

### SDK Version

terraform-provider-github v5.9.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment]
@johankees thanks for reporting! Is this something you have any interest in opening up a PR to fix?

**Comment by johankees** [comment]
I wish I would be able to. I'm not a go developer, so don't think I'll be able to fix this myself. I'm more than happy to help testing if that's needed.

**Comment by kfcampbell** [comment]
I don't see anything suspicious in the code so far. It looks like that property is set [here](https://github.com/integrations/terraform-provider-github/blob/510bb2f427e82bb7c99574c62d0870d8cfc7aec0/github/resource_github_repository.go#L356). 

Does your organization have projects enabled by default on new repos?

**Comment by johankees** [comment]
Thanks for the reply @kfcampbell . Are you referring to the "Enable Projects for the organization" setting? If so, this has been enabled for our org, but reading the description for this setting, it just allow creating projects, but doesn't enable it (by default).

**Comment by kfcampbell** [comment]
Ah, you're right! I was thinking of this setting: 

![image](https://user-images.githubusercontent.com/9327688/207409304-baf6c62a-d565-4edc-bd79-041f4b61f211.png)

I'm still unsure what a proper resolution for this would be.

**Comment by wwsean08** [comment]
Hmm I gave this a shot today with this minimal setup and wasn't able to recreate the issue, this is my minimal setup based on your original description:

```hcl
terraform {
  required_providers {
    github = {
      source = "integrations/github"
      version = "5.13.0"
    }
  }
}

provider "github" {
  owner = "test-organization-wwsean08"
}

resource "github_repository" "example" {
  name        = "example-no-projects"
  description = "Repository should be created without project"

  visibility = "public"

  has_projects = false
}
```

The resulting repo doesn't have projects enabled, https://github.com/test-organization-wwsean08/example-no-projects.  
<img width="806" alt="Screenshot 2023-01-03 at 10 07 27 PM" src="https://user-images.githubusercontent.com/839261/210494286-3bd29375-dff7-4518-8eef-f48a7ce39e20.png">

I also tested with version `5.9.0` of the provider and had the same results, https://github.com/test-organization-wwsean08/example-no-projects-5-9-0

<img width="813" alt="Screenshot 2023-01-03 at 10 06 59 PM" src="https://user-images.githubusercontent.com/839261/210494224-2f55cc2e-2098-439e-9458-8cfe37c57402.png">

I'm not sure I can take this bug any further as I can't seem to recreate the issue.

**Comment by arunsathiya** [comment]
I see the same outcome as @wwsean08, both in the case of a personal account and an organization account. I also double-checked that projects are enabled at the organization-level, and without it enabled, projects cannot be created for each organization repository either.

Overall, I think something changed in terms of API, `go-github` implementation or was an user/implementation error earlier, and that this issue can be closed.
