### ISSUE TITLE
[BUG]: autolinks are not recreated when removed outside of terraform

### ISSUE THREAD

**Issue by svalevka** [integrations/terraform-provider-github#1381]
### Describe the need

When Autolinks are created using terraform but removed outside of terraform, plan fails instead of recreating them.

How to reproduce:

* Create autolinks  resource
```
resource "github_repository" "repo" {
  name = "test-node"
  description = "test=node"
}

resource "github_repository_autolink_reference" "autolink" {
  repository = github_repository.repo.name
  key_prefix = "TICKET-"
  target_url_template = "https://example.com/TICKET?query=<num>"
}
```
* Run `terraform apply` which creates repository and autolinks as expected
* Remove autolinks from GUI or via gh cli
* Rerun `terrafom plan`. Expected to recreate the autolinks, instead getting the error below

```
│ Error: GET https://api.github.com/repos/${ORG}/test-node/autolinks/871833: 404 Not Found []
│ 
│   with github_repository_autolink_reference.autolink,
│   on main.tf line 6, in resource "github_repository_autolink_reference" "autolink":
│    6: resource "github_repository_autolink_reference" "autolink" {
│ 
```
* Workaround
Remove autolink resource from terraform state and rerun the plan

### API Version

5.9.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment]
@svalevka is this something you have any interest in opening a PR to fix?

**Comment by svalevka** [comment]
@kfcampbell Unfortunately I don't think I have enough Golang experience to do that

**Comment by wwsean08** [comment]
I opened a PR @svalevka, hopefully this will be merged soon :)

**Comment by svalevka** [comment]
Thank you very much @wwsean08 , really appreciated
