### ISSUE TITLE
[MAINT]: In order to import a project, a PATCH call is made to get security and analysis information

### ISSUE THREAD

**Issue by puiterwijk** [integrations/terraform-provider-github#1387]
### Describe the need

The Repository object runs an Edit call (with no changes) at the moment of Read, in order to get the security and analysis information.
This information is also reported in the original repository retrieval, so the additional call is not needed, and it also doesn't have to be a PATCH call.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment]
@puiterwijk thanks for reporting this! Do you have any interest in opening up a PR to fix this behavior?

**Comment by kfcampbell** [comment]
:facepalm: :facepalm: :facepalm: of course you've already done that! Please forgive me, I'll get that reviewed ASAP. Thanks!
