### ISSUE TITLE
[BUG]: `github_repository_environment` is unusable if the environment name contains `/`

### ISSUE THREAD

**Issue by Sebelino** [integrations/terraform-provider-github#1389]
### Terraform Version
```
$ terraform -v                                        
Terraform v1.3.5
on linux_amd64
```

### Affected Resource(s)
- `github_repository_environment`

### Terraform Configuration Files
```hcl
resource "github_repository_environment" "this" {
  environment = "customer/production"
  repository  = "infrastructure"
}
```

### Expected Behavior
Running `terraform apply` should create an environment named `customer/production`.

### Actual Behavior
`terraform apply` fails with the following error message:
```
github_repository_environment.this: Creating...
╷
│ Error: PUT https://api.github.com/repos/Sebelino/infrastructure/environments/customer/production: 404 Not Found []
│ 
│   with github_repository_environment.this,
│   on main.tf line 82, in resource "github_repository_environment" "this":
│   82: resource "github_repository_environment" "this" {
│ 
╵
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create a `github_repository_environment` resource with a name that contains a front-slash (`/`).
1. Run `terraform apply`

### Important Factoids
The problem is that the environment name needs to be URL encoded before we make the call: https://github.com/integrations/terraform-provider-github/blob/40f1500156289538b8ec8ebf5bc6182bddeabb7b/vendor/github.com/google/go-github/v48/github/repos_environments.go#L175

A workaround is to change the environment name to `customer%2Fproduction`, but that should not be necessary.

**Comment by kfcampbell** [comment]
@Sebelino thanks for reporting! Is this something you'd have interest in opening a PR to fix?
