### ISSUE TITLE
[BUG]: github_branch data_source returns empty response when ref does not exist

### ISSUE THREAD

**Issue by tho93** [integrations/terraform-provider-github#1408]
### Describe the need

The [github_branch data_source](https://registry.terraform.io/providers/integrations/github/latest/docs/data-sources/branch) returns an empty result when the GitHub ref does not exist. It seems like the default behavior is to fail, as data_sources are commonly used as assertion checks for Terraform.

It seems like that is the desired behavior as well
```
if err.Response.StatusCode == http.StatusNotFound {
	log.Printf("[DEBUG] Missing GitHub branch %s/%s (%s)", orgName, repoName, branchRefName)
	d.SetId("")
	return nil
}
```

Here is an example of a non-existent branch:
```
provider "github" {
  owner = "owner"
}

data "github_branch" "self" {
  repository = "this-repository-exists"
  branch     = "this-branch-doesnt-exist"
}

> terraform state show data.github_branch.self
# data.github_branch.self:
data "github_branch" "self" {}
```

`terraform apply` will also finish successfully without erroring. I have verified that the data_source indeed works for existing branches.

**EDIT:**

I now see that this behavior may be intentional and working as expected from these commits:
https://github.com/integrations/terraform-provider-github/commit/4f7109e1fd7e4c2fd8793c83fac45ce8579a85f1
https://github.com/integrations/terraform-provider-github/commit/cae33d218ba895b0671e2f8a49579d495b8d58ad

Feel free to close this issue if that is the case.

### SDK Version

terraform-provider-github v5.10.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment]
This is indeed intentional behavior! Please let us know if you have questions or concerns about it.
