### ISSUE TITLE
Error authenticating with GitHub app

### ISSUE THREAD

**Issue by nickjmv** [integrations/terraform-provider-github#1411]
I'm trying to get the provider working but I have a couple of issues. I managed to get it working using a PAT but then I get the following error:
```
Error: non-200 OK status code: 401 Unauthorized body: "{\"message\":\"Personal access tokens with fine grained access do not support the GraphQL API\",\"documentation_url\":\"https://docs.github.com/graphql/guides/forming-calls-with-graphql#authenticating-with-graphql\"}"
```
with config:
```
provider "github" {
  owner = "X"
  token = "XXXXX"
}
```

I also tried, but without any luck.
```
provider "github" {
  owner = "X"
  token = "XXXXX"
  app_auth {
    id              = var.github_app_id
    installation_id = var.github_app_installation_id
    pem_file        = file("${path.module}/terraform-github-mgmt.2022-12-05.private-key.pem")
  }
}
```

Could someone help me or provide me with a clear guide on how to create the GitHub app?

**Comment by kfcampbell** [comment]
One option here of course is to use a "classic" PAT, which is accepted by the GitHub GraphQL API. Perhaps you've already seen the [GitHub docs for creating an App](https://docs.github.com/en/developers/apps/building-github-apps/creating-a-github-app) and [installing it on a repo](https://docs.github.com/en/developers/apps/managing-github-apps/installing-github-apps), which can be helpful. 

What error are you getting when attempting to authenticate using your App?

**Comment by nickjmv** [comment]
With the GitHub app configuration I get the following error:
```
Error: failed to create OAuth token from GitHub App: {"message":"Not Found","documentation_url":"https://docs.github.com/rest/reference/apps#create-an-installation-access-token-for-an-app"}
│ 
│   with provider["registry.terraform.io/integrations/github"],
│   on provider.tf line 1, in provider "github":
│    1: provider "github" {

```
Maybe it is something in my variable for the provider, but I'm using the following values from the app page:

App ID: XXX -> app_id
Client ID: Iv1.XXX -> installation_id
Private key download -> pem_file

**Comment by AtzeDeVries** [comment]
You first need to install the app into your repo or ORG

If you list your installed app and click on it you see an number in the url, which is `the installation_id`

**Comment by nickjmv** [comment]
Aha that was the ID I was missing indeed! Now I can successfully create a group in GitHub. Now the next error I get is to create a repository, which gives me this:
```
Error: POST https://api.github.com/user/repos: 401 Requires authentication []
│ 
│   with module.cni-repositories["testy"].github_repository.repository,
│   on repository/repository.tf line 1, in resource "github_repository" "repository":
│    1: resource "github_repository" "repository" {
```

**Comment by nickjmv** [comment]
Ah, I already found my issue! I found my answer in this issue https://github.com/integrations/terraform-provider-github/issues/846
Apparently, I had to pass the provider from the root of my repository to my submodule. After doing that it worked!
