### ISSUE TITLE
[MAINT]: Public Repositories do not play well with Advanced Security settings

### ISSUE THREAD

**Issue by lbordowitz** [integrations/terraform-provider-github#1419]
### Describe the need

First of all, thank you very much for adding the GitHub Advanced Security settings in terraform, see #1104 . This has been a boon to our organization, and we've used it to track and add settings to every repository using a common setup module.

Most of our repositories are private, but one of them is public. I've tried a dynamic setting to remove the `advanced_security` block from the public repository, but now, trying to remove it, I get the message `422 Advanced security is always available for public repos []`.

I do want to keep other security settings, like "Secret scanning", without having a required block specifying advanced security for the public repo. Please advise if there's a better way to go about this, otherwise, let me know if this is something that can be adjusted in the `security_and_analysis` block.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment]
Ideally, this sort of thing wouldn't throw a 422 at the API level. In the provider, perhaps an inelegant solution would be ignoring 422s for those specific requests.

**Comment by sethvargo** [comment]
Hey @nickfloyd - could we rollback https://github.com/integrations/terraform-provider-github/pull/1304 and release a new version? This unintentionally introduced a breaking change. By sending these values in API calls to public repos, GitHub rejects them.

I think we should only add these fields to the API if they are explicitly supplied, or rollback and explore a different engineering option. For now, pinning to `5.11.0` is a workaround, but this is a fairly serious bug as it makes `github_repository` completely unusable in `5.12.0` and introduced a breaking change.

/cc @marzvrover @kfcampbell

**Comment by kuhlman-labs** [comment]
@sethvargo I'll take a look, I have some ideas of how to handle.

**Comment by kuhlman-labs** [comment]
@sethvargo This PR should fix this issue:
https://github.com/integrations/terraform-provider-github/pull/1431

**Comment by usmonster** [comment]
> For now, pinning to `5.10` is a workaround, but this is a fairly serious bug as it makes `github_repository` completely unusable in `5.11` and `5.12` and introduced a breaking change.

Just a small correction: unless I'm mistaken, the change was introduced in [`5.9.0`](https://github.com/integrations/terraform-provider-github/releases/tag/v5.9.0), so the workaround should be to pin to `5.8.0`. Hope this helps someone, and looking forward to the fix! 🙏

**Comment by Luis-3M** [comment]
Exactly @usmonster - we're facing the same issue as of right now.
Currently on `5.10.0` of the provider with no way to look back or forward bc of what you've mentioned.

We're seeing two distinct errors for private and public repos accordingly (**settings have only been enabled for public repos since this is a free feature. We're explicitly disabling them for private repos**):
- Private repos: `422 Advanced security has not been purchased []`
- Public repos: `422 Advanced security is always available for public repos []`

Current workaround: rerun the pipeline.

**Comment by usmonster** [comment]
We went ahead and pinned `5.8.0` since it seems the issue fixed by #1368 is apparently no longer present (maybe a fix on the API?). Hope this is a suitable workaround for some!

**Comment by kfcampbell** [comment]
@usmonster we don't pin to any specific API version in this provider, which as far as I'm aware with the recently-introduced API versioning means we automatically use the latest. I don't think the verison of the provider correlates with API version at all.

**Comment by miotke** [comment]
I understand that everyone is probably just getting back from the holiday/end of year break but I'm wondering if there's an update for this issue/a fix being released soon. Like other have mentioned, we get the `422 Advanced security is always available for public repos []` error when trying to create a public repo. 

We are currently on v5.11.0 and are unable to revert back to v5.8.0 (which I understand works around this issue) due to some additional features we needed in v5.10.0+. To elaborate on those features, we needed to give a custom role to a team which, if I'm reading the release notes correctly, became available in [v5.10.0](https://github.com/integrations/terraform-provider-github/releases/tag/v5.10.0)

Because we're in this bind we are unfortunately stuck when it comes to creating new public repos. If there's something I'm missing which could help us out or there are more details I'm happy to hear suggestions or feedback.

**Comment by kfcampbell** [comment]
@miotke would you prefer to ignore 422 errors in the public repo case? What do you see as a path forward?

**Comment by miotke** [comment]
Hi @kfcampbel, I saw that you mentioned this as a possible path forward above, it would probably resolve the immediate need.

My only concern with ignoring an error is if there's something we actually need to be alerted of. Although if we can depend on GitHub (we probably can) to ensure that advanced security is always enabled for public repos it's probably not a huge concern. All that said, I'm not sure if this is an error worth ignoring or if we need to actually take action on it.

**Comment by kuhlman-labs** [comment]
@miotke This PR fixes this issue, do you mind taking a look and giving feedback?
https://github.com/integrations/terraform-provider-github/pull/1431

**Comment by miotke** [comment]
@kuhlman-labs, I took a look at the PR but I don't think I can contribute any useful feedback since I don't know go or how this implementation works. If I am understanding that PR correctly the public repos will not include any advanced security options but GitHub will enforce it by default because it's a public repo? 

Sorry, I wish I was able to supply more useful feedback 😞.

**Comment by kuhlman-labs** [comment]
@miotke The logic of the PR basically changes the request that is sent to the API based on the repos visibility. Advanced Security is enabled on public repos by default so if you send an API request with that field you will get an error, but you can still control the other aspects of advanced security like push protection and secret scanning on public repos.

**Comment by jtgrohn** [comment]
In addition to the public repo issues everyone has been commenting on, there is another issue for private/internal repos with updating the provider version. If a repo was created at/after the `security_and_analysis` block was introduced (e.g. at `5.9.0`+), without the block explicitly set, and then is updated to a newer version (doesn't seem to matter which), the plan wants to remove the block. e.g.

```terraform
Terraform will perform the following actions:

  # github_repository.repo will be updated in-place
  ~ resource "github_repository" "repo" {
        id                          = "security_and_analysis_test"
        name                        = "security_and_analysis_test"
      - vulnerability_alerts        = true -> null
        # (28 unchanged attributes hidden)

      - security_and_analysis {
          - advanced_security {
              - status = "enabled" -> null
            }

          - secret_scanning {
              - status = "enabled" -> null
            }

          - secret_scanning_push_protection {
              - status = "enabled" -> null
            }
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

<details>
<summary>Steps to reproduce</summary>

create Terraform config:
```
provider "github" {
  token = "foo"
  owner = "bar"
}

terraform {

  required_providers {
    github = {
      source  = "integrations/github"
      version = "5.9.0"
    }
  }

  backend "local" {}
}

resource "github_repository" "repo" {
    name = "security_and_analysis_test"

    visibility           = "internal"
}
```
apply
update provider version in terraform config, so the resulting config is:
```
provider "github" {
  token = "foo"
  owner = "bar"
}

terraform {

  required_providers {
    github = {
      source  = "integrations/github"
      version = "5.10.0"
    }
  }

  backend "local" {}
}

resource "github_repository" "repo" {
    name = "security_and_analysis_test"

    visibility           = "internal"
}
```
and the resulting plan tries to remove the `security_and_analysis` block (see above). 
</details>

**Comment by kfcampbell** [comment]
@jtgrohn do you mind creating a new issue with those details? My guess is that we're missing a migration function, but I'd like to keep that separate from this issue.

**Comment by bombelme** [comment]
@usmonster did you have any problems with downgrading to v5.8.0? I am unable to downgrade because of this:
```
╷
│ Error: Resource instance managed by newer provider version
│
│ The current state of module.repos["repo"].github_repository.this was created by a newer provider version than is currently selected. Upgrade the github provider to work with this state.
╵
```
Strangely, the last time when I needed to downgrade the GH provider I didn't have this problem.

**Comment by usmonster** [comment]
@bombelme, yes, we saw the same and "just" had to delete & re-import the state for `github_repository` resources. 🙃 Hope it helps a little while waiting for #1431 to land.

**Comment by gszakonyNitro** [comment]
Version `5.13.0` works without any issue.

**Comment by jtgrohn** [comment]
> Version `5.13.0` works without any issue.

No it doesn't.

```terraform
provider "github" {
  token = "foo"
  owner = "bar"
}

terraform {

  required_providers {
    github = {
      source  = "integrations/github"
      version = "5.13.0"
    }
  }

  backend "local" {}
}

resource "github_repository" "repo" {
    name       = "public_security_and_analysis"
    visibility = "public"
    security_and_analysis {
        advanced_security {
            status = "enabled"
        }
        secret_scanning {
            status = "enabled"
        }
        secret_scanning_push_protection {
            status = "disabled"
        }
    }
}
```

still results in a `terraform apply` failure of

```terraform
github_repository.repo: Creating...
╷
│ Error: PATCH https://api.github.com/repos/jtgrohn/public_security_and_analysis: 422 Advanced security is always available for public repos []
│ 
│   with github_repository.repo,
│   on main.tf line 18, in resource "github_repository" "repo":
│   18: resource "github_repository" "repo" {
│ 
╵
```
