### ISSUE TITLE
[BUG]: datasource github_repository produces an error: GET kubernetes/ingress-nginx/pages: 404 Not Found

### ISSUE THREAD

**Issue by idelsink** [integrations/terraform-provider-github#1420]
### Terraform Version
```sh
$ terraform --version 
Terraform v1.3.6
on linux_amd64
+ provider registry.terraform.io/hashicorp/github v5.11.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- datasource github_repository

### Terraform Configuration Files
```hcl
data "github_repository" "hashicorp_terraform" {
  full_name = "hashicorp/terraform"
}
data "github_repository" "kubernetes_ingress_nginx" {
  full_name = "kubernetes/ingress-nginx"
}
```

### Debug Output
[out.log](https://github.com/integrations/terraform-provider-github/files/10195273/out.log)

### Expected Behavior
I expected both of the data source (`data.github_repository.hashicorp_terraform` and `data.github_repository.kubernetes_ingress_nginx`)  to return data successfully, but only one of them succeeded. 

### Actual Behavior

```sh
$ terraform apply 
data.github_repository.hashicorp_terraform: Reading...
data.github_repository.kubernetes_ingress_nginx: Reading...
data.github_repository.hashicorp_terraform: Read complete after 0s [id=terraform]
╷
│ Error: GET https://api.github.com/repos/kubernetes/ingress-nginx/pages: 404 Not Found []
│ 
│   with data.github_repository.kubernetes_ingress_nginx,
│   on main.tf line 28, in data "github_repository" "kubernetes_ingress_nginx":
│   28: data "github_repository" "kubernetes_ingress_nginx" {
│ 
╵

```

### Steps to Reproduce

1. Use the configuration as provided:
```terraform
data "github_repository" "hashicorp_terraform" {
  full_name = "hashicorp/terraform"
}
data "github_repository" "kubernetes_ingress_nginx" {
  full_name = "kubernetes/ingress-nginx"
}
```

2.  `terraform apply`

### Important Factoids

I did not explicitly configure the provider nor did I configure any accounts. 

### References

> Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:

Not that I could find

**Comment by kfcampbell** [comment]
@idelsink This is interesting. When exporting a GITHUB_OWNER and a GITHUB_TOKEN I'm unable to reproduce the error using the following HCL: 

```hcl
terraform {
  required_providers {
    github = {
      source = "integrations/github"
    }
  }
}

data "github_repository" "hashicorp_terraform" {
  full_name = "hashicorp/terraform"
}
data "github_repository" "kubernetes_ingress_nginx" {
  full_name = "kubernetes/ingress-nginx"
}
```

When exporting only a GITHUB_TOKEN, it succeeds as well. When exporting a GITHUB_OWNER, it fails as you've mentioned, which leads me to believe that there's some kind of bug when configuring an anonymous owner. #1029 may help in this regard, which I'd like to get in soon.

**Comment by idelsink** [comment]
Yeah I already had a feeling it had something to do with that. For my local testing I did not configure an account (setting the GITHUB_OWNER nor GITHUB_TOKEN). Good to hear there is already some other issue that might resolve this :tada:
