### ISSUE TITLE
[MAINT]: Next release date

### ISSUE THREAD

**Issue by tomleicircle** [integrations/terraform-provider-github#1421]
### Describe the need

Hi!

I just have a quick question around when is the next release happening? We're mainly looking for the feature added in [issue 1352](https://github.com/integrations/terraform-provider-github/issues/1352) and just trying to find out when will this be released.

Thanks!

Tom

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment]
In the past we haven't had a standardized cadence for releases, although we've had several substantive PRs merged in recently and we're past due for one. I'll cut v5.12.0 now!

**Comment by kfcampbell** [comment]
The latest release is [here](https://github.com/integrations/terraform-provider-github/releases/tag/v5.12.0) and should be up on the Terraform Registry within an hour or so.
