### ISSUE TITLE
[Feature Request] Provide 'Releases' data source

### ISSUE THREAD

**Issue by joshgodsiff** [integrations/terraform-provider-github#144]
I would find it useful to be able to retrieve release artefacts from GitHub via Terraform (i.e. the data that can technically be gotten from https://api.github.com/repos/:owner/:repo/releases and its sub-APIs at the moment).

For context, I need to grab a release artefact that's being published to a *private* GitHub and deploy it to our infrastructure. The fact that it's private means that I can't just point TF at the public HTTPS endpoint for the artefact, and interacting with the API itself is complex enough it would require scripting.

**Comment by radeksimko** [comment]
Hi @Kheldar 
thanks requesting the mentioned data source.

Do you mind providing a bit more context about your use case? Specifically I'm curious which Terraform provider & resource would you use to deploy the artefact.

**Comment by Kheldar** [comment]
In this specific instance, I need to get it onto S3 (the artefact is a Lambda package). In general, it would be good to be able to pass this to any resource that can currently take a file.

**Comment by philnielsen** [comment]
Bumping this and also providing another use case.

We would like to get version numbers from a github release (or tag, but that is a different API and therefore probably a different data source from this card) that would then be used to deploy that version of a docker container with another terraform provider. (AWS in our case but could be anything else)

**Comment by benj-fletch** [comment]
Hi, I'd like to work on this if possible? I notice it's an older ticket but believe there is still some value in providing this resource?
