### ISSUE TITLE
[BUG]: Resource github_repository does not detect changes

### ISSUE THREAD

**Issue by giner** [integrations/terraform-provider-github#1446]
`github_repository` does not detect changes in many of the parameters if they are either done directly on GitHub or the resource is imported. Here are some parameters which are affected (the list is not comprehensive):
- allow_rebase_merge
- allow_squash_merge
- allow_update_branch
- delete_branch_on_merge

The reason for this behaviour seems to be related to how GitHub treats ETag. Specifically ETag update is not triggered by the changes in the parameters listed above. Commenting out the following lines makes the detection work: https://github.com/integrations/terraform-provider-github/blob/42f8195553962035f17dbdc259f6b8bf5ee017c7/github/resource_github_repository.go#L492-L494

**Comment by giner** [comment]
The only expected side effect is increased number of requests towards GitHub APIs. However this is unavoidable unless GitHub devs document in detail which changes are covered by ETag. Depending on what that doc would have some optimization could be done.

**Comment by benlangfeld** [comment]
I reported the broken API behaviour to Github in https://support.github.com/ticket/personal/0/2004710. I'll relay any response I receive from them here.

**Comment by benlangfeld** [comment]
While we wait for Github to resolve their caching implementation, it's reasonably easy to strip all etag values from terraform state in order to force a refresh:

```sh
contents="$(jq '.resources[].instances[].attributes.etag = ""' terraform.tfstate)" && echo -E "${contents}" > terraform.tfstate
```

**Comment by giner** [comment]
@benlangfeld do we know whether GitHub has fixed this issue? I've tested on a few options and I can't reproduce it.

**Comment by benlangfeld** [comment]
> @benlangfeld do we know whether GitHub has fixed this issue? I've tested on a few options and I can't reproduce it.

Indeed repeating the test I did in February, I now get the expected result of immediate cache invalidation:

```
❯ gh api /repos/powerhome/example-rails-app --include --jq ".allow_rebase_merge"

HTTP/2.0 200 OK
Cache-Control: private, max-age=60, s-maxage=60
Date: Mon, 28 Aug 2023 18:48:06 GMT
Etag: W/"5caa68e6e4147db9e442123aebc8888a570392636feb5f64d4a82de5f88b8d77"
Last-Modified: Fri, 28 Apr 2023 22:06:53 GMT
X-Github-Api-Version-Selected: 2022-11-28

false

❯ gh repo edit powerhome/example-rails-app --enable-rebase-merge
✓ Edited repository powerhome/example-rails-app

❯ gh api /repos/powerhome/example-rails-app --include --jq ".allow_rebase_merge" --header 'If-None-Match: W/"5caa68e6e4147db9e442123aebc8888a570392636feb5f64d4a82de5f88b8d77"'

HTTP/2.0 200 OK
Cache-Control: private, max-age=60, s-maxage=60
Date: Mon, 28 Aug 2023 18:50:19 GMT
Etag: W/"9edf8f5dc6db2730f1bb19a4f1a90c5c3a0a48ceedc0aa5742fc1e41441a2628"
Last-Modified: Fri, 28 Apr 2023 22:06:53 GMT
X-Github-Api-Version-Selected: 2022-11-28

true

❯ gh api /repos/powerhome/example-rails-app --include --jq ".allow_rebase_merge"

HTTP/2.0 200 OK
Cache-Control: private, max-age=60, s-maxage=60
Date: Mon, 28 Aug 2023 18:51:38 GMT
Etag: W/"9edf8f5dc6db2730f1bb19a4f1a90c5c3a0a48ceedc0aa5742fc1e41441a2628"
Last-Modified: Fri, 28 Apr 2023 22:06:53 GMT
X-Github-Api-Version-Selected: 2022-11-28

true
```

I'd say Github have solved this on their end.

**Comment by kfcampbell** [comment]
Closing according to @benlangfeld's above comments. Please reopen if this is not the case!
