### ISSUE TITLE
Wrong link to Code of conduct

### ISSUE THREAD

**Issue by raven-wing** [integrations/terraform-provider-github#1456]
### Describe the need

When accepting code of conduct (to report an issue) there is wrong link for it. 
It probably should be  [THIS](https://github.com/integrations/terraform-provider-github/blob/main/CODE_OF_CONDUCT.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment]
@raven-wing do you have any interest in opening up a PR to fix this?

**Comment by nickfloyd** [comment]
Hey @raven-wing, thanks for catching this - it looks like the relative link is that way on all of our templates.  Let us know if you'd be up for submitting a quick PR to get these updated and thanks again for making this community and source better! ❤️
