### ISSUE TITLE
[FEAT]: Add resources to customize OIDC subject claims

### ISSUE THREAD

**Issue by F21** [integrations/terraform-provider-github#1458]
### Describe the need

I would like to be able to customize OICD subject claims for GitHub actions on a per-repo or per-organization basis.
This can be accomplished via the API, but it would be really great if we can do this in Terraform too.

Docs: https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#customizing-the-subject-claims-for-an-organization-or-repository
API: https://docs.github.com/en/rest/actions/oidc#set-the-customization-template-for-an-oidc-subject-claim-for-a-repository

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment]
@F21 I agree this would be a nice feature! Do you have any interest in opening up a PR for this behavior?

**Comment by F21** [comment]
@kfcampbell Sure! Definitely happy to open a PR for this, but we need to get this supported in https://github.com/google/go-github first, so I logged https://github.com/google/go-github

**Comment by kfcampbell** [comment]
@F21 thank you! You rock.

**Comment by F21** [comment]
This can be implemented once https://github.com/google/go-github/pull/2615 is merged.
