### ISSUE TITLE
Unable to set different contexts for different repos

### ISSUE THREAD

**Issue by Karthikraja9** [integrations/terraform-provider-github#1474]
### Describe the need

What I am trying to do: 

I am using terraform module for github_branch_protection; when I try to set the branch protection, I would like to set required_pull_request_reviews in a few repos and required_status_checks on a few others.

resource "github_branch_protection" "branch_protection" {
  #for_each = toset(var.repository_names)
  repository_id = github_repository.main.node_id
  pattern     = var.repository_default_branches

  required_pull_request_reviews {
    required_approving_review_count = var.review_count
  }

  required_status_checks {
    strict   = var.strict
    contexts = [var.strict == "true" ? "gitStream.cm" : "none"]
  }
}

Is there any way I can make the terraform ignore required_status_checks block in the module?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment]
Hmm...that sounds like a Terraform/HCL question rather than one with the branch protection resource. Perhaps it's possible to use a [conditional expression](https://developer.hashicorp.com/terraform/language/expressions/conditionals) somehow?
