### ISSUE TITLE
[FEAT]: Add support for required_workflows APIs

### ISSUE THREAD

**Issue by fproulx-boostsecurity** [integrations/terraform-provider-github#1475]
### Describe the need

Required workflows is a really cool new feature that should be supported via terraform.

https://docs.github.com/en/rest/actions/required-workflows?apiVersion=2022-11-28#create-a-required-workflow

### API Version

2022-11-28

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aitorpazos** [comment]
Is anyone working on this already?

**Comment by kfcampbell** [comment]
@aitorpazos please feel free to open up a PR if you'd like! To the best of my knowledge nobody is working on it at the moment. You can find our [CONTRIBUTING.md here](https://github.com/integrations/terraform-provider-github/blob/main/CONTRIBUTING.md).

**Comment by sam-robson** [comment]
Happy to pick this up if no one is working on it. Will need to wait for the next go-github release (to pick up [this bug fix](https://github.com/google/go-github/commit/daa96df75b7cd073beac60ebd619343fe7d4491f)), but then I can get started if no one objects.

**Comment by sam-robson** [comment]
> Hi @sam-robson , do you have any news on this? Thanks!

Hey @philippeboyd, I have a PR ready to go, but I am still waiting for the next go-github release

**Comment by sam-robson** [comment]
Ran into a significant bump here - it looks as if GitHub are in the process of scrapping Required Workflows, see [this comment](https://github.com/integrations/terraform-provider-github/pull/1741#issuecomment-1596809915) on the PR for more details.

**Comment by sam-robson** [comment]
I've received a response to my support ticket, for those interested:

"Required workflows are being brought back from public to private beta. Organizations that are already utilising required workflows will still be able to access them however no new organisations will be signed up to the beta.

Required workflows are being moved into the new Repository Rules - currently in [Public Beta](https://github.blog/changelog/2023-04-17-introducing-repository-rules-public-beta/). The workflow functionality is not available at this stage, however it is expected to be before the planned date for Repository Rules to be generally available around July 31st."
