### ISSUE TITLE
Terraform apply result in an error creating a team

### ISSUE THREAD

**Issue by ilmax** [integrations/terraform-provider-github#1497]
I'm running into something strange here. I have a GitHub enterprise account and I would like to create several teams in an organization, here's the simplified hcl code:

Please note that I'm authenticating with an access token 

```tf
terraform {
  required_providers {
    github = {
      source  = "integrations/github"
      version = "~> 5.15.0"
    }
  }
}

provider "github" {
  owner = "myOrg"
}

locals {
  teams = [
    {
      name        = "team1",
      description = "team1 description"
    },
    {
      name        = "team2",
      description = "team2 description"
    },
    {
      name        = "team3",
      description = "team3 description"
    }
  ]
}


resource "github_team" "team" {
  name        = each.value.name
  description = each.value.description
  privacy     = "closed"

  for_each = { for team in local.teams : team.name => team }
}
```

This code fails with:

```tf
╷
│ Error: non-200 OK status code: 401 Unauthorized body: "{\"message\":\"Personal access tokens with fine grained access do not support the GraphQL API\",\"documentation_url\":\"https://docs.github.com/graphql/guides/forming-calls-with-graphql#authenticating-with-graphql\"}"
│
│   with github_team.team["team3"],
│   on main.tf line 34, in resource "github_team" "team":
│   34: resource "github_team" "team" {
│
╵
╷
│ Error: non-200 OK status code: 401 Unauthorized body: "{\"message\":\"Personal access tokens with fine grained access do not support the GraphQL API\",\"documentation_url\":\"https://docs.github.com/graphql/guides/forming-calls-with-graphql#authenticating-with-graphql\"}"
│
│   with github_team.team["team2"],
│   on main.tf line 34, in resource "github_team" "team":
│   34: resource "github_team" "team" {
│
╵
╷
│ Error: non-200 OK status code: 401 Unauthorized body: "{\"message\":\"Personal access tokens with fine grained access do not support the GraphQL API\",\"documentation_url\":\"https://docs.github.com/graphql/guides/forming-calls-with-graphql#authenticating-with-graphql\"}"
│
│   with github_team.team["team1"],
│   on main.tf line 34, in resource "github_team" "team":
│   34: resource "github_team" "team" {
│
```

The funny thing is that teams actually gets created:

![image](https://user-images.githubusercontent.com/3263338/213711832-3a9858d6-7b89-4eb7-ad02-e8a0831b20f6.png)

I verified that PAT (a fine graded PAT) has organization permissions Read and Write for Members.

Apparently the issue is caused by the call to `removeDefaultMaintainer` that seems to execute a graphql api call that doesn't supports the new token format.
I think this may be pointed out in the documentation to raise awareness.
Looking at the code, I was also thinking if it's possible to use the [ListTeamMemberById](https://github.com/google/go-github/blob/master/github/teams_members.go#L27) api call to avoid this limitation altogether.

**Comment by kfcampbell** [comment]
Are you using GitHub Enterprise Server or GitHub Enterprise Cloud? Would you mind giving the version if you do use GHES? I'm unable to reproduce this with a standard free GitHub org account.

**Comment by ilmax** [comment]
I'm using GitHub enterprise cloud. I was looking at the log and the graphql call to find the members of the group returns an error. Just make sure you are using the new beta PAT

**Comment by niels-s** [comment]
We are also using the new fine-grained PAT tokens for our organization (not using enterprise GH). We are using version v5.8.0.

**Comment by ilmax** [comment]
@niels-s if you set 

```tf
create_default_maintainer = true
```

on the `github_team` resource, you can move on successfully but I think this can be changed in the provider to avoid the error altogether

**Comment by ilmax** [comment]
Actually we can change the provider to not use the graphql api to get the team members. I may look into picking this one up soon-ish™

**Comment by mecostav** [comment]
hello! 

it appears that i can replicate this issue. the `github_repository` is created just fine, however its on the team creation part that i get this error 

```bash
╷
│ Error: non-200 OK status code: 401 Unauthorized body: "{\"message\":\"Personal access tokens with fine grained access do not support the GraphQL API\",\"documentation_url\":\"https://docs.github.com/graphql/guides/forming-calls-with-graphql#authenticating-with-graphql\"}"
│ 
│   with module.test_project_app_repo.module.repo_team_admin.github_team.team,
│   on modules/github/team/team.tf line 1, in resource "github_team" "team":
│    1: resource "github_team" "team" {
│ 
```

same as before the teams are created just fine, but the resource error's out anyway.
