### ISSUE TITLE
Terraform fails to import github_team_repository with Github team slug as team_id

### ISSUE THREAD

**Issue by pradeepbhadani** [integrations/terraform-provider-github#1498]
## Issue Description

`github_team_repository` accepts `Github team slug` which is a `string` as  valid `team_id` argument. However, when importing this resource, `team_id` only expects a `numeric` value and throws below error if using a `Github team slug` (which is a `string` value),

```
$> terraform import 'github_team_repository.teams' team-a:test-repo
Acquiring state lock. This may take a few moments...
github_team_repository.teams: Importing from ID "team-a:test-repo"...
github_team_repository.teams: Import prepared!
  Prepared github_team_repository for import
github_team_repository.teams: Refreshing state... [id= team-a:test-repo]
╷
│ Error: Unexpected ID format ("team-a"), expected numerical ID. strconv.ParseInt: parsing "team-a": invalid syntax

```

## Terraform version
Terraform v1.3.2

## Provider Version
Github v5.15.0

## Affected Resource(s)
Please list the resources as a list, for example:
* github_team_repository

## Expected Behavior
Successful Import

## Actual Behavior
Terraform import fails with the mentioned error

```
$> terraform import 'github_team_repository.teams' team-a:test-repo
Acquiring state lock. This may take a few moments...
github_team_repository.teams: Importing from ID "team-a:test-repo"...
github_team_repository.teams: Import prepared!
  Prepared github_team_repository for import
github_team_repository.teams: Refreshing state... [id= team-a:test-repo]
╷
│ Error: Unexpected ID format ("team-a"), expected numerical ID. strconv.ParseInt: parsing "team-a": invalid syntax


```

## Steps to Reproduce
1. Run Terraform import command with `team_id` as `string` value

**Comment by jo-hoenzsch-s1** [comment]
Would love to see this resolved. Ran into this myself and it would save me a lot of time to have this.
