### ISSUE TITLE
[BUG]: Diff detection not working for security_and_analysis features

### ISSUE THREAD

**Issue by danielpops** [integrations/terraform-provider-github#1505]
github.com/Yelp/paasta shows secret scanning enabled in the UI:
<img width="1577" alt="image" src="https://user-images.githubusercontent.com/10519220/213831492-77e51d8f-d8d7-437e-b403-0c5fd03b0a30.png">

## Expected
The terraform plan should show no change or show a diff.

## Actual

Setting it to enabled or disabled in terraform doesn't reflect the correct diff (it always shows as an add)

Value in terraform matches what's configured on the repo:

```
  # github_repository.repo["paasta"] will be updated in-place
  ~ resource "github_repository" "repo" {
        id                          = "paasta"
        name                        = "paasta"
        # (32 unchanged attributes hidden)

      + security_and_analysis {

          + secret_scanning {
              + status = "enabled"
            }
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.

```

Value in terraform doesn't match what's configured on the repo:

```
Terraform will perform the following actions:

  # github_repository.repo["paasta"] will be updated in-place
  ~ resource "github_repository" "repo" {
        id                          = "paasta"
        name                        = "paasta"
        # (32 unchanged attributes hidden)

      + security_and_analysis {

          + secret_scanning {
              + status = "disabled"
            }
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.

```

**Comment by danielpops** [comment]
FWIW, it does show proper diff detection once the setting has already been managed by terraform

```
Terraform will perform the following actions:

  # github_repository.repo["paasta"] will be updated in-place
  ~ resource "github_repository" "repo" {
        id                          = "paasta"
        name                        = "paasta"
        # (32 unchanged attributes hidden)

      ~ security_and_analysis {

          ~ secret_scanning {
              ~ status = "enabled" -> "disabled"
            }
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

**Comment by kfcampbell** [comment]
Hmm...I'm not sure I can reproduce this. Here's the steps I took:

- Used latest main branch of provider and set up local development according to the steps in our [CONTRIBUTING.md](https://github.com/integrations/terraform-provider-github/blob/main/CONTRIBUTING.md#local-development-setup)
- Created a `main.tf` file with the following HCL:
```hcl
terraform {
  required_providers {
    github = {
      source  = "integrations/github"
      version = "~> 5.15.0"
    }
  }
}

provider "github" {
  # owner = "kfcampbell-terraform-provider" # defined in environment
  # token = "" # defined in environment
}

resource "github_repository" "testRepo" {
  name = "1505-experiments"
  auto_init = true
}
```
- Run `terraform apply` and see repository created appropriately
- Run `terraform plan` and see no changes to configuration
- Manually enable secret scanning in the UI
- Run `terraform apply` again, see no changes to configuration

I'm not seeing an add for it anywhere. What am I doing wrong here?

**Comment by kfcampbell** [comment]
Closing this issue due to lack of response recently. Please reopen if there's still appetite here.
