### ISSUE TITLE
[Bug] Import github_team_member return 404 not found

### ISSUE THREAD

**Issue by vuanhson** [integrations/terraform-provider-github#1508]
Not sure this bug happen only with me or other, so I raise it here. 
This happen with `github_team_members` only, I think because of terraform set organization id of endpoint URL to 0 instead of correct ID when doing api call, which lead to 404 error. I already set GITHUB_OWNER to correct organization ID

<img width="876" alt="Screen Shot 2023-01-25 at 13 48 18" src="https://user-images.githubusercontent.com/6960172/214482487-132b81fe-b433-4a7d-ae6e-0a0dc6cbbee6.png">

Expected output: import successful
Actual output: 404 not found
Terraform version: 1.3.7
Github Provider version: 5.16.0
You can reproduce this by doing terraform import or plan with target is `github_team_members` resources. Plan/apply on other resource type run fine, no problem.

**Comment by kfcampbell** [comment]
Can you share a snippet of HCL that reproduces this issue? I'm not seeing any likely culprits in the code currently.

**Comment by vuanhson** [comment]
@kfcampbell 
This is my self-made module
```
resource "github_team_members" "default" {
  team_id = var.team_id
  dynamic "members" {
    for_each = var.members
    content {
      username = members.key
      role     = members.value
    }
  }
}
```

and the member code

```
module "sre" {
  source  = "./modules/github_team_members"
  team_id = github_team.sre.id
  members = {
    # Role: maintainer
    (github_membership.abc123.username)  = "maintainer",
    (github_membership.def456.username)   = "maintainer",
    # Role: member
    (github_membership.ghi789.username) = "member",
    (github_membership.jkl012.username)  = "member",
  }
}
```
I'm not surprise if 404 happen with all resource type (repository, membership etc..), it can be mistake from my end, but it only happen with `github_team_members`, so idk how to deal with it.
I'm using App to authenticate terraform, granted Repository (Administration RW + Contents RW) + Org (Custom repository roles RW + Members RW) if permission is related to this problem

**Comment by kfcampbell** [comment]
Hmm...is that all the code required for the "sre" module? I've dumped both snippets in a main.tf file but I'm not able to initialize it.

**Comment by vuanhson** [comment]
I found out problem is I didn't set the `required_providers` for the module so instead of pulling for the new integrations/github it using the old hashicorp/github
