### ISSUE TITLE
Always create resource when apply

### ISSUE THREAD

**Issue by mvn-bachhuynh-dn** [integrations/terraform-provider-github#151]
### Terraform Version
terraform -v                                                                                          
Terraform v0.11.8
+ provider.github v1.2.1

### Affected Resource(s)
github_membership

### Expected Behavior
0 to add, 0 to change, 0 to destroy

### Actual Behavior
```
 bach.huynh@Bachs-MacBook-Pro  terraform apply                                                                                            203.205.52.100 
github_membership.at-bachhuynh: Refreshing state... (ID: tsrnd:at-bachhuynh)

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + github_membership.at-bachhuynh
      id:       <computed>
      role:     "admin"
      username: "at-bachhuynh"

  + github_membership.ml-bach-huynh
      id:       <computed>
      role:     "member"
      username: "ml-bach-huynh"


Plan: 2 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value:
```

### Steps to Reproduce
1. `terraform apply`
2. yes (to confirm)
3. `terraform apply` (Again)
4. Issue happen.

**Comment by radeksimko** [comment]
Hi @at-bachhuynh ,
to better understand the issue & make it reproducible would you mind sharing more details? Specifically I'm interested in a [debug log](https://www.terraform.io/docs/internals/debugging.html) from terraform commands you ran (minus any secrets).

Feel free to use [our GPG key](https://keybase.io/hashicorp) to encrypt it and/or send it privately to radek@hashicorp.com if you worry about sensitive data in this log.

Thanks.
