### ISSUE TITLE
When a repo is marked as archived any permissions other than `pull` show delta in plan

### ISSUE THREAD

**Issue by majormoses** [integrations/terraform-provider-github#153]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
```
$ terraform --version
Terraform v0.11.7
```
### Affected Resource(s)
Please list the resources as a list, for example:
- `github_repository`
- `github_team_repository`

### Terraform Configuration Files
```hcl
# Add a repository to the team
resource "github_team" "some_team" {
  name        = "SomeTeam"
  description = "Some cool team"
}

resource "github_repository" "some_repo" {
  name = "some-repo"
  archived = true # or someone set through the UI
}

resource "github_team_repository" "some_team_repo" {
  team_id    = "${github_team.some_team.id}"
  repository = "${github_repository.some_repo.name}"
  permission = "push"
}

```

### Expected Behavior
`github_team_repository` team should see that the repo is archived and not attempt to update permissions.

### Actual Behavior
It shows up in our plans until resource is removed

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`
1. `terraform apply`

**Comment by rogersbernat** [comment]
Detected the same behavior with newer versions: 

```
Terraform v0.12.24
+ provider.github v2.4.1
```

When a plan rans on a folder with an archived repo, it shows permissions need to be changed from "**pull**" to " **push**" or viceversa. Changing the permissions in the **.tf** file does not fix the issue as it appears again.


It is a good idea to exclude the archived repos from updating permissions, as they are automatically changed to RO in Github: there's no way to change them using github console.

Meanwhile is there a recommendation to workaround this bug?  Is it in your plans to fix it for this 2020? 

Many thanks in advance.
