### ISSUE TITLE
[BUG] github_branch_protection_v3 `checks` does not allow for colons

### ISSUE THREAD

**Issue by mbarany** [integrations/terraform-provider-github#1531]
If my status check context includes a colon then it fails.
Our CircleCi jobs for example `ci/circleci: unit_test` produces the following error:
```
Error: Could not parse unit_test:-1 as valid app_id
```

Potential solutions are:
- Use a different different character to split the string
- Separate out the context and app_id as separate input variables (e.g. `checks = [ { context = "ci/circleci: unit_test", app_id = 1234 } ]`

[Link to original "checks" feature PR](https://github.com/integrations/terraform-provider-github/pull/1415)

**Comment by nickschuch** [comment]
For those looking for a workaround.....

It's not great :D

Revert back to using the depreciated `contexts` field.
