### ISSUE TITLE
[FEAT]: all org members(users) data source

### ISSUE THREAD

**Issue by mac2000** [integrations/terraform-provider-github#1532]
### Describe the need

Will be nice to have GitHub org members data source so me may retrieve all members and their public email if it is available

Use case: make sure that github org does not contain deactivated active directory members

Current impl: we ask teammates to make sure that GitHub account they are using have publicly available work email, so script that sync members can rely on it (e.g. if by mistake you will make your email private or personal, script will just kick you out of org)

Yes, I know, there are enterprise'ish plans everywhere, so everything may be in sync out of the box, it is just an use case example

I was able to retrieve [azuread users](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/data-sources/users) list successfully, but it seems that in github provider both [users](https://registry.terraform.io/providers/integrations/github/latest/docs/data-sources/users) and [members](https://registry.terraform.io/providers/integrations/github/latest/docs/data-sources/membership) are requiring user list to be retrieved

Wondering if that option may be set as optional, so if not set, whole list is returned, something like:

```graphql
query getAllMembers($org:String!,$after:String) {
  organization(login:$org) {
    membersWithRole(first:100,after:$after) {
      nodes {
        id
        login
        email
      }
    }
  }
}
```

somewhere [here](https://github.com/integrations/terraform-provider-github/blob/main/github/data_source_github_users.go#L79) as an else statement:

<img width="498" alt="image" src="https://user-images.githubusercontent.com/88868/216819487-caef8af1-987c-45bd-bed7-3c4a027cf048.png">

which technically should solve this feature request and will be backward compatible

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment]
@mac2000 do you have any interest in opening a PR to implement this behavior?

**Comment by mac2000** [comment]
while we are waiting for an review and approve for emails, here is how we can receive member role from an graphql side:

```gql
query  {
  organization(login:"your_org_name") {
    membersWithRole(first:100) {
      edges {
        role # ADMIN, MEMBER
        node { id login }
      }
    }
  }
}
```

not sure yet if this will be as easy as emails addition, but i bed that when it will come to part two with reading all users it definitely will become clear
