### ISSUE TITLE
[FEAT]: Environment Variables for Github Actions

### ISSUE THREAD

**Issue by FritzerMcQ** [integrations/terraform-provider-github#1534]
### Describe the need

Github created the possibility to set environment variables for github actions. This feature is already reflected in the newest REST API version of github: 2022-11-28.
Documentation example [here](https://docs.github.com/en/rest/actions/variables?apiVersion=2022-11-28#create-an-environment-variable).
It seems like, the environment variables are pretty similar to the already here implemented environment secrets.

### API Version

2022-11-28

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by KamranBiglari** [comment]
It's really useful to have this feature. I can move my non-sensitive variables from secret and directly use them as environment variable instead of secret in specific environment.

**Comment by pr1ntr** [comment]
really need this. :)

**Comment by eowoyn** [comment]
+1 please

**Comment by kishaningithub** [comment]
https://github.com/google/go-github/pull/2652 has been released in [v50.1.0](https://github.com/google/go-github/releases/tag/v50.1.0) can we bump [go-github](https://github.com/google/go-github) to this version?

**Comment by JeffPignataro-BillGO** [comment]
Any idea if these will make it into the next release? I'm very eager to be able to control our environment variables via Terraform.
