### ISSUE TITLE
Plugin.(*GRPCProvider).UpgradeResourceState request was cancelled & Error: The terraform-provider-github_v4.25.0 plugin crashed!

### ISSUE THREAD

**Issue by shivakumar-ralla** [integrations/terraform-provider-github#1536]
### Describe the need

# Hello.

We are configuring the github provider with organization and github_token for authentication. As we are able to deploy using terraform configuration previously. Now recently we are facing multiple issues/errors with the provider as below.

`The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.`

`Error: The terraform-provider-github_v4.25.0 plugin crashed!`

`This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.`

We are using the below versions.

**Terraform Version**
1.0.1

**Terraform Configuration Files**

```yaml

terraform {
  required_version = ">= 1.0.1"

  required_providers {
    github = {
      source  = "hashicorp/github"
       version = "= 4.25.0"
    }
  }
}

provider "github" {
  token= "=var.github_token"
  owner= "example-org"
}

```
**Expected Behavior**
I'd expect it to create my environments and github team.

**Actual Behavior**

We tried to update the github provider version to latest and terrform version to latest also , and we are facing the same error , Can any one please provide the solution , how to fix the error.

`The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.`

`Error: The terraform-provider-github_v4.25.0 plugin crashed!`

`This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.`

### Relevant log output

```yaml
tack trace from the terraform-provider-github_v5.17.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x78 pc=0xe20710]

goroutine 197 [running]:
github.com/integrations/terraform-provider-github/v5/github.resourceGithubRepositoryEnvironmentRead(0xc0001727e0, {0xeb62c0?, 0xc000201280?})
	github.com/integrations/terraform-provider-github/v5/github/resource_github_repository_environment.go:128 +0x4b0
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0001ab040, 0xc0005329b0, {0xeb62c0, 0xc000201280})
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/resource.go:470 +0x1aa
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc00009ef30, {0xc00056ea80?, 0x4b86c6?}, 0xc00056ea80)
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/helper/plugin/grpc_provider.go:535 +0x34b
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler({0x1060aa0?, 0xc00009ef30}, {0x12c9a50, 0xc00068c4e0}, 0xc00056ea20, 0x0)
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/tfplugin5/tfplugin5.pb.go:3269 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001baa80, {0x12cd1a0, 0xc0000a2ea0}, 0xc00068e000, 0xc000292f60, 0x19895d0, 0x0)
	google.golang.org/grpc@v1.46.2/server.go:1283 +0xcfd
google.golang.org/grpc.(*Server).handleStream(0xc0001baa80, {0x12cd1a0, 0xc0000a2ea0}, 0xc00068e000, 0x0)
	google.golang.org/grpc@v1.46.2/server.go:1[620](https://github.com/OS-Runway/Anvil/actions/runs/4121827075/jobs/7117899521#step:7:621) +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.46.2/server.go:922 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.46.2/server.go:920 +0x28a

Error: The terraform-provider-github_v5.17.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by kfcampbell** [comment]
@Shivakumar-2020 does this happen when specifying `source  = "integrations/github"` as well as `source  = "hashicorp/github"`?

**Comment by kfcampbell** [comment]
Can you please provide a small snippet of sample code that can reproduce this issue?

**Comment by julbugreporter** [comment]
We encountered the same error with the same integrations/github above version or latest 5.23.0. The issue seems to occur during Terraform Refreshing state.
- When we use the same token, we can create a new repo via GitHub API, but it failed to create a new repo with Terraform because it has already failed at Terraform refreshing state earlier. As a result, GitHub Support mentioned that GitHub API is working well and the error does not come from GitHub's backend. 
- The issue for Terraform GitHub provider temporarily goes away each time we regenerate a new github token for authentication.

Is there any limitation for Terraform Refreshing State?

**Comment by prabha-reddy** [comment]
> @Shivakumar-2020 does this happen when specifying `source = "integrations/github"` as well as `source = "hashicorp/github"`?

Is it fixed @kfcampbell 
We are also having the same issue:
TF Version: ```
(Terraform v1.5.1
on linux_amd64)
``` and provider ```
( required_providers {
    github = {
      source  = "integrations/github"
      version = "~> 5.28.0"
    })
```
We are getting the error while TF refresh for "github_repository_environment" , "github_repository_file" and "additional_repo_permissions"

Hey @kfcampbell Can we use (source = "hashicorp/github")?

**Comment by kfcampbell** [comment]
> Is it fixed @kfcampbell

No, not yet. Can you share a simplified HCL file to reproduce? 

> Hey @kfcampbell Can we use (source = "hashicorp/github")?

Hashicorp's version of the plugin was transferred here...3 years ago? If you'd like to use the old version, you may, but you'll be missing all new features and bugfixes added since the transfer. It's not recommended.

**Comment by prabha-reddy** [comment]
Thanks for the reply @kfcampbell 
It's happening while Terraform refresh for "github_repository_environment" ,"github_repository_file" and "additional_repo_permissions" resources.

May I know,Is GitHub team working on this or any ETA on the issue would be helpful. Thanks!

**Comment by kfcampbell** [comment]
@prabha-reddy GitHub's SDK team unfortunately does not get the time to do feature development ourselves on these issues. PRs are appreciated though!
