### ISSUE TITLE
[BUG]: Using spaces in environment names does not work

### ISSUE THREAD

**Issue by BenHall-1** [integrations/terraform-provider-github#1545]
## Context

When creating an environment with spaces using "github_repository_environment" "enviroment", the environment name gets URL encoded, rather than the spaces being parsed as spaces, they are changed to +

**Example**:
```tf
resource "github_repository_environment" "enviroment" {
  repository = "testrepo"
  environment = "Test - Env"
}
```

## Expected Outcome

The env will be created with the name "Test - Env"

## Actual Outcome

The env is created as "Test+-+Env"

## Related

Looks like this was related to #1392 where a change was made to support "/" characters inside environment names

**Comment by calebworks** [comment]
This bug also prevents *importing* environments with spaces in their names, which results in the following error:

```
│ Error: Cannot import non-existent remote object
│
│ While attempting to import an existing object to "module.repositories[\"redacted\"].github_repository_environment.main[\"sample
│ environment\"]", the provider detected that no object exists with the given id. Only pre-existing objects can be imported; check that the id is correct
│ and that it is associated with the provider's configured region or endpoint, or use "terraform apply" to create a new remote object for this
│ resource.
```

**Comment by nint8835** [comment]
I ran into this problem, I see what the cause is and am currently working on a fix.
