### ISSUE TITLE
[FEAT]: Creating "environment variables" (not secrets) missing

### ISSUE THREAD

**Issue by clemenstan** [integrations/terraform-provider-github#1550]
### Discussed in https://github.com/integrations/terraform-provider-github/discussions/1549

<div type='discussions-op-text'>

<sup>Originally posted by **clemenstan** February 15, 2023</sup>
Hello, 
Github just release this year the option to also create "environment variables" instead of only "environment secrets" in for github deployment environments. 
Could you please add this feature to the Github-Provider?
Thanks in prior!

Best 
Clemens</div>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ViacheslavKudinov** [comment]
Isn't it duplication of https://github.com/integrations/terraform-provider-github/issues/1534 ?

**Comment by clemenstan** [comment]
Oh, sorry, I haven't found that one. Yes, this is then a dublication.
