### ISSUE TITLE
[BUG]: Cannot create github_actions_runner_group resource

### ISSUE THREAD

**Issue by shanee-spring** [integrations/terraform-provider-github#1553]
I can't create the github_actions_runner_group resource.
I also tried to import it and then run a terraform plan and I see the same error logs.

Versions:
```
$ terraform --version
Terraform v1.3.9
on darwin_amd64
+ provider registry.terraform.io/integrations/github v5.17.0
```

```
╷
│ Error: Plugin did not respond
│
│   with github_actions_runner_group.this["test"],
│   on runners.tf line 52, in resource "github_actions_runner_group" "this":
│   52: resource "github_actions_runner_group" "this" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
Releasing state lock. This may take a few moments...

Stack trace from the terraform-provider-github_v5.17.0 plugin:

panic: interface conversion: interface {} is []interface {}, not []string

goroutine 57 [running]:
github.com/integrations/terraform-provider-github/v5/github.resourceGithubActionsRunnerGroupCreate(0x1b32820?, {0x1ab48c0?, 0xc00061a580})
	github.com/integrations/terraform-provider-github/v5/github/resource_github_actions_runner_group.go:92 +0x9ca
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc00066e960, 0xc0003060a0, 0xc0002eb6c0, {0x1ab48c0, 0xc00061a580})
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/resource.go:320 +0x438
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc000147a80, 0xc0002319a0, 0x1cadf9a?, 0xf?)
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/provider.go:294 +0x70
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc0001210d0, {0xc000371b20?, 0x10b3c46?}, 0xc000371b20)
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/helper/plugin/grpc_provider.go:895 +0x7c5
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x1c60420?, 0xc0001210d0}, {0x1ec8710, 0xc00057f290}, 0xc000123a40, 0x0)
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/tfplugin5/tfplugin5.pb.go:3305 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00023aa80, {0x1ecbee0, 0xc0006424e0}, 0xc0005b6000, 0xc0003e5320, 0x258c7a0, 0x0)
	google.golang.org/grpc@v1.46.2/server.go:1283 +0xcfd
google.golang.org/grpc.(*Server).handleStream(0xc00023aa80, {0x1ecbee0, 0xc0006424e0}, 0xc0005b6000, 0x0)
	google.golang.org/grpc@v1.46.2/server.go:1620 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.46.2/server.go:922 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.46.2/server.go:920 +0x28a

Error: The terraform-provider-github_v5.17.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by aminzar-access** [comment]
Any update on this? Thanks

**Comment by kfcampbell** [comment]
Hi @aminzar-access, the GitHub SDK team has been focused on other feature work recently. Unfortunately Nick and I don't get the chance to directly fix issues like this super often. If you'd like to investigate or put up a PR yourself, please feel free!

**Comment by harshal-shah** [comment]
Hi, I noticed the error while trying to create an actions runner group. This was probably [introduced](https://github.com/integrations/terraform-provider-github/pull/1513) in v5.17.0. Using v5.16.0 of the provider helped me mitigate the issue for now.

**Comment by kfcampbell** [comment]
Hmm...@harshal-shah, do you think it's worth reverting #1513?

**Comment by v-rosa** [comment]
I've faced this issue and using v5.20 I was able to create the runner groups.

**Comment by robert-spring** [comment]
i've tried every version up to 5.25 and i still get the error :(

**Comment by pnag90** [comment]
Same here:

`│ Error: Plugin did not respond
│
│   with github_actions_runner_group.default,
│   on github.tf line 16, in resource "github_actions_runner_group" "default":
│   16: resource "github_actions_runner_group" "default" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-github_v5.25.0 plugin:

        google.golang.org/grpc@v1.50.1/server.gonil pointer dereference:1340 +0xd13
google.golang.org/grpc.(*Server).handleStream(0xc0000001e0, {0x15ee948, 0xc000583ba0}, 0xc000668240, 0x0)
        google.golang.org/grpc@v1.50.1/server.go:1713 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.50.1/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.50.1/server.go:963 +0x28a

Error: The terraform-provider-github_v5.25.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.`

**Comment by kfcampbell** [comment]
I think #1633 is a duplicate of this issue. Generally the cause of the problem is insufficient token permissions, which the provider should handle more gracefully.

**Comment by jkruse14** [comment]
@shanee-spring - how are you authorizing the provider? i just found apps don't support all endpoints - [here](https://docs.github.com/en/rest/overview/endpoints-available-for-github-apps?apiVersion=2022-11-28)
