### ISSUE TITLE
Plugin did not respond

### ISSUE THREAD

**Issue by sindhurakls** [integrations/terraform-provider-github#1562]
Error: Plugin did not respond
│
│   with github_repository_webhook.example_webhook,
│   on s3.tf line 37, in resource "github_repository_webhook" "example_webhook":
│   37: resource "github_repository_webhook" "example_webhook" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs    
│ may contain more details.
╵

Stack trace from the terraform-provider-github_v5.18.0.exe plugin:

panic: interface conversion: interface {} is nil, not bool

goroutine 29 [running]:
github.com/integrations/terraform-provider-github/v5/github.resourceGithubRepositoryWebhookObject(0xc0006c1620?)
        github.com/integrations/terraform-provider-github/v5/github/resource_github_repository_webhook.go:95 +0x35c
github.com/integrations/terraform-provider-github/v5/github.resourceGithubRepositoryWebhookCreate(0x19dbd20?, {0x1949f20?, 0xc0003488c0})
        github.com/integrations/terraform-provider-github/v5/github/resource_github_repository_webhook.go:109 +0xbd
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc00040a1e0, 0xc0000770e0, 0xc00065c260, {0x1949f20, 0xc0003488c0})
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/resource.go:320 +0x438
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc000079b80, 0xc0006c18c8, 0x1b8f386?, 0xf?)
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/provider.go:294 +0x70
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc000006ad8, {0xc00065a150?, 0xe2a1a6?}, 0xc00065a150)
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/helper/plugin/grpc_provider.go:895 +0x7c5
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x1b39700?, 0xc000006ad8}, {0x1ed6720, 0xc0005be180}, 0xc00065a0e0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/tfplugin5/tfplugin5.pb.go:3305 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00016e000, {0x1eda2e8, 0xc0000844e0}, 0xc0007bc000, 0xc00061b470, 0x26babc0, 0x0)
        google.golang.org/grpc@v1.50.1/server.go:1340 +0xd13
google.golang.org/grpc.(*Server).handleStream(0xc00016e000, {0x1eda2e8, 0xc0000844e0}, 0xc0007bc000, 0x0)
        google.golang.org/grpc@v1.50.1/server.go:1713 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.50.1/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.50.1/server.go:963 +0x28a

Error: The terraform-provider-github_v5.18.0.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by kfcampbell** [comment]
@sindhurakls can you please share a snippet of HCL we can use to reproduce this issue?

**Comment by kfcampbell** [comment]
Closing this now due to lack of response; please feel free to reopen if warranted.
