### ISSUE TITLE
[FEAT]: Support `node_id` as repository reference for all resources

### ISSUE THREAD

**Issue by stefan-hartmann-lgs** [integrations/terraform-provider-github#1573]
### Describe the need

Whenever resources are used which reference a repository, sometimes the repository `name` must be used and sometimes there is support for `node_id`.

The `node_id` has the big advantage that if the repository is renamed aka the `name` changes the resources will not be destroyed and re-created.

There is support for `node_id` for instance in e.g https://registry.terraform.io/providers/integrations/github/latest/docs/resources/branch_protection

BUT no support for it in:
- https://registry.terraform.io/providers/integrations/github/latest/docs/resources/branch
- https://registry.terraform.io/providers/integrations/github/latest/docs/resources/branch_default

This is a problem especially when using the `branch` resource, because Terraform will destroy the branch (there is code which can not be deleted!) and will re-create it from scratch.

Especially the `branch` resource is therefore not usable for us at all.

Hereby I request the support for `node_id` repository reference for all resources.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment]
I love the idea from a usability perspective. My main concern is that this could lead to an increase in API calls and therefore rate limiting, which has been a problem in the past (and a reason various resources have made changes between using the REST API and the GraphQL API)...this would need to be approached thoughtfully, perhaps with documentation about the API usage before/after.
