### ISSUE TITLE
[MAINT]: Terraform Provider Retrieval Error: Could not retrieve the list of available versions for provider -/artifactory

### ISSUE THREAD

**Issue by Luffy-Yao** [integrations/terraform-provider-github#1575]
### Describe the need

I have a providers.tf below

`terraform {
 required_providers {
    aws = {
       source = "hashicorp/aws"
       version = "\>= 3.0"
    }
    artifactory = {
       source = "registry.terraform.io/jfrog/artifactory"
    }
 }
}

   provider "aws" {
      region = "us-west-2"
      alias  = "west"
   }`

### SDK Version

Terraform: v0.13.0

### Relevant log output

```shell
Terraform v0.13.0
Configuring remote state backend...
Initializing Terraform configuration...

Setup failed: Failed terraform init (exit 1): <nil>

Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider -/artifactory:
provider registry registry.terraform.io does not have a provider named
registry.terraform.io/-/artifactory
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment]
Hi! This issue doesn't appear to be related to the GitHub Terraform provider, which is what this repository is for. You may want to open up an issue elsewhere!
