### ISSUE TITLE
[BUG]: `integrations/github` authentication issues that disappear when using older/retired `hashicorp/github`

### ISSUE THREAD

**Issue by YElyousfi** [integrations/terraform-provider-github#1579]
### Describe the need

I couldn't select bug when creating an issue so I made it under a feature issue. My apologies.

Authenticating via GitHub App doesn't seem to properly pick up the owner as the error message is displaying a blank value. It works perfectly when I use `hashicorp/github` but I get an error when I use `integrations/github`. I've tried setting `GITHUB_OWNER` environment variable as well.

Any idea why this could be happening? Seems to be a bug with the provider not picking up the owner.

Here is my `config.tf`:
```terraform
terraform {
  required_providers {
    archive = {
      source  = "hashicorp/archive"
      version = "~> 2.0"
    }

    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.0"
    }

    github = {
      source  = "integrations/github" # works with hashicorp/github
      version = "~> 5.0" # 5.18.0
    }
  }

  required_version = "~> 1.3.1"
}

provider "github" {
  owner = local.organization 
  app_auth {
    id              = var.github_app_id 
    installation_id = var.github_app_installation_id 
    pem_file        = var.github_app_pem_file_content
  }
}
```

The resources are provisioned in a separate file called `main.tf` in the same directory

<img width="903" alt="image" src="https://user-images.githubusercontent.com/5570159/222983286-950738f0-754f-472e-ab94-746a50d6450e.png">

The error above isn't specific to provisioning a webhook but also occurs when creating a data source to fetch repositories.

This could be related to issue #1231 

### Relevant log output

```shell
Error: this resource can only be used in the context of an organization, "" is a user
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment]
Hmm...we've seen similar issues in the past when using multiple terraform files/modules. Redefining the authentication in each module may do the trick. If you'd like to investigate to discover why this is happening, please feel free!

**Comment by lukas-schmitt-otto** [comment]
i have the same problem
