### ISSUE TITLE
[BUG]: Validation error in `github_team_membership` when using team slug

### ISSUE THREAD

**Issue by PabloPie** [integrations/terraform-provider-github#1583]
### Describe the need

This [PR](https://github.com/integrations/terraform-provider-github/pull/1502) introduced the possibility of using the team slug in the `github_team_membership` resource instead of the ID. The feature doesn't seem to work because the Validation was not changed in [the schema](https://github.com/integrations/terraform-provider-github/blob/b4042f1c704d29f03f9619488a89e085b0b17b96/github/resource_github_team_membership.go#LL29C26-L29C26).

### Relevant log output

```shell
│ Error: Unexpected ID format ("admin"), expected numerical ID. strconv.ParseInt: parsing "admin": invalid syntax
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment]
@PabloPie great catch! Is this something you have any interest in opening up a PR to fix?

**Comment by PabloPie** [comment]
Would removing the Validation be enough? From what I see in other resources there is no validation function: https://github.com/integrations/terraform-provider-github/blob/023587e08dc3302046f6640c22d36069e248e4a0/github/resource_github_team_repository.go#L24-L29

**Comment by kfcampbell** [comment]
@PabloPie that seems like a reasonable solution to me.
