### ISSUE TITLE
Error: Field 'requireLastPushApproval' doesn't exist on type 'BranchProtectionRule'

### ISSUE THREAD

**Issue by enricojonas** [integrations/terraform-provider-github#1586]
Terraform Version

```
Terraform v1.3.9
on linux_amd64
+ provider registry.terraform.io/integrations/github v5.18.0

GHES 3.7.4
```

This problem is there since v5.12.0, it is working fine with v5.11.0. We cannot upgrade because of this. I hope it will work with GHES 3.8.0+ but we cannot be sure. Shouldn't we ensure compatibility with current minor release of GHES at least?

Affected Resource(s)

```
github_branch_protection.main
```

Terraform Configuration Files

```
resource "github_branch_protection" "main" {
  for_each                        = local.repositories
  repository_id                   = github_repository.repos[each.key].id
  allows_deletions                = false
  allows_force_pushes             = false
  enforce_admins                  = true
  pattern                         = "main"
  push_restrictions               = []
  require_conversation_resolution = false
  require_signed_commits          = false
  required_linear_history         = false

  required_pull_request_reviews {
    dismiss_stale_reviews           = true
    dismissal_restrictions          = []
    require_code_owner_reviews      = false
    required_approving_review_count = 1
    restrict_dismissals             = false
  }

  required_status_checks {
    contexts = can(each.value.required_status_checks) ? each.value.required_status_checks : []
    strict   = true
  }
}

```

I have also tried to add require_last_push_approval = false to required_pull_request_reviews but that doesn't help either.

What should have happened?
Branch protection rule should have been applied without error

What actually happened?
Following error is thrown:

```
│ Error: Field 'requireLastPushApproval' doesn't exist on type 'BranchProtectionRule'
│ 
│   with github_branch_protection.main["xxx"],
│   on github_branch_protection.tf line 1, in resource "github_branch_protection" "main":
│    1: resource "github_branch_protection" "main" {
```

Please list the steps required to reproduce the issue, for example:

    terraform apply

**Comment by pascal-hofmann** [comment]
The field was added in 3.8: https://docs.github.com/en/enterprise-server@3.8/graphql/reference/objects

**Comment by seanorama** [comment]
There are many other reports of issues with GHES depending on version, so we will likely always be chasing something that github.com has but GHES doesn't.

How can the provider be updated to not fail if certain features are missing? Or allow defining the GHES version, which ties to a map of support features (versioning).

**Comment by kfcampbell** [comment]
There's been a little bit of discussion around that idea [here](https://github.com/integrations/terraform-provider-github/issues/1090). We should really open a separate issue to track the GHES versioning difficulties.

**Comment by macetw** [comment]
Is there a hope of this being fixed without a big feature of version-tracking?
