### ISSUE TITLE
bug: unset `GITHUB_TOKEN` environment variable taking precedence over `token` provider configuration

### ISSUE THREAD

**Issue by emeraldsanto** [integrations/terraform-provider-github#1592]
### Terraform Version

```bash
> terraform -v
1.3.4
```

### Provider Version

```hcl
terraform {
  required_providers {
    github = {
      source  = "integrations/github"
      version = "5.18.0"
    }
  }
}
```

### Affected Resource(s)

- `github_organization_webhook`

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
// github-runners/_providers.tf
provider "github" {
  owner = "my-org"
  token = var.github_runners_github_pat
}

// github-runners/main.tf
resource "random_password" "webhook-secret" {
  length = 24
}

resource "github_organization_webhook" "default" {
  configuration {
    content_type = "json"
    secret       = random_password.webhook-secret.result
    url          = "${aws_apigatewayv2_api.default.api_endpoint}/webhooks"
  }
  events = ["workflow_job"]
}

// terraform-cloud/github-runners.tf
data "tfe_organization" "my-org" {
  name = "my-org"
}

data "tfe_workspace" "github_runners" {
  name         = "github-runners"
  organization = data.tfe_organization.my-org.name
}

variable "github_runners_github_pat" {
  type = string
}

resource "tfe_variable_set" "github_runners" {
  name         = "GitHub Runners"
  description  = "Variables for managing GitHub Actions Self-hosted runners"
  organization = data.tfe_organization.my-org.name
}

resource "tfe_variable" "github_runners_github_pat" {
  category        = "terraform"
  key             = "github_runners_github_pat"
  sensitive       = true
  value           = var.github_runners_github_pat
  description     = "PAT for the runners to register themselves against GitHub"
  variable_set_id = tfe_variable_set.github_runners.id
}

resource "tfe_workspace_variable_set" "github_runners" {
  for_each        = local.github_runners_workspaces
  variable_set_id = tfe_variable_set.github_runners.id
  workspace_id    = data.tfe_workspace.github_runners[each.value].id
}
```

### Debug Output

https://gist.github.com/emeraldsanto/2252c5450d3489e9cf8f9f10ef777b94

### Expected Behavior

```hcl
provider "github" {
  owner = "my-org"
  token = var.github_runners_github_pat
}
```

should authenticate in the same way as

```hcl
provider "github" {}
```

with environment variables `GITHUB_OWNER=my-org` and `GITHUB_TOKEN=xxx`.

### Actual Behavior

When passing in values for `owner` and `token` explicitly

```hcl
provider "github" {
  owner = "my-org"
  token = var.github_runners_github_pat
}
```

the Terraform provider still reached for the empty (unset) `GITHUB_OWNER` variable to determine scope and failed to consider the `token` property, instead stating

```txt
2023-03-10T02:32:27.270Z [DEBUG] provider.terraform-provider-github_v5.18.0: 2023/03/10 02:32:27 [INFO] No token present; configuring anonymous owner.
```

which made the apply fail with

```txt
[31m│[0m [0m[1m[31mError: [0m[0m[1mthis resource can only be used in the context of an organization, "" is a user[0m
[31m│[0m [0m
[31m│[0m [0m[0m  with module.now-iad1-notny.module.github-runners[0].github_organization_webhook.default,
[31m│[0m [0m  on ../../modules/github-runners/main.tf line 5, in resource "github_organization_webhook" "default":
[31m│[0m [0m   5: resource "github_organization_webhook" "default" [4m{[0m[0m
[31m│[0m [0m
[31m╵[0m[0m
2023-03-10T02:32:30.275Z [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF"
2023-03-10T02:32:30.276Z [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/github/5.18.0/linux_amd64/terraform-provider-github_v5.18.0 pid=316
2023-03-10T02:32:30.276Z [DEBUG] provider: plugin exited
Operation failed: failed running terraform apply (exit 1)
```

In order to resolve this, we've had to add the `GITHUB_OWNER` and `GITHUB_TOKEN` with the exact same values as we used explicitly. This resulted in a successful Terraform apply which to me proves that these environment variables take precedence over the explicit configuration.

### Steps to Reproduce

1. Configure the `github` provider with explicit values for `owner` and `token`
2. Create a `github_organization_webhook`
3. `terraform apply`

It should fail with the error `this resource can only be used in the context of an organization, "" is a user`. If you try again with implicit configuration via `GITHUB_OWNER` and `GITHUB_TOKEN` then it should work.

### References

- https://github.com/integrations/terraform-provider-github/issues/501
- https://github.com/integrations/terraform-provider-github/issues/769

**Comment by coyotespike** [comment]
I can confirm that this bug also applies to the following Terraform resources:

- `github_membership`
- `github_branch_protection`

Perhaps a problem with Terraform core? Of course, I prefer to have variables locally defined as this improves code visibility for new team members.

Thanks to @emeraldsanto for reporting this and saving me some hours of frustration!
