### ISSUE TITLE
[FEAT]: Provider add OIDC support to authenticate to GitHub's API

### ISSUE THREAD

**Issue by fproulx-boostsecurity** [integrations/terraform-provider-github#1593]
### Describe the need

GitHub Actions supports OIDC to authenticate to AWS, GCP, Azure, etc. In the context of using terraform provider like this one we are downgrading to using a long term secret (at best the GitHub App Private Key)

I understand that this is not just a problem in the terraform provider and would require GitHub.com itself to allow to get ephemeral tokens through OIDC where we could bind the trust to one highly protected repo (where infrastructure as code happens) with branch protection, environment protection etc...

Is that something you've already considered?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment]
I do wish we had more support for OIDC available. I unfortunately don't have any wisdom on how this might happen internally; contacting GitHub support about it is probably your best bet.
