### ISSUE TITLE
[FEAT]: Add a way to create environment variables

### ISSUE THREAD

**Issue by JFCote** [integrations/terraform-provider-github#1596]
### Describe the need

Hi!

I'm using the resource to create environments with terraform: https://registry.terraform.io/providers/integrations/github/latest/docs/resources/repository_environment

And I see there is a way to create secrets too. https://registry.terraform.io/providers/integrations/github/latest/docs/resources/actions_environment_secret
But I can't find any resources to create the variables.

That would be a nice feature.
Thanks !

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by punkch** [comment]
May be this one?https://registry.terraform.io/providers/integrations/github/latest/docs/resources/actions_environment_variable
