### ISSUE TITLE
[MAINT]: Enable parallelism to increase performance for self hosted Enterprise servers

### ISSUE THREAD

**Issue by Roviluca** [integrations/terraform-provider-github#1597]
### Describe the need

As a self hosted  Github Enterprise user I am not bound to github.com rate limits so I would like to discuss if it is possible to unlock the possibility to have parallel requests.

I understand [your concerns](https://github.com/integrations/terraform-provider-github/pull/235) related to rate limiting and best practices but, in my opinion, it should not limit everyone.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nickfloyd** [comment]
Hey @Roviluca, Thanks for the suggestion. I would love to hear more about how you think this could be solved.  We could do initialization bypasses or something like that.  My least favorite option would be to ship a separate "enterprise" provider where we've implemented the more esoteric concerns of enterprise.

Let us know if you have any ideas and/or would like to take a stab at drafting a PR to express your idea.

Thanks again for the idea and for being involved in our community! ❤️
