### ISSUE TITLE
[FEAT]: github_actions_repository_access_level should set `repository` value

### ISSUE THREAD

**Issue by Serneum** [integrations/terraform-provider-github#1599]
### Describe the need

When importing a `github_actions_repository_access_level` resource, an ID is set based on the repository name, but `repository` is never set. This leads to importing the `github_actions_repository_access_level`, then having to run another plan and apply to set the `repository` value for the `github_actions_repository_access_level` resource.

As a note, I am using v5.16.0 of the Terraform provider, but the recent release notes do not seem to mention anything about addressing this issue, though it is possible I skimmed over it.

### Relevant log output
When checking state:
```shell
terraform state show "module.my-repo.github_actions_repository_access_level.repository_access_level[0]"
# module.my-repo.github_actions_repository_access_level.repository_access_level[0]:
resource "github_actions_repository_access_level" "repository_access_level" {
    access_level = "none"
    id           = "my-repo"
}
```

After a plan:
```
# module.my-repo.github_actions_repository_access_level.repository_access_level[0] will be updated in-place
  ~ resource "github_actions_repository_access_level" "repository_access_level" {
        id           = "my-repo"
      + repository   = "my-repo"
        # (1 unchanged attribute hidden)
    }
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nickfloyd** [comment]
Hey @Serneum, another great catch ❤️m we really appreciate your involvement here. Like the doc change is this something you'd be interested in taking a stab at?  Thanks again for all of the help in making our community better!
