### ISSUE TITLE
[BUG] push_restrictions doesn't actually update

### ISSUE THREAD

**Issue by griseau** [integrations/terraform-provider-github#1611]
I'm having difficulties setting Github Actions bot in push_restrictions setting for github_branch_protection. 
I have the following code : 

```
data "github_app" "github-actions" {
  slug = "github-actions"
}

resource "github_branch_protection" "protection" {
  repository_id  = github_repository.repo.name
  pattern        = var.barnch_name
  enforce_admins = true

  required_pull_request_reviews {
    dismiss_stale_reviews           = true
    required_approving_review_count = 1
  }
  push_restrictions = [
    data.github_app.github-actions.node_id
  ]
}

```

This succeeds to apply, but in Github in only activates push restriction but doesn't allow anyone in this restriction. When trying to re-apply, it seems that no-one is allowed, tries to add it again and successfully terminate, but the issue is still the same, no-one got added. 

Using this version : 
```
terraform {
  required_providers {
    github = {
      source  = "integrations/github"
      version = "~> 5.18"
    }
  }
}
```

Thanks for your help !

**Comment by richardj-bsquare** [comment]
I have a similar terraform configuration, but in my case the push_restriction is set to a named team. In my case the terraform applies okay, and the setting is correct, however, subsequent plans still indicate that `push_restrictions` needs adding to the resource implying that is isn't read into state correctly.

**Comment by tsteele116** [comment]
Have the same issue on 5.41.0
