### ISSUE TITLE
Bug: repository data source returns null instead of error when not found

### ISSUE THREAD

**Issue by kbolino** [integrations/terraform-provider-github#1612]
### Terraform Version

```
Terraform v1.4.2
on linux_arm64
+ provider registry.terraform.io/integrations/github v5.18.3
```

### Affected Resource(s)

- Data source `github_repository`

### Terraform Configuration Files

```hcl
terraform {
  required_version = "~> 1.4"
  required_providers {
    github = {
      source  = "integrations/github"
      version = "~> 5.18"
    }
  }
}

data "github_repository" "this" {
  name = "nonexistent-repo"
}

output "github_repository_id" {
  value = data.github_repository.this.repo_id
}
```

### Debug Output

https://gist.github.com/kbolino/cf42fd736ff5a2befcde4c2fb751300e

### Panic Output

N/A

### Expected Behavior

An error, since the repository does not exist.

While this behavior may not be strictly required by Terraform, it is how other providers (e.g. `aws`) implement singular data sources. There's also nothing in [the docs for the data source](https://registry.terraform.io/providers/integrations/github/latest/docs/data-sources/repository) that would imply it will silently succeed with null results when the repository doesn't exist. 

### Actual Behavior

The apply succeeds but no output is produced.

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `TF_LOG=DEBUG terraform apply`
2. `TF_LOG=DEBUG terraform output github_repository_id`

An example session:

```
vscode ➜ /workspaces/infrastructure/github-demo (main) $ TF_LOG=DEBUG terraform apply
data.github_repository.this: Reading...
data.github_repository.this: Read complete after 1s

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
vscode ➜ /workspaces/infrastructure/github-demo (main) $ TF_LOG=DEBUG terraform output github_repository_id
╷
│ Warning: No outputs found
│ 
│ The state file either has no outputs defined, or all the defined outputs are empty. Please define an output in your configuration with the `output` keyword and run `terraform refresh` for
│ it to become available. If you are using interpolation, please verify the interpolated value is not empty. You can use the `terraform console` command to assist.
╵
```

### Important Factoids

N/A

### References

N/A

**Comment by JSNortal** [comment]
I think this is intended at least according to this PR #1031 

I'm trying to code something against this behaviour. Is this something that will be patched out?
