### ISSUE TITLE
repository settings not applying

### ISSUE THREAD

**Issue by svalevka** [integrations/terraform-provider-github#1623]
Hi,

When I use `github_repository` resource and apply terraform plan, the settings are shown as not updated even after successful apply.
Terraform version used = `1.2.8`
Authentication is done via github app.

How to reproduce

1. Create plan below
```
terraform {
  required_providers {
    github = {
      source  = "integrations/github"
      version = "~> 5.18.3"
    }
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.40.0"
    }
  }
}


resource "github_repository" "repository" {
  name        = "test_repository"
  description = "Test Repository"
  visibility  = "private"

  allow_merge_commit = false
  allow_rebase_merge = false
  allow_squash_merge = true

  auto_init              = true
  has_projects           = true
  has_wiki               = false
  delete_branch_on_merge = true
  topics                 = ["test"]
}
```
Plan applies successfully. 
However each time I run subsequent plan/apply, the message below keeps reappearing
```
terraform plan

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # github_repository.repository will be updated in-place
  ~ resource "github_repository" "repository" {
      ~ allow_squash_merge          = false -> true
      ~ delete_branch_on_merge      = false -> true
        id                          = "test_repository"
      + merge_commit_message        = "PR_TITLE"
      + merge_commit_title          = "MERGE_MESSAGE"
        name                        = "test_repository"
      + squash_merge_commit_message = "COMMIT_MESSAGES"
      + squash_merge_commit_title   = "COMMIT_OR_PR_TITLE"
        # (27 unchanged attributes hidden)
    }
```

**Comment by andrioli** [comment]
same thing here.

in my case, when I do a subsequent plan, sometimes, everything looks correct, but after some time in a next plan always there is "some" changes to apply.

also noted that the current state reported by plan is always wrong (does not reflect my state file and does not reflect the configurations on GitHub), but the desired state is always correct.

**Comment by WTPascoe** [comment]
We're seeing something _similar_ to this, but in our case some of the changes have been made, but terraform wants to make it again on the next run.

So I have a repo that TF is managing via this provider, and a plan suggests doing
`allow_squash_merge: false -> true`

Looking at the repo though, allow squash merge is already enabled.

Other values are not being set and terraform on apply claims set them, but checking the repo shows no change. An example of this would be `squash_merge_commit_title`

From what I can tell, this isn't happening where we use a personal access token (PAT) - only where we use a GitHub app to authenticate, but I can't prove that yet.

This feels like a higher priority issue than Normal as it makes the provider unusable in this case.

**Comment by andrioli** [comment]
> same thing here.
> 
> in my case, when I do a subsequent plan, sometimes, everything looks correct, but after some time in a next plan always there is "some" changes to apply.
> 
> also noted that the current state reported by plan is always wrong (does not reflect my state file and does not reflect the configurations on GitHub), but the desired state is always correct.

Maybe something changed on GitHub API... the problem is not happening any more (no version changed)

**Comment by gvwirth** [comment]
We're having the exact same issue, all providers at the latest versions. We're using a Github App to authenticate. I get "No changes" at first, but after some time we get

```
  ~ resource "github_repository" "repo" {
      ~ allow_merge_commit          = false -> true
      ~ allow_rebase_merge          = false -> true
      ~ allow_squash_merge          = false -> true
        id                          = "test-repo"
      + merge_commit_message        = "PR_TITLE"
      + merge_commit_title          = "MERGE_MESSAGE"
        name                        = "test-repo"
      + squash_merge_commit_message = "COMMIT_MESSAGES"
      + squash_merge_commit_title   = "COMMIT_OR_PR_TITLE"
        # (26 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }
```

**Comment by regner** [comment]
We are getting this as well. As far as I can tell it's after some time, or after we merge a PR. Without having looked at the code my guess would be a cache issue from GitHub.

I don't know exactly what endpoint this provider uses to get a repository, but I found this in the GitHub API docs: https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#get-a-repository

The response scheme for that requests lists `allow_merge_commit` as an attribute. When I make a request from the CLI, the response does NOT have that attribute in it. So I don't think this is a problem with the GitHub provider. From its point of view, the value wasn't in the response, so it needs to be updated.

I don't know why GitHub is not including that attribute in the response though, and I am unsure where to ask GitHub about it.

A quick search though and I did find these discussions:
* https://github.com/orgs/community/discussions/53757
* https://github.com/orgs/community/discussions/24331

According to those, this is only an issue with the REST API and not the GraphQL API. I don't know which this provider uses.

**Comment by regner** [comment]
Started a discussion on the GitHub community: https://github.com/orgs/community/discussions/54353

**Comment by regner** [comment]
I haven't had a chance to test this as I am on vacation, but I opened an issue with GitHub support and they said the PAT must have write permission on the repository contents.

![image](https://github.com/integrations/terraform-provider-github/assets/815037/de78e2b4-349c-41cb-9bca-a0d67215190e)

**Comment by regner** [comment]
Tested and confirmed. If the token has read and write permission for the repository contents this is not a problem. It might make sense to update the documentation for the resource to explain this.

**Comment by svalevka** [comment]
As mentioned, we use github app.
I tried to use github token instead, and all issues disappeared.
However , after some time , two repositories still report the same issue. This is an improvement from 92+ repositories previously.

**Comment by regner** [comment]
It might be best to open a ticket with GitHub. My guess is the issue would be similar in that the get repositories API is not returning the correct information for the GitHub app token.

**Comment by kfcampbell** [comment]
> It might make sense to update the documentation for the resource to explain this.

Thanks for figuring that out! Do you have any interesting in opening up a docs PR to reflect that?

**Comment by andrioli** [comment]
As I mentioned before https://github.com/integrations/terraform-provider-github/issues/1623#issuecomment-1511417221 the issue was not happening here anymore (Auth using a GitHub App). 

But now we are facing another issue. Sometimes the plan reports some changes like the following:

```
  ~ resource "github_repository" "omitted_repository" {
        id                          = "omitted"
      ~ merge_commit_message        = "PR_TITLE" -> "MERGE_MESSAGE"
      ~ merge_commit_title          = "MERGE_MESSAGE" -> "PR_TITLE"
        name                        = "omitted"
        # (32 unchanged attributes hidden)
    }
 ```

In the resource definition we have:
```
  merge_commit_message        = "MERGE_MESSAGE"
  merge_commit_title          = "PR_TITLE"
```

And this is what we have in our state file:
```
            "merge_commit_message": "MERGE_MESSAGE",
            "merge_commit_title": "PR_TITLE",
```

And on GitHub UI
![image](https://github.com/integrations/terraform-provider-github/assets/499182/92deda3b-6703-433c-a080-7994cebbf17c)

when we have these "changes" to apply, applying the changes always lead to a 500 error:
```
Error: PATCH https://api.github.com/repos/omitted_org/omitted_repository: 500  []

  with github_repository.omitted_repository,
  on repo_omitted_repository.tf line 1, in resource "github_repository" "omitted_repository":
   1: resource "github_repository" "omitted_repository" {

```

on further plan, normally we got no changes to apply.

When the plan do not report this weird "changes", no error 500 happens. This is happening only to a few resources (I think is happening only for 3 of our repos). But is happening frequently.

**Comment by svalevka** [comment]
I can confirm that issue has gone once "Content" permission was added to Github App

**Comment by andrioli** [comment]
> I can confirm that issue has gone once "Content" permission was added to Github App

My app already have the "Contents" permission with read and write access, but the issue mentioned above https://github.com/integrations/terraform-provider-github/issues/1623#issuecomment-1572546307 is still happening.

I suppose is something with GitHub API, And I can confirm that is only happening with always the same three repositories resources!

**Comment by andrioli** [comment]
Ouch, my bad 😛 

I was analyzing the issue deeper and just found the issue was from our side. From my previous comment https://github.com/integrations/terraform-provider-github/issues/1623#issuecomment-1572546307 I said:

> In the resource definition we have:
>```
>  merge_commit_message        = "MERGE_MESSAGE"
>  merge_commit_title          = "PR_TITLE"
>```

The argument `merge_commit_message` does not accept the value `MERGE_MESSAGE` and the argument `merge_commit_title` does not accept the value `PR_TITLE`. Actually, the values are inverted and should be:

>```
>  merge_commit_message        = "PR_TITLE"
>  merge_commit_title          = "MERGE_MESSAGE"
>```

And surprise, these bad definitions are present only on the three repositories that was failing. All of our other `github_repository` resources have the correct values. 

So now I can confirm that this is not an issue anymore

**Comment by svalevka** [comment]
Switching over to GraphQL resource is pretty straightforward to fix the issue as well.

**Comment by regner** [comment]
Not sure this should be marked as completed. Seems to me the docs need updating to explain this.
