### ISSUE TITLE
`github_organization_settings` gives `422 Validation Failed` with some combinations of member privileges for repository creation

### ISSUE THREAD

**Issue by Laffs2k5** [integrations/terraform-provider-github#1628]
Hi,

I'm observing some pre-existing settings of member privileges for repository creation in the github org.  in combination with specific configuration of the arguments `members_can_create_public_repositories` and `members_can_create_private_repositories` causing `422 Validation Failed []` failures from https://api.github.com/orgs/<my org>

Detailed error response from the debug-log:
```log
{
 "message": "Validation Failed",
 "errors": "Private-only repository creation policy is not allowed for this organization.",
 "documentation_url": "https://docs.github.com/rest/reference/orgs#update-an-organization"
}
```

### Terraform Version
```shell
$ terraform version 
Terraform v1.4.2
on linux_amd64
```

### Affected Resource(s)
Please list the resources as a list, for example:
- github_organization_settings

### Terraform Configuration Files
```hcl
variable "org_name" {
  description = "The name of the github organization to manage"
  nullable    = false
  type        = string
}

variable "github_auth_personal_access_token" {
  description = "PAT - Personal access token (classic)"
  default     = null
  type        = string
  sensitive   = true
}

terraform {
  required_version = "~> 1.4.0"
  required_providers {
    github = {
      source  = "integrations/github"
      version = "~> 5.18.0"
    }
  }
}

provider "github" {
  owner = var.org_name
  token = var.github_auth_personal_access_token
}

resource "github_organization_settings" "settings" {
  billing_email                           = "someone@example.com"
  members_can_create_public_repositories  = true
  members_can_create_private_repositories = true
}
```

### Debug Output
```shell
export TF_LOG="DEBUG"
export TF_LOG_PROVIDER="TRACE"
```
https://gist.github.com/Laffs2k5/e997e016c60e9bcdc290051583a37517

### Panic Output
N/A.

### Expected Behavior
The provider should have allowed members to create both public and private repos in the org.

Like this (from org. settings -> Member privileges):
![image](https://user-images.githubusercontent.com/24737456/228776500-2bfd850f-e642-4c74-82e5-38ec3138c319.png)

### Actual Behavior
Terraform throws this error during apply:
```log
╷
│ Error: PATCH https://api.github.com/orgs/dsb-norge-dev: 422 Validation Failed []
│ 
│   with github_organization_settings.settings,
│   on main.tf line 29, in resource "github_organization_settings" "settings":
│   29: resource "github_organization_settings" "settings" {
│ 
╵
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Have a github org on the "free" plan.
2. Make sure members of the target org. are **disallowed** to create both public and private repos. Do this by manually unchecking the boxes _Private_ and _Public_ from org. settings -> Member privileges -> Repository creation.
3. Run `terraform apply`.
4. Observe the error.

#### Workaround
A workaround for the issue is to first apply with allowing only public repo creation:
```hcl
resource "github_organization_settings" "settings" {
  billing_email                           = "someone@example.com"
  members_can_create_public_repositories  = true
  members_can_create_private_repositories = false
}
```

Result in gui:
![image](https://user-images.githubusercontent.com/24737456/228775537-fd053a24-e81a-4656-91e6-aca7a053bfa3.png)

Then afterwards applying a different configuration with allowing both types of repo creation:
```hcl
resource "github_organization_settings" "settings" {
  billing_email                           = "someone@example.com"
  members_can_create_public_repositories  = true
  members_can_create_private_repositories = true
}
```

Result in gui:
![image](https://user-images.githubusercontent.com/24737456/228776081-362d7502-d6f5-48f4-bffe-0081dfa0e3ba.png)

That being said, this workaround does not fit very well with Terraform and immutable desired state configuration.

#### Successful and non-successful scenarios

There are multiple combinations of pre-existing settings and terraform declarations that result in this error. Likewise there are also configurations which does not fail. Below I' try to summarize:

| allow private<br>(org. setting before) | allow public<br>(org. setting before) | allow private<br>(declared) | allow public<br>(declared) | Result | Comment                              |
|:--------------------------------------:|:-------------------------------------:|:---------------------------:|:--------------------------:|:------:|--------------------------------------|
|                    ☐                   |                   ☐                   |              ☑              |              ☑             |  error |                                      |
|                    ☐                   |                   ☐                   |             null            |              ☑             |  error |                                      |
|                    ☐                   |                   ☐                   |         not declared        |              ☑             |  error |                                      |
|                    ☐                   |                   ☐                   |              ☑              |            null            |  error | Expected due to defaults in provider |
|                    ☐                   |                   ☐                   |              ☑              |        not declared        |  error | Expected due to defaults in provider |
|                    ☐                   |                   ☐                   |             null            |            null            |  error |                                      |
|                    ☐                   |                   ☑                   |              ☑              |              ☑             |   OK   |                                      |
|                    ☐                   |                   ☑                   |              ☐              |              ☑             |   OK   |                                      |
|                    ☐                   |                   ☑                   |         not declared        |              ☑             |   OK   |                                      |
|                    ☐                   |                   ☑                   |         not declared        |              ☐             |  error | Expected due to defaults in provider |
|                    ☑                   |                   ☑                   |              ☑              |              ☑             |   OK   |                                      |
|                    ☑                   |                   ☑                   |              ☐              |              ☐             |   OK   |                                      |
|                    ☑                   |                   ☑                   |              ☐              |              ☑             |   OK   |                                      |

### References
N/A

**Comment by kfcampbell** [comment]
:heart: :heart: :heart: oh my goodness this is an incredible bug report. Thank you so much! Please feel free to open a PR to fix this behavior as well if you have the time and inclination.
