### ISSUE TITLE
[FEAT]: Can't configure `Fork pull request workflows from outside collaborators` from Terraform

### ISSUE THREAD

**Issue by fjakobs** [integrations/terraform-provider-github#1632]
### Describe the need

I want to configure [Fork pull request workflows from outside collaborators](https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks) from Terraform for my repo but I can't find that setting. I'd expect this to be a property of the [github_repository](https://registry.terraform.io/providers/integrations/github/latest/docs/resources/repository) resource.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by arunsathiya** [comment]
It looks like this is blocked by the lack of availability of a field to control this setting in the underlying API (scanned [permissions](https://docs.github.com/en/rest/actions/permissions?apiVersion=2022-11-28), [workflow runs](https://docs.github.com/en/rest/actions/workflow-runs?apiVersion=2022-11-28), and [this community discussion](https://github.com/orgs/community/discussions/35808)), and in turn, that means unavailability in `go-github`:

https://github.com/google/go-github/blob/d26bcb8be17264a1fad1aaf15147625c0df75a99/github/repos.go#L545-L572
