### ISSUE TITLE
[MAINT]: potential auth token exposure with invalid `token`

### ISSUE THREAD

**Issue by wyardley** [integrations/terraform-provider-github#1635]
### Describe the need

When an invalid credential with a newline is set (or something that's otherwise an invalid bearer token, presumably), the provider throws an error that exposes the cleartext value of the credential. I used `asdf\n` in my example, but it will do the same thing if provided a legitimate token with a newline at the end.

I am happy to report this as a security vuln explicitly, though not sure if it rises to this level. Also, despite the bug report about security issues mentioning this, I don't see the terraform provider explicitly listed in terms of things that are in scope.

```hcl
provider "github" {
  owner = "foo"
  token = "asdf\n"
}

resource "github_repository_deploy_key" "main" {
  title      = "foo-deploy-key"
  repository = "somerepo"
  key        = "[set a real key]
  read_only  = false
}
```

### SDK Version

terraform-provider-github v5.20.0

### Relevant log output

```shell
2023-04-04T13:24:44.951-0700 [DEBUG] provider.terraform-provider-github_v5.20.0: -----------------------------------------------------
2023-04-04T13:24:44.957-0700 [ERROR] vertex "github_repository_deploy_key.main" error: Post "https://api.github.com/repos/foo/somerepo/keys": net/http: invalid header field value "Bearer asdf\n" for key Authorization
╷
│ Error: Post "https://api.github.com/repos/foo/somerepo/keys": net/http: invalid header field value "Bearer asdf\n" for key Authorization
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wyardley** [comment]
Hi - I can try to take a quick look to see if there's an easy / obvious way to do this, but I'm not super familiar with this codebase.

I took a quick look, and don't think it's here:
https://github.com/integrations/terraform-provider-github/blob/50447aea7da5b090f261f408f158dac6d70a5bcd/github/apps.go#L45-L51

so my question is, would the change needed be upstream in https://github.com/google/go-github? I'm not seeing where in the provider code the actual auth is setup or http requests are made (even in helper routines), so guessing it's via this or another library?

I guess there are potentially some naive fixes possible too, like stripping any `\n`s at the end of the token in the main provider code (again, it seems like when it's a bad token with no `\n`, the token is not exposed, but presumably there are other strings that could also generate invalid headers without containing a newline).

**Comment by kfcampbell** [comment]
> I took a quick look, and don't think it's here:

You are correct!

> would the change needed be upstream in https://github.com/google/go-github? 

It's possible that would be a better solution; I haven't quite thought it all the way through yet. 

> where in the provider code the actual auth is setup

The auth is set up in [this function](https://github.com/integrations/terraform-provider-github/blob/main/github/provider.go#L233) I believe; that's where we store our tokens in a struct for future use. 

> I guess there are potentially some naive fixes possible too

Agreed! Let's hold off on exploring these for the moment; I'm hopeful we can do better.

**Comment by wyardley** [comment]
Otherwise, I guess you’d have to write some kind of error handler / interceptor in the provider, but that is also bigger / more structural than something I’d want to take on here.

**Comment by kfcampbell** [comment]
Acknowledged. The go-github library [doesn't appear](https://github.com/google/go-github/blob/4806e1db75a11944b74c87be74e4bfacc71c21f0/README.md?plain=1#L87) to handle authentication itself, though it could perhaps still handle redaction. 

What's really throwing me is your log above shows an `[ERROR]` level log, which we don't have any instances of in the GitHub provider itself. It must be coming from Terraform under the hood somewhere. I wonder if we shouldn't recommend that folks use [`sensitive = true`](https://developer.hashicorp.com/terraform/tutorials/configuration-language/sensitive-variables#refactor-database-credentials) on their credentials to protect them from showing up in logs.

**Comment by wyardley** [comment]
I could be wrong, but I think even if the credential were marked as sensitive, I don’t think that would help here.

something at some layer has to be handling auth for the API calls, right?

**Comment by wyardley** [comment]
The bit you linked to did give me a pointer tho: https://github.com/integrations/terraform-provider-github/blob/fd54e803055f23af1f7df0ab3d534e972c5109b7/github/config.go#L53

**Comment by wyardley** [comment]
@kfcampbell interesting: I think #1643 may have fixed this:
When I was testing, built off of a local up to date version of the provider without any changes, I get:
```
│ Error: Post "https://api.github.com/repos/xxx/yyt/keys": net/http: invalid header field value for "Authorization"
```
I confirmed that the exact same terraform code with the old provider version exhibits the behavior above.

So this may be an easy fix by just releasing.

It might be too magic to add this, but would also be possible to switch the code above to trim newlines or even leading / trailing spaces.

**Comment by kfcampbell** [comment]
Oh awesome, thanks for doing the research! [v5.22.0](https://github.com/integrations/terraform-provider-github/releases/tag/v5.22.0) has that fix in it. I'll close the issue for now, but please feel free to reopen if you discover otherwise.
