### ISSUE TITLE
github_branch_protection requires branch to exist

### ISSUE THREAD

**Issue by abridgett** [integrations/terraform-provider-github#164]
### Terraform Version
0.11.10

### Affected Resource(s)
- github_branch_protection

### Expected Behavior
A branch protection rule should be created for the branch (or fnmatch wildcard) in question

### Actual Behavior
```
github_branch_protection.release-branch-protection: PUT https://api.github.com/repos/foo/bar/branches/release/protection: 404 Branch not found []
```

### Important Factoids
I wonder if this is a limitation of the github API, the request being sent matches what you'd expect from https://developer.github.com/v3/repos/branches/#update-branch-protection
It _is_ possible to do this from the UI though.

**Comment by jonathanan** [comment]
This is limitation of the GitHub API: https://github.community/t5/GitHub-API-Development-and/REST-API-v3-wildcard-branch-protection/m-p/14547#M260

**Comment by patrickmarabeas** [comment]
Github v4 API provides the ability to specify a pattern rather than a branch.

I have uplifted the resource to use the v4 API: https://github.com/terraform-providers/terraform-provider-github/pull/337

**Comment by kfcampbell** [comment]
Closing as #337 has been merged/released. Please create a new issue for further problems with this!
