### ISSUE TITLE
[FEAT]: Support Code Scanning default setup

### ISSUE THREAD

**Issue by srgustafson8** [integrations/terraform-provider-github#1648]
### Describe the need

We manage our whole GitHub organisation programatically, including the creation of repositories. We are also a GHAS customer, and want to use it to it's maximum. Getting all teams across 500+ repositories to enable Code Scanning is a headache, so being able to automatically enable the default scanning programatically for a repository would be helpful.

There is [now an API for this](https://github.blog/changelog/2023-03-21-code-scanning-api-to-enable-default-setup-with-codeql-on-a-repository/) so it can be Terraformed.  

Depends on https://github.com/google/go-github/issues/2751 for the go-github SDK to support it. 

### API Version

2022-11-28

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by VariableExp0rt** [comment]
I'd be happy to give this a shot @kfcampbell

**Comment by kfcampbell** [comment]
@VariableExp0rt please go for it!

**Comment by VariableExp0rt** [comment]
@kfcampbell apologies I haven't been able to get to this over the last few weeks, but should now have some time to take a crack at it.
