### ISSUE TITLE
[MAINT]: Make `github_ref` respect `owner` (vs taking it from the PAT)

### ISSUE THREAD

**Issue by ksatirli** [integrations/terraform-provider-github#1650]
### Describe the need

Currently, the `github_ref` data source does not take an `owner` input and defaults to the one that can be derived from the PAT.

When using the data source with a personal access token (for my user `ksatirli`), this results in an empty response for a `github_ref` for `hashicorp/setup-terraform`:

```hcl
data "github_ref" "terraform" {
  ref        = "tags/v2.0.3"
  owner      = "hashicorp"
  repository = "setup-terraform"
}
```

Output:

```
  "etag" = tostring(null)
  "id" = tostring(null)
  "ref" = tostring(null)
  "repository" = tostring(null)
  "sha" = tostring(null)
```

Comparatively: when I poll a `repository` that belongs to the same `owner` as the PAT, the data source works as expected.

Change request: The `github_ref` data source should support an `owner` attribute that is used to query the GH API.

### SDK Version

5.22.0 and earlier

### API Version

n/a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rstuhlmuller** [comment]
```data "github_ref" "terraform" {
  ref        = "tags/v2.0.3"
  owner      = "hashicorp"
  repository = "setup-terraform"
}
```

**Comment by rstuhlmuller** [comment]
`data "github_ref" "terraform" {
  ref        = "tags/v2.0.3"
  owner      = "hashicorp"
  repository = "setup-terraform"
}
`

**Comment by rstuhlmuller** [comment]
```go
data "github_ref" "terraform" {
  ref        = "tags/v2.0.3"
  owner      = "hashicorp"
  repository = "setup-terraform"
}
```

**Comment by rstuhlmuller** [comment]
```hcl
data "github_ref" "terraform" {
  ref        = "tags/v2.0.3"
  owner      = "hashicorp"
  repository = "setup-terraform"
}
```

**Comment by ivica3730k** [comment]
Thank you very much @ksatirli, this will be very useful.

I guess that the owner in this case can also be an organization? 

Thank you!

**Comment by kfcampbell** [comment]
Yep! In the context of the provider, "owner" means either a user account or an organization.
