### ISSUE TITLE
etag changes detected in new Terraform "Drift Detection" scans

### ISSUE THREAD

**Issue by devopsrick** [integrations/terraform-provider-github#1653]
Hashicorp has released Drift Detection in both Terraform Cloud and Terraform Enterprise and it is picking up the etag changes that normal Terraform runs ignore.  Is this something that can be addressed on the provider side?

The resources I am seeing etag changes on:
github_team
github_team_repository
github_team_sync_group_mapping

**Comment by gabrielrinaldi** [comment]
This is pretty annoying as it creates a false drift detection in Terraform, it is hard to know if there is an actual problem or just normal usage of the platform. From my understanding this has been fixed in the past and recently came back.

**Comment by devopsrick** [comment]
This seems to have been resolved in the latest versions of the provider and terraform enterprise.
