### ISSUE TITLE
[FEAT]: Better error handling on OAuth token fetch for incorrect app ids

### ISSUE THREAD

**Issue by mattmshell** [integrations/terraform-provider-github#1665]
### Describe the need

I made a mistake configuring the provider and provided the wrong GITHUB_APP_ID. 

```
│ Error: failed to create OAuth token from GitHub App: {"message":"Integration not found","documentation_url":"https://docs.github.com/rest"}
│ 
│   with provider["registry.terraform.io/integrations/github"],
│   on provider.tf line 12, in provider "github":
│   12: provider "github" {
```

With `mitmproxy`, you can recreate this and observe the underlying error:

```
HTTP_PROXY="http://localhost:8888" HTTPS_PROXY="http://localhost:8888" GITHUB_APP_ID="123123123" terraform plan
```

It is a 404:

![image](https://user-images.githubusercontent.com/103135056/234030468-a704bdfd-4fb9-4273-9bcb-441d4e2a6743.png)

This is due to the provider [treating non-created HTTP status codes as "Integration not found" errors](https://github.com/integrations/terraform-provider-github/blob/2b22c641efae3f40a21fff8cff67615dab5e59a3/github/apps.go#L60). A better error message would indicate the application OR installation (not integration) wasn't found.

### Relevant log output

```shell
│ Error: failed to create OAuth token from GitHub App: {"message":"Integration not found","documentation_url":"https://docs.github.com/rest"}
│ 
│   with provider["registry.terraform.io/integrations/github"],
│   on provider.tf line 12, in provider "github":
│   12: provider "github" {
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment]
This error message is coming from the GitHub API, not the provider specifically. That being said, we should handle it more gracefully. The obvious solution I can see would be filtering on the 404 status code and/or the "Integration not found" message and print a custom error message before dumping the body of the response.
