### ISSUE TITLE
[FEAT]: Remove parent team when parent_team_id == 0

### ISSUE THREAD

**Issue by Milkshak3s** [integrations/terraform-provider-github#1668]
## Currently:
If a team has a parent and the `parent_team_id` is updated to `0` or `null` in the associated Terraform resource, the TF state will update the `parent_team_id` to `0`, but the GitHub team will remain under its original parent.

This brings the TF state out of line with what is true in GitHub, and is unexpected behavior.

## Suggested change
If the new `parent_team_id` is `0` and the field `parent_team_id` is not currently `0` or `null`, pass `true` as the `removeParent` argument to `EditTeamByID` (rather than hardcoding it to `false`, as is current`:
https://github.com/integrations/terraform-provider-github/blob/e83bb8d8ffd505d63d068527df25efcdccdfc7a0/github/resource_github_team.go#L233

https://github.com/integrations/terraform-provider-github/blob/e83bb8d8ffd505d63d068527df25efcdccdfc7a0/vendor/github.com/google/go-github/v51/github/teams.go#L224

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment]
@Milkshak3s that seems like a reasonable approach! Do you have the inclination to open a PR for this behavior?

**Comment by Milkshak3s** [comment]
@kfcampbell I would love to! A bit swamped this week, but I should have some cycles next week to get something up.

**Comment by scott-doyland-burrows** [comment]
It is worth noting that there are some other issues with parent teams - almost the reverse issue of what was reported above.

I create two teams in terraform and apply, and then alter one in terraform to have a parent team and apply.

I then go to GitHub and update the child team to not have the parent team.

I run a terraform apply and it does not report a diff, even though the terraform code still has the parent team defined.
The statefile shows the parent team (for the child team) as set to ```""```.

Terraform should show a diff.

Looks like the logic for parent teams is broken - and I wonder if using a new resource would be preferable, as per my suggestion here:

https://github.com/integrations/terraform-provider-github/issues/1954

**Comment by scott-doyland-burrows** [comment]
Just to add to the above, if I delete the parent team via terraform (it remains in place in GitHub which is the wrong behaviour), then I see the statefile alters from this:

```
            "name": "scott-team02",
            "node_id": "T_kwDOBQjlXc4AhnuY",
            "parent_team_id": "8813444",
            "parent_team_read_id": "8813444",
            "parent_team_read_slug": "scott-team01",
            "privacy": "closed",
            "slug": "scott-team02"
```

to this:

```
            "name": "scott-team02",
            "node_id": "T_kwDOBQjlXc4AhnuY",
            "parent_team_id": "",
            "parent_team_read_id": "8813444",
            "parent_team_read_slug": "scott-team01",
            "privacy": "closed",
            "slug": "scott-team02"
```

Note how it is only the ```parent_team_id``` that is set back to ```""```.

Also I notice this when I apply terraform to make the change:

```
Terraform will perform the following actions:

  # module.teams.github_team.teams["scott-team02"] will be updated in-place
  ~ resource "github_team" "teams" {
        id                        = "8813464"
        name                      = "scott-team02"
      - parent_team_id            = "8813444" -> null
        # (8 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

Note it says the parent team ```8813444``` will become ```null```.  Either the resource should work on the team-name, the team-slug, or the team-id.  It is confusing to attach a parent team of ```scott-team01``` and then have it (attempt to) remove ```8813444```.

**Comment by fbousquethopper** [comment]
This changed actually created another problem: 

When you don't want to manage to the parent_team_id from Terraform, you no longer can skip the parent_team_id attribute as it now automatically removes the parent team link if there is no value specified. 

I'm no expert, but shouldn't we just remove the parent relationship if the value is null or empty?

```go
if parentTeamID, ok := d.GetOk("parent_team_id"); ok {
	teamId, err := getTeamID(parentTeamID.(string), meta)
	if err != nil {
		return err
	}
	editedTeam.ParentTeamID = &teamId
	removeParentTeam = false
} else {
	removeParentTeam = true
}
```
