### ISSUE TITLE
[FEAT]: Expose repository_ids in github_team data_source

### ISSUE THREAD

**Issue by felixlut** [integrations/terraform-provider-github#1670]
### Describe the need

Currently the [`github_team`](https://registry.terraform.io/providers/integrations/github/latest/docs/data-sources/team) data_source exposes the attribute [`repositories`](https://registry.terraform.io/providers/integrations/github/latest/docs/data-sources/team#repositories), which is a list of repository names. 

My use-case is that I want to create a `github_actions_organization_secret` with the `selected_repository_ids` set to the repositories which a specific `github_team` has access to. The `github_actions_organization_secret` requires a list of  repository ids, but the `github_teams` data_source only provides a list of repository names. While this list of names can be chained with the [`github_repository`](https://registry.terraform.io/providers/integrations/github/latest/docs/resources/repository) resource to fetch the id:s, [the API call for fetching this information is already done](https://github.com/integrations/terraform-provider-github/blob/e9bb788f4a640bba0d0545880af8c2d63e8d47b5/github/data_source_github_team.go#L154-L168) within the `github_team` data_source, so it might as well be exposed there directly. 

## Suggested Change
A new attribute can be added to the `github_team` data_source exposing these id:s, `repository_ids` for example. It might be valuable to expose even more attributes, such as the `role_name` the team has for the repository. In my mind the `repositories` attribute should probably be a list of structs exposing these 3 fields:
* `repository_name`
* `repository_id`
* `role_name` (`admin`/`maintain`/`write`/...)

However, Implementing this would break backwards compatibility, so I think one of the 2 following solutions are the best options:
1. Adding a new attribute called `repository_detailed`, which contains each connected repository's `name`, `id` and `role_name`
    * This would not break any compatibility, but still expose all fields one would want 
    * I'm not that used to Terraform Provider development, but I think a list of structs could be extended in the future if more than these three attributes are wanted if the future
    * ```go
	  "repositories_detailed": {
		  Type:     schema.TypeList,
		  Computed: true,
		  Elem: map[string]*schema.Schema{
			  "repo_name": {
				  Type:     schema.TypeString,
				  Required: true,
			  },
			  "repo_id": {
				  Type:     schema.TypeInt,
				  Computed: true,
			  },
			  "role_name": {
				  Type:     schema.TypeString,
				  Computed: true,
			  },
		  },
	  } 
	  ```
2. Adding 2 new attributes, one for the `repository name`, one for the repository `role_name`
    * Not as elegant as 1, but it works

### SDK Version

_No response_

### API Version

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felixlut** [comment]
I'm willing to work on this also, just need the go ahead that this is something you'd be willing to merge!

**Comment by kfcampbell** [comment]
> Adding 2 new attributes, one for the repository name, one for the repository role_name

The new attributes would be repo ID and role_name, right? I believe the name is what's already returned. 

Great breakdown of the problem here. In a perfect world, we'd implement the breaking change and a migration, stack it up with a few others, and release a major version. In the meantime, I think your `repositories_detailed` approach is a good intermediary. I'd be happy to review such PR(s).

**Comment by felixlut** [comment]
@kfcampbell in my mind it would be better to have the `repo_name` be included in the `repositories_detailed` field as well, mostly because of a "might as well" feeling. But I aösp think it would make it easier to introduce the breaking change in the future. If it's there, the migration would simply be that the `repositories` field would be deprecated in favor for the detailed one, which already include all the fields from the get go. I'd be happy to do leave it out though, since the the implementation difference is really miniscule. 

But great, I'll start working on this now then!
