### ISSUE TITLE
[FEAT]: a rulesets resource

### ISSUE THREAD

**Issue by rbtcollins** [integrations/terraform-provider-github#1680]
### Describe the need

We use IaaC to manage our branch protection rules, and [rulesets](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-rulesets/about-rulesets) look like a great upgrade.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment]
I agree this would be an awesome resource. That would use [this API](https://docs.github.com/en/rest/repos/rules?apiVersion=2022-11-28), which does not appear to have upstream support in google/go-github. That will need to be done first before PRing this project.

**Comment by YElyousfi** [comment]
It looks like as of last week, rulesets have been implemented in google/go-GitHub's latest release: https://github.com/google/go-github/releases/tag/v53.2.0

**Comment by amenocal** [comment]
should this issue be closed due to : https://github.com/integrations/terraform-provider-github/pull/1808 and many other [PRs](https://github.com/integrations/terraform-provider-github/pulls?q=is%3Apr+rulesets+is%3Aclosed) ?
