### ISSUE TITLE
[BUG]: github_external_groups does not return all groups

### ISSUE THREAD

**Issue by bryanrcampbell** [integrations/terraform-provider-github#1687]
### Describe the need

We've been using `github_external_groups` for months now without issue. We have around 96 groups right now that are synced in from our IdP. We use the data provider to pull in all groups, then create a github team to mirror that group.

The following has been working:
```
data "github_external_groups" "_" {}
```

We noticed today that it's only pulling in 30 groups now, not the full 96.

That API's default page size is 30 which makes us think maybe the provider is only returning on page of results. Looking at the provider code, i don't see that information passed along(https://github.com/integrations/terraform-provider-github/blob/ce50fe093e103f47c758672e016c38ee5d38a443/github/data_source_github_external_groups.go#L49). I'm mostly surprised that it's been working up until now.

Thanks for the help!

### SDK Version

terraform-provider-github v5.25.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bodgit** [comment]
Literally just bumped into this same bug myself, could see 38 groups in the UI but Terraform only had a list of 30.

According to the [API documentation](https://docs.github.com/en/enterprise-cloud@latest/rest/teams/external-groups?apiVersion=2022-11-28#list-external-groups-in-an-organization) the most groups you can request in one go is 100 and the provider code doesn't seem to be doing any sort of pagination currently.

In fact, looking at this line: https://github.com/integrations/terraform-provider-github/blob/ce50fe093e103f47c758672e016c38ee5d38a443/github/data_source_github_external_groups.go#L51

The code is ignoring the second returned value, which is the API response that contains the pagination hints. I'll see if I can work out a fix unless someone beats me to it.

**Comment by bodgit** [comment]
I've created #1688 which seems to fix things for me, I now get all groups returned.

**Comment by mdrankowski** [comment]
@bodgit I confirm your update fixes it for us too, thanks! Do we know when it can get deployed?

**Comment by kfcampbell** [comment]
@bodgit I share your hunch about the API behavior. Thank you for the fix! I'll get it released shortly.
