### ISSUE TITLE
[BUG] Try to import an unknow autolink: Plugin did not respond

### ISSUE THREAD

**Issue by Esysc** [integrations/terraform-provider-github#1698]
### Context
Since release [v5.19.0](https://github.com/integrations/terraform-provider-github/releases/tag/v5.19.0), we can now import autolinks by its well known prefix and this is a cool feature for automation.

In my company we are in the phase of importing  multiple existing unmanaged repositories using our tool [Terravalet](https://github.com/Pix4D/terravalet) that generates a batch of import Terraform commands.

Each `terraform import` could address a resource that exists in Terraform configuration, but not yet "live". The error below it's expected if the resource doesn't exist upstream:

```hcl
Error: Cannot import non-existent remote object

While attempting to import an existing object to
github_team_repository.all_teams["test-import-gh.integration"], the provider
detected that no object exists with the given id. Only pre-existing objects
can be imported; check that the id is correct and that it is associated with
the provider's configured region or endpoint, or use "terraform apply" to
create a new remote object for this resource.
```

This is OK, a successive `terraform apply` will tune the repository configuration in GitHub.

### Problem
Since we can now import autolinks by prefix, the same context applies: the prefix may already exist OOB and successfully imported, or living just in the Terraform configuration. The latter causes a plugin crash:

```
+ terraform import 'module.github.github_repository_autolink_reference.global_autolinks["my-repo.AUTO-"]' my-repo/AUTO- 
module.github.data.github_organization_teams.all: Reading... 
module.github.data.github_user.users["tech-user1"]: Reading... 
module.github.data.github_user.users["tech-user2"]: Reading... 
module.github.github_repository_autolink_reference.global_autolinks[""my-repo.AUTO-""]: Importing from ID "my-repo/AUTO-"... 
module.github.data.github_organization_teams.all: Read complete after 5s [id=MDEyOk9yZ2FuaXphdGlvbjc2NTU3NDg=] 
╷ 
│ Error: Plugin did not respond 
│  
│   with module.github.data.github_user.users["tech-user2"], 
│   on ../../tf-modules/github/main.tf line 155, in data "github_user" "users": 
│  155: data "github_user" "users" { 
│  
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain more details. 
╵ 
 
Stack trace from the terraform-provider-github_v5.23.0 plugin: 
 
panic: runtime error: invalid memory address or nil pointer dereference 
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf9a7f0] 
 
goroutine 942 [running]: 
github.com/integrations/terraform-provider-github/v5/github.resourceGithubRepositoryAutolinkReference.func1(0xc0006ee230, {0x1049ee0?, 0xc000216c40}) 
	github.com/integrations/terraform-provider-github/v5/github/resource_github_repository_autolink_reference.go:47 +0x170 
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).ImportState(0xc0000e1f80, 0xc00059b988, {0xc000580360, 0x1f}) 
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/provider.go:390 +0xf8 
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ImportResourceState(0xc00000eb18, {0xc000d0dd80?, 0x4b8786?}, 0xc000d0dd80) 
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/helper/plugin/grpc_provider.go:963 +0xb6 
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ImportResourceState_Handler({0x12437c0?, 0xc00000eb18}, {0x15e9280, 0xc0005de540}, 0xc0006ee070, 0x0) 
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/tfplugin5/tfplugin5.pb.go:3323 +0x170 
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00017a1e0, {0x15ed148, 0xc0001cba00}, 0xc00079dd40, 0xc0006dfbf0, 0x1e09618, 0x0) 
	google.golang.org/grpc@v1.50.1/server.go:1340 +0xd13 
google.golang.org/grpc.(*Server).handleStream(0xc00017a1e0, {0x15ed148, 0xc0001cba00}, 0xc00079dd40, 0x0) 
	google.golang.org/grpc@v1.50.1/server.go:1713 +0xa1b 
google.golang.org/grpc.(*Server).serveStreams.func1.2() 
	google.golang.org/grpc@v1.50.1/server.go:965 +0x98 
created by google.golang.org/grpc.(*Server).serveStreams.func1 
	google.golang.org/grpc@v1.50.1/server.go:963 +0x28a 
 
Error: The terraform-provider-github_v5.23.0 plugin crashed!
```

This is the line at the origin of the crash
`github.com/integrations/terraform-provider-github/v5/github/resource_github_repository_autolink_reference.go:47 +0x170`

The workaround consists in NOT running `terraform import` of not yet existing autolinks, but I'd rather expect an error 404 instead of a crash.

### Versions

Terraform v1.4.5
integrations/github v5.23.0

**Comment by kfcampbell** [comment]
I think it would be reasonable to check to see if `*autolink.ID` is nil before attempting to `strconv.FormatInt` it and return an error if so. @Esysc do you have any interest in opening up a PR for this behavior? If not, I can do it.

**Comment by Esysc** [comment]
> I think it would be reasonable to check to see if `*autolink.ID` is nil before attempting to `strconv.FormatInt` it and return an error if so. @Esysc do you have any interest in opening up a PR for this behavior? If not, I can do it.

I will try to do in the next days, thanks for your answer.

**Comment by kfcampbell** [comment]
I'd like to bump this as I think the fix would be pretty simple and beneficial. I can open up the PR if you'd prefer not to; please let me know.
