### ISSUE TITLE
Update existing branch protection from terraform

### ISSUE THREAD

**Issue by pjetly-insight** [integrations/terraform-provider-github#1699]
Hello,

I am trying to update branch protection rules of an existing private repo in my organization.
But when i try to execute terraform apply, i get this error:

Error: Name already protected: develop

I know branch protection already exists on develop but i want to add more rules. cant i do that?

**Comment by julioagos** [comment]
Try importing the branch protection rules first. You can use this https://registry.terraform.io/providers/integrations/github/latest/docs/resources/branch_protection_v3#import

**Comment by pjetly-insight** [comment]
Thank you, it helped  and resoved the issue.
