### ISSUE TITLE
[FEAT]: github_repository select organization to use in Enterprise

### ISSUE THREAD

**Issue by michaelkacher** [integrations/terraform-provider-github#1702]
### Describe the need

We are leveraging GitHub Enterprise Managed Users and have multiple organizations in the enterprise.

We are trying to create repositories for specific organizations, but currently do not see an argument in github_repository for setting the organization.

Potentially something like setting the owner field below:
```
resource "github_repository" "example" {
  name        = "example"
  owner         = "my-org"
  description = "My awesome codebase"

  visibility = "internal"
}
```

I believe a workaround is we could create a separate Terraform pipeline for each organization and set the owner in the provider, but it would require a maintaining the terraform state for each organization.

Would the workaround be the recommended approach? Thoughts on this as a feature?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment]
That's a great question and feature suggestion. It would be helpful for the owner to be able to be specified at the resource level. You are correct that right now it can only be specified at the provider level, which requires separate state. 

It would be a breaking change to require owner on all repository resources, but perhaps a non-breaking change could make it optional and default to the provider owner if it's not there.

**Comment by pascal-hofmann** [comment]
Can't you just use multiple provider blocks? See https://developer.hashicorp.com/terraform/language/providers/configuration#alias-multiple-provider-configurations
