### ISSUE TITLE
How to update repo or branch protection rule via terraform?

### ISSUE THREAD

**Issue by pjetly-insight** [integrations/terraform-provider-github#1706]
what is the best way to update branch protection rules or repo settings via terraform?
any example?

**Comment by kfcampbell** [comment]
You can find our docs on [branch protection](https://registry.terraform.io/providers/integrations/github/latest/docs/resources/branch_protection) and [various repository settings](https://registry.terraform.io/providers/integrations/github/latest/docs/resources/repository) on the Terraform Registry.
