### ISSUE TITLE
[FEAT]: Is there any reason that secrets are "ForceNew" for any changes?

### ISSUE THREAD

**Issue by empath-nirvana** [integrations/terraform-provider-github#1720]
### Describe the need

The provider always deletes and recreates the github actions secret when the plaintext is updated -- is this actually necessary or can it be updated in place?  This causes a problem with trying to use the provider with something like the crossplane upjet controller because it blocks resource deletion.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Satak** [comment]
Same issue here even with
```terraform
  lifecycle {
    ignore_changes = [plaintext_value]
  }
```

**Comment by lmal54321** [comment]
Same as https://github.com/integrations/terraform-provider-github/issues/1383

**Comment by kfcampbell** [comment]
Closing as duplicate of 1383.
