### ISSUE TITLE
[DOCS]: `github_team_membership` role field values are incorrect

### ISSUE THREAD

**Issue by lopopolo** [integrations/terraform-provider-github#1721]
### Describe the need

[role](https://registry.terraform.io/providers/integrations/github/latest/docs/resources/team_membership#role) is documented as either being `maintainer` or `member`, but the accepted values are `admin` or `member`.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment]
@lopopolo do you have the inclination to open up a PR to fix this behavior? The file to change is [here](https://github.com/integrations/terraform-provider-github/blob/main/website/docs/r/team_membership.html.markdown). If not, I can do it!

**Comment by lopopolo** [comment]
I won't have time to get to this soon. @kfcampbell If you could take this, I'd appreciate it

**Comment by kfcampbell** [comment]
Hmm...it looks like according to the [API docs](https://docs.github.com/en/rest/teams/members?apiVersion=2022-11-28#add-or-update-team-membership-for-a-user), `maintainer` and `member` are correct. If you believe this is incorrect, could you file a bug [with the REST API](https://github.com/github/rest-api-description)? 

Also, the provider enforces `member` or `maintainer` when setting this role and defaults to member if it's not set. Does setting `maintainer` deterministically fail for you?

**Comment by lopopolo** [comment]
This is the terraform code I have: https://github.com/artichoke/project-infrastructure/blob/trunk/modules/github-team/main.tf.

It applies cleanly and gives the intended configuration in the teams for the organization.

I recall this code throws an API error if using `maintainer` (I don't have the text of that error at this point).

**Comment by lopopolo** [comment]
One thing to note here is that the user I'm attaching as a maintainer to the GitHub team is an admin of the GitHub Organization that team is a part of.
