### ISSUE TITLE
[BUG]:  Error when trying to set GitHub action secret

### ISSUE THREAD

**Issue by jacob7395** [integrations/terraform-provider-github#1736]
### Describe the need

When running the bellow terraform, I get a 404 error looks like an extra / is being put in the repository name

``` tf
resource "github_actions_secret" "azure_credentials" {
  repository       = "WisperBot"
  secret_name      = "AZURE_CREDENTIALS"
  plaintext_value  = <<EOF
{
    "clientId": "${azuread_service_principal.git_auth.application_id}",
    "clientSecret": "${azuread_application_password.git_auth.value}",
    "subscriptionId": "${var.subscription_id}",
    "tenantId": "${azuread_service_principal.git_auth.application_tenant_id}"
}
    EOF
}
```

![image](https://github.com/integrations/terraform-provider-github/assets/9060893/524f88af-bdcd-4646-9d1c-f24fe72e2b21)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hippogriffin** [comment]
I was getting the same error but resolved it by setting the GITHUB_OWNER variable in my terminal

**Comment by jacob7395** [comment]
Ye that appears to sort, looks like It's in the docs too just missed it.

Thanks for pointing it out hopefully this will help someone else in the future.
