### ISSUE TITLE
[BUG]: SIGSEGV panic in `5.28.0` related to pages feature of github_repository resource

### ISSUE THREAD

**Issue by Laffs2k5** [integrations/terraform-provider-github#1743]
Hi,

I'm observing SIGSEGV panic related to usage of pages in repo resources in provider version in `5.28.0`.

### Terraform Version
Please note that the bug was also observed with terraform version `1.4.6`, but I've later upgraded in an attempt to work around the bug.

```shell
$ terraform version 
Terraform v1.5.0
on linux_amd64
```

### Affected Resource(s)
- github_repository

### Terraform Configuration Files
```hcl
variable "org_name" {
  nullable = false
  type     = string
}

variable "app_id" {
  nullable = false
  type     = string
}

variable "app_installation_id" {
  nullable = false
  type     = string
}

variable "github_auth_app_private_key" {
  nullable  = false
  type      = string
  sensitive = true
}

terraform {
  required_version = ">= 1.4.6, <= 1.5.0"
  required_providers {
    github = {
      source  = "integrations/github"
      version = "~> 5.28.0"
    }
  }
}

provider "github" {
  owner = var.org_name
  app_auth {
    id              = var.app_id
    installation_id = var.app_installation_id
    pem_file        = var.github_auth_app_private_key
  }
}

resource "github_repository" "repo_no_pages" {
  name       = "this-repo-has-no-pages"
  visibility = "public"
}

resource "github_repository" "repo_with_pages" {
  name       = "this-repo-has-pages-enabled"
  visibility = "public"
  auto_init  = true # avoid 'main branch must exist before GitHub Pages can be built'
  pages {
    source {
      branch = "main"
      path   = "/"
    }
  }
  depends_on = [
    github_repository.repo_no_pages
  ]
}
```

### Debug Output
```shell
export TF_LOG="DEBUG"
export TF_LOG_PROVIDER="TRACE"
```
https://gist.github.com/Laffs2k5/0bdeff004b5c6c0fe7e947e327e1b368

### Panic Output

Important part:
```shell
Stack trace from the terraform-provider-github_v5.28.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf9a5a7]

goroutine 115 [running]:
github.com/integrations/terraform-provider-github/v5/github.expandPages({0xc000694e00?, 0x1295cf8?, 0x1b?})
```

For full output from `apply` see https://gist.github.com/Laffs2k5/9abc3ac1e3d6f993689c9fbb83490e6d

### Expected Behavior
Both repos declared should be created. The latter should have the pages feature configured.

### Actual Behavior
Both repos was created. The latter does not have the pages feature configured.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Make sure none of the declared repos already exists in the org.
2. Run `terraform init`.
3. Run `terraform apply`.
4. Observe the panic.

### Important Factoids

**Workaround**: To work around this issue downgrade to version `5.27.0` of the provider.

### References
N/A

**Comment by kfcampbell** [comment]
Hmm...looks like this is related to #1716. @0x46616c6b do you have thoughts on what might be happening here?

**Comment by 0x46616c6b** [comment]
I checked it and can't reproduce the issue. But I checked it with a PAT. At work I also used that provider with a GitHub App. I will double check the code and try to find the nil pointer.

My configuration which is working (not really differs from @Laffs2k5:

```terraform
resource "github_repository" "this" {
  name       = "tf-test-provider"
  visibility = "public"
  auto_init  = true

  pages {
    source {
      branch = "main"
      path   = "/"
    }
  }
}

terraform {
  required_providers {
    github = {
      source  = "integrations/github"
      version = "5.28.0"
    }
  }
}

provider "github" {
  owner = var.github_owner
}

variable "github_owner" {
  type    = string
  default = "0x46616c6b"
}
```

**Comment by 0x46616c6b** [comment]
Oh, update! I can reproduce it on a newly created repository. Will dig into that and provide a fix!

**Comment by Laffs2k5** [comment]
> Hmm...looks like this is related to #1716. @0x46616c6b do you have thoughts on what might be happening here?
> 
> @Laffs2k5 does this only occur with v5.28.0 or does it happen with previous versions of the provider as well?

As noted one workaround is to stick with `v5.27.0`. 
I have not observed the issue using prior versions of the provider.
