### ISSUE TITLE
[BUG]: Error when using different types of 'pull_request_bypassers' in the 'github_branch_protection' resource

### ISSUE THREAD

**Issue by cclavero-mk** [integrations/terraform-provider-github#1747]
### Describe the need

When you mix different types of 'pull_request_bypassers' in the 'github_branch_protection' resource, for example mixing normal users and GitHub Apps, the provider doesn't work as expected when you try to execute the `apply` and gives an strange error about 'Could not resolve to a node'. If we comment the GitHub App the `apply` works as expected

### SDK Version

terraform-provider-github v5.26.0

### Relevant log output

```shell
Error: Could not resolve to a node with the global id of ''
│ 
│   with module.repos["xxx"].github_branch_protection.main["xxxx"],
│   on ../../../modules/repository/main.tf line 47, in resource "github_branch_protection" "main":
│   47: resource "github_branch_protection" "main" {
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mering** [comment]
Duplicate of #1248

**Comment by Klaitos** [comment]
I'm facing the issue. I'm pretty sur this was working before ? Is there any workaround ?
