### ISSUE TITLE
[BUG]: Validation error in github_team_membership when using team slug

### ISSUE THREAD

**Issue by kristian-lesko** [integrations/terraform-provider-github#1749]
### Describe the need

Hello, I'm duplicating the issue #1583, as it sadly seems not to be fixed for the `github_team_membership` resource.

PR #1664 only fixed this for the `github_team` and `github_team_members` resources; same fix (removing validation and allowing slugs) should probably be applied for `github_team_membership`.

Thank you 🙂 

### Relevant log output

```shell
Inappropriate value for attribute "team_id": string required.
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment]
@kristian-lesko do you have the inclination to open up a PR for this behavior?

**Comment by kristian-lesko** [comment]
Hello @kfcampbell, I can surely try to open one.
