### ISSUE TITLE
[FEAT]: Allowing Dependabot to access private dependencies 

### ISSUE THREAD

**Issue by NikitaCloudRuntime** [integrations/terraform-provider-github#1752]
### Describe the need

Hello,

I checked documentation and reviewed existing terraform resources but haven't found the way how to [enable Dependabot to access private dependencies](https://docs.github.com/en/organizations/keeping-your-organization-secure/managing-security-settings-for-your-organization/managing-security-and-analysis-settings-for-your-organization#allowing-dependabot-to-access-private-dependencies) 
Could you let me know if it possible somehow over current terraform provider?

Thank you

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment]
@NikitaCloudRuntime I don't think API support for this functionality exists. Are you able to find API docs for it?
