### ISSUE TITLE
[DOCS]: Example usage in github_repository_collaborators doesn't match argument reference

### ISSUE THREAD

**Issue by commscheck** [integrations/terraform-provider-github#1757]
### Describe the need

Page in question: https://registry.terraform.io/providers/integrations/github/latest/docs/resources/repository_collaborators

The "example usage" shows this:

```terraform
resource "github_repository_collaborators" "a_repo_collaborators" {
  repository = github_repository.some_repo.name

  user {
    permission = "admin"
    username  = "SomeUser"  // (1)
  }

  team {
    permission = "pull"
    team_id = github_team.some_team.slug   // (2)
  }
}
```

* The user block example (1) shows `user.username`, but the argument reference says it should be `usernames`. I think the example is correct for this one?
* The team block example (2) shows `team.team_id`, but the argument reference says it should be `team`. Unsure which is correct (maybe `team_id` if I'm reading the [source code](https://github.com/integrations/terraform-provider-github/blob/main/github/resource_github_repository_collaborators.go#L62) correctly?.
* The top-level `user` argument says "(Optional) List of uses" which has a typo, should be "users".

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment]
@commscheck do you have any interest in opening up a PR to fix this?

**Comment by Nmishin** [comment]
looks like it was resolved here: https://github.com/integrations/terraform-provider-github/pull/1936
