### ISSUE TITLE
github_repositories data only returns public repos

### ISSUE THREAD

**Issue by dandill-curative** [integrations/terraform-provider-github#1760]
I'm not sure if this is expected behavior or a bug, and it was unclear in the documentation. When using github_repositories to query my org's github repos I am only able to get public repos to be returned. Private repos are not included in the output.

```
data "github_repositories" "repo" {
  query           = "org:myorgname"
  include_repo_id = true
}
```

**Comment by duxbuse** [comment]
You will need an auth token to see non-public stuff
