### ISSUE TITLE
Membership fails when also adding to team and only 1 license seat available

### ISSUE THREAD

**Issue by robburger** [integrations/terraform-provider-github#177]
### Terraform Version
`Terraform v0.11.11`

### Provider Version
`terraform-provider-github_v1.3.0_x4`

### Affected Resource(s)
- github_membership
- github_team_membership

### Terraform Configuration Files
```hcl
resource "github_team" "team" {
  name        = "Team"
}

resource "github_membership" "name_surname" {
  username = "gh_username"
  role     = "member"
}

resource "github_team_membership" "name_surname_team" {
  team_id  = "${github_team.team.id}"
  username = "gh_username"
  role     = "member"
}
```

### Debug Output (important bits, in order)
```bash
[DEBUG] Creating membership: orgname/gh_username
[DEBUG] Creating team membership: 123456/gh_username (member)
---[ REQUEST ]---------------------------------------
PUT /teams/123456/memberships/gh_username HTTP/1.1
---[ REQUEST ]---------------------------------------
PUT /orgs/orgname/memberships/gh_username HTTP/1.1
---[ RESPONSE ]--------------------------------------
HTTP/1.1 200 OK
---[ RESPONSE ]--------------------------------------
HTTP/1.1 422 Unprocessable Entity

PUT https://api.github.com/orgs/orgname/memberships/gh_username: 422 You must purchase at least one more seat to add this user as a member. [{Resource: Field:user Code:no_seat Message:}]
```

### Expected Behavior
An existing GitHub user should have been created and added to a team, taking up an available seat.

### Actual Behavior
An invite was sent to the user, but `terraform apply` fails due to `422` error and does not update state file.

### Steps to Reproduce
1. Ensure that there is *only* one available license on a paid GitHub plan
2. Invite a user to the org and a team in a single `terraform apply`

### Important Factoids
This appears to be a race condition, happening only if there is one license left in a paid GitHub plan. It seems that Terraform chooses to apply the team membership before the org membership. GitHub, as part of the API call on team membership, also invites the user and claims the last available seat. On the subsequent org API call, I suspect GitHub checks available licenses before seeing if there is a pending invite for that user.

### Workaround
A manual `depends_on` in the `github_membership` resource block resolves this.

### Solution
Would be great if the dependency was internal to the provider.

**Comment by rmclaughlin-nelnet** [comment]
I ran into this today. Any chance getting this fixed?
