### ISSUE TITLE
[FEAT]: SAML external identity exposed for GitHub user

### ISSUE THREAD

**Issue by felixlut** [integrations/terraform-provider-github#1794]
### Describe the need

The company I work for is using an [external IDP provider (Azure AD)](https://docs.github.com/en/enterprise-cloud@latest/organizations/managing-saml-single-sign-on-for-your-organization/connecting-your-identity-provider-to-your-organization) for our Organizations SSO/SAML integration to GitHub. Sometimes we want to know the ``User`` mapping between GitHub and our IDP (i.e., GitHub user `X` corresponds to Azure AD user `Y`). 

This information is available in the UI via https://github.com/orgs/{MY-ORG}/people/{GITHUB-USERNAME}/sso, and via the [GraphQL API](https://github.com/github/platform-samples/issues/168), so it should be technically possible to fetch said information (`externalIdentities` under [`OrganizationIdentityProvider`](https://docs.github.com/en/graphql/reference/objects#organizationidentityprovider)).

My initial suggestion would be to expose it under the [`github_user`](https://registry.terraform.io/providers/integrations/github/latest/docs/data-sources/user) datasource, but I could also see an argument for exposing it under [`github_membership`](https://registry.terraform.io/providers/integrations/github/latest/docs/data-sources/membership) datasource, since that is already tying the user to a specific Organization. With the former, either you would need to specify the Organization in the datasource, or infer it from the [`owner`](https://registry.terraform.io/providers/integrations/github/latest/docs#owner) field of the provider (which might not always be set). Or a third option would be to create an entirely new datasource, eg `github_user_external_identity`. Opinions would be appreciated 😄 

I'm willing to work on this as well, if this is something you'd be willing to merge!

### API Version

GraphQL API

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment]
I'm more in favor of a new datasource but I'd also be willing to expose it under github_membership. This is definitely something I'd be happy to review/release!

**Comment by felixlut** [comment]
I'll start playing around with a new datasource!

**Comment by kfcampbell** [comment]
@felixlut I just remembered #1778 exists. Instead of a fresh implementation, would you mind reviewing/validating @jsifuentes's contribution and we can go from there? Thank you!

**Comment by felixlut** [comment]
@kfcampbell I'll take a look! I've essentially gotten my own implementation to work (just the most fun part left, the tests 😅), but at first glance #1778 looks somewhat different from mine. #1778 is fetching every single external identity from the Org, while I fetch it for a single user. I think both can live at the same time, just as [`repository_pull_request`](https://registry.terraform.io/providers/integrations/github/latest/docs/data-sources/repository_pull_request) and [`repository_pull_requests`](https://registry.terraform.io/providers/integrations/github/latest/docs/data-sources/repository_pull_requests) (notice the `s`).

I'll take a more thorough look tomorrow!

**Comment by jsifuentes** [comment]
Hi. Apologies for not creating an issue before submitting the PR.

I didn't fully consider putting this functionality in the existing `github_organization` data source before I created the new data source in #1778. Frankly, I'm happy to change the approach if can agree on how it'll look in the response.

Do you or @kfcampbell have a preference on whether the external identities are returned in their own key or whether the SAML identities are merged into the existing `members` key?

iow, if an `externalIdentities` object is returned for a `login`, do we put merge it in here with the members?
https://github.com/integrations/terraform-provider-github/blob/8ad3299ca3edd0b6c4ade6439c905676bbe26967/github/data_source_github_organization.go#L140-L148

Or do we put `external_identities` as its own key here?
https://github.com/integrations/terraform-provider-github/blob/8ad3299ca3edd0b6c4ade6439c905676bbe26967/github/data_source_github_organization.go#L155-L164

I'm leaning towards the first option.

**Comment by felixlut** [comment]
@jsifuentes I looked for this feature about a month ago, finding no issues or PR:s, but when I created #1794 I honestly spent 0 seconds looking again. So I wouldn't have found it either way😅

I'm torn between the two (i.e., its own datasource or as a part of `github_organization`). I'd say that your first approach would be the better, i.e., expanding the `user` field with the additional content, but depending on how detailed the external identity information should be, it could become somewhat "bloaty". 

For my usecase, I realized that I might want more that just the `name_id` that you expose with #1778, but cramming all that into the existing datasource might be a bit much. I realized that `name_id` and `username` where identical for almost everyone in my Organization, except for a few edge-cases who had changed their names in real life. In those cases `name_id` seemed to be the one to go with, but that's just from my limited testing. Not sure what the difference between these two actually are, so I'd like both to be exposed if possible (see code snippet and image below). 

I also realized that there is a difference between `samlIdentity` and `scimIdentity`, see [docs here](https://docs.github.com/en/graphql/reference/objects#externalidentity). At my work we've started looking into [enabling SCIM](https://docs.github.com/en/enterprise-cloud@latest/organizations/managing-saml-single-sign-on-for-your-organization/about-scim-for-organizations), and as such I'd like the SCIM information to be made available as well. 

```go
Schema: map[string]*schema.Schema{
	"username": {
		Type:     schema.TypeString,
		Required: true,
	},
	"organization": {
		Type:     schema.TypeString,
		Optional: true,
	},
	// Can't set named Keys from what I understand (https://discuss.hashicorp.com/t/custom-provider-how-to-reference-computed-attribute-of-typemap-list-set-defined-as-nested-block/22898/2)
	"saml_identity": {
		Type:     schema.TypeMap,
		Computed: true,
		Elem: &schema.Schema{
			Type: schema.TypeString,
		},
	},
	"scim_identity": {
		Type:     schema.TypeMap,
		Computed: true,
		Elem: &schema.Schema{
			Type: schema.TypeString,
		},
	},
},
```
resulting in the actual fields being something like this:

![image](https://github.com/integrations/terraform-provider-github/assets/34520175/a134700d-8924-42f5-ac94-01dbadbb101a)

Cramming "EVERYTHING" into the existing `github_organization` might be a bit "bloaty" (introducing extra API calls, and "hiding" the external identity information as opposed to a dedicated resource comes to mind for example). @kfcampbell what are your general stance when it comes to these things? Keeping `github_organization` simple, and allow #1778 to create a new dedicated resource that can be more detailed, or alter `github_organization` to be more detailed? Personally I'm leaning toward a dedicated datasource like #1778

I also opened a draft PR with my implementation #1796, which shows how I mean😄

**Comment by kfcampbell** [comment]
Thank you both for the thoughts and discussion here! I'm in favor of a separate data source for the bloat reasons mentioned.

**Comment by felixlut** [comment]
Then I propose that #1778 should be altered slightly to include `saml_identity` and `scim_identity`, while also including the `github_login` as in the code snippet below (and #1796 for reference). 

```go
Schema: map[string]*schema.Schema{
	"github_login": {
		Type:     schema.TypeString,
		Computed: true,
	},

	// Can't set named Keys from what I understand (https://discuss.hashicorp.com/t/custom-provider-how-to-reference-computed-attribute-of-typemap-list-set-defined-as-nested-block/22898/2)
	"saml_identity": {
		Type:     schema.TypeMap,
		Computed: true,
		Elem: &schema.Schema{
			Type: schema.TypeString,
		},
	},
	"scim_identity": {
		Type:     schema.TypeMap,
		Computed: true,
		Elem: &schema.Schema{
			Type: schema.TypeString,
		},
	},
},
```

When #1778 is merged, I'll see if it makes sense to add `github_user_external_identity` in #1796 as well, and if so base it on however #1778 turns out. Sounds good @jsifuentes @kfcampbell ?

**Comment by jsifuentes** [comment]
I pushed a change to #1778 that adds additional SAML fields and the SCIM fields to the data source. Hope that works for your use case.

**Comment by felixlut** [comment]
#1778 looks good to me, except for a [short comment](https://github.com/integrations/terraform-provider-github/pull/1778#discussion_r1266400586) I made. 

I'll leave it to you/@kfcampbell whether or not to change that.
