### ISSUE TITLE
[BUG] Sudden issue with Dependabot secrets

### ISSUE THREAD

**Issue by nikolay** [integrations/terraform-provider-github#1801]
The code has been working for years, but suddenly, I started getting this error:

```
Terraform v1.5.3
on linux_amd64
...
Error:  PUT https://api.github.com/orgs/gramLabs/dependabot/secrets/[REDACTED]: 422 Invalid request.
Invalid property /selected_repository_ids/0: `[REDACTED]` is not of type `string`.
Invalid property /selected_repository_ids/1: `[REDACTED]` is not of type `string`.
...
Invalid property /selected_repository_ids/30: `[REDACTED]` is not of type `string`. []

  with github_dependabot_organization_secret.secrets["[REDACTED]"],
  on secrets.tf line 23, in resource "github_dependabot_organization_secret" "secrets":
  23: resource "github_dependabot_organization_secret" "secrets"


Operation failed: failed running terraform apply (exit 1)
```

**Comment by kfcampbell** [comment]
@nikolay what version of the provider are you using? Can we narrow it down to a specific pull request, or do you think it's an API-side change?

**Comment by nikolay** [comment]
@kfcampbell Always the latest and greatest. I downgraded to v5.29, but it seems to be a GitHub API issue, I guess.

**Comment by kfcampbell** [comment]
Hmm...I'm not seeing any particularly suspicious PRs to this repo recently, are you?

**Comment by nikolay** [comment]
As the ticket states, it just suddenly stopped working, i.e. something has changed on the GitHub's side, I guess.

**Comment by kfcampbell** [comment]
In that case, perhaps the best thing to do would be report it to the [API team here](https://github.com/orgs/community/discussions/categories/api-and-webhooks).

**Comment by nikolay** [comment]
@kfcampbell The API is fine and works great - it's the provider you maintain or the Go library that's not using it correctly. The error message is pretty clear - you want a string to be a string, which it is, though you have a problem with strings being strings.

**Comment by kfcampbell** [comment]
I wonder if it's related to https://github.com/google/go-github/pull/2817. There hasn't been a new release cut since that PR went in, but we can update ASAP as soon as there is one.

**Comment by nikolay** [comment]
@kfcampbell Most probably if Dependabot secrets are covered by that as the issue I'm getting is specifically with Dependabot secrets only - the rest work just fine.

**Comment by kfcampbell** [comment]
That is indeed Dependabot-specific. Still waiting on the release, unfortunately. Perhaps we can request one if it doesn't happen soon.

**Comment by nikolay** [comment]
@kfcampbell Any update? It's not fun to have the whole GitHub provisioning stuck because otherwise, I have to recreate all Dependabot secrets manually...

**Comment by kfcampbell** [comment]
@nikolay the library has been updated in the provider and I'll be cutting a new release later today, which should hopefully resolve the issue. Please report back here if it does not.

**Comment by nikolay** [comment]
Thank you very much, @kfcampbell! 🙇🏻

**Comment by kfcampbell** [comment]
Do you mind trying [v5.34.0](https://github.com/integrations/terraform-provider-github/releases/tag/v5.34.0) and reporting back?

**Comment by nikolay** [comment]
@kfcampbell It worked! Thank you very much!
