### ISSUE TITLE
[FEAT]: Add packages IP ranges to github_ip_ranges

### ISSUE THREAD

**Issue by mikkoc** [integrations/terraform-provider-github#1812]
### Describe the need

https://api.github.com/meta has `packages` IP ranges.

These are not yet available in the data source `github_ip_ranges`

Can you please add them?

### SDK Version

5.32.0

### API Version

5.32.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Pati93** [comment]
Hi all,
I would like to work on this issue.

**Comment by kfcampbell** [comment]
@Pati93 in the future, please feel free to open up PRs for any issue you like! In this case, it looks like #1958 is already open for this issue and we're simply waiting on a google/go-github release.
