### ISSUE TITLE
[BUG]: Refreshing state with token unset will delete all existing non-anonymous resources from the state

### ISSUE THREAD

**Issue by isaac-solvo** [integrations/terraform-provider-github#1816]
Happens with 5.31.0

1. Create a private repository, run Terraform with the `GITHUB_TOKEN` environment variable set
2. Run `terraform refresh`. Everything looks OK.
3. Unset the `GITHUB_TOKEN` environment variable.
4. Run `terraform refresh`.
5. Your state is now empty.

This is a potential major headache.
Resources should not be deleted from the state as a result of an unset authentication token.

**Comment by kfcampbell** [comment]
Does re-setting the token and running `terraform apply` or `terraform refresh` reload the state? 

In what circumstances does this happen?
