### ISSUE TITLE
[BUG] Owner name is missing while requesting public-key

### ISSUE THREAD

**Issue by Nairda015** [integrations/terraform-provider-github#1827]
Hey

I don't see bug template so I created an empty one.
<img width="1114" alt="image" src="https://github.com/integrations/terraform-provider-github/assets/44712992/06acb107-120d-4260-9318-7ba474a051dc">

```tf
resource "github_actions_secret" "aws_owner" {
  repository      = var.repo_name
  secret_name     = "AWS_OWNER"
  plaintext_value = var.aws_owner_login
}
```

this works fine if I put this in the root main.tf
but after I move this into the custom module request for public-key breaks

```
│ Error: GET https://api.github.com/repos//Upskill.EventSourcing/actions/secrets/public-key: 404 Not Found []
│ 
│   with module.gh_integration.github_actions_secret.aws_owner,
│   on modules/gh_integration/main.tf line 80, in resource "github_actions_secret" "aws_owner":
│   80: resource "github_actions_secret" "aws_owner" {

```

The owner name is missing :/ 

config 
```tf
terraform {
  required_providers {
    github = {
      source  = "integrations/github"
      version = "~> 5.0"
    }
  }
}

provider "github" {
  token = var.github_token
}
```

terraform -v
Terraform v1.5.2
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v5.9.0
+ provider registry.terraform.io/hashicorp/external v2.3.1
+ provider registry.terraform.io/hashicorp/github v5.32.0
+ provider registry.terraform.io/hashicorp/local v2.4.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/random v3.5.1
+ provider registry.terraform.io/hashicorp/time v0.9.1
+ provider registry.terraform.io/hashicorp/tls v4.0.4
+ provider registry.terraform.io/integrations/github v5.31.0

**Comment by kfcampbell** [comment]
We see this pretty commonly. I'm not sure if there's anything we can do at the provider level to fix this. Can you also define the owner and token in the block where you're calling the GitHub provider?

**Comment by Nairda015** [comment]
adding owner prop unfortunately didn't help  
```tf
provider "github" {
  token = var.github_token
  owner = var.repo_owner
}```

**Comment by sharkymcdongles** [comment]
Also seeing the same problem when I try and get branches. Code expects owner for the URL but never sets it, so this is clearly a bug and the provider is unusable as a result.

**Comment by cdegroot** [comment]
Seeing the same when using the Github CLI for auth and trying to retrieve a runner token. The url in the error has `//` where the owner should be.

**Comment by zpbonjour** [comment]
+1
I am not able to set any secrets with `github_actions_secret`.  With or without the owner name in the repository name.  
I did notice that Terraform is hitting:
(with owner/repo in the `repository` value)
> https://api.github.com/repos/my_github_username/my_org_name/my_repo_name/actions/secrets/public-key

(with only the repo in the `repository` value)
> https://api.github.com/repos/my_github_username/my_repo_name/actions/secrets/public-key

I did some experimenting with PyGithub just to make sure my token was working and everything else.  Using the same token I **was** able to get the public key via PyGithub. Based on their documentation they are hitting
> https://api.github.com/repos/my_org_name/my_repo_name/actions/secrets/public-key

See that difference?  **Terraform is adding my Github username to the API request when I am working with a repository owned by an organization.**  If the `repository` value has an owner specified (**owner**/repo) it should be omitting my Github username from the API request.

Example:

```
resource "github_actions_secret" "AWS_ACCESS_KEY_ID" {
  repository      = "my_org_name/my_orgs_repo_name"
  secret_name     = "AWS_ACCESS_KEY_ID"
  encrypted_value = aws_iam_access_key.ak.id
}
```
> https://api.github.com/repos/my_org_name/my_orgs_repo_name/actions/secrets/public-key


```
resource "github_actions_secret" "AWS_ACCESS_KEY_ID" {
  repository      = "my_repo_name"
  secret_name     = "AWS_ACCESS_KEY_ID"
  encrypted_value = aws_iam_access_key.ak.id
}
```
> https://api.github.com/repos/my_github_username/my_repo_name/actions/secrets/public-key

**Comment by zpbonjour** [comment]
For those who saw my previous comment that I deleted, this fixed my issue
```
provider "github" {
  token = var.github_token
  owner = "my_org_name"
}
...
resource "github_actions_secret" "AWS_ACCESS_KEY_ID" {
  repository      = "my_orgs_repo_name". 
  secret_name     = "AWS_ACCESS_KEY_ID"
  encrypted_value = AWS_ACCESS_KEY_ID.ak.id
}

```

**Comment by rkulinski** [comment]
@zpbonjour I have the same setup and issue still persists.

**Comment by jylenhofdecat** [comment]
Because perhaps someone else will have the trouble :

See if you change the namespace in your main terraform and your module terraform call like here :
https://github.com/integrations/terraform-provider-github/issues/876#issuecomment-1303790559

**Comment by kfcampbell** [comment]
Thanks @jylenhofdecat! This behavior is also documented on our docs site [here](https://registry.terraform.io/providers/integrations/github/latest/docs#example-usage): 

> You *must* add a `required_providers` block to every module that will create resources with this provider. If you do not explicitly require `integrations/github` in a submodule, your terraform run may [break in hard-to-troubleshoot ways](https://github.com/integrations/terraform-provider-github/issues/876#issuecomment-1303790559).
