### ISSUE TITLE
[DOCS]: Docs for github_branch_protection restrictions are inaccurate 

### ISSUE THREAD

**Issue by macetw** [integrations/terraform-provider-github#1841]
### Describe the need

For `github_branch_protection`, documentation states:

     limited to a list of one type of restriction (user, team, app)

... but this is not true. GitHub itself is not limited in this way. You can have more than one type of restriction (teams + users), but if you do, you must supply node-id's for each item. For example:

      push_restrictions = [
           data.github_team.testing-team.node_id,
           data.github_team.release-team.node_id,
           data.github_user.svervice-user.node_id,
     ]

It took me a long time to find this workaround Please update the doc to include this workaround: it took me way too long to find it.

Also important to document: the given user or team must have specific write access to the repository. If he/she/they don't, github will reject the given actor. This will create drift in the terraform drift if github rejects the given actor.

### Relevant log output

```shell
Terraform will perform the following actions:

  # github_branch_protection.av-release-candidate will be updated in-place
  ~ resource "github_branch_protection" "av-release-candidate" {
        id                              = "MDIwOkJyYWZZZFByb3RlY3Rpb25SdWxlNDQ2MQ=="
      ~ push_restrictions               = [
          + "MDQZZZVhbTExMQ==",
          + "MDQZZZVhbTI5",
            # (1 unchanged element hidden)
        ]
        # (9 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by macetw** [comment]
The pasted relevant log output, is a representative section of a terraform-plan, where drift has occurred, with a actor that was outside permissions of write access.

**Comment by kfcampbell** [comment]
@macetw do you have any interest in opening up a PR to document this behavior? The relevant file is [here](https://github.com/integrations/terraform-provider-github/blob/main/website/docs/r/branch_protection.html.markdown).
