### ISSUE TITLE
[DOCS]: github_issue owner argument field is not expected but is required on docs

### ISSUE THREAD

**Issue by evertonspader-tomtom** [integrations/terraform-provider-github#1849]
### Describe the need

The documentation for `github_issue` describes `owner` as a [supported argument](https://registry.terraform.io/providers/integrations/github/latest/docs/resources/issue#argument-reference), however, running a simple issue with the following code:

```hcl
terraform {
  required_version = ">= 1.3.0"
  required_providers {
    github = {
      source  = "integrations/github"
      version = "5.33.0"
    }
  }
}

provider "github" {
  owner = var.github_organization
}

variable "github_organization" {
  type        = string
  default     = "my-org"
  description = "Name of organization in Github"
}

variable "github_repository_name" {
  description = "GitHub repository name"
  type        = string
  default   = "my-repo"
}

resource "github_issue" "test" {
  repository = var.github_repository_name
  title      = "Test Issue Title"
  body       = "The body of my issue"
  owner      = var.github_organization
}
```

Yields in the following error:
```shell
│ Error: Unsupported argument
│ 
│   on issue.tf line 5, in resource "github_issue" "test":
│    5:   owner      = var.github_organization
│ 
│ An argument named "owner" is not expected here.
```

From the [source code](https://github.com/integrations/terraform-provider-github/blob/main/github/resource_github_issue.go#L22-L75) it seems indeed that the `owner` argument is not available.

On the other hand, if `repository_name` is set in the `github_issue` resource and the `owner` is also set in the provider block, the `terraform apply` command fails with the following error message:

```shell
github_issue.test: Creating...
╷
│ Error: POST https://api.github.com/repos//my-repo/issues: 404 Not Found []
│ 
│   with github_issue.test,
│   on issue.tf line 1, in resource "github_issue" "test":
│    1: resource "github_issue" "test" {
│ 
```

It seems as if it's failing to pick up the owner/organization to prefix in the repository name.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment]
That is a great catch. Do you have the interest/inclination to open up a PR for this behavior?

**Comment by Nmishin** [comment]
Added MR for removing parameter from the docks: https://github.com/integrations/terraform-provider-github/pull/1944

But I can't reproduce the second one issue, I used provider version v5.39.0, maybe something changed between versions.
