### ISSUE TITLE
[Bug] Terraform refresh fails if deployment environment's branch policy has been deleted

### ISSUE THREAD

**Issue by calebworks** [integrations/terraform-provider-github#1853]
### Describe the need

If a repository deployment environment has a branch policy rule that's tracked in Terraform state and that branch policy is deleted outside of Terraform, subsequent Terraform refresh operations will fail as the Github API returns a 404.

Rather than shitting the bed, the Github provider should handle this 404 gracefully and re-create the deleted branch policy.

Re-creating the branch policy manually doesn't fix the issue. The only way I've found to resolve it is to manually remove the `github_repository_deployment_branch_policy` resource from the Terraform state with `terraform state rm` and re-run the refresh operation.

### Steps to reproduce:
1. Deploy a `github_repository_deployment_branch_policy` resource
2. Manually delete the branch policy in the Github console
3. Run any of a `terraform plan`, `terraform apply` or `terraform refresh` operation. The operation will fail with an error similar to:
```
│ Error: GET https://api.github.com/repos/redacted/redacted/environments/redacted/deployment-branch-policies/redacted: 404 Not Found []
│
│   with github_repository_deployment_branch_policy.main,
│   on main.tf line 1, in resource "github_repository_deployment_branch_policy" "main":
│  1: resource "github_repository_deployment_branch_policy" "main" {
│
```

This completely breaks any project that implements branch policies and unnecessarily requires manual remediation to fix it.

### SDK Version

5.32

### Relevant log output

```shell
As above
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by o-sama** [comment]
I'll take a look at this in the next couple of days, but off the top of my head I think this'll be as simple as checking for a 404 in the read function and removing the resource from state if that's the case. Will create a PR in the coming days for this.
