### ISSUE TITLE
[BUG]: Provider fails whenever a github_release is manually deleted from GitHub

### ISSUE THREAD

**Issue by bloudraak** [integrations/terraform-provider-github#1864]
### Expected Behavior

Whenever a github_release is manually deleted in GitHub after being created using the Terraform provider, the provider should inform Terraform that the resource no longer exists by setting the id to empty. 

### Actual Behavior

The terraform provider fails with a 404, and you have to manually delete the github_release from the state file.

### Terraform Version

Terraform v1.5.6
on darwin_arm64
+ provider registry.terraform.io/integrations/github v5.34.0

### Affected Resource(s)

- resource_github_release

### Terraform Configuration Files

```hcl
resource "github_release" "this" {
  repository = "example"
  tag_name   = "v0.1.0"
  name       = "v0.1.0-initial"
  body       = "body"
  draft      = false
  prerelease = true
}
```

### Steps to Reproduce

1. Create a release using Terraform
2. Go to GitHub, delete the release
3. Run `terraform plan` or `terraform apply` and notice a 404  

### Panic Output

```shell
module.repository["template"].github_repository.this: Refreshing state... [id=template]
module.repository["terraform-azure-storage-account"].github_repository.this: Refreshing state... [id=terraform-azure-storage-account]
module.repository["template"].github_branch.this: Refreshing state... [id=template:main]
module.repository["terraform-azure-storage-account"].github_branch.this: Refreshing state... [id=terraform-azure-storage-account:main]
module.repository["terraform-azure-storage-account"].github_release.this[0]: Refreshing state... [id=118808064]
module.repository["terraform-azure-storage-account"].github_branch_protection_v3.this: Refreshing state... [id=terraform-azure-storage-account:main]
module.repository["template"].github_branch_protection_v3.this: Refreshing state... [id=template:main]

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: GET https://api.github.com/repos/myorg/terraform-azure-storage-account/releases/118808064: 404 Not Found []
│ 
│   with module.repository["terraform-azure-storage-account"].github_release.this[0],
│   on modules/repository/main.tf line 55, in resource "github_release" "this":
│   55: resource "github_release" "this" {
│ 
╵
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment]
@bloudraak do you have the interest/inclination to open up a PR for this behavior?

**Comment by o-sama** [comment]
@kfcampbell since this is essentially the same issue in #1875, but for a different resource, I can replicate that change for this resource as well to get this out of the way tonight.
