### ISSUE TITLE
[FEAT]: OpenTF support

### ISSUE THREAD

**Issue by skyzyx** [integrations/terraform-provider-github#1869]
### Describe the need

https://opentf.org/announcement

We want to understand how this provider is affected by the OpenTF announcement, and what the plans for support are moving forward.

From a technical perspective, I expect that it will be a no-op for the time being as OpenTF anticipates maintaining compat/interop for the foreseeable future. (However, OpenTF has stated that _some_ functionality may be added to OpenTF that is a _superset_ of what's in base Terraform. [[source](https://github.com/opentffoundation/roadmap/issues/24)])

From a process perspective:

1. If there is a bug in OpenTF that does not exist in Terraform (or vice-versa), will bug reports (as they pertain to this project) be treated equally on both platforms?

1. Will testing be performed with code targeting both platforms?

1. For OpenTF's potential future "superset" functionality, will that be treated as a first-class citizen?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment]
Hi @skyzyx!

I don't have concrete answers for you; I'm still processing this whole thing myself. So far my thoughts are:
1. I don't know. _Hopefully_ the platforms stay in sync in this regard. 
2. I'm definitely not opposed to doing CI testing on both platforms, we should do that. 
3. I don't know, it's too early to tell. 

I know these are unsatisfying answers and I'm hopeful we can take concrete steps on number two at least in the near future.

**Comment by skyzyx** [comment]
Your response is greatly appreciated.

This whole situation has created uncertainty at a time when we could really do without it. My company leverages several open-source and SaaS offerings in the Terraform ecosystem, and I've been reaching out across the ecosystem to understand where everyone is on this topic, and identifying what we need to watch out for.

Hoping for the very best from this whole situation, but planning ahead for the absolute worst.

**Comment by kfcampbell** [comment]
Agreed, this type of disruption is never desirable. Feel free to chime in with more thoughts as the situation progresses and we can talk about how things shake out.
