### ISSUE TITLE
[DOCS]: Clarify collaborator roles and what permissions they confer

### ISSUE THREAD

**Issue by jkodroff** [integrations/terraform-provider-github#1872]
### Describe the need

The docs for resources like `github_team_repository`, the GH user docs, and the GH API docs seem inconsistent with what the available roles are and what permissions they confer.

The [`github_team_repository` docs](https://github.com/integrations/terraform-provider-github/blob/main/website/docs/r/team_repository.html.markdown) say:

```
`permission` - (Optional) The permissions of team members regarding the repository.
  Must be one of `pull`, `triage`, `push`, `maintain`, `admin` or the name of an existing [custom repository role](https://docs.github.com/en/enterprise-cloud@latest/organizations/managing-peoples-access-to-your-organization-with-roles/managing-custom-repository-roles-for-an-organization) within the organisation. Defaults to `pull`.
```

The [Collaborators API docs](https://docs.github.com/en/rest/collaborators/collaborators?apiVersion=2022-11-28#get-repository-permissions-for-a-user) say:

> Checks the repository permission of a collaborator. The possible repository permissions are admin, write, read, and none.

> Note: The permission attribute provides the legacy base roles of admin, write, read, and none, where the maintain role is mapped to write and the triage role is mapped to read. To determine the role assigned to the collaborator, see the role_name attribute, which will provide the full role name, including custom roles. The permissions hash can also be used to determine which base level of access the collaborator has to the repository.

According to [Repository roles](https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/managing-repository-roles/repository-roles-for-an-organization#permissions-for-each-role) in GH docs, Read and Triage are _not_ the same (they have different checkmarks in the screenshot below):

<img width="736" alt="image" src="https://github.com/integrations/terraform-provider-github/assets/410614/f49d8498-b444-446b-8282-faa5276f3a08">

Ideally, I would like the docs to contain:

1. The complete list of roles, including any aliases, with legacy values clearly indicated.
2. A link to a single source in docs for the most current info (although it looks like these change pretty infrequently).

If the maintainers can point me to where the source of truth is for this (maybe in the SDK docs? not sure), I'm happy to make this change across all affected resources.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by GilUpstream** [comment]
We just ran into this as well. Thanks for submitting the issue.

**Comment by jkodroff** [comment]
@kfcampbell If you know what the source of truth should be, I can submit a PR, but I also understand that GH might need to resolve the inconsistency with the sources I cited before you can give me an answer.

**Comment by kfcampbell** [comment]
@jkodroff The second part of your response is unfortunately correct. Perhaps it would be appropriate to log a request [here](https://github.com/orgs/community/discussions/categories/api-and-webhooks)?

**Comment by jkodroff** [comment]
@kfcampbell Done: https://github.com/orgs/community/discussions/72727
