### ISSUE TITLE
[BUG]: import github_organization_ruleset crashed provider

### ISSUE THREAD

**Issue by zoezhangmattr** [integrations/terraform-provider-github#1886]
### Expected Behavior

should work expected to import github_organization_ruleset

### Actual Behavior

Stack trace from the terraform-provider-github_v5.36.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x102f0d764]

goroutine 83 [running]:
github.com/integrations/terraform-provider-github/v5/github.flattenConditions(0x140009daa38, 0x1)
        github.com/integrations/terraform-provider-github/v5/github/respository_rules_utils.go:180 +0x314
github.com/integrations/terraform-provider-github/v5/github.resourceGithubOrganizationRulesetRead(0x14000c80bd0, {0x10331a260?, 0x14000224f00?})
        github.com/integrations/terraform-provider-github/v5/github/resource_github_organization_ruleset.go:492 +0x5bc
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0x14000492be0, 0x14000120500, {0x10331a260, 0x14000224f00})
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/resource.go:470 +0x1ac
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0x1400011f638, {0x1400010d020?, 0x0?}, 0x1400010d020)
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/helper/plugin/grpc_provider.go:535 +0x338
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler({0x1035460e0?, 0x1400011f638}, {0x1035a8f08, 0x14000909c80}, 0x14000c80700, 0x0)
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/tfplugin5/tfplugin5.pb.go:3269 +0x174
google.golang.org/grpc.(*Server).processUnaryRPC(0x140003a8000, {0x1035ad108, 0x14000592d00}, 0x14000a117a0, 0x14000881770, 0x103e3c190, 0x0)
        google.golang.org/grpc@v1.55.0/server.go:1337 +0xc7c
google.golang.org/grpc.(*Server).handleStream(0x140003a8000, {0x1035ad108, 0x14000592d00}, 0x14000a117a0, 0x0)
        google.golang.org/grpc@v1.55.0/server.go:1714 +0x840
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.55.0/server.go:959 +0x88
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.55.0/server.go:957 +0x170

Error: The terraform-provider-github_v5.36.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Terraform Version

terraform core version 1.5.7
github terraform version: terraform-provider-github_v5.36.0

### Affected Resource(s)

github_organization_ruleset

### Terraform Configuration Files

```hcl
resource "github_organization_ruleset" "sre-general-rule" {
  name        = "sre-general-rule"
  target      = "branch"
  enforcement = "active"

  conditions {
    ref_name {
      include = ["~ALL"]
      exclude = []
    }
  }

  rules {
    creation                = true
    update                  = true
    deletion                = true
    required_linear_history = true
    required_signatures     = true

    branch_name_pattern {
      name     = "example"
      negate   = false
      operator = "starts_with"
      pattern  = "ex"
    }
  }
}
```

### Steps to Reproduce

import existent org repository ruleset

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by o-sama** [comment]
@zoezhangmattr thanks for submitting this! @csainty has also shared a couple of things with me and I'm working on fixes, I'll aim to open a PR related to this today.
