### ISSUE TITLE
[DOCS]: Document how github_repository_ruleset.rules.required_status_checks.required_check.integration_id can be found

### ISSUE THREAD

**Issue by dimber-cais** [integrations/terraform-provider-github#1893]
### Describe the need

Its not clear from the documentation how the following property's value can be found so it may be correctly set:
```
github_repository_ruleset.rules.required_status_checks.required_check.integration_id can be found
```

Its also unclear from the GH API documentation, all they say is:
> integration_id integer
The optional integration ID that this status check must originate from.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mikutas** [comment]
It's still unclear how `integration_id` can be found.
