### ISSUE TITLE
[BUG]: Terraform AWS provider handling of the tag ignores

### ISSUE THREAD

**Issue by anil1396** [integrations/terraform-provider-github#1907]
### Expected Behavior

We have added the ignore tag in the AWS provider to ignore the deletion of platform tag but still it's not working as expected:

provider "aws" {
  region     = var.region
  access_key = var.aws_access_key_id
  secret_key = var.aws_secret_access_key
  token      = var.aws_session_token

  default_tags {
    tags = {
      created-by = "TF_Geosigns-Be-BPA2-Pipeline"
    }
  }
  
  ignore_tags {
    key_prefixes = [
      "platform"
    ]
  }
}

### Actual Behavior

It's failing with below error
![Terraform_error](https://github.com/integrations/terraform-provider-github/assets/98594353/86f75aab-77aa-425b-a0f8-b7da6c522893)
 :

![image](https://github.com/integrations/terraform-provider-github/assets/98594353/0e912c4b-e597-47fe-bca9-3eb6732c5ac2)

### Terraform Version

Terraform version - 5.17.0

### Affected Resource(s)

- it's a private GitHub repository
- Enabled branch protection

### Steps to Reproduce

aws_instance.be-bpa2-testanu: Modifying... [id=i-02ec3fbcab27beaca]
╷
│ Error: updating tags for volume (vol-04872cadc542c5482): untagging resource (vol-04872cadc542c5482): UnauthorizedOperation: You are not authorized to perform this operation. Encoded authorization failure message: f_t_cXPaYpJY1BNFByQ4_hIZCNxnYuVJOd3OvJIvDKFE91tk-jy-pGdlKEfe7i23fVvc1vWg8CUjD_KTwaPADVcODb5A8b7iT9rflfxZM9T5Zw6sc703qp1KyI0pCAUIFmadVPaHS8x4ypyI7p-vMYoQpVSSB6kOAxdG0jwD_UI16Ff4T2i8nCYx_aguY6kxemi_lQOTJ4lny3fvtS9TVv_OUYWatnuE2A3duh1K4gLQRaCYcqmOLEErk51dZPCJk_Jq6SY1RFLWi75CAxmHLDRG-fs8POxnl5ijOGjoI1ZhrD7Q3g2nUdCeRL5eOLpFsdBqqlDuGyZ9yRaoi8vO4GlNgEKNetXS78ImUDwVzcpaSRMfHq1QPj50qULnWdFIxCTA1sfc8eBo61ayPOBD_QWrHy2vz2gW7QGZ7SJiVlCghW_3dQzbNPnX7a0gM88eTwnSEynpUzjMNmTjwf4FgexQBqle9G3YiXagDjDlxo7bht9SMf_Qjck-cVc0feBtMYNCND1gmkjWxb-E69qfNZCyXWGNIxFKBNsDH8gOKI_zvIh95PHM5nnboITGCUaEmAf7Ofjl2StzxOR5IcorlkkR1AcA7cI6xyOKddbLASW0QUJgCeUO9JAfiUp_agBV9vjKhdC4vj5RCwm_XIlY8kOy3K7RAI8wcPOLeiiHNIfqgyRT6sHIA68L1cfN90OsdsoxUsIB3QbapKZ600_X8EiEzkrpmh_lPgb1ciO-lKr-nv51O3y5SsDnNT3BGtMUTC4hSnmpVIdZJo1DF3CyD6Zl6b4wX_8FIb4r-XViwRuETQPpiwrWlO_o64xTYqXSyfWqhShzq1L1t2AcZXALbesayse_VBTkAL5Ie8JAnwxir5DpG4p7cAGS2DyvjUIfqzM67TBHKs49sejksc6c8Sk0F2oh89TG5L0tUKsc_7VPbplk8mEMae8exciZayykIN_NSsqwpJCtraZlcALo0KIpmNvsnuDmMim7Uf-fUScX26zFykLJHfQteIDkF0Rg-GgFAk3O6CPPJ0oM11zCWn26tsgdyrGxZ-aAiKthnJ_jxPuwv-mhHJ9oTxHtgMQbEaYpIseYiR_7hM3AlUKtU3X43ySPaek1u93rBPZ5MOji-caB4Jk8AFQlKu__rlGKvhL7qF-JAPoFFRkjlToacmMyLleFUlKmoc4fGGh-tLY3-Xmdk3wpUaAS7wqi4-oBXPNGeOt9wwxMifhxP1lU3mdNwD4UaamVqGD23HhCE987LmOsmZ0-rIbT9mpWheFL9KHXfMGyNszFqJoTkVc3TbxLV-1RyLmwKQuC3JsaQ86gjZDk5BRklI8yLHS_2Lt1k6QisTEnIxENeiG3WwGwJFEy0otQc9KpEZ9Dytjm3qO93O7kmoQdsBgqpws7kIx5E7dvY0nYztDr1sp8evzVlwRQd_hbp-5DoCy8VGzvRxObfKUuENgQ23ujJaiEYNhzANCQvTcWjivqY0DXIOQFco-CsN8c_0mBZTWuB7QU12HTm4SVJpHt_rW2UJl598EQUKllT1l9zTS7tyuvdtCb1d3i58lem6pb6IfQyYQqpPU6zIi1xVJsJkxkL1EKefu7hXlwNgIlgqNldp2TbcB09cZAPub59f0eWZFGT2vWDxgO_Tu6ByFCzQlhJz-uK3428j6G9MBXrjqJcD-Af16tHynqBDCmbzGFHbn06g__YyAaV_kOW0K2dcQArD8Wrq_433vfcLiTyeit2zpMqBdsv_quf-4PrXWVR3XZTGgnIIc3es98W-eH3m20mA-z99D4wAH9XH-gGMxaiEFge_bOglRqswbMZdj9Kpn8SHgAMe_LYVCg-feoHW6FjIW6bBQhXxwcbLwAPiK7IVLAv3-_
│ 	status code: 403, request id: 67fafb93-d9f0-4cb8-bfa4-20309a214735
│ 
│   with aws_instance.be-bpa2-testanu,
│   on BE-BPA2-TESTANU.tf line 1, in resource "aws_instance" "be-bpa2-testanu":
│    1: resource "aws_instance" "be-bpa2-testanu" {
│ 
╵
╷
│ Error: updating tags for volume (vol-0403c57f3101ff169): untagging resource (vol-0403c57f3101ff169): UnauthorizedOperation: You are not authorized to perform this operation. Encoded authorization failure message: krU_rhYT-yI5q16IilZ7ZX5kKgHJkFrIZjvtRb63XY2AiHlSyvqGFrZBT3y6jrTvTwdRjkDlNgJ2rI2R7kd4e8kcZ_pcvDR7Pn-A56hb0I9eIn6_QaDzPzKoKn8BAnt2aUqdevJGPVKVFAQ6GIxVJX30OQTgXOjShLsLc_m4kinS_rMGy4bR4tr6kSgv26HKA83rxKSwtHNIhwTqdKVHYIFLtqpyWuYtmNhySGdnsQYNSMy4Pb93s1d9Yr58ICHUm0qW95uLm1RX-cgTaczW5iQVGi7pdwyNrginx8DGkB-yW7OBzyi2SsTs3jtzd361VF6RuQgsreoBjwTXr8xP_gJ2TgNncYAqO02Svkdd9I4Y0zUZ4u8qeiGh6YZIiCSJi9Eo1v0jkrZ8X3vqjYUOK_BmdJjuWCMCT9TeDbnTC3bTZzw-2QVutbmhRO0Ytscc42UsCF5gQHUwSFQ4ei2z91aXsM6L0grMHhjBXTpJZPfV09KXrzckqKvGqaZ6ghXllLm73zN63unZWf5S4nvQq1S3iHnyj8H20YKgD232_Z9pLouG_oiep8AbqyA3tEvGwVnSskmurgyQmZlkE5rmpHhB_zvbIx4TKp8pe7PBpnq0yU0du9SuSVuaGG5ay3cOJ4WmvzaU7Qu8oYYsJ6We1yWdNwGk7dG4RGoMS_4uwzehO6K-UNVpH9dnm_UGkgzkXhm3ShWT9-_VgGSE--eN1GNDcJg_fUJj9EBa0vDfmskMa9Ii4T73CM-Y2JriPCWyATvZOQ2nec5AZmrEbMChloeedDJqDPqWPJgocW4Ajf4mhhXs_Z4mKc8srLxrrMDtvFrSAidY9dcQrnBFLMKgBdhvX1e36o0wrV9cwM_lFu6trjcWUC8jhac0VnwB1I5em9tGSA_pBVhFdm_yDUYf4s_xLBFVFAIAeMtUtupB0VJQjWBa9PQFvjjnWkBV6T57pBnn81UdrKlutgh2mshScpqHTTr7JqJxQKejy3CnMv4Z7nVthDEEuaUZxTaBaAY_C05CNsSAG7ITkLaSK_2hpmfYYalrj_g_QniwKUeD4bilAUfJnCkXrQcRzQoIi0DK4VfBK-KGyCbHoyktG9Xk7BzEAzzspMZUK9xwqjrJZHSDLxvRgHFpb1KuZL-R5HGtmwOFzbin_ZAwuu8YbXEnZuKt0iur_XjkiebUp2ijGGzBzQ5xjrUbyOF-cot2DCUIpf5YNykgprMYwNaRfFesLh_W0TvVHp0yE4U7KVxmcoSouQZ6AjICNiU2Uu6by_eT2SPNXrCzLYjlPEoeg3PY5rp3UIPyf7a0ABQyw4mnzAONzxr8acBPTe30l_SBklJEcDChI_CSFGD0cIMQO21RuChEjQ3CJA5AtsJUasnRVE8zxF3nX80TVYAiSJ5oiS1JxadURMQyC4IjcMnxgQYFuSoIucn7LsjsLq3kzBVjuMIo3FWesXaOenmrqO_bLTM0THUIsASenoB-RUbdDASG_-3t7iuJDIi1A-ufHyG3SvpkFf6kHTjzybziO1z0LEAwdKdOefmvbVZ70CFv7jDO83vZc6BM64X9vRsbXwhbK9s0fUo1Ndl1KkeJbdzanqkDqOhaApGJZsHgEdePwqWWz8FSMxjXlcll3W6rlhXpsufgoxa3_IgyP58pXp-Ar4I0XXvFXQQLi1pASwHckZeQy58xeGlw5cgdB8uAZb5KZV73DcMvc77sc2U_cB24awv2FOjuLf_HFIavdBX-X2_BMM7ncgAzhk4lVXy1pX6IAOF-2Dg88hOX2i4ELwDAbLgPkIHmfqek7nXGtDe4XY_WA8Z8qxcL38AEPsqHSofL51ecYshvZtNw1szsy6Jblt4jCYiIoKs0CvsplRXEqNk8
│ 	status code: 403, request id: 970876ac-fd20-46ae-b80b-dbad9babe62f
│ 
│   with aws_instance.be-bpa2-test1,
│   on BE-BPA2-TESTSRINI.tf line 1, in resource "aws_instance" "be-bpa2-test1":
│    1: resource "aws_instance" "be-bpa2-test1" {
│ 
╵
Operation failed: failed running terraform apply (exit 1)
Error: Terraform exited with code 1.
Error: Process completed with exit code 1.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by o-sama** [comment]
Hi @anil1396, this repository is for the GitHub provider. I think you want to post this in [https://github.com/hashicorp/terraform-provider-aws](`terraform-provider-aws`).

When you do post there, you should include the planned output as well. What you've posted here only shows TF wanted to untag the resource, it doesn't show what tags it wanted to remove.

As for the error you're getting itself, it seems that whatever role TF is using doesn't have the permissions to perform the untag resource action on the volumes.
