### ISSUE TITLE
[BUG]: Organization ruleset invalid property condition

### ISSUE THREAD

**Issue by jcshadhara** [integrations/terraform-provider-github#1909]
### Expected Behavior

The organization ruleset specified in the terraform file applies without errors

### Actual Behavior

The API throws an error when trying to apply an organization ruleset with a condition field:
```
│ Error: POST https://api.github.com/orgs/MyOrganization/rulesets: 422 Invalid request.
│ 
│ Invalid property /conditions: data matches no possible input. See `documentation_url`. []
```

### Terraform Version

Terraform version >= 1.3.6
on linux_amd64
provider registry.terraform.io/integrations/github v5.37.0

### Affected Resource(s)

github_organization_ruleset

### Terraform Configuration Files

```hcl
Ruleset configuration as follows:

resource "github_organization_ruleset" "master_main_branch_protection" {
  name        = "Master and main branches protection"
  target      = "branch"
  enforcement = "active"

  conditions {
    ref_name {
      include = [
        "refs/heads/master",
        "refs/heads/main"
      ]
      exclude = []
    }
  }

  rules {
    deletion         = true
    non_fast_forward = true
    pull_request {
      dismiss_stale_reviews_on_push   = true
      require_code_owner_review       = true
      required_approving_review_count = 1
      require_last_push_approval      = true
    }
  }
}

```
```


### Steps to Reproduce

_No response_

### Debug Output

_No response_

### Panic Output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by o-sama** [comment]
Hi @jcshadhara, i think I know what's happening. Can you try setting either `repository_name` or `repository_id` and reporting back please?

The API expects one of them to be defined even if it's empty.

I'll add that to the documentation and potentially change the schema to reflect that, but it could potentially be a major version change so I'll look into that before saying anything for sure.

Hope this helps!

**Comment by jcshadhara** [comment]
I confirm that adding the following code into the `conditions` property made it work:
```
repository_name {
  include = []
  exclude = []
}
```
Before adding the aforementioned piece of code, I tried with the property `repository_id` but threw the same error posted in the main post.

**Comment by o-sama** [comment]
Interesting, let me play around with that. The API should accept the `repository_id` and `ref_name` combination as per the docs

**Comment by tj-smith47** [comment]
This still does not reflect in the documentaiton: https://registry.terraform.io/providers/integrations/github/latest/docs/resources/organization_ruleset

There is also an undocumented property under `conditions.repository_name` called `protected` that shows when running apply.
