### ISSUE TITLE
[FEAT]: Allow renaming repositories without causing github_branch recreation

### ISSUE THREAD

**Issue by brettswan** [integrations/terraform-provider-github#1926]
### Describe the need

Currently, if you create a repository and a branch, referencing the repository in the branch resource definition, you're unable to rename the repository without causing the branch to be recreated (destroyed and rebuilt). Example code below:
```hcl
resource "github_repository" "this" {
  name = var.name
  description = var.description
  visibility = "internal"
  auto_init = true
  allow_update_branch = true
  
  has_downloads = false
  has_issues = false
  has_discussions = false
  has_projects = false
  has_wiki = true
}

resource "github_branch" "default" {
  repository = github_repository.this.id
  branch = var.default_branch
}
```
This is because the `github_branch` resource uses the repository _name_ instead of the repository _id_, and repository is currently setup with `ForceNew` set to `true`. As a result, if you change the name of the repository, Terraform thinks it needs to destroy the existing branch and replace it with a new resource. Considering the repository itself hasn't changed, only the name, this is super undesirable behavior because Terraform will attempt to destroy a branch that may have commits already, or if the branch is protected, prevent Terraform from ever executing successfully to make the change. 

I propose that the `github_branch` resource optionally take a repository id or name, and only recreate the resource if the repository id has changed.

### Relevant log output

```shell
# module.repositories["MyRepo"].github_branch.default must be replaced
-/+ resource "github_branch" "default" {
      ~ etag          = "W/\"<etag>\"" -> (known after apply)
      ~ id            = "MyRepoOldName:master" -> (known after apply)
      ~ ref           = "refs/heads/master" -> (known after apply)
      ~ repository    = "MyRepoOldName" -> "MyRepoNewName" # forces replacement
      ~ sha           = "<sha>" -> (known after apply)
      + source_sha    = (known after apply)
        # (2 unchanged attributes hidden)
    }
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TechDawg270** [comment]
if this is considered a good first issue, i would love to give it a shot for hacktoberfest

**Comment by brettswan** [comment]
I'd think this should be pretty straight forward to implement, just don't have bandwidth to take this on myself right now

**Comment by TechDawg270** [comment]
I wonder if this is the product of how `for_each` is implemented. I was unable to reproduce the error using this exact config

**Comment by athenaroa** [comment]
@TechDawg270 Any updates on this?

**Comment by akshaykrjain** [comment]
any plan to fix this?

**Comment by samhine** [comment]
Should this have been moved to "✅ Done"?
Seems to still be an issue for me on 6.5.0
