### ISSUE TITLE
[BUG?]: Required Permission might be changed for /repos/<org>/<repo>/collaborators

### ISSUE THREAD

**Issue by tk3fftk** [integrations/terraform-provider-github#1929]
### Expected Behavior

We use terraform GitHub provider to managing repository permission.

According to [Collaborators - GitHub Docs](https://docs.github.com/en/rest/collaborators/collaborators?apiVersion=2022-11-28#list-repository-collaborators)
> GitHub Apps must have the members organization permission and metadata repository permission to use this endpoint.

Our apps includes below permissions so it may meets the requirement.

- Repo
  - Administration: Read and write
  - Contents: Read and write
  - Metadata: Read-only (cannot select Read and write)
  - Pull requests: Read and write
- Org
  - Members: Read and write

I have created a support ticket for this but there is no response.

### Actual Behavior

After 2023/9/25 (JST), GET `/repos/<org>/<repo>/collaborators` returns 403 for public repo and 404 for private repo via GitHub Apps. 

> Error: -27T06:21:28.681Z [ERROR] vertex "github_repository_collaborators.foo (expand)" error: GET https://api.github.com/repos/org/repo/collaborators?affiliation=direct&per_page=100: 403 Resource not accessible by integration []

### Terraform Version

Terraform v1.4.5
on linux_amd64
+ provider registry.terraform.io/integrations/github v5.37.0

### Affected Resource(s)

- github_repository_collaborators

### Terraform Configuration Files

```hcl
resource "github_repository_collaborators" "repos_A" {
  for_each = toset(local.repos)

  repository = each.key
  team {
    permission = "pull"
    team_id    = github_team.teams["team_A"].slug
  }
}
```

### Steps to Reproduce

- generate a token via `actions/create-github-app-token@v1`
- execute `terraform plan` or maybe  `curl -L  -X GET  -H "Accept: application/vnd.github+json"   -H "Authorization: Bearer token"   -H "X-GitHub-Api-Version: 2022-11-28"  https://api.github.com/repos/org/repo/collaborators`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Luis-3M** [comment]
@tk3fftk we're also facing the same problem with a similar setup - GitHub app. Could you clarify how did you manage to fix this issue ?

**Comment by tk3fftk** [comment]
@Luis-3M 
We add `owner: <target org>` parameter to `actions/create-github-app-token`. The app token has a scope to manupulate repos. The default scope of a generated token is only its repository.

**Comment by Luis-3M** [comment]
@tk3fftk Understood. How is your CI looking like and Terraform GitHub provider block ?

**Comment by Luis-3M** [comment]
@tk3fftk Any info you could provide on this topic ?

**Comment by tk3fftk** [comment]
Sorry, I don't know what you want. One suggestion may be you can try to reproduce the problem with gh cli, REST API, and some GitHub Actions like https://github.com/tk3fftk/create-github-app-token/tree/test-reproduce-auth-error .

**Comment by Luis-3M** [comment]
@tk3fftk 
Trying to understand how do you authenticate the GitHub Terraform provider. In our case the GitHub provider looks as it follows:

`provider "github" {
  owner          = "<ORG_OWNER>"
  write_delay_ms = 50

  app_auth {}
}`

We then provide on each GH action step the given GH APP ID, INSTALLATION ID and PEM FILE so Terraform is able to authenticate the provider and manage repositories accordingly.

Are you suggesting that instead we should exchange a token and use it, as opposed to use the GH APP directly ?

**Comment by tk3fftk** [comment]
well, my issue was not provider's issue but also how to generate app token used by GitHub Terraform Provider.

**Comment by Luis-3M** [comment]
@tk3fftk Could you present how are you initialising the GitHub provider ?

**Comment by tk3fftk** [comment]
```
variable "github_app_token" {
  type = string
}

provider "github" {
  token = var.github_app_token
  owner = local.github_organization
}
```

**Comment by Luis-3M** [comment]
Thanks @tk3fftk  - we've got the same configuration and are still facing a 403.
GitHub app permissions also look OK. However, we're using `github_repository_collaborator` resource instead of `github_repository_collaborators`. Will give this a try and attempt to use the latter.
