### ISSUE TITLE
[BUG]: Github branch deleted outside terraform state gives 404

### ISSUE THREAD

**Issue by davidforslof** [integrations/terraform-provider-github#1933]
### Expected Behavior

With terraform:

1. Create a branch from default branch
2. Change or add a file in the new branch
3. Create a PR to default branch

In Github:
1. Merge PR
2. Delete base ref branch

Run terraform again

### Actual Behavior

If the branch gets deleted automatically on merge, TF cannot find the file in the branch, and the error code is `Error: unexpected status code: 404 Not Found`. TF should then remove the file and the branch from state, since it is deleted in Github.

This seems to be done correctly on github_branch: https://github.com/integrations/terraform-provider-github/blob/main/github/resource_github_branch.go#L124

But not on github_repository_file: 
https://github.com/integrations/terraform-provider-github/blob/main/github/resource_github_repository_file.go#L238

### Terraform Version

Terraform v1.5.7
on linux_amd64
+ provider registry.terraform.io/integrations/github v5.39.0

### Affected Resource(s)

- github_branch
- github_repository_file

### Terraform Configuration Files

```hcl
data "github_repository_file" "codeowners_file" {
  repository = github_repository.repository.name
  branch     = var.default_branch
  file       = "CODEOWNERS"
}

resource "github_branch" "codeowners" {
  repository = github_repository.repository.name
  branch     = "codeowners"
}

resource "github_repository_file" "codeowners" {
  count               = strcontains(coalesce(lower(data.github_repository_file.codeowners_file.content), "not"), "@mybot") ? 0 : 1
  repository          = github_repository.repository.name
  branch              = github_branch.codeowners.branch
  file                = "CODEOWNERS"
  content             = data.github_repository_file.codeowners_file.content != null ? replace("/(\\*.+)/", data.github_repository_file.codeowners_file.content, "$0 @mybot") : replace("/(\\*.+)/", file("${path.module}/CODEOWNERS_template"), "$0 @mybot")
  commit_message      = "Update CODEOWNERS [skip ci]"
  overwrite_on_create = true
}

resource "github_repository_pull_request" "codeowners" {
  count           = strcontains(coalesce(lower(data.github_repository_file.codeowners_file.content), "not"), "@mybot") ? 0 : 1
  base_repository = github_repository.repository.id
  base_ref        = var.default_branch
  head_ref        = github_branch.codeowners.branch
  title           = "Update CODEOWNERS"
  body            = "Automated PR from TF"
  depends_on      = [github_repository_file.codeowners[0], github_branch.codeowners[0]]
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nickfloyd** [comment]
Fixed by #1937
