### ISSUE TITLE
[BUG]: encountering issues with Terraform attempting a hard replacement even when using the repository name as specified in the documentation

### ISSUE THREAD

**Issue by Moradabuaqel1** [integrations/terraform-provider-github#1934]
### Expected Behavior

no replacement or changes should be happen when using repository name instead of repository id as specified in the documentation.

### Actual Behavior

encountering issues with Terraform attempting a hard replacement even when using the repository name as specified in the documentation

### Terraform Version

Terraform v1.5.6
on darwin_amd64
+ provider registry.terraform.io/integrations/github v5.33.0

### Affected Resource(s)

-github_branch_protection

### Terraform Configuration Files

```hcl
resource "github_branch_protection" "example" {


  repository_id  = "example-service"

  pattern          = "master"
  enforce_admins   = false
  allows_deletions = false


  required_status_checks {
    contexts = ["default"]
  }

  required_pull_request_reviews {
    dismiss_stale_reviews  = true
    require_code_owner_reviews = true
  }
}
```

### Steps to Reproduce

import example-service from existing repo
run terraform apply

### Debug Output

```shell
if i changed the repo name with id it works properly and i get what expected
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nickfloyd** [comment]
Hey @Moradabuaqel1 thank you for hunting this down and apologies for the trouble.  I am going to assign the labels `hacktoberfest` and `Up for Grabs` to signal to the community that this is something that has been verified and can be worked. Please feel free to pick the issue up if you have time! Thank you again for all that you do for this community ❤️  !
