### ISSUE TITLE
[BUG]: repo_id attribute not generated

### ISSUE THREAD

**Issue by neilharris123** [integrations/terraform-provider-github#1940]
### Expected Behavior

The [documentations](https://registry.terraform.io/providers/integrations/github/latest/docs/resources/repository#attributes-reference) attribute reference suggests an attribute name repo_id should be available.  
However, non of our repos attributes contain this key. 

### Actual Behavior

All other attributes exist, but `repo_id` does not. 

### Terraform Version

Terraform 0.13.7
integrations/github version 5.39.0

### Affected Resource(s)

- github_repository

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nickfloyd** [comment]
Hey @neilharris123 Thanks for reaching out.  The following is where `repo_id` is present:
1. In the resourceGithubRepository [schema](https://github.com/integrations/terraform-provider-github/blob/680c66e184d858bdc409c51a004d5a4cb1cce80d/github/resource_github_repository.go#L391)
2. In the dataSourceGithubRepository [data source](https://github.com/integrations/terraform-provider-github/blob/680c66e184d858bdc409c51a004d5a4cb1cce80d/github/data_source_github_repository.go#L215)
3. In the github_respoitory [docs](https://github.com/integrations/terraform-provider-github/blob/680c66e184d858bdc409c51a004d5a4cb1cce80d/website/docs/d/repository.html.markdown?plain=1#L94) (as you pointed out)

For clarity, were you expecting to see it somewhere else as well?  Have a look at this [test](https://github.com/integrations/terraform-provider-github/blob/680c66e184d858bdc409c51a004d5a4cb1cce80d/github/data_source_github_repositories_test.go#L68) that makes use of `include_repo_id` as part of the query.  Docs [here](https://registry.terraform.io/providers/integrations/github/latest/docs/data-sources/repositories).  Let me know if that's what you were looking for.

**Comment by deepbrook** [comment]
> > Hey @neilharris123 Thanks for reaching out. The following is where `repo_id` is present:
> > 
> > 1. In the resourceGithubRepository [schema](https://github.com/integrations/terraform-provider-github/blob/680c66e184d858bdc409c51a004d5a4cb1cce80d/github/resource_github_repository.go#L391)
> > 2. In the dataSourceGithubRepository [data source](https://github.com/integrations/terraform-provider-github/blob/680c66e184d858bdc409c51a004d5a4cb1cce80d/github/data_source_github_repository.go#L215)
> > 3. In the github_respoitory [docs](https://github.com/integrations/terraform-provider-github/blob/680c66e184d858bdc409c51a004d5a4cb1cce80d/website/docs/d/repository.html.markdown?plain=1#L94) (as you pointed out)
> > 
> > For clarity, were you expecting to see it somewhere else as well? Have a look at this [test](https://github.com/integrations/terraform-provider-github/blob/680c66e184d858bdc409c51a004d5a4cb1cce80d/github/data_source_github_repositories_test.go#L68) that makes use of `include_repo_id` as part of the query. Docs [here](https://registry.terraform.io/providers/integrations/github/latest/docs/data-sources/repositories). Let me know if that's what you were looking for.
> 
> @nickfloyd ,the issue is with `github_repository` data source (single repo data source, not multiple repo data source)
> 
> That said, I too run into a similar issue. When referencing `data.github_repository.<name>.name` Terraform complains the related field is not set, implying `name` returns `null`:
> 
> ```terraform
> variable "repositories" {
>   type = map(string)
> }
> 
> data "github_team" "administrators" {
>   slug = "code-security"
> }
> 
> data "github_repository" "owned" {
>   for_each = var.repositories
>   name     = each.key
> }
> 
> resource "github_team_repository" "maintainership" {
>   for_each = data.github_repository.owned
> 
>   team_id    = "@code-security"
>   repository = each.value.name
>   permission = "push"
> }
> ```
> 
> yields:
> 
> ```shell
> │ Error: "repository": required field is not set
> │
> │   with module.repositories.github_team_repository.maintainership["my-repo"],
> │   on modules/repositories/main.tf line 40, in resource "github_team_repository" "maintainership":
> │   40: resource "github_team_repository" "maintainership" {
> │
> ╵
> ```
> 
> As there's no `includ_repo_id` flag for the single repo data source, I'd say something's off in the read function?

This issue actually masks the actual bug: loading up repositories not owned by the GITHUB_TOKEN does not raise an error if the repo isn't found. Instead of raising an *error*, it silently nulls all attributes instead.
