### ISSUE TITLE
[BUG]: github_organization_ruleset unable to remove bypassers 

### ISSUE THREAD

**Issue by aminzar-access** [integrations/terraform-provider-github#1952]
### Expected Behavior

When you set [bypass_actors](https://registry.terraform.io/providers/integrations/github/latest/docs/resources/organization_ruleset#bypass_actors) to null remove all bypassers.

### Actual Behavior

It does not remove them. It also gets confused on every plan and it tries to swap existing bypassers for some reason!

### Terraform Version

Terraform v1.6.1
on linux_amd64
+ provider registry.terraform.io/integrations/github v5.39.0

### Affected Resource(s)

- github_organization_ruleset

### Debug Output

```shell
# module.organization.github_organization_ruleset.this["pr_default"] will be updated in-place
  ~ resource "github_organization_ruleset" "this" {
        id          = "118285"
        name        = "Pull Request Default Ruleset"
        # (5 unchanged attributes hidden)

      ~ bypass_actors {
          ~ actor_id    = 5 -> 1
          ~ actor_type  = "RepositoryRole" -> "OrganizationAdmin"
            # (1 unchanged attribute hidden)
        }
      ~ bypass_actors {
          ~ actor_id    = 1 -> 5
          ~ actor_type  = "OrganizationAdmin" -> "RepositoryRole"
            # (1 unchanged attribute hidden)
        }

        # (4 unchanged blocks hidden)
    }
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aminzar-access** [comment]
exact same issue in `github_repository_ruleset` resource as well.

**Comment by stevehipwell** [comment]
We're seeing general churn for `github_repository_ruleset` resources.
