### ISSUE TITLE
[BUG]: Cannot set owner when authenticating with gh cli

### ISSUE THREAD

**Issue by steveoh** [integrations/terraform-provider-github#1966]
### Expected Behavior

when I set the owner in the provider, all actions should be taken on repositories in that org.

### Actual Behavior

api requests go to my personal accounts org

### Terraform Version

Terraform v1.5.7
on darwin_amd64
+ provider registry.terraform.io/hashicorp/github v5.40.0
+ provider registry.terraform.io/hashicorp/google v5.2.0
+ provider registry.terraform.io/hashicorp/google-beta v5.2.0
+ provider registry.terraform.io/hashicorp/local v2.4.0
+ provider registry.terraform.io/integrations/github v5.40.0

### Affected Resource(s)

- github_actions_environment_secret

### Terraform Configuration Files

```hcl
provider "github" {
  owner = "my-org"
}

resource "github_repository_environment" "prod" {
  environment = "prod"
  repository  = "repo"

  reviewers {
    users = [
      data.github_user.one.id,
      data.github_user.two.id,
      data.github_user.three.id
    ]
  }

  deployment_branch_policy {
    protected_branches     = false
    custom_branch_policies = true
  }
}
```

### Steps to Reproduce

with the gh cli installed, add a `github_repository_environment` and some `github_actions_environment_secret` to an existing repository.

Apply the plan.

### Debug Output

```shell
Error: PUT https://api.github.com/repos/wrong-owner/repo/environments/prod: 404 Not Found []
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by steveoh** [comment]
This only happens when using 

```
terraform {
  required_providers {
    github = {
      source  = "integrations/github"
    }
  }
}
```

which is the new provider. The hashicorp provider does not have this bug.

**Comment by steveoh** [comment]
@kfcampbell can you point me and others in the right direction so we can be successful to implement the fix? I ask since you marked this as up for grabs which to me implies it's not a priority for the maintainers.

**Comment by kfcampbell** [comment]
I don't have a confident answer on what the right direction here is. It's probably related to #1655 as well; frequently our resources take the owner of the token instead of a specified owner.

**Comment by calebworks** [comment]
> This only happens when using
> 
> ```
> terraform {
>   required_providers {
>     github = {
>       source  = "integrations/github"
>     }
>   }
> }
> ```
> 
> which sets the new provider. The hashicorp provider does not have this bug.

Just for anyone else coming across this bug, the code to use the hashicorp version of the provider (which seems to have fixed the issue for me) is:

```
terraform {
  required_providers {
    github = {
      source  = "hashicorp/github"
    }
  }
}

# Or alternatively, omit the source altogether
terraform {
  required_providers {
    github = {}
  }
}

```
