### ISSUE TITLE
[FEAT]: Add `prevent_self_review` boolean to the `github_repository_environment` resource

### ISSUE THREAD

**Issue by nnellanspdl** [integrations/terraform-provider-github#1967]
### Describe the need

Requesting an update to the [github_repository_environment](https://registry.terraform.io/providers/integrations/github/latest/docs/resources/repository_environment) resource to support the `prevent_self_review` boolean as defined in the [API here](https://docs.github.com/en/rest/deployments/environments?apiVersion=2022-11-28#create-or-update-an-environment)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Nmishin** [comment]
going to work on that
