### ISSUE TITLE
[FEAT]: Add "Require workflows to pass before merging" support to github_organization_ruleset

### ISSUE THREAD

**Issue by lawliet89** [integrations/terraform-provider-github#1970]
### Describe the need

Add support for "required workflow" rule in the organisation ruleset resource `github_organization_ruleset`. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by relusc** [comment]
hi, we'd also like to see this feature being implemented and I am also up for contributing here, however this requires v57 of https://github.com/google/go-github. Is there some sort of timeline until v57 will be used in the provider ?

**Comment by kfcampbell** [comment]
@relusc I've opened #2081 to update the go-github version in the project! That should be merged shortly.

**Comment by relusc** [comment]
Thanks @kfcampbell for the quick update :)

I have created https://github.com/integrations/terraform-provider-github/pull/2082 which should resolve this issue.
