### ISSUE TITLE
[FEAT]: Disable GitHub Actions can approve pull requests 

### ISSUE THREAD

**Issue by ignacio-circle** [integrations/terraform-provider-github#1977]
### Describe the need

This setting can be applied both at the Organization and Repository level and prevents Github Actions from being able to approve pull request reviews. This setting is necesary to avoid branch protection bypasses as documented [here](https://medium.com/cider-sec/bypassing-required-reviews-using-github-actions-6e1b29135cc7).

There is currently no way to manage this setting through Terraform. The API endpoint to configure this is https://docs.github.com/en/rest/actions/permissions?apiVersion=2022-11-28#set-default-workflow-permissions-for-an-organization and https://docs.github.com/en/rest/actions/permissions?apiVersion=2022-11-28#set-default-workflow-permissions-for-a-repository

This would be a great addition for users that manage all Github settings through TF

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by robbycuenot** [comment]
Bump on this feature request. I toggle this on and off at the repo and org level and managing it through TF would be useful :)

**Comment by ignacio-circle** [comment]
Looks like the go-github module has just merged a change to support the required API requests to support terraforming this setting (https://github.com/google/go-github/pull/3054). There is still no module release containing the new feature but hopefully soon
