### ISSUE TITLE
[DOCS]: is github_repository_dependabot_security_updates supposed to be private API?

### ISSUE THREAD

**Issue by stevemao** [integrations/terraform-provider-github#1989]
### Describe the need

It is in the code base but it's not visible on the documentation

### SDK Version

5.41.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by grahamhar** [comment]
Apologies, it looks like I made a mistake when naming the documentation files when I implemented this feature. PR raised to fix it
