### ISSUE TITLE
[BUG]: Parent team relationships can no longer be skipped since 5.41.0

### ISSUE THREAD

**Issue by fbousquethopper** [integrations/terraform-provider-github#1990]
### Expected Behavior

In version 5.40.0 it was possible to not specify the github_team.parent_team_id argument to skip the parent relationship and leave it as is in GitHub.

We should keep this behavior and only remove the parent relationship is the parent_team_id is set to null, "". 

This would only be relevant in cases where there is a parent relationship configured in GitHub and you don't want to manage it from Terraform.

### Actual Behavior

In 5.41.0, if you don't specify the github_team.parent_team_id argument, it will explicitly remove any team parent. relationship.

Such a bug seems to have been introduced in 5.41.0 from this issue: https://github.com/integrations/terraform-provider-github/issues/1668

### Terraform Version

Terraform v1.2.8
on darwin_amd64
+ provider registry.terraform.io/integrations/github v5.40.0

### Affected Resource(s)

- github_team

### Terraform Configuration Files

```hcl
resource "github_team" "test_team1" {
      name            = "test_team1"
      #parent_team_id = "5144562"
      privacy         = "closed"
}
```

### Steps to Reproduce

```
% terraform plan 
github_team.test_team1: Refreshing state... [id=5144564]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # github_team.test_team1 will be updated in-place
  ~ resource "github_team" "test_team1" {
        id                        = "5144564"
        name                      = "test_team1"
      - parent_team_id            = "5144562" -> null
        # (8 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fbousquethopper** [comment]
These lines are to be reviewed:
https://github.com/integrations/terraform-provider-github/blob/f85bfb878f9d649cc337764a617d1c5427ab5670/github/resource_github_team.go#L249C2-L258C3

I'm not proficient enough in Go to suggest a fix though.

**Comment by scott-doyland-burrows** [comment]
The behaviour you describe is from this change https://github.com/integrations/terraform-provider-github/pull/1979

I think the current behaviour is the correct approach.  Terraform is managing the team as a whole, and the resource manages the parent team relationship.

When managing the team via terraform, then terraform should be the source of truth.  If there is no parent team defined in terraform, then there should be no parent team defined in GitHub.

If you do not specify a parent team in terraform, then it will be set to ```""``` and terraform removes the parent team relationship.  This has to be the case for it to work as terraform is designed to work.

The behaviour you would like is allowing terraform to purposely ignore a diff between terraform and GitHub without us asking it to.  To ignore a diff you should instead use an ```ignore_changes```.

```
resource "github_team" "team1" {
  name    = "scott_team01"
  privacy = "closed"
}

resource "github_team" "team2" {

  lifecycle {
    ignore_changes = [parent_team_id]
  }

  name    = "scott_team02"
  privacy = "closed"
}
```


Ideally, in my opinion, we'd have a separate resource to manage team nesting and then remove the ability for the ```github_team``` resource to manage the parent teams.
