### ISSUE TITLE
[BUG]: When putting in a PR the immediate response GHA job fails

### ISSUE THREAD

**Issue by scott-doyland-burrows** [integrations/terraform-provider-github#2002]
### Expected Behavior

Job should work

### Actual Behavior

Job fails

### Terraform Version

N/A

### Affected Resource(s)

Looks like this fails:

https://github.com/integrations/terraform-provider-github/blob/main/.github/workflows/immediate-response.yml

See this output from GHA:

https://github.com/integrations/terraform-provider-github/actions/runs/6756184050/job/18365370590

The error ```Resource not accessible by integration``` can mean it is a GITHUB_TOKEN permissions error - although the yaml looks correct and hasn't been updated recently.

### Terraform Configuration Files

```hcl
N/A
```

### Steps to Reproduce

Put in a PR

### Debug Output

```shell
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by arunsathiya** [comment]
![image](https://github.com/integrations/terraform-provider-github/assets/18581859/be00ae2b-743f-45e8-b609-1352ae822895)

Looking at [this workflow link](https://github.com/integrations/terraform-provider-github/actions/workflows/immediate-response.yml), it looks like this workflow is not in use anymore. I searched the issues section a bit, but couldn't find the issue that led to this workflow being manually disabled.

I think a maintainer will need to confirm that the workflow is intentionally disabled, and if so, this issue can be closed. / cc @kfcampbell for any insights.

**Comment by kfcampbell** [comment]
I don't know why it was disabled; I would say that without additional context I would prefer if it was working correctly and enabled rather than disabled.
