### ISSUE TITLE
[BUG]: Importing github_repository_environment_deployment_policy resource does not populate repository and environment fields.

### ISSUE THREAD

**Issue by dcfsc** [integrations/terraform-provider-github#2012]
### Expected Behavior

After import and terraform plan, should see 
```
No changes. Your infrastructure matches the configuration.
```

### Actual Behavior

1. terraform plan
```
# github_repository_environment_deployment_policy.feature must be replaced  
-/+ resource "github_repository_environment_deployment_policy" "feature" {  
      + environment    = "dly" # forces replacement  
      ~ id             = "xxx-recs-event-streaming:dly:1212XXXX" -> (known after apply)  
      + repository     = "xxx-recs-event-streaming" # forces replacement  
        # (1 unchanged attribute hidden)  
    }
```

### Terraform Version

$ terragrunt version
Terraform v1.6.2
on linux_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.35.0
+ provider registry.terraform.io/hashicorp/azurerm v3.50.0
+ provider registry.terraform.io/integrations/github v5.42.0

### Affected Resource(s)

- github_repository_environment_deployment_policy

### Terraform Configuration Files

```hcl
resource github_repository_environment env {
  environment = var.env
  repository  = var.repository.name

  deployment_branch_policy {
    protected_branches     = true
    custom_branch_policies = true
  }
}

resource "github_repository_environment_deployment_policy" "feature" {  
  repository        = data.github_repository.xxxx.name  
  environment       = github_actions_environment.env.environment  
  branch_pattern = "feature/**"  
}
```

### Steps to Reproduce

1. Create an environment
2. Add a deployment policy via the portal
3. Define the policy in configuration:
4. Import the policy
```
$ tg import github_repository_environment_deployment_policy.feature xxx-recs-event-streaming:dly:1212XXXX  
```
5. Examining the state -- note the nulls 
```
{  
  "mode": "managed",  
  "type": "github_repository_environment_deployment_policy",  
  "name": "master",  
  "provider": "provider[\"registry.terraform.io/integrations/github\"]",  
  "instances": [  
    {  
      "schema_version": 0,  
      "attributes": {  
        "branch_pattern": "master",  
        "environment": null,  <<<<< BAD
        "id": "xxx-recs-event-streaming:dly:1212XXXX",  
        "repository": null    <<<<<< BAD
      },  
      "sensitive_attributes": [],  
      "private": "xxxxxxx=="  
    }  
  ]  
},
```
6. workaround: patch the state directly and push the fixed state:
```
{  
  "mode": "managed",  
  "type": "github_repository_environment_deployment_policy",  
  "name": "master",  
  "provider": "provider[\"registry.terraform.io/integrations/github\"]",  
  "instances": [  
    {  
      "schema_version": 0,  
      "attributes": {  
        "branch_pattern": "master",  
        "environment": "dly",  
        "id": "xxx-recs-event-streaming:dly:1212XXXX",  
        "repository": "xxx-recs-event-streaming"  
      },  
      "sensitive_attributes": [],  
      "private": "XXXXX=="  
    }  
  ]  
},
```
7. now a plan....
```
...
github_repository_environment_deployment_policy.master: Refreshing state... [id=xxx-recs-event-streaming:dly:1212XXXX]  
...
data.azurerm_subscription.current: Read complete after 0s [id=/subscriptions/XXXX]  
  
No changes. Your infrastructure matches the configuration.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mw-root** [comment]
This is a really frustrating bug. If you have piles of repos you sit waiting for it to re-create all these resources and your deployment environments are flapping in and out.

**Comment by meridius** [comment]
This happened to me too. It seems like a quick fix since TF already has all the values it needs (`environment` and `repository`) since they are part of the import `id`.

> GitHub Repository Environment Deployment Policy can be imported using an ID made up of name of the `repository` combined with the `environment` name of the environment with the `Id` of the deployment policy, separated by a `:` character, e.g.

**Comment by PScoriae** [comment]
this is still happening.

**Comment by samj** [comment]
Got me too!

**Comment by samj** [comment]
Filed #3076 in the hope it gets renewed attention.

I see it's **Status: Up for grabs** but I don't have time to dig into the internals of another project right now.
