### ISSUE TITLE
[FEAT]: Add support for Social Accounts Organization Settings

### ISSUE THREAD

**Issue by yordis** [integrations/terraform-provider-github#2019]
### Describe the need

Under https://github.com/organizations/[org]/settings/profile you can add "Social accounts"

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by arunsathiya** [comment]
It looks like `go-github` (in turn, the Terraform provider) are blocked by the REST API not supported social accounts fields yet:

https://docs.github.com/en/rest/orgs/orgs?apiVersion=2022-11-28#update-an-organization

I could identify this payload from the browser console when updating the links, but the fields don't seem to be working when I call the API endpoint. I asked support about it, but I think we have to wait for official documentation to pop up.

**Comment by kfcampbell** [comment]
Thanks for doing the research, @arunsathiya.
