### ISSUE TITLE
[BUG]: github_team data block is taking longer than expected

### ISSUE THREAD

**Issue by ukhan262** [integrations/terraform-provider-github#2023]
### Expected Behavior

data calls for github_team should resolve in less than 30 seconds.

### Actual Behavior

In the past, when we have had the data blocks for github_team, it would take only ~30 seconds max. Now the refresh block is painfully slow and some of the calls are over 4 minutes.

This has taken our plans to go from 10 minutes to 40+ minutes.

We are leveraging the latest version of the github provider.

### Terraform Version

Terraform v1.5.6
Github provider version 5.42.0

### Affected Resource(s)

Data Sources:
- github_team

### Terraform Configuration Files

```hcl
data "github_team" "org_team" {
  slug = "teamname"
}
```

### Steps to Reproduce

```
terraform init
terraform plan
```

### Debug Output

<img width="1708" alt="Screenshot 2023-11-20 at 11 50 24 AM" src="https://github.com/integrations/terraform-provider-github/assets/37010344/48e58bca-1ebe-4297-b158-d6ce6832acb4">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment]
Interesting...have you looked into what PRs/API calls might be causing this?
