### ISSUE TITLE
[BUG]: Cannot add more than one team to Github_branch_protection_v3 bypass_pull_request_allowances

### ISSUE THREAD

**Issue by andrewhharmon** [integrations/terraform-provider-github#2033]
### Expected Behavior

when providing more than one value in the list for 
```
bypass_pull_request_allowances {
    teams = ["teamA", "teamB"]
}
```

all teams in the list should be added 

### Actual Behavior

422 Validation Failed [{Resource: Field: Code: Message:Context must be unique per branch protection.}]

### Terraform Version

Terraform Version 1.5.6
Provider version v5.42.0

### Affected Resource(s)

Github_branch_protection_v3

### Terraform Configuration Files

```hcl
locals {
  # Create a map of repository names to repository data.
  repository_override = {
    repo-a = {
      teams = ["web-developers", "infrastructure-engineers"]
    }
}


resource "github_branch_protection_v3" "repos" {
  for_each = { for k, v in data.github_repository.repos : k => v }

  repository = each.value.name
  branch     = each.value.default_branch

  enforce_admins = false

  required_pull_request_reviews {
    required_approving_review_count = 1
    dismiss_stale_reviews           = true

    bypass_pull_request_allowances {
      teams = lookup(lookup(local.repository_override, each.value.name, {}), "teams", null)
      users = lookup(lookup(local.repository_override, each.value.name, {}), "users", null)
    }
  }
```

### Steps to Reproduce

terraform apply

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment]
Oh that's interesting...the code is in place to flatten the provided list for the API call. I wonder if the fix is as simple as removing the `MaxItems: 1,` line in `github/resource_github_branch_protection_v3.go` and testing it with both a single item and a list. 

Good catch!
