### ISSUE TITLE
[FEAT]: Fetch data.github_tree from a specific owner

### ISSUE THREAD

**Issue by Tiino1** [integrations/terraform-provider-github#2071]
### Describe the need

Exactly like data.github_repository_file we would like to be able to use data.github_tree while specifying the owner

Desired behaviour:

```terraform
data "github_repository" "this" {
  name = "example"
}

data "github_branch" "this" {
  branch     = data.github_repository.this.default_branch
  repository = data.github_repository.this.name
}

data "github_tree" "this" {
  recursive  = false
  repository = "my_owner/${data.github_repository.this.name}"
  tree_sha   = data.github_branch.this.sha
}
```

If a repository of the type "owner/repo" (with a slash in the middle) is passed, the owner would be as specified and not the owner of the token

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment]
I would _love_ to standardize this across all our resources. We have an unfortunate mix of behavior around this.
