### ISSUE TITLE
[BUG]:  Not able to switch repo visibility from public to private while adding configuration to enable Advanced Security

### ISSUE THREAD

**Issue by pcs-wongkt** [integrations/terraform-provider-github#2073]
### Expected Behavior

```
resource "github_repository" "new_repo" {
  name = "test-repo"
  auto_init = true
  visibility = var.repo_visibility
  
  security_and_analysis {
    dynamic "advanced_security" {
      for_each = (var.repo_visibility != "public") ? [1] : []
      content {
        status = "enabled"
      }
    }
  }
}

variable "repo_visibility" {
  type        = string
}

repo_visibility = "public"
```

I am able to create a repo with the configuration above, where repo_visibility is set to "public".

I expect to be able to change the repo's visibility to "internal" or "private" while using a dynamic block to include the advanced security block, so that I can keep advanced security enabled even if my repo is no longer public.

### Actual Behavior

This fails with the following error:

`Error: PATCH https://api.github.com/repos/pcs-pipelines/test-repo-2: 422 Advanced security is always available for public repos. []`

In addition, the tfstate file now shows the new repo visibility (Which would be either internal or private), but the actual repo on GitHub is still public.

### Terraform Version

```
Terraform v1.6.5
on windows_amd64
+ provider registry.terraform.io/integrations/github v5.42.0
```

### Affected Resource(s)

- github_repository

### Steps to Reproduce

`terraform apply`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zepeng811** [comment]
resurrecting this as it is still a problem in Oct 2025.

The Order of Operation should be:
1. make the repo private
2. apply advanced security changes

but in the code it seems like the current order is 2 -> 1, since it is part of the same resource we cannot apply things like `depends_on` to control the order.
