### ISSUE TITLE
[BUG]: Docs left nav github_repository_automated_security_fixes should be github_repository_dependabot_security_updates

### ISSUE THREAD

**Issue by davidham** [integrations/terraform-provider-github#2096]
### Expected Behavior

The Resources left nav item `github_repository_automated_security_fixes` should be `github_repository_dependabot_security_updates`. The destination page is correct but the link title is wrong.

### Actual Behavior

The left nav item is `github_repository_automated_security_fixes`.

### Terraform Version

Terraform v1.6.6
on darwin_arm64

### Affected Resource(s)

- github_repository_dependabot_security_updates

### Steps to Reproduce

Go to https://registry.terraform.io/providers/integrations/github/latest/docs/resources/repository_automated_security_fixes. The page title is correct but the left navigation link is not.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment]
Is [this spot](https://github.com/integrations/terraform-provider-github/blob/main/website/github.erb#L308) where you're thinking of?

**Comment by synack-badamson** [comment]
seems this was fixed by #1989 / #2138
