### ISSUE TITLE
[FEAT]: github_repository_topics should use owner from repository full name "owner/repo"

### ISSUE THREAD

**Issue by A-deLuna** [integrations/terraform-provider-github#2099]
### Describe the need

The `github_repository_topics` resource does not allow the "full name" repository format `owner/repo_name`. I need to create different provider aliases to manage topics across different repo owners.

Terraform providers [can't be instantiated in a loop][0]. Making it necessary to have a large number of duplicate providers and resource definitions to allow managing repo topics across different owners.

[0]:https://github.com/hashicorp/terraform/issues/19932  

The`github_repository_collaborator` allows the [repository][1] argument be in the format of `owner/repo_name` and will use the owner form the repo name if specified, otherwise falls back to the provider owner. `github_repository_topics` could behave in the same way to be consistent.

[1]: https://registry.terraform.io/providers/integrations/github/latest/docs/resources/repository_collaborator#argument-reference

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nickfloyd** [comment]
Hey @A-deLuna thanks for letting us know about this need! ❤️  Let us know if you'd be interested coming up with a way to address it and then submitting a PR to be reviewed.  For now I have labeled this as "Up For Grabs" so that the community knows that it's available as well.
