### ISSUE TITLE
[FEAT]: Add "approving workflow runs from public forks" settings

### ISSUE THREAD

**Issue by jooola** [integrations/terraform-provider-github#2108]
### Describe the need

The Github Actions settings page allow configuring whether a maintainer approval is required for workflows to run on fork Pull requests: https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks

I didn't find any way to configure this options using the GitHub terraform provider "5.44.0"

This would greatly help us to ensure some sensitive pipeline are not run without the approval of a maintainer, and using terraform will make sure we didn't overlook configuring these settings in a repository.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nickfloyd** [comment]
Hey @jooola thanks for letting us know about this need! ❤️  Let us know if you'd be interested coming up with a way to address it and then submitting a PR to be reviewed.  For now I have labeled this as "Up For Grabs" so that the community knows that it's available as well.

**Comment by manjinder-mckc** [comment]
@jooola @nickfloyd I was looking at the request and I scanned [permissions](https://docs.github.com/en/rest/actions/permissions?apiVersion=2022-11-28) and [workflow runs](https://docs.github.com/en/rest/actions/workflow-runs?apiVersion=2022-11-28) today, but it doesn't look like it's possible yet. Thoughts ?

**Comment by kfcampbell** [comment]
I also don't see it in the [forks section](https://docs.github.com/en/rest/repos/forks?apiVersion=2022-11-28). You're correct @manjinder-mckc, this is blocked until further API support becomes available.

**Comment by zerok** [comment]
Couldn't find a discussion for this on the community board and so I created one 😄 https://github.com/orgs/community/discussions/161687

**Comment by gregtyler** [comment]
This feature is [now available in the API](https://github.blog/changelog/2025-07-31-github-actions-new-apis-and-windows-latest-migration-notice/)
