### ISSUE TITLE
[FEAT]: allow creating organization_ruleset.required_status_checks only with strict_required_status_checks_policy

### ISSUE THREAD

**Issue by igorkliushnikov** [integrations/terraform-provider-github#2111]
### Describe the need

Organisational rulesets allow creating rules that enforce branches to be up to date before merging without specifying any check:
<img width="935" alt="Screenshot 2024-01-19 at 14 44 04" src="https://github.com/integrations/terraform-provider-github/assets/122813874/fd9c3af4-f004-4350-bc68-c36d09315f4f">

What about making [required_check](https://registry.terraform.io/providers/integrations/github/latest/docs/resources/organization_ruleset#required_check) optional if [strict_required_status_checks_policy](https://registry.terraform.io/providers/integrations/github/latest/docs/resources/organization_ruleset#strict_required_status_checks_policy) is set to true?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nickfloyd** [comment]
Hey @igorkliushnikov thanks for letting us know about this need! ❤️  Let us know if you'd be interested coming up with a way to address it and then submitting a PR to be reviewed.  For now I have labeled this as "Up For Grabs" so that the community knows that it's available as well.

**Comment by igorkliushnikov** [comment]
@nickfloyd , sorry for the delay, I've missed the notification somehow. I will be happy to experiment with the implementation next week.

**Comment by igorkliushnikov** [comment]
Long story short: the provider has correct validation that prevents creating a rule without concrete check, while Web UI allows to set a setting that has no effect 😄

While trying to implement the requested feature in the provider code, I was forced to reevaluate my original assumptions. I discovered that even though I can set the "required up-to-date branch" setting in the UI, in fact it will work only if it is used together with a check name. Therefore there is nothing to change in the provider code, and I'm closing the issue.
