### ISSUE TITLE
[BUG]: data resource github_user throw error "got unconvertible type 'github.Timestamp'"

### ISSUE THREAD

**Issue by zibenua** [integrations/terraform-provider-github#2123]
### Expected Behavior

Data source retrieve information about a GitHub user.

```
data "github_user" "example" {
  username = "example"
}
```
or 

```
data "github_user" "current" {
  username = ""
}
```

### Actual Behavior

Terraform fails with error:

```data.github_user.example: Reading...

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: created_at: '' expected type 'string', got unconvertible type 'github.Timestamp', value: '2015-06-14 12:00:16 +0000 UTC'
│ 
│   with data.github_user.example,
│   on data.tf line 1, in data "github_user" "example":
│    1: data "github_user" "example" {
```

### Terraform Version

Checked with terraform 1.3.9, 1.5.0, 1.7.1  on darwin_amd64

### Affected Resource(s)

data source - github_user

### Terraform Configuration Files

```hcl
terraform {
  required_version = "= 1.7.1"
  required_providers {
    github = {
      source  = "integrations/github"
      version = "6.0.0-beta"
    }
  }
}

provider "github" {
  token    = "<MY_TOKEN>"
}

data "github_user" "example" {
  username = ""
}
```

### Steps to Reproduce

terraform init
terraform plan

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment]
Does this happen in the latest v5 version of the provider as well, or is it specific to the v6 beta?

**Comment by richjyoung** [comment]
Also encountered the same error a few days ago, for me in a fresh 5.45.0 plugin environment this does not cause an error during `terraform plan`.
