### ISSUE TITLE
[FEAT]: github_repository_webhook owner attribute

### ISSUE THREAD

**Issue by avidspartan1** [integrations/terraform-provider-github#2127]
### Describe the need

I work with a GitHub Enterprise instance, using a single token, and would like to create many webhooks across several different Organizations. The list of organiziations can change based on deployment of the Terraform module, so using provider aliases isn't an option (or, at best, incredibly messy).

If there was an optional `owner` attribute available for the `github_repository_webhook` resource, I could do this easily. As it stands, I have to use the hacky workaround mentioned in #1436, which seems to lead to state inconsistency.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mblum14** [comment]
I've got a similar issue but with the `github_app_installation_repository` resource. Would be helpful to be able to specify an alternate `owner` in this case as well.

**Comment by kfcampbell** [comment]
We need to do a better job of this across all resources. I've started #1655 to track a more comprehensive effort there.
