### ISSUE TITLE
[FEAT]: Support for setting the retention period for Github Actions artifacts and logs

### ISSUE THREAD

**Issue by mmf55** [integrations/terraform-provider-github#2150]
### Describe the need

The GitHub Terraform provider currently doesn't support setting the retention period for GitHub Actions artifacts and logs. It would be great if it were possible to set this value through Terraform.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment]
Is this possible through the API right now?

**Comment by StefanLobbenmeierObjego** [comment]
FYI this is general documentation on the feature - checking if there is any api documentation for it:
https://docs.github.com/en/actions/administering-github-actions/usage-limits-billing-and-administration#artifact-and-log-retention-policy

**Comment by dlacosteGFM** [comment]
I understand why the stale -> not planned happened, but honestly this is a really important feature because by default once your limit you can't publish artifacts any more.

Would be very nice to be able to set this via API call and via terraform!
