### ISSUE TITLE
[BUG]: `github_repositories` data source query not working with custom properties

### ISSUE THREAD

**Issue by anttijman** [integrations/terraform-provider-github#2161]
### Expected Behavior

The query should only return the repositories with custom property `is_confidential` set to no

### Actual Behavior

The query returned all of my org's repositories despite whether the custom property `is_confidential` is yes or no

### Terraform Version

Terraform version: 1.7.2
+ integrations/github/5.42.0/linux_amd64/terraform-provider-github_v5.42.0

### Affected Resource(s)

- github_repositories data source

### Terraform Configuration Files

```hcl
# Every repo has custom property is_confidential. It is set to yes by default. This will return every repo that is not confidential
data "github_repositories" "all_but_confidential" {
  query = "org:<my-org> props.is_confidential:no"
}
```

### Steps to Reproduce

- Create a custom property with:
  - type single select
  - Require this property for all repositories
- Change this custom property for some repositories
- Use the github_repositories data source to query the repositories using the custom property e.g. query = "org:my-org props.my-custom-property:my-custom-property-value"

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anttijman** [comment]
curling the github api with custom properties works just fine and also it works in GitHub UI

**Comment by jimsheldon** [comment]
It would be great to see this fixed, but here is my workaround.

In this case, `custom-property-name` is a true/false value and I'm looking for where it is true.

```hcl
data "github_repositories" "all" {
  query = "org:myorg archived:false"
}

data "github_repository_custom_properties" "all" {
  for_each = toset(data.github_repositories.all.names)

  repository = each.value
}

locals {
  custom_property_name_repos = [
    for repo in data.github_repository_custom_properties.all : repo.repository
    if contains(
      repo.property,
      {
        property_name  = "custom-property-name",
        property_value = toset(["true"])
      }
    )
  ]
}
```
