### ISSUE TITLE
[BUG]: Argument error - An argument named "blocks_creations" is not expected here.

### ISSUE THREAD

**Issue by gh-risharma** [integrations/terraform-provider-github#2166]
### Expected Behavior

Earlier the job ran successfully with the same argument mentioned in github_branch_protection resource

### Actual Behavior

But now its failing with the above error.

### Terraform Version

1.7.4

### Affected Resource(s)

-github_branch_protection

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gh-risharma** [comment]
![image](https://github.com/integrations/terraform-provider-github/assets/147606478/b87530ca-985b-4ff3-ae48-e02aad55dd95)

**Comment by georgekaz** [comment]
This isn't a bug, it's a breaking change in v6 as bradam12 says, to resolve #594.

Change your code from

```
resource "github_branch_protection" "example" {
  push_restrictions = []
  blocks_creations = false
}
```
to
```
resource "github_branch_protection" "example" {
  restrict_pushes {}
}
```
This issue should be closed @kfcampbell

**Comment by kfcampbell** [comment]
👍 thanks @georgekaz
