### ISSUE TITLE
[BUG]: Validation prevents valid `results_per_page` setting

### ISSUE THREAD

**Issue by dschniepp** [integrations/terraform-provider-github#2172]
### Expected Behavior

According to the docs [1000](https://github.com/integrations/terraform-provider-github/blob/3f27927e3f61c532d09f6a4de443289d6417e167/website/docs/d/repositories.html.markdown?plain=1#L10) results per page should be allowed.

### Actual Behavior

The maximum number of allow results is 100, according to `toDiagFunc(validation.IntBetween(0, 100), "results_per_page")`

### Terraform Version

Terraform v1.7.4
on darwin_arm64
+ provider registry.terraform.io/integrations/github v6.0.0

### Affected Resource(s)

- github_repositories

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

<sub>Daniel Schniepp [daniel.schniepp@mercedes-benz.com](mailto:daniel.schniepp@mercedes-benz.com), Mercedes-Benz Mobility AG on behalf of Mercedes-Benz Tech Innovation GmbH.</sub >

**Comment by kfcampbell** [comment]
I think you might be looking at the wrong docs. For getting organization repositories, the docs are [here](https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#list-organization-repositories) and show a max of 100: 

![image](https://github.com/integrations/terraform-provider-github/assets/9327688/5377457a-2f4f-4e0a-af54-a2fd6916d892)

The docs you've linked are for the search API, which doesn't apply for the data source for organization repos.

**Comment by dschniepp** [comment]
Thank you for pointing it out, I only saw this in the terraform registry, for the `github_repositories` data resource. So I think the documentation is then wrong, as I didn't check the GitHub API.
 
<img width="1398" alt="Bildschirmfoto 2024-03-05 um 16 52 30" src="https://github.com/integrations/terraform-provider-github/assets/1108670/984b2ed4-1115-4887-ba1d-c3ea54598292">

**Comment by kfcampbell** [comment]
Okay I've had a chance to look at this a little longer and now I think you're right and I'm wrong. The API to retrieve organization repositories does indeed only allow 30 results per page, but upon closer inspection this data source calls the search API which allows 1000 results per page, and not the list repositories endpoint. I was confused. 

Would you like to create a PR to modify the validation function, or shall I?

**Comment by dschniepp** [comment]
Thank you. I will submit a PR.
