### ISSUE TITLE
[BUG]: Since `6.0.1` the `github_actions_repository_permissions` resource errors on read when it's disabled

### ISSUE THREAD

**Issue by stevehipwell** [integrations/terraform-provider-github#2182]
### Expected Behavior

When a `github_actions_repository_permissions` resource is set to disabled it should be able to be read correctly.

### Actual Behavior

We're getting the following error when we have a `github_actions_repository_permissions` resource set to disabled.

> ╷
│ Error: GET https://api.github.com/repos/my-org/test/actions/permissions/selected-actions: 409  []
│ 
│   with module.repo["test"].github_actions_repository_permissions.default,
│   on modules/repo/main.tf line 72, in resource "github_actions_repository_permissions" "default":
│   72: resource "github_actions_repository_permissions" "default" {
│ 
╵

I suspect that this has been caused by the changes in https://github.com/integrations/terraform-provider-github/commit/97d51139cde3bcb2d7838844e8f24086e4830e52.

### Terraform Version

Terraform v1.5.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/random v3.6.0
+ provider registry.terraform.io/integrations/github v6.0.1

### Affected Resource(s)

- `github_actions_repository_permissions`

### Terraform Configuration Files

```hcl
locals {
  actions_enabled = false
}

resource "github_actions_repository_permissions" "default" {
  repository      = "my-repo"
  enabled         = local.actions_enabled
  allowed_actions = local.actions_enabled ? "all" : null
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment]
Oh, that's not ideal. Do you think this is severe enough to warrant a rollback of #2114? @Danielku15, do you have thoughts on how we might go about resolving this?

**Comment by Danielku15** [comment]
I'll try to have a look tomorrow (its already 11pm here) 😅 From my direct changes I cannot directly infer what would trigger this. My new conditions mainly target the allowed_actions="selected". I assume they trigger some unintended else-path. Should be easy to fix once I narrowed down the exact path.

**Comment by kfcampbell** [comment]
@Danielku15 thanks for the attention here! You're correct that integration tests are not automatically running on PRs and merges; I've opened https://github.com/integrations/terraform-provider-github/issues/1414 to track this but we haven't gotten the time or priority to work on it unfortunately. We've struggled with the expense, time, and hassle of automatically testing resources and we're certainly in an unhealthy position now. In the meantime, I've been running relevant tests manually, which is not ideal. 

I appreciate you opening the PR, I'll look shortly!

**Comment by stevehipwell** [comment]
@kfcampbell it looks like the `v6.1.0` release hasn't made it to the registry yet? Is this expected?

**Comment by kfcampbell** [comment]
It's definitely not. Let's keep future discussion about that issue on #2191.

**Comment by stevehipwell** [comment]
#2191 wasn't created when I added this comment, but I saw it was opened and am following it.
