### ISSUE TITLE
[MAINT]: Bump go-github to v60

### ISSUE THREAD

**Issue by nayuta** [integrations/terraform-provider-github#2187]
### Describe the need

Bump go-github from v57 to v60

This bump has some breaking changes to fix.
- In V60
  - https://github.com/google/go-github/pull/3070
  - https://github.com/google/go-github/pull/3073

These changes seem to feature changes and bug fixes but need triage.
- In V59
  - https://github.com/google/go-github/pull/3049
  - https://github.com/google/go-github/pull/3023
- In v58
  - https://github.com/google/go-github/pull/3017

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nayuta** [comment]
@kfcampbell I already created the PR for this. Could you tell me about the next step?

**Comment by kfcampbell** [comment]
Hi, thanks for doing that. What happens next is @nickfloyd or I will review it when we can, which is usually (but not always) a Monday or a Friday. Please be patient, we don't get as much time as we'd like to do this. Thank you for contributing!

**Comment by nayuta** [comment]
Hi, thanks for replying. I got about the situation. I'm always grateful to you for maintaining the repository!

**Comment by JamieB101** [comment]
hey @kfcampbell, hope you're having a good week. Quick question, is this something that you'll be looking at soon? I only ask because it seems to be holding up the Custom Properties tf provider which we're super-keen to use! 
https://github.com/integrations/terraform-provider-github/issues/1956

**Comment by kfcampbell** [comment]
Closing this issue as #2304 has been merged.
