### ISSUE TITLE
[BUG]: v6.2.0 didn't sync to Hashicorp

### ISSUE THREAD

**Issue by bradam12** [integrations/terraform-provider-github#2201]
### Expected Behavior

6.2.0 should be available on Hashicorp. Same as #2191 last week.
Two releases in a row, which is odd.

### Actual Behavior

v6.2.0 didn't sync over.

### Terraform Version

N/A

### Affected Resource(s)

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment]
It was indeed the same issue as #2191. Hashicorp has resynced the registry listing and v6.2.0 is now showing.
