### ISSUE TITLE
[FEAT]: Support push rules

### ISSUE THREAD

**Issue by stevehipwell** [integrations/terraform-provider-github#2235]
### Describe the need

I'd like to be able to configure [push rules](https://github.blog/changelog/2024-04-18-push-rules-public-beta/) via TF/

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ViacheslavKudinov** [comment]
Same here

**Comment by TheArtheist** [comment]
Should be good to go now.
https://docs.github.com/en/rest/repos/rules?apiVersion=2022-11-28#create-a-repository-ruleset
https://docs.github.com/en/graphql/reference/enums#repositoryrulesettarget
