### ISSUE TITLE
[BUG]:  azurerm_linux_function_app, there is container_registry_managed_identity_client_id, the azure portal has no such field

### ISSUE THREAD

**Issue by baoj-dfo** [integrations/terraform-provider-github#2290]
### Expected Behavior

 azure portal's function app has no container_registry_managed_identity_client_id related concept

### Actual Behavior

need a way to get this value from portal 

### Terraform Version

Terraform v1.8.5

### Affected Resource(s)

azurerm_linux_function_app

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nnellanspdl** [comment]
I think you want the azurerm repo, not this repo.

https://github.com/hashicorp/terraform-provider-azurerm
