### ISSUE TITLE
[BUG]: GITHUB prefix not allowed in GitHub Actions repository variables

### ISSUE THREAD

**Issue by cra-schleupen** [integrations/terraform-provider-github#2375]
### Expected Behavior

GitHub App authentication can be used with environment variables as repository variables in github actions workflow.

### Actual Behavior

Docs and code state, that for authentication from github app can be configured from enviroment:

```
GITHUB_OWNER
GITHUB_APP_ID
GITHUB_APP_INSTALLATION_ID
GITHUB_APP_PEM_FILE
```

The `GITHUB_` prefix is not allowed when using github actions repository variables:

> Variable names cannot start with GITHUB_ prefix.

### Terraform Version

na

### Affected Resource(s)

- provider auth config with github app

### Terraform Configuration Files

```hcl
provider "github" {
  owner = var.github_organization
  app_auth {}
}
```

### Steps to Reproduce

Setup auth as described here: https://registry.terraform.io/providers/integrations/github/latest/docs#github-app-installation 

Try to configure GITHUB_APP_ID as repository variable (`github.com/<owner>/<repo>/settings/variables/actions/new`) so it can be used from github actions workflow.

Get error: 

> Variable name cannot start with "GITHUB_" prefix.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by audunsolemdal** [comment]
The setup auth guide you linked to refers to environment variables set in your github actions workflow, not repository variables.

**Comment by cra-schleupen** [comment]
I consider this a bug, because you're using a prefix that is reserved for github actions. 

If you want to use a resuable workflow (e.g.) you can't pass environment from the caller to the called workflow. Configuring this as repo or enviroment variables would simplify the setup.

If you think it's ok, feel free to close the issue.

**Comment by kfcampbell** [comment]
This error actually comes from the API, not from the provider, so this isn't a decision I can change. All variable names that start with `GITHUB_` are reserved for Actions environment variables.
