### ISSUE TITLE
[BUG]: Using a team ID for `github_repository_collaborators` causes churn

### ISSUE THREAD

**Issue by stevehipwell** [integrations/terraform-provider-github#2414]
### Expected Behavior

Based on the documentation I'd expect to be able to set `team_id` to the team ID and have no churn.

### Actual Behavior

It looks like the team slug is stored in the state which is causing churn on every run.

### Terraform Version

Terraform v1.7.5
on windows_amd64

### Affected Resource(s)

- github_repository_collaborators

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by petergasper** [comment]
As a workaround, I was able to use the resource by replacing id with the slug
  team {
    permission = "pull"
    team_id    = data.github_team.repo_teams["xyz"].slug
  }

**Comment by stevehipwell** [comment]
@petergasper I saw this churn even when using the slug.

**Comment by petergasper** [comment]
@stevehipwell I did not, but I have changed it once I had the state file with resources in place. Maybe I got lucky with my setup. Should be fixed now :rocket:
