### ISSUE TITLE
[FEAT]: How cant I able to expose the github token in .tfvars file.

### ISSUE THREAD

**Issue by Anto4595** [integrations/terraform-provider-github#2418]
### Describe the need

Hello Team,

I have created a terraform script that will create a repo and its working fine.

But in the .tfvars file I am exposing the github token as plain text. But I want to secure it somehow so that the token is not exposed to anyone who is testing the code.

How can I achieve it in terraform ?

Thank You.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stevehipwell** [comment]
@Anto4595 this isn't really the forum to request help with terraform, but you should find your answer in the Terraform docs, specifically "[Protect sensitive input variables](https://developer.hashicorp.com/terraform/tutorials/configuration-language/sensitive-variables)".

**Comment by kfcampbell** [comment]
Thanks @stevehipwell!
