### ISSUE TITLE
[DOCS]: github_repository_dependabot_security_updates resource in doc uses github_repository.test.id instead of github_repository.test.name

### ISSUE THREAD

**Issue by ViacheslavKudinov** [integrations/terraform-provider-github#2433]
### Describe the need

Example should look like
```hcl
resource "github_repository" "repo" {
  name         = "my-repo"
  description  = "GitHub repo managed by Terraform"

  private = false

  vulnerability_alerts   = true
}

resource "github_repository_dependabot_security_updates" "example" {
  repository  = github_repository.test.name # changed to name instead of id 
  enabled     = true
}
```
currently 
https://registry.terraform.io/providers/integrations/github/latest/docs/resources/repository_dependabot_security_updates#example-usage
is used ` repository  = github_repository.test.id` and it creates an error
```
Error: PUT https://api.github.com/repos/ORG/REPO_ID/automated-security-fixes: 404 Not Found []
```
as [API expects](https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#enable-automated-security-fixes) "repo name" in API request, not a "repo ID".

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment]
Please feel free to submit a PR for this if you'd like!

**Comment by ViacheslavKudinov** [comment]
Sure, thank you. 
I will try.
Need to start with contribution guide.

**Comment by ViacheslavKudinov** [comment]
Here we go https://github.com/integrations/terraform-provider-github/pull/2439

**Comment by ViacheslavKudinov** [comment]
Hi @kfcampbell 
could it be reviewed and merged if no issues with this PR?
Thank you in advance.
