### ISSUE TITLE
New Resource: Github Organization

### ISSUE THREAD

**Issue by ghost** [integrations/terraform-provider-github#25]
Should there be a Terraform resource that allows the creation of a GitHub Organization?

**Comment by grubernaut** [comment]
Hey @pantocrator27, thanks for the issue! Currently we cannot create a new GitHub Organization via the Github API. 

The API, however, does allow for modifying the Github Organization once it's already been created. Would that be useful here?

**Comment by pantocrator27** [comment]
I think that would be useful because it could be imported after it was created.  What are you thoughts?

**Comment by majormoses** [comment]
+1 for import and edit. Pretty sure you need to confirm some things in order to initially setup an organization.

**Comment by mrparkers** [comment]
@grubernaut The GitHub Enterprise API allows for the creation of organizations.  Would it make sense to add support for a resource like `github_enterprise_organization`?  If there are no objections to this, I'll happily make a PR to add support for this.  The team I'm working with wants to use terraform to manage all of our GHE orgs, and this would be extremely useful.

**Comment by radeksimko** [comment]
@mrparkers Sorry for the delay here. I assume this would be mapped to https://developer.github.com/enterprise/2.14/v3/enterprise-admin/orgs/ ? If so, I agree that a new resource covering this would be helpful, but I wouldn't try to build any abstractions above the API, i.e. cover both creation and management of the data.

If we are ever going to build a resource for managing details of an organization, it should IMO work for both GHE and github.com.

So I'm thinking along the lines of

```hcl
resource "github_enterprise_organization" "example" {
  login = "example-org"
  profile_name = "Example, Inc."
  admin = "johndoe"
}

resource "github_organization" "example" {
  login = "${github_enterprise_organization.example.login}" # Or this can be hard-coded for github.com
  billing_email = "john.doe@example.com"
  name = "..." # There's a conflict, unfortunately, so we might need to work warn the user (that they should use just one of the two resources for managing name) and work around this somehow
  email = "..."
...
}
```

**Comment by mrparkers** [comment]
Perhaps I'm misunderstanding, but how can this potential resource support both public github and GHE when public github does not have a way of creating orgs through an API? Would the create function just error out if it isn't running against GHE, and users that want to manage orgs for public github would just be expected to import this?

I can devote some time to this but I think I need a bit of clarification about how this should work.

**Comment by majormoses** [comment]
I am supportive of this idea: https://github.com/terraform-providers/terraform-provider-github/issues/25#issuecomment-410618161

**Comment by rd-michel** [comment]
Is anybody still working on this topic?

**Comment by shannonrdunn** [comment]
Surprising that we are unable to create Github Enterprise Organizations via this provider, as its available via the api.

Really hurts our IaC efforts for managing github enterprise.

**Comment by UbiquitousBear** [comment]
@radeksimko is this something that can be revisited?

**Comment by jcudit** [comment]
I think this would be a great new addition and welcome PRs.

**Comment by andyfeller** [comment]
Just because I haven't seen anyone mention this, GitHub's GraphQL API provides the [`createEnterpriseOrganization` mutation](https://docs.github.com/en/enterprise-cloud@latest/graphql/reference/mutations#createenterpriseorganization) which is the only API interface I know of to create an organization today:

```graphql
mutation {
  createEnterpriseOrganization(input: {
    enterpriseId: $enterpriseId
    login: $login
    profileName: $profileName
    billingEmail: $billingEmail
    adminLogins: [$admin]
    clientMutationId: $clientMutationId
  }) {
    clientMutationId
  }
}
```

That said, I'm not in any form a Terraform novice / adept / pro / expert capable of building and contributing this myself.
