### ISSUE TITLE
github_repository_collaborator should accept both short-and-long-form repository name formats

### ISSUE THREAD

**Issue by sudoforge** [integrations/terraform-provider-github#256]
### Terraform Version

```
→ tf version
Terraform v0.12.4
```

### Affected Resource(s)

- `github_repository_collaborator`

### Terraform Configuration Files

Example configuration:

```hcl
resource github_repository example {
  name      = "issue-example-256"
  auto_init = true
}

resource github_repository_collaborator example {
  username   = "some-username"
  repository = github_repository.example.full_name
  permission = "pull"
}
```

### Debug Output

Irrelevant.

### Panic Output

N/A

### Expected Behavior

The `github_repository_collaborator` resource should have been created.

### Actual Behavior

A 404 error is received from the upstream API due to the endpoint not accepting the format of the name output by `github_repository.full_name`:

[`PUT /repos/:owner/:repo/collaborators/:username`][0]

[0]: https://developer.github.com/v3/repos/collaborators/#add-user-as-a-collaborator

The GitHub API is inefficient and wildly inconsistent. This issue *should* be fixed upstream, but because it won't be, the Terraform provider should accept the `full_name` format and simply strip the `:owner/` portion of the string, so that it is in **parity with other resources, like `github_repository_deploy_keys`**, etc...

### Steps to Reproduce

1. Copy the example plan, above.
2. Change `some-username` to anything
3. Run `terraform apply`

### Important Factoids

N/A

### References

- GH-59
- GH-176

**Comment by sudoforge** [comment]
I'd be happy to take care of this if it is approved for development.

**Comment by tracypholmes** [comment]
Hi @sudoforge. Thank you for opening this issue! We would be happy to accept a PR for this if you would like to open one.

**Comment by sudoforge** [comment]
well, this is a blast from the past. i can't add labels, but i'll try to make time for this over the next few weeks if it is still relevant.

**Comment by kfcampbell** [comment]
I've added the relevant labels. That sounds good to me, thank you!
