### ISSUE TITLE
Add support for creating script hooks in Github repositories

### ISSUE THREAD

**Issue by usamaahmadkhan** [integrations/terraform-provider-github#263]
This is a feature request.

### Terraform Version
Not applicable 

### Affected Resource(s)
Not applicable 

### Terraform Configuration Files
Not applicable 

### Debug Output
Not applicable 

### Panic Output
Not applicable 

### Expected Behavior
Terraform should support a resource to install a hook (simple scripts in `.git/hooks/`) while creating a repository

### Actual Behavior
No support for hooks

### Steps to Reproduce
Not applicable 

### Important Factoids
Alot of times people want to have a small check in their git repo e.g. (no AWS keys are checked in the code) so they keep a small script under `.git/hooks/`. It would be awesome if terraform could provide a resource to add these scripts under hooks/ directory

### References
Not applicable

**Comment by kfcampbell** [comment]
The best workaround at present is probably using the `resource_github_repository_file.go` resource.
