### ISSUE TITLE
Feature request: alternative way to maintain team membership

### ISSUE THREAD

**Issue by jacekn** [integrations/terraform-provider-github#280]
It would be convenient to have ability to maintain team membership using member list rather than user-team resources.

Currently team membership is configured using resources like this:
```
resource "github_team_membership" "some_team_membership" {
  team_id  = "${github_team.some_team.id}"
  username = "SomeUser"
  role     = "member"
}
```

In a larger organization, for example with over 100 teams and 1000 users, number of resources that need to be managed will be very large, it can even be tens of thousands. This will cause state refresh to take a very long time.

It would be good to be able to provide list of team member, possibly to the "github_team" resource like this:
```
resource "github_team" "some_team" {
  name        = "some-team"
  description = "Some cool team"
  privacy     = "closed"
  members = ["user1", "user2", "user3", "user4"]
  maintainers = ["maintainer1"]
}
```

Solution above would dramatically reduce number of individual resources.

### Terraform Version
```
Terraform v0.12.8
+ provider.github v2.2.1
```
### Affected Resource(s)
- github_team
- github_team_membership

### Important Factoids

According to the GH v3 API documentation it is possible to retrieve/update team membership using single API calls so the enhancement I'm proposing would also cut down number of necessary API round trips.

In my opinion it's nice to maintain team membership in a tfvars.json configs, for example using structures like this:
```
"team_one": {
  "description": "awesome team",
  "privacy": "secret",
  "members": ["user1", "user2", "user3", "user4"],
  "maintainers": ["maintainer1"]
}
```

This structure could be directly translated to the github_team resources using "for_each" which would be very convenient.

### References
- https://developer.github.com/v3/teams/members/

**Comment by Jonnymcc** [comment]
I wonder if this same idea could be used for managing the repositories that teams have access to using the github_team resource alone, and not use multiple github_team_repository resources.

**Comment by guessi** [comment]
Just ran into this problem as well.

And here's my solution for creating `github_team_repository` in batch.

_Similarly, it should be possible to create `github_team_membership` in batch as well._

```
variable "repositories" {
  type = list(string)

  default = [
    "repositoryA",
    "repositoryB",
    "repositoryC",
  ]
}

resource "github_team_repository" "Developer" {
  for_each   = toset(var.repositories)
  repository = each.key
  team_id    = 123456
  permission = "pull"
}
```

Once the resource been created, you should be able to list/update/delete them afterward:
```
$ terraform state list

github_team_repository.Developer["repositoryA"]
github_team_repository.Developer["repositoryB"]
github_team_repository.Developer["repositoryC"]
```

Hope these information could help.

**Reference:**
- [for_each: Multiple Resource Instances Defined By a Map, or Set of Strings](https://www.terraform.io/docs/configuration/resources.html#for_each-multiple-resource-instances-defined-by-a-map-or-set-of-strings)

**Comment by guessi** [comment]
I'm able to manipulate the resources with the trick of `for_each`, which required Terraform 0.12.x.
But still looking for the built-in solution for passing members as list with `github_team`, or even more complex.

@Jonnymcc FYI

Here's my solution (workaround) for creating `github_team_repository` in batch.

```
variable "repositories" {
  type = list(string)

  default = [
    "repositoryA",
    "repositoryB",
    "repositoryC",
  ]
}

resource "github_team_repository" "Developer" {
  for_each   = toset(var.repositories)
  repository = each.key
  team_id    = 123456
  permission = "pull"
}
```

Once the resource been created, you should be able to list/update/delete them afterward:
```
$ terraform state list

github_team_repository.Developer["repositoryA"]
github_team_repository.Developer["repositoryB"]
github_team_repository.Developer["repositoryC"]
```

Hope these information could help.

**Reference:**
- [for_each: Multiple Resource Instances Defined By a Map, or Set of Strings](https://www.terraform.io/docs/configuration/resources.html#for_each-multiple-resource-instances-defined-by-a-map-or-set-of-strings)

**Comment by jacekn** [comment]
Actually this is now possible using the `team_members` resource!
https://registry.terraform.io/providers/integrations/github/latest/docs/resources/team_members

So this issue can be closed for sure. Thank you!
