### ISSUE TITLE
Feature request: Autolink references

### ISSUE THREAD

**Issue by tiesmaster** [integrations/terraform-provider-github#285]
GitHub recently launched ["Autolink references"](https://github.blog/2019-10-14-introducing-autolink-references/). It would be awesome if you'd configure that using the `github_repository` resource ;)

**Comment by mrwacky42** [comment]
Does GitHub API even support this yet?

**Comment by mwarkentin** [comment]
I haven't seen it anywhere.. would be nice though..

**Comment by lsowen** [comment]
Looks like the API might not support it yet?  https://github.community/t5/GitHub-API-Development-and/Support-autolink-reference-configuration-in-the-API/td-p/44850

**Comment by mwarkentin** [comment]
https://github.blog/changelog/2021-08-02-apis-for-autolinks/

**Comment by lsowen** [comment]
Created a feature request in the github rest library this provider uses to add support for this new feature: https://github.com/google/go-github/issues/2044

**Comment by entropitor** [comment]
This is now implemented in the go-github library: https://github.com/google/go-github/pull/2046

**Comment by jensenbox** [comment]
Does this mean we get it nearly for free in the provider?

**Comment by jcudit** [comment]
I believe our provider is now up to date so this issue can be worked if there is anyone interested.

**Comment by rescDev** [comment]
Hey guys, I created #924 that adds a new resource `github_repository_autolink_reference`

**Comment by mwarkentin** [comment]
@rescDev nice, thank you!
