### ISSUE TITLE
2.2.1 tries to re-create existing resources when nothing changes

### ISSUE THREAD

**Issue by calvin-brizzi** [integrations/terraform-provider-github#292]
### Terraform Version
Terraform v0.12.13
Github Provider version 2.2.1

### Affected Resource(s)
All Github resources

### Expected Behavior
As nothing has changed, no changes to be committed.

### Actual Behavior
All resources are created again.

For example `terraform state list` includes
`github_team_repository.developers["docs"]`

but then `terraform apply` spits out

```
# github_team_repository.developers["docs"] will be created
  + resource "github_team_repository" "developers" {
      + etag       = (known after apply)
      + id         = (known after apply)
      + permission = "push"
      + repository = "docs"
      + team_id    = "<redacted>"
    }
```

### Steps to Reproduce
Pin version to 2.2.0
`terraform apply`
no changes 

Upgrade to 2.2.1
`terraform apply`
prompted to recreate everything, refuse

Change back to 2.2.0
`terraform apply`
no changes

(Debug output contains a lot of info about users in my org, but can try sanitise and post a version if needed)

**Comment by jcudit** [comment]
Is this still happening in recent versions of the provider?

**Comment by wagnst** [comment]
I still see similar behaviour, its not delete/create buy its to change cause of `etag`:

```
  ~ resource "github_team_repository" "collaborator" {
      ~ etag       = "W/\"83664adfafb19facd285b7e98ff5f4c10fe93630709c99e29f702baf53631553\"" -> "W/\"c7bdfce5f170b3902721e3c4d35945fe19528997de9ff0b84d4d3ea93c644d9c\""
        id         = "4201076:xxx"
        # (3 unchanged attributes hidden)
    }
```
