### ISSUE TITLE
request: support null for required_approving_review_count

### ISSUE THREAD

**Issue by skeggse** [integrations/terraform-provider-github#294]
### Terraform Version

```
Terraform v0.12.13
+ provider.github v2.2.1
```

### Affected Resource(s)

```
github_branch_protection.required_pull_request_reviews.required_approving_review_count
```

### Terraform Configuration Files

```hcl
resource "github_branch_protection" "default" {
  repository = github_repository.repo.name
  branch     = "master"

  enforce_admins = true

  required_status_checks {
    strict = true
  }

  required_pull_request_reviews {
    required_approving_review_count = null
  }
}
```

### Debug Output

N/a

### Panic Output

N/a

### Expected Behavior
What should have happened?

The provider should have configured the branch protection without any required reviewers. The upstream service supports `null` for the `required_approving_review_count` field, and assigns it accordingly if the containing `required_pull_request_reviews` block is omitted.

### Actual Behavior
What actually happened?

The provider configured branch protection with one reviewer, per the [provider-configured default](https://github.com/terraform-providers/terraform-provider-github/blob/885cb9495f0d4c3b20e48b52a034e215ec81cab8/github/resource_github_branch_protection.go#L104).

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

Nope.

### References
https://github.com/terraform-providers/terraform-provider-github/pull/181

**Comment by iniinikoski** [comment]
Also bumped into this... :|

**Comment by rradillen** [comment]
3 years later I am still running into this issue: PR 971 could also provide an acceptable fix for this bug

**Comment by kfcampbell** [comment]
Closing as #971 has been merged and released.

**Comment by skeggse** [comment]
thank you!
