### ISSUE TITLE
Feature Request > New branch protection features support

### ISSUE THREAD

**Issue by kuwas** [integrations/terraform-provider-github#305]
# Description

Please add support for the new branch protection features:
* `required_linear_history`
* `allow_force_pushes`
* `allow_deletions`

### Terraform Version
```
Terraform v0.12.16
```

### Affected Resource(s)
- `github_branch_protection`

### Terraform Configuration Files
```hcl
resource "github_branch_protection" "example" {
  repository = "example-repo"
  branch = "master"
  required_linear_history = true
  allow_force_pushes = false
  allow_deletions = false
}
```

### Debug Output
n/a

### Panic Output
n/a

### Expected Behavior
New branch protection features are supported

### Actual Behavior
New branch protection features are not supported

### Steps to Reproduce
n/a

### Important Factoids
Currently not supported by go-github client, see references below

### References
- I've opened https://github.com/google/go-github/issues/1345 to add support to the go client as a prerequisite
- API docs: https://developer.github.com/v3/repos/branches/#update-branch-protection

**Comment by arri-cc** [comment]
Now that #342 is merged, this update is now possible.  Working on it now.

**Comment by arri-cc** [comment]
actually, we need the latest version v29.0.3 https://github.com/google/go-github/tree/v29.0.3

I'll submit a separate PR to hopefully get that done first.

**Comment by martinssipenko** [comment]
@arri-cc you are correct. I tried doing a simple upgrade, but turned out it's not that simple, I've opened issue #368 where I outlined the issue.

**Comment by benj-fletch** [comment]
@arri-cc I think you will also encounter issues when upgrading the Terraform version as there is a Go 1.12 SDK feature used in TF v0.12.14 onwards causing issues as we are on Go 1.11.
I have raised #370 to hopefully remediate this issue

**Comment by arri-cc** [comment]
> @arri-cc I think you will also encounter issues when upgrading the Terraform version as there is a Go 1.12 SDK feature used in TF v0.12.14 onwards causing issues as we are on Go 1.11.
> I have raised #370 to hopefully remediate this issue

Interesting, we're currently using Terraform v0.12.15, so thanks for the heads up.

**Comment by yordis** [comment]
@arri-cc are you still working on this? Can I help somehow?

**Comment by arri-cc** [comment]
@yordis Hi!

I've been waiting in the wings while @benj-fletch and @martinssipenko sort out a number of issues that were discovered after upgrading to go-github v29.0.2.
#370 and #372 are now completed.  Now what's left is the upgrade to go-github v29.0.3, which is the release that adds the branch protection features we're interested in.  The remaining open issue (afaik) is here #369, which appears to be near completion.

**Comment by arri-cc** [comment]
looks like we have go-github v29.0.3 now, i'll revisit this

**Comment by kuwas** [comment]
@jcudit Will #473 be merged soon? Thanks

**Comment by TigerC10** [comment]
Looking forward to #473 😄

**Comment by jimsmith-fd** [comment]
+1 for `required_linear_history` or `require_linear_history` whatever the argument will be settled on.

I posted a comment here (as there seems to be a few splits for this argument) https://github.com/integrations/terraform-provider-github/pull/473#issuecomment-770833289

**Comment by jcudit** [comment]
I'm now seeing `requiresLinearHistory`, `allowsDeletions` and `allowsForcePushes` available via the GraphQL API for [`BranchProtectionRule`](https://docs.github.com/en/graphql/reference/objects#branchprotectionrule).  Seems like we can proceed with making these configurable for the `github_branch_protection` resource.

I had hoped the `github_branch_protection_v3` resource was transitional and did not plan on updating it with new features. Curious to hear if just enabling these features for just the `github_branch_protection` resource would satisfy everyone or if there are a lot of users still stuck on `github_branch_protection_v3`.

**Comment by anelson** [comment]
> I had hoped the `github_branch_protection_v3` resource was transitional and did not plan on updating it with new features. Curious to hear if just enabling these features for just the `github_branch_protection` resource would satisfy everyone or if there are a lot of users still stuck on `github_branch_protection_v3`

We are not using `github_branch_protection_v3` at all.  Eagerly awaiting the additional of `requiresLinearHistory` support to `github_branch_protection`!

**Comment by majormoses** [comment]
> I'm now seeing `requiresLinearHistory`, `allowsDeletions` and `allowsForcePushes` available via the GraphQL API for [`BranchProtectionRule`](https://docs.github.com/en/graphql/reference/objects#branchprotectionrule). Seems like we can proceed with making these configurable for the `github_branch_protection` resource.
> 
> I had hoped the `github_branch_protection_v3` resource was transitional and did not plan on updating it with new features. Curious to hear if just enabling these features for just the `github_branch_protection` resource would satisfy everyone or if there are a lot of users still stuck on `github_branch_protection_v3`.

I think there are probably some orgs stuck on v3 for various reasons, my org is not using it anymore. I think we should support both APIs while github keeps pushing features to it. It does not mean that we have to have 1:1 feature parity though that would be ideal as it makes it easier for folks to migrate when they are ready.

**Comment by dududko** [comment]
Any update on this issue ?

**Comment by bspammer** [comment]
I've just submitted a PR to add this, tested to work locally
