### ISSUE TITLE
Deleting a user from a team does not revoke a pending invitation

### ISSUE THREAD

**Issue by josh-padnick** [integrations/terraform-provider-github#307]
### Terraform Version
Terraform v0.11.14

### Affected Resource(s)
- github_team_membership

### Terraform Configuration Files
```hcl
resource "github_team_membership" "membership" {
  count    = "${length(var.team_user_names)}"
  team_id  = "${github_team.team.id}"
  username = "${element(var.team_user_names, count.index)}"
  role     = "member"
}
```

### Expected Behavior
We had a user that received an invitation to join our GitHub Org but did not yet accept that invitation (a "pending member invitation") at the time that we deleted his username. But when we looked in GitHub, the invitation was still outstanding and had not been revoked.

### Actual Behavior
The invitation should have been revoked.

**Comment by kpfleming** [comment]
Which version of terraform-provider-github are you using?

**Comment by josh-padnick** [comment]
Our provider block is set to `* provider.github: version = "~> 2.2"` so I'm using 2.2.1.
