### ISSUE TITLE
Leftover module in state that should have been removed

### ISSUE THREAD

**Issue by nikovirtala** [integrations/terraform-provider-github#344]
### Terraform Version
Terraform: `0.12.19`
GitHub Provider: `2.3.1`

### Affected Resource(s)

Please list the resources as a list, for example:
- github_repository
- github_membership

It is not clear for me whether this is a provider or core issue.

### Expected Behavior

```
Apply complete! Resources: 0 added, 0 changed, 1 destroyed.
```

### Actual Behavior

We are unable to delete successfully repositories or member from our GitHub organization – at least the member removal was working before GitHub Provider version `2.3.0`.  

```
running "/home/atlantis/.atlantis/bin/terraform0.12.19 apply -input=false -no-color -lock=true \"/home/atlantis/.atlantis/repos/FinnishRail/github-repository-provisioner/163/default/prod-default.tfplan\"" in "/home/atlantis/.atlantis/repos/FinnishRail/github-repository-provisioner/163/default": exit status 1
module.yet-another-repository-to-be-deleted.github_repository.default: Destroying... [id=yet-another-repository-to-be-deleted]
module.yet-another-repository-to-be-deleted.github_repository.default: Destruction complete after 0s

Error: leftover module module.yet-another-repository-to-be-deleted in state that should have been removed; this is a bug in Terraform and should be reported
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Remove repository or membership from the configuration
2. `terraform plan`
3. `terraform apply`

**Comment by jcudit** [comment]
Is this still an issue with more recent versions of this provider?
