### ISSUE TITLE
Add github-actions ip addresses on datasource github_ip_ranges

### ISSUE THREAD

**Issue by bkamin29** [integrations/terraform-provider-github#351]
Hello,

Can you add the publics ip addresses used by github-actions as result of the datrasource `github_ip_ranges` ?

### Terraform Version
```
▶ terraform version
Terraform v0.12.20
+ provider.aiven (unversioned)
+ provider.github v2.3.2
+ provider.google v2.19.0
+ provider.google-beta v3.7.0
+ provider.grafana v1.5.0
+ provider.kubernetes v1.10.0
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.template v2.1.2
+ provider.ultradns v0.1.1
```

### Affected Resource(s)
Please list the resources as a list, for example:
- `github_ip_ranges`

**Comment by benj-fletch** [comment]
Hi @benesis002 I'm not exactly sure what you are after in this request - based on your TF modules I'm guessing you need the IP addresses for some whitelist to allow deployment?

I don't believe that the [Github Meta API](https://developer.github.com/v3/meta/) makes available the IP addresses it uses for hosted runners, though some digging has revealed that they are [hosted on Azure](https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners#ip-addresses-of-github-hosted-runners) and use the public IP addresses of the MS datacentres.

Does this help your use case? If not are you able to provide some more context around what you require the IP addresses for?

**Comment by benesis002** [comment]
Hell

> Hi @benesis002 I'm not exactly sure what you are after in this request - based on your TF modules I'm guessing you need the IP addresses for some whitelist to allow deployment?
> 
> I don't believe that the [Github Meta API](https://developer.github.com/v3/meta/) makes available the IP addresses it uses for hosted runners, though some digging has revealed that they are [hosted on Azure](https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners#ip-addresses-of-github-hosted-runners) and use the public IP addresses of the MS datacentres.
> 
> Does this help your use case? If not are you able to provide some more context around what you require the IP addresses for?

**Comment by benesis002** [comment]
> Hi @benesis002 I'm not exactly sure what you are after in this request - based on your TF modules I'm guessing you need the IP addresses for some whitelist to allow deployment?
> 
> I don't believe that the [Github Meta API](https://developer.github.com/v3/meta/) makes available the IP addresses it uses for hosted runners, though some digging has revealed that they are [hosted on Azure](https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners#ip-addresses-of-github-hosted-runners) and use the public IP addresses of the MS datacentres.
> 
> Does this help your use case? If not are you able to provide some more context around what you require the IP addresses for?

Hello,

Yes, i want to use this datasource result to create firewall rules.
And yes maybe github action use Azure serverless service, so Github don't have a public ip address static list :/

**Comment by elliotchaim** [comment]
This would be a great feature. Right now I'm forced to either remove network security rules, or wrap my `terraform apply` in a bash script which manually adds the current IP. But then terraform will surely remove the new IP when it applies the configuration. So I'll have to pass the current IP into terraform as well. It's messy and hard to maintain

**Comment by dodwmd** [comment]
A work around until it's supported:

```
data "http" "github-meta" {
  url = "https://api.github.com/meta"
  request_headers = {
    Accept = "Accept: application/vnd.github.v3+json"
  }
}
locals {
  github_actions_ips = jsondecode(data.http.github-meta.body)["actions"]
}
output "github_actions_ips" {
  value = local.github_actions_ips
}
```
