### ISSUE TITLE
[Feature Request] Add Option Data services Dependency graph

### ISSUE THREAD

**Issue by abilous-ti** [integrations/terraform-provider-github#390]
Hi there,

### Terraform Version
Terraform v0.12.24
- provider.github v2.4.0

### Affected Resource(s)
- github_repository

![image](https://user-images.githubusercontent.com/22077679/77404346-43610d80-6dba-11ea-966d-e912f9dee685.png)

**Comment by anGie44** [comment]
hi @abilous-ti, looks like this will be a side-effect of #444.  enabling vulnerability alerts will also enable the dependency graph (referenced here: https://developer.github.com/v3/repos/#enable-vulnerability-alerts)

**Comment by sa-spag** [comment]
I confirm it does @abilous-ti. Nonetheless, we still lack an input to configure Dependabot security updates (#588) and access to alerts.
