### ISSUE TITLE
[Feature Request] Authoritative repository access management

### ISSUE THREAD

**Issue by eriksw** [integrations/terraform-provider-github#395]
Currently, there appears to be no way to authoritatively manage repository permissions using the GitHub terraform provider.

My use case is that there are repositories that have been created over the years, that have been imported into management by terraform, but these repositories have miscellaneous grants of read/admin/write permissions to arbitrary teams and users. (Most commonly, 'admin' to the user that initially created the repo, but there's also cases like read access being granted to a contract pentester that nobody remembered to revoke, etc...)

`github_team_repository` and `github_repository_collaborator` exist, but they are only additive: the absence of a resource setting the access for a team/user will not remove that user's access.

It would be great if there was an equivalent to [google_project_iam_policy](https://www.terraform.io/docs/providers/google/r/google_project_iam.html) — something where I can declare what users and teams should have what levels of access, and that upon apply will remove all other access.

**Comment by maroux** [comment]
Just opened a PR for this issue, still working on tests.

**Comment by maroux** [comment]
@jcudit could someone take a look at the linked PR and let me know if this is something you'd be open to merging?

**Comment by maroux** [comment]
cc @kfcampbell maybe?

The PR is now complete with tests.

**Comment by eriksw** [comment]
@maroux Is your PR intended to cover team access as well, or just individual users?

What I'm hoping will eventually be part of this provider is a resources where there's one instance of that resource and it covers both team and user(/collaborator) access in an authoritative manner. (Everything that's not a GitHub App and not inherited from the organization level.)

**Comment by maroux** [comment]
@eriksw both teams and individual users. Example config:
```
resource "github_repository_collaborators" "a_repo_collaborators" {
  repository = "our-cool-repo"

  user {
    permission = "admin"
    username  = "SomeUser"
  }
  
  team {
    permission = "pull"
    team_id = "SomeTeam"
  }
}
```

**Comment by eriksw** [comment]
Please don't close this until an authoritative resource is available.
