### ISSUE TITLE
Insecure default for `private` setting with github_repository resource

### ISSUE THREAD

**Issue by preston-hf** [integrations/terraform-provider-github#436]
The `github_repository` resource currently makes new repositories public by default, and requires you to specify that you want it private. This is a poor choice from a security perspective, especially considering this resource only works with organizations.

I posit that most users of this Terraform provider are private companies with private codebases, with a majority of their repositories being private ones with sensitive IP that would be damaging if exposed to the web. In consideration of this, this resource has an insecure default that should be deprecated and inverted. The `private` setting should default to true instead of false, or maybe we should deprecate the usage of private altogether in favor of `public = true` so that it's even more obvious that you're exposing the repo to the world. I am happy to contribute either of these changes if Hashicorp agrees.

### Terraform Version
N/A

### Affected Resource(s)
Please list the resources as a list, for example:
- github_repository

### Terraform Configuration Files
```hcl
resource "github_repository" "super_secret_stuff" {
  name        = "example"
  description = "My org's crown jewels"

  template {
    owner = "github"
    repository = "terraform-module-template"
  }
}
```

### Expected Behavior
Repository should be created as private by default

### Actual Behavior
Repository is created as public by default

**Comment by majormoses** [comment]
While I am a fan of "secure by default" this also means deviating from the upstream default: https://developer.github.com/v3/repos/#parameters-5.

If you work for an organization I recommend that you never use `github_repository` anywhere outside your companies module where you can specify your own sane/safe/secure defaults. The reality is that Github is used more for open than closed source and I think that is something we should weigh here.

**Comment by jcudit** [comment]
A compromise here may be to remove the public /private configuration options in favour of a required visibility option that has no default. 

I like the idea above about wrapping this provider with modules to smooth out the interface. We could make modules geared towards the different use cases of this provider and publish them to the Terraform Registry.
