### ISSUE TITLE
URL built incorrectly when trying to reference a release by tag

### ISSUE THREAD

**Issue by smiller171** [integrations/terraform-provider-github#450]
While Trying to use the releases functionality I discovered that the release tag url is being built incorrectly, making it impossible to get a release by tag. This is actually an issue with an upstream dependency and I've opened a PR with them to resolve it. https://github.com/google/go-github/pull/1520

### Terraform Version
Terraform v0.12.24

### Affected Resource(s)
Please list the resources as a list, for example:
- github_release

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
data "github_release" "this" {
  repository  = "redacted"
  owner       = "redacted"
  retrieve_by = "tag"
  release_tag = var.github_release_tag
}

output "github_release_assets_url" {
  value = data.github_release.this.asserts_url
}
```

### Debug Output
https://gist.github.com/smiller171/3d098ae89f1e89add580c25cd37fd389

### Panic Output
N/A

### Expected Behavior
Get URL of release assets

### Actual Behavior
404 error because it's building the release url incorrectly

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

### Important Factoids
N/A

### References
https://github.com/google/go-github/pull/1520

**Comment by smiller171** [comment]
@anGie44 here's the new issue

**Comment by anGie44** [comment]
thank you @smiller171 ! 

hmm its interesting because, locally I tried to do something similar with:
```
provider "github" {}

data "github_release" "this" {
  repository  = "terraform-provider-aws"
  owner       = "terraform-providers"
  retrieve_by = "tag"
  release_tag = "v2.61.0"
}

output "github_release_assets_url" {
  value = data.github_release.this.asserts_url
}
```
and this returns as expected with: 
`github_release_assets_url = https://api.github.com/repos/terraform-providers/terraform-provider-aws/releases/26296110/assets`

but if I do 
```
provider "github" {}

data "github_release" "this" {
  repository  = "terraform-provider-github"
  owner       = "terraform-providers"
  retrieve_by = "tag"
  release_tag = "v2.7.0" // or any other tag
}

output "github_release_assets_url" {
  value = data.github_release.this.asserts_url
}
```
I get a similar message as in your comment:
```
data.github_release.this: Refreshing state...

Error: GET https://api.github.com/repos/terraform-providers/terraform-provider-github/releases/tags/v2.7.0: 404 Not Found []

  on main.tf line 3, in data "github_release" "this":
   3: data "github_release" "this" {
```
I wonder if there's an issue with the actual ownernship of a github_repository or something about the releases being accessible for certain repositories (perhaps a setting of sort)?

**Comment by smiller171** [comment]
Maybe it has to do with how the release is created?

ugh...in the `terraform-provider-aws` repo it _must_ be `tags` and in the `terraform-provider-github` repo it _must_ be `tag`

**Comment by smiller171** [comment]
Sounds like the only _right_ way to do it is to try both? The difference seems totally undocumented.

**Comment by anGie44** [comment]
actually this post here may explain what we're seeing: https://stackoverflow.com/questions/26140372/cannot-get-releases-for-a-repo-with-the-github-api

**Comment by smiller171** [comment]
@anGie44 I thought that was it too, but I tried to properly publish a release and `/tags/` still doesn't work for me

**Comment by anGie44** [comment]
@smiller171 ugh quite strange indeed.maybe reaching out to Github Support might give better insight to this interesting tags vs. tag discrepancy?

**Comment by jcudit** [comment]
Experimentation results follow:

- A call to https://api.github.com/repos/terraform-providers/terraform-provider-aws/releases produces an empty list for my account
- A call to https://api.github.com/repos/terraformtesting/acceptance-tests/releases produces a successful full listing for my account
- A call to https://api.github.com/repos/hashicorp/vault/releases produces an empty list for my account

This seems like access to releases requires some level of permissions that may not be consistent across all organizations for my account.
