### ISSUE TITLE
Terraform# github_repository doesnot support "include all branches" when creating from template

### ISSUE THREAD

**Issue by arpit-malviya-tm** [integrations/terraform-provider-github#467]
### Terraform Version
Terraform v0.12.24

### Affected Resource(s)
github_repository
https://www.terraform.io/docs/providers/github/r/repository.html

### Expected Behavior
Template should provide option to enable "Include all branches when creating a repository from a template"
Github released this feature in Mar'20: https://github.blog/changelog/2020-03-31-include-all-branches-when-creating-a-repository-from-a-template/

### Actual Behavior
template supports only following arguments:

- owner: The GitHub organization or user the template repository is owned by.
- repository: The name of the template repository.

**Comment by SanderKnape** [comment]
Doesn't seem to be possible yet with the API: https://developer.github.com/v3/repos/#create-a-repository-using-a-template

**Comment by arpitmalviya2020** [comment]
Thanks Sander! This should help. Then would have to wait until we have API version for it.

**Comment by snuggie12** [comment]
Looks like this is possible now? https://docs.github.com/en/rest/reference/repos#create-a-repository-using-a-template--parameters

**Comment by joey-jonko-paypal** [comment]
The GitHub Go pkg seems to support this now as well.
https://github.com/google/go-github/blob/1df4afdba0bc327459f7f22822793f000ffc2606/github/repos.go#L434-L443

**Comment by kvillar** [comment]
This would be very useful and is now available with the API.

**Comment by kfcampbell** [comment]
This is complete as of #1353.
