### ISSUE TITLE
Feature request: New data source--list a user's repository invitations

### ISSUE THREAD

**Issue by nl-brett-stime** [integrations/terraform-provider-github#484]
Hi there,

### Terraform Version
```
Terraform v0.12.26
+ provider.github v2.7.0
+ provider.local v1.4.0
```

### Affected Resource(s)
terraform-provider-github

### Terraform Configuration Files
I'd like to be able to write something like the following. E.g., if we've issued collaborator invites to a CICD/build-automation bot for numerous repositories, we need to know which invitations are still pending/unaccepted and accept those.

```hcl
resource "github_user_invitation_accepter" "bot_accept" {
  provider = github.bot_account

  for_each = data.github_user_invitations.bot_invites
  invitation_id = each.value.invitation_id
}
```

### Expected Behavior
The new data source would call the GitHub API to list the invitations for a specified user:
https://developer.github.com/v3/repos/invitations/#list-a-users-repository-invitations

### Important Factoids
When issuing invitations via the github_repository_collaborator resource, the invite ID is retained in the Terraform backend/state but the invite status, whether accepted or not, is not persisted. If you try to derive the list of unaccepted invites by looping over all collaborators for each repository as follows, you get the error further below.

```hcl
locals {
  need_invite_repos = toset([
    for item in data.github_collaborators.this:
      item.repository
      if !contains(item.collaborator.*.login, "some_github_username")
  ])
  invitation_ids_to_accept = toset([
    for item in github_repository_collaborator.this:
      item.invitation_id
      if contains(local.need_invite_repos, item.repository)
  ])
}

resource "github_user_invitation_accepter" "bot_accept" {
  provider = github.bot

  // Need to filter out previously accepted invites otherwise we get 404 errors.
  for_each = local.invitation_ids_to_accept
  invitation_id = each.value
}
```

...that produces this:
```
Error: Invalid for_each argument

  on main.tf line 91, in resource "github_user_invitation_accepter" "example":
  91:   for_each = local.invitation_ids_to_accept

The "for_each" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the for_each depends on.

```

There are also problems when issuing invites with elevated permissions. E.g., if a user has previously accepted an invite with 'read' permissions but now we want to issue a new invitation with 'write' permissions. In that case, it's hard to distinguish whether the invite is accepted or not using the output of the github_repository_collaborator resource.

**Comment by nl-brett-stime** [comment]
Ultimately, it'd be great to do both of the following in a single pass of `terraform apply`:

* Issue a bunch of invitations using one provider instance associated with org admin credentials
* Accept the invitations with another provider instance associated with bot credentials.

**Comment by jcudit** [comment]
Interesting use case @nl-brett-stime, thanks for writing this up.

Would using a GitHub App be an acceptable solution here?  See also https://github.com/terraform-providers/terraform-provider-github/issues/509, which may align to your use case.  We may be able to skip the invite workflow in favour of an app installation.
