### ISSUE TITLE
Feature Request > GitHub App authentication support

### ISSUE THREAD

**Issue by kuwas** [integrations/terraform-provider-github#514]
### Terraform Version
v0.13.0-beta3

### Affected Resource(s)
- provider configuration

### Terraform Configuration Files
```hcl
provider "github" {
  app_id          = var.app_id
  private_key_pem = var.private_key_pem
}
```

### Debug Output
n/a, this feature doesn't exist

### Panic Output
n/a, this feature doesn't exist

### Expected Behavior
Terraform authenticates as a GitHub App, this removes the need of making a bot GitHub account for terraform usage

### Actual Behavior
n/a, this feature doesn't exist

### Steps to Reproduce
n/a, this feature doesn't exist

### Important Factoids
- GitHub Apps has higher API limits than a Personal Access Token
  - https://developer.github.com/apps/building-github-apps/understanding-rate-limits-for-github-apps/#server-to-server-requests

### References
- https://developer.github.com/apps/building-github-apps/authenticating-with-github-apps/#authenticating-as-a-github-app
- https://github.com/google/go-github/issues/1069

**Comment by dutsmiller** [comment]
I would add that it would be nice to be able to use repository deployment keys in the same fashion.  While this would limit the over functionality of the provider, it would be nice to not have to tie the use of the provider to a specific user account.

**Comment by patrickmarabeas** [comment]
It's been on my list to port over - but you can use this provider to auth via Github App, and feed the token into the official Github Terraform provider:

Provider schema: https://github.com/patrickmarabeas/terraform-provider-github-v4/blob/master/github-v4/provider.go#L31

Access the token: https://github.com/patrickmarabeas/terraform-provider-github-v4/blob/master/github-v4/data_source_github_token.go

**Comment by jcudit** [comment]
Very interested in seeing this one ship.  Thanks for getting the discussion started!

**Comment by patrickmarabeas** [comment]
I'll start working on integrating the functionality: https://github.com/terraform-providers/terraform-provider-github/pull/613

**Comment by jspiro** [comment]
Is there a simple string I can generate by hand that encodes OAuth2 info in it that will drop-in work in the existing provider? The docs say
> token - (Optional) A GitHub OAuth / Personal Access Token. When not provided or made available via the GITHUB_TOKEN environment variable, the provider can only access resources available anonymously.
But I can't figure out what to give it. We're not OAuth2 knowledgable here, so any help or examples would be deeply appreciated. We're hitting our API limits constantly and need to switch over.

**Comment by alloveras** [comment]
Hey @patrickmarabeas,
It seems like [the link](https://github.com/terraform-providers/terraform-provider-github/pull/613) to your PR above is broken (perhaps you discarded it? 😃)

I started a new one from scratch [here](https://github.com/integrations/terraform-provider-github/pull/753). This message is just to make sure we aren't duplicating efforts 😉

**Comment by patrickmarabeas** [comment]
@alloveras yeah they moved the repo. I haven't done much more, so sweet as 👍
