### ISSUE TITLE
[feature request] add deployment environment resource

### ISSUE THREAD

**Issue by raboley** [integrations/terraform-provider-github#528]
I like the idea of using [github environments](https://docs.github.com/en/rest/reference/repos#deployments), and for my repositories that are only terraform it would be nice to have this be part of the github provider.

I would think this could be a resource that always ran last and could succeed for the environment if all terraform succeeded, and fail if it failed.

The reason I thought of terraform is for transient environments that when I delete them I would want to inactivate the environment that the transient branch belonged to. Any feedback on this idea would be appreciated! 

thanks!

**Comment by raboley** [comment]
I think I would need to create a middleware or something to get this to actually work, I added this issue
https://github.com/terraform-providers/terraform-provider-github/issues/528

to the tf provider for github because I think it would be interesting if terraform could manage it, but probably out of scope.

**Comment by raboley** [comment]
oops wrong issue

**Comment by jcudit** [comment]
This is a cool concept, thanks for starting the discussion!  🤔  what what example HCL look like?

**Comment by srgustafson8** [comment]
I just had a PR merged into the go-github module that provides the client for environments and environment secrets (google/go-github#1847). Not sure how long this will take to make it's way here but it may help

**Comment by nadenf** [comment]
For those interested I am currently working on this in conjunction wth #681.

**Comment by nadenf** [comment]
PR has been raised. Huge thank you to @srgustafson8 for adding support in go-github.

**Comment by kfcampbell** [comment]
Closing as #805 has been merged. Thanks @nadenf!
