### ISSUE TITLE
Plan output keeps changing randomly

### ISSUE THREAD

**Issue by brikis98** [integrations/terraform-provider-github#53]
### Terraform Version

Terraform v0.10.7

### Affected Resource(s)

- github_team_repository

### Terraform Configuration Files

The basic structure is a module that defines a team and the repos that team can access:

```hcl
resource "github_team" "team" {
  name = "${var.team_name}"
}

resource "github_team_repository" "repos" {
  count      = "${length(var.team_repo_names)}"
  team_id    = "${github_team.team.id}"
  repository = "${element(var.team_repo_names, count.index)}"
  permission = "pull"
}
```

We use this module to manage ~40 teams, each with access to 10 - 50 repos.

### Expected Behavior

Since all of the code has already been applied, I expect to see "no changes" when I run `terraform plan`.

### Actual Behavior

Every time I run `terraform plan`, I get a completely different output. Sometimes it says it wants to create team foo and give it access to a bunch of repos, sometimes team bar, sometimes several teams, sometimes "no changes", etc. 

### Steps to Reproduce

1. `terraform apply`
1. `terraform plan`

### Important Factoids

My best guess is that Terraform is making one API call for every (team, repo) pair, this results in way too many API calls, getting throttled, and Terraform is hiding the error message.

### References

- Perhaps #5?

**Comment by damacus** [comment]
If you're getting throttled. You should see a 500 error from the github api. 

You can mitigate against this behaviour by turning down the parallelism e.g. `-parallelism=5`.

I suspect there isn't much we can do about the API calls, as we're tied to how it's implemented in https://github.com/google/go-github/

It does sound like something hasn't been applied, or something is reverting an earlier apply.

**Comment by brikis98** [comment]
> You should see a 500 error from the github api.

Terraform doesn't show any errors. Where would this show up?

> I suspect there isn't much we can do about the API calls, as we're tied to how it's implemented in 

Terraform should show an error in these cases instead of swallowing the error and showing random diffs!

> It does sound like something hasn't been applied, or something is reverting an earlier apply.

No, everything has been applied, there are no diffs at all. Besides, running `plan` shows *different* diffs every time.

**Comment by majormoses** [comment]
Just to confirm if you are being rate limited they use a 403 like this:
```
* module.devops_repo_<ORG>-<REPO>.github_branch_protection.master: github_branch_protection.master: GET https://api.github.com/repos/<ORG>/<REPO>/branches/master/protection: 403 API rate limit of 5000 still exceeded until 2018-06-22 13:19:46 -0700 PDT, not making remote request. [rate reset in 7m12s]
```
