### ISSUE TITLE
not able get read sync groups

### ISSUE THREAD

**Issue by venky999** [integrations/terraform-provider-github#560]
I am trying to read AD groups that are synced from Azure but I am getting 502 error from data source but I can see the groups synced when I check from GitHub GUI

### Terraform Version
Terraform v0.13.0

### Affected Resource(s)
data "github organization team sync groups"

### Terraform Configuration Files
```hcl
data "github_organization_team_sync_groups" "all-groups" {}

resource "random_pet" "groups" {
  for_each = { for g in data.github_organization_team_sync_groups.all-groups.groups : g.group_name => g }
  keepers = {
    group_id          = each.value.group_id
    group_name        = each.value.group_name
    group_description = each.value.group_description
  }
}
```

### Panic Output
  |  
  |  Error: GET https://api.github.com/orgs/MYORG/team-sync/groups?page=X%27XXXXX0%27&per_page=100: 502 Server Error []
  |  
  | on data.tf line 11, in data "github_organization_team_sync_groups" "all-groups":
  | 11: data "github_organization_team_sync_groups" "all-groups" {}
  |  
  |  
  | make: *** [build] Error 1

### Expected Behavior
Should get list of synced AD groups
### Actual Behavior
Failed to read sync ad groups

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

**Comment by devopsrick** [comment]
We get frequent 500 errors using the github_organization_team_sync_groups data source.  Is anything being done on the backend to make this api call more reliable?

**Comment by devopsrick** [comment]
data github_organization_team_sync_groups resource has begun throwing 500s every refresh due to 429 results from the provider (Okta in my case).  Is there any way the provider can handle these errors more gracefully?
