### ISSUE TITLE
github_branch_protection not working on user repos

### ISSUE THREAD

**Issue by ahmadnassri** [integrations/terraform-provider-github#561]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

```
Terraform v0.13.4
+ provider registry.terraform.io/-/github v3.0.0
+ provider registry.terraform.io/hashicorp/github v3.0.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- github_branch_protection

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files

my tf file is a custom module and is functional when using with orgs, but when trying to operate the same config for a user account `owner = 'ahmadnassri'` it throws an error that branch protection is not supported for user accounts

### Debug Output

```
Error: This resource can only be used in the context of an organization, "ahmadnassri" is a user.

  on module/main.tf line 50, in resource "github_branch_protection" "branch_protection":
  50: resource "github_branch_protection" branch_protection {
```

### Expected Behavior

should allow branch protection to run on user repos

### Actual Behavior

branch protection does not run for user repos

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

**Comment by jcudit** [comment]
I believe this was fixed by https://github.com/terraform-providers/terraform-provider-github/issues/501.  @ahmadnassri can you confirm whether or not your use case is still affected?

**Comment by ahmadnassri** [comment]
yes this is now functional. closing
