### ISSUE TITLE
Create GitHub "releases" for new versions

### ISSUE THREAD

**Issue by MPV** [integrations/terraform-provider-github#563]
### Expected Behavior

A GitHub "release" having been created for new versions of this repo (not just a git tag).

### Actual Behavior

No "latest" release in this repo, i.e:
https://github.com/terraform-providers/terraform-provider-github/releases/latest

### Steps to reproduce

This doesn't work:

```shell
$ curl https://api.github.com/repos/terraform-providers/terraform-provider-github/releases/latest
{
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest/reference/repos#get-the-latest-release"
}
```

But this works for other providers, for example:

```shell
$ curl https://api.github.com/repos/terraform-providers/terraform-provider-google/releases/latest
{
  "message": "Moved Permanently",
  "url": "https://api.github.com/repositories/93446075/releases/latest",
  "documentation_url": "https://docs.github.com/v3/#http-redirects"
}
```

The web UI equivalent for comparison: 
https://github.com/terraform-providers/terraform-provider-github/releases/
vs
https://github.com/terraform-providers/terraform-provider-google/releases

>![Skärmavbild 2020-10-06 kl  13 49 10](https://user-images.githubusercontent.com/62675/95198049-d3a4f400-07da-11eb-8258-23b6c576aaea.png)

vs

>![Skärmavbild 2020-10-06 kl  13 47 40](https://user-images.githubusercontent.com/62675/95197872-8e80c200-07da-11eb-881f-512dde5ac808.png)

### Important Factoids

This will enable tools like [`tfupdate`](https://github.com/minamijoyo/tfupdate) (and the [tfupdate-github-action](https://github.com/daisaru11/tfupdate-github-actions)) to automatically create pull requests to users' repositories when a new version of this provider is released.

**Comment by jcudit** [comment]
Thanks for raising this.  I was unaware the release tooling was behaving this way.  Although things since `v2.9.0` have been fairly unstable, so this may have been helping others from friction with this provider 🙃 .

This one should get fixed up by the next bugfix release.

**Comment by jcudit** [comment]
The `v2.9.2` release has been added manually.  When we switch to the new release tooling behind the Provider Registry, new releases will automatically be published.  For now, I will document the release process to include this manual step.

Note that I've only published `v.2.9.2` as it seems like the most stable version that the community has chosen to run.  Happy to cut others if needed.

**Comment by MPV** [comment]
Looks like this has been solved, and we can close this now?

...given that this works now:
https://github.com/integrations/terraform-provider-github/releases/latest

**Comment by jcudit** [comment]
https://github.com/integrations/terraform-provider-github/releases looks up to date, however our old project repository at https://github.com/hashicorp/terraform-provider-github/releases will remain without releases as it is archived.

Closing for now but feel free to reopen with additional details!
