### ISSUE TITLE
Change to default branch in v3.1.0 breaks refresh of existing resources

### ISSUE THREAD

**Issue by onematchfox** [integrations/terraform-provider-github#564]
v3.1.0 included https://github.com/terraform-providers/terraform-provider-github/pull/562 which adjusted the default branch on resources from `master` to `main`. This breaks the refresh of existing state on resources like `github_repository_file` where the `branch` was not explicitly set as these are now being refreshed against the incorrect branch. May be more resources affected? 

### Expected Behavior
Breaking changes should not be introduced by minor version increments. Existing resources should not be replaced.

### Actual Behavior
Files provisioned by the `github_repository_file` resources are being destroyed and then fail to be recreated as the new "default" branch does not exist. 

``` 
# github_repository_file.file must be replaced
-/+ resource "github_repository_file" "file" {
      ~ branch              = "master" -> "main" # forces replacement
      .....
    }
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Provision a file using the `github_repository_file` with `branch` not set explicitly using v3.0.0
2. Upgrade to v3.1.0 and run `terraform plan again

### References
- https://github.com/terraform-providers/terraform-provider-github/pull/562

**Comment by onematchfox** [comment]
Also logged under #566

**Comment by doug-skinner** [comment]
@jcudit has there been any progress on this issue? It's currently affecting our usage of this resource at my company.

**Comment by kfcampbell** [comment]
Jeremy does not work at GitHub anymore unfortunately! I miss having him around. To the best of my knowledge, there's been no progress on this issue, though ideas and PRs are welcome!

**Comment by sbkg0002** [comment]
This also seems to happen when you rename the repository _name_.
