### ISSUE TITLE
[feature request] Supporting individual permissions management

### ISSUE THREAD

**Issue by mallyvai** [integrations/terraform-provider-github#573]
This is a feature request from some internal customers. We have access to the team_repository resource today, but a user_repository resource would also be helpful.

**Comment by jcudit** [comment]
This would be difficult given that user creation is not automated.  We may be able to automate creation of a GitHub App instead, but the resulting entity would not behave exactly like a user account.

The team sync feature may also help here if your customers are declared in some external directory already.
