### ISSUE TITLE
Error: Provider produced inconsistent final plan

### ISSUE THREAD

**Issue by kzw** [integrations/terraform-provider-github#576]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version

0.12.29

### Expected Behavior
terraform apply without any error

### Actual Behavior
```
Error: Provider produced inconsistent final plan

When expanding the plan for
module.xyz-abcd.github_branch_protection.this[0] to
include new values learned so far during apply, provider
"registry.terraform.io/-/github" produced an invalid new value for .branch:
was cty.StringVal("master"), but now cty.StringVal("develop").

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
no

**Comment by jcudit** [comment]
@kzw is this still happening for your use case? which release of the provider are you using?
