### ISSUE TITLE
Creating a secret fails as owner/org is not populated for public-key URL

### ISSUE THREAD

**Issue by alephnull** [integrations/terraform-provider-github#578]
### Terraform Version
```
% terraform version
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/github v3.1.0
```

### Affected Resource(s)
- `github_actions_secret`

### Terraform Configuration Files
```hcl
provider "github" {
  owner = "TykTechnologies"
}

resource "github_actions_secret" "sekret" {
  repository       = "tyk-analytics"
  secret_name      = "tf_secret"
  plaintext_value  = "supersekret"
}
```

### Debug Output
https://gist.github.com/alephnull/9a0d63903164a7b9187f2b4487c0c32a

### Expected Behavior
The secret is created.

### Actual Behavior
The `owner` parameter provided does not seem to populated in the URL for the public-key. Changing `owner` to `organization` has no effect. Looking [at the code](https://github.com/terraform-providers/terraform-provider-github/blob/b587cb0fae13aee6394811208cae4a9e9c1f00c6/github/resource_github_actions_secret.go#L134) it appears that only repo keys are supported.

### Steps to Reproduce
1. `terraform plan -out tf.plan && terraform apply tf.plan`

### Important Factoids
None at this time.

### References
None at this time.

**Comment by alephnull** [comment]
This particular problem does not exist on v2.9.2 with the following minimal manifest:
```
provider "github" {
  organization = "TykTechnologies"
}

resource "github_actions_secret" "ecr-keyid" {
  repository       = "tyk-analytics"
  secret_name      = "tf_secret"
  plaintext_value  = "supersekret"
}
```
However, it returns 404 for private repos: `Error: GET https://api.github.com/repos/TykTechnologies/tyk-analytics/actions/secrets/public-key: 404 Not Found []`

**Comment by thelucid** [comment]
Any news on this?

**Comment by jcudit** [comment]
Nothing planned as yet.  The project is getting some issue grooming at the moment, so a fix here will likely ship alongside related bugs.  My aim is to return here with more clear timelines.

**Comment by thelucid** [comment]
@jcudit Do you happen to know when the bug was introduced? I had this working a month or so ago, but now can't write a secret from within a GitHub action. I imagine anyone using the `github_actions_secret` resource will be hitting this issue.

I'm happy to install an older release for the time being — until this is fixed — but not sure exactly how I'll go about it, or what release to go for. Happy to help out with a PR if it moves things along, but my Go knowledge is minimal.

**Comment by jcudit** [comment]
🤔  we haven't shipped any changes to that resource since it was released.

I see the debug log has the following error:

> [1m[31mError: [0m[0m[1mGET https://api.github.com/repos//tyk-analytics/actions/secrets/public-key: 404 Not Found [][0m

That path looks incomplete as it is missing an `owner` right before the `/tyk-analytics` repository.  Can you try by updating the `repository` field to include the `owner` prefix?

**Comment by thelucid** [comment]
I added an organization which got around the path issue. But we still receive a 403 for `https://api.github.com/repos/our-org/our-repo/actions/secrets/public-key`.

It seems as though maybe Github have changes the access that the `${{secrets.GITHUB_TOKEN}} receives or something?

**Comment by Drache93** [comment]
Eek, just ran into this old issue. Tried setting `owner` and/or `organization` same result, the missing value in the path like`/repos//tyk-analytics`. With owner prefix in repo you just get `/repos//owner/tyk-analytics`. Tried locally with vars, env and through GitHub Action.

**Comment by jcudit** [comment]
Any chance we can get the provider version and some sample HCL that will help us reproduce this issue?

**Comment by out-of-mana** [comment]
I've run into this issue again. I solved it once previously, this time it popped up after I did a `terraform init --upgrade` after making changes to the module that I use github secrets in.

 I don't rememeber what the solution was (sorry this isn't helpful) but I feel like it was something about the difference between environment variables and terraform variables. I seem to remember there was an upgrade for `integrations/github` that played a role.
Not super helpful but this 

This time, I updated everything again just to be sure and I'm still seeing the issue. Terraform 1.11.0, upgraded to integrations/github 4.19.0.

My providers.tf looks like:

`
terraform {
  backend "remote" {
    organization = "my-organization"
    workspaces {
      name = "my-workspace"
    }
  }
  required_providers {
    github = {
      source  = "integrations/github"
      version = "4.11.0"
    }
  }
}
provider "github" {
  owner = var.github_owner
  token = var.github_token
}
`

Using static values in providers.tf doesn't make a difference. Pulling my hair out trying to remember how I sorted this out last time..

**Comment by out-of-mana** [comment]
REPRODUCED: I've managed to identify the problem for me. The difference seems to be if I'm passing github_token via *environmental* variable or terraform variable. This was the same issue in the past now that I'm seeing it again.

terraform github_owner variable in providers.tf is _ignored_ but once I set TF_GITHUB_OWNER, it started working. I'm not much of a go guy but that'd be where I would look to fix it. It's only pulling the owner variable from the environment, not if you pass it in via terraform variable.

**Comment by jcudit** [comment]
Ah! This makes more sense now and seems related to a large source of friction we're working to remove in v5.

🙇🏾 for following through with this extra information.  My hope is this type of confusion is removed once v5 is released this quarter.

**Comment by theartusz** [comment]
I can confirm that workaround suggested by @out-of-mana worked.

I experianced same error with `404 not found` and after setting env variables for `TF_VARS_GITHUB_OWNER` the `terraform apply` went through and created secrets.

Thanks! 🙂

**Comment by mohalsherif** [comment]
I just had the same issue , but for me i was defining the `required_providers` block and once in the `provider` block. I was only setting the token in one of them and they were overriding each other. I removed one of them and it worked

**Comment by umfaccess** [comment]
Removing `token` and `owner` from `provider "github"` and exporting them as `GITHUB_TOKEN` and `GITHUB_OWNER` environment variables did the trick.
