### ISSUE TITLE
Refresh Provider Documentation Ahead Of Transfer

### ISSUE THREAD

**Issue by jcudit** [integrations/terraform-provider-github#585]
To better integrate with the new Provider Registry (🎉 ), this project will be transferred to the `github` organization.  Some documentation needs updating to unblock this transfer:

- [x] Add a `CONTRIBUTING.md`
- [x] Add a `CODE_OF_CONDUCT.md`
- [x] Add a `SECURITY.md`
- [x] Add a compatible `LICENSE`
- [x] Update `README` with common conventions
  - [x] Document support expectations
- [ ] Document release process

**Comment by jcudit** [comment]
Discussed the license briefly with @paultyng and we'll be switching to MIT to avoid friction with the transfer.  The license change will be part of the next major release in case this is considered "breaking" for consumers of this project.

**Comment by kfcampbell** [comment]
Our release process is documented in [RELEASE.md](https://github.com/integrations/terraform-provider-github/blob/main/RELEASE.md).
