### ISSUE TITLE
Documentation is out of date / inconsistent between Registry Docs + Terraform.io Docs

### ISSUE THREAD

**Issue by Gowiem** [integrations/terraform-provider-github#595]
### Terraform Version
N/A

### Affected Resource(s)
- https://www.terraform.io/docs/providers/github/index.html
- https://registry.terraform.io/providers/hashicorp/github/latest/docs

### Terraform Configuration Files
N/A

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
These Docs should be the same for the released version, but they're not which leads to a lot of confusion when working through this provider. 

### Actual Behavior
The docs are out of date. See screenshots.

terraform.io docs mention deprecated `branch` input for `github_branch_protection`.
![image](https://user-images.githubusercontent.com/1392040/98693630-c2955880-232d-11eb-9a77-c0e08d587f75.png)

registry docs mention correct `pattern` input for `github_branch_protection`.
![image](https://user-images.githubusercontent.com/1392040/98693796-f6707e00-232d-11eb-872b-8ead17a2ee53.png)

### Steps to Reproduce
View both docs sites linked above and compare `github_branch_protection` for example. You will see they're different.

### Important Factoids
- The old docs are still showing up regularly via Google search.
- This is probably already known about, but as a consumer... this is driving me nuts so I wanted to be 100% that you folks were aware. 

### References
N/A

**Comment by czeeb** [comment]
It looks like the registry is updated.  I've seen it take a few hours after a release to update the documentation on terraform.io.

**Comment by Gowiem** [comment]
@czeeb I've been seeing this disconnect between registry + terraform.io over the past week, so I believe it's a more long running problem unfortunately.

**Comment by jcudit** [comment]
Checked with Hashicorp about this and they've confirmed there is a temporary hack in place that is keeping the two documentation sites in place.  Once this repository migrates away from the `terraform-providers` org and to the Provider Registry, the old docs will go away.

Apologies for this added confusion, definitely drives me nuts as well as docs are an important part of consuming software.  This is tracked and will follow up once the repository transfer completes.  Most likely by end of year.

**Comment by Gowiem** [comment]
@jcudit Ah thanks for the info! Glad ya'll are on top of it 💯 👍

**Comment by ChristophShyper** [comment]
Also, for example in https://www.terraform.io/docs/providers/github/r/repository.html it says about default branch being `master`, while its `main` now. And changing this value doesn't make any effect, but that's a different issue.

**Comment by shogo82148** [comment]
Any progress?

https://github.com/terraform-providers/terraform-provider-github/issues/595#issuecomment-726364251

> Apologies for this added confusion, definitely drives me nuts as well as docs are an important part of consuming software. This is tracked and will follow up once the repository transfer completes. Most likely by end of year.

The new year of 2021 has come.

**Comment by jcudit** [comment]
We've co-ordinated to transfer this repository out of the `terraform-providers` organization.  This has unblocked efforts to fix documentation drift.  New releases via the Terraform Registry automation that recently merged should now be causing documentation to be in sync.  I have this queued for a more in-depth follow up once we've finalized things in the Terraform Registry.

Thanks everyone for being patient on this one, definitely a point of confusion for the community.

**Comment by colltoaction** [comment]
Looking good https://registry.terraform.io/providers/integrations/github/latest/docs

**Comment by jcudit** [comment]
I believe the documentation drift issue has been resolved now that we've migrated the project out of the previous organization and hooked into the Terraform Registry from our current repository.  Our release process is now aligned with best practices and documentation should be in sync because of this.  I think this can be closed?

**Comment by kfcampbell** [comment]
Closing this as @jcudit mentioned earlier.
