### ISSUE TITLE
Label name has a colon 

### ISSUE THREAD

**Issue by jaydeland** [integrations/terraform-provider-github#596]
Import is failing when the name value has a colon in the string - "1: PM Review"

https://github.com/terraform-providers/terraform-provider-github/blob/376ff1b00c02378a81331487a2fca29930670752/github/util.go#L50

**Comment by jaydeland** [comment]
You can work around this by using URL encoding in the ID:
terraform import github_issue_label.PMReview "REPO:1%3A%20PM%20Review"

**Comment by kfcampbell** [comment]
I believe this is still a valid issue. At a minimum, we should document this behavior.
