### ISSUE TITLE
github_branch_protection still slow with version 4.0.0

### ISSUE THREAD

**Issue by SanderKnape** [integrations/terraform-provider-github#606]
As was reported earlier with version 3.1.0, the performance of the `github_branch_protection` resource has slowed down significantly now that this resource is using v4 of the GitHub API. It makes using the github provider unusable when working with dozens of repositories.

Is there a way to keep using the v3 version of the API somehow?

**Comment by jcudit** [comment]
There was some discussion around a new resource pinned at the v3 / REST implementation over [here](https://github.com/terraform-providers/terraform-provider-github/issues/566#issuecomment-722004719). Still unclear on what an acceptable migration path would be though if we went ahead with this approach. Any ideas?

🤔 there is also the optimization approach in case anyone can recommend ways to improve the GraphQL implementation.

**Comment by SanderKnape** [comment]
Hmm, I understand the problem. I'm not sure what the best approach would be. Adding the `github_branch_protection_v3` resource sounds like a reasonable option. As long as I can use future versions of this provider with the branch protection performance of API v3, I don't have a strong preference for a specific implementation. I can't comment on which implementation would be the easiest to maintain moving forward.

**Comment by lijok** [comment]
Reason for its slowness: https://github.com/integrations/terraform-provider-github/issues/849

**Comment by akloss-cibo** [comment]
Oof... this is still super annoying.  Like really.  A lot.

**Comment by kfcampbell** [comment]
`github_branch_protection_v3` still uses the REST API, which may help. I'd be very receptive to thoughts on how to improve the experience using the GraphQL API.

**Comment by akloss-cibo** [comment]
It's still slow.  We pretty heavily use/abuse `-target` to avoid planning around github things because of how much longer it takes to run the plans.
