### ISSUE TITLE
Feature: Support for granting access to security alerts

### ISSUE THREAD

**Issue by wimnat** [integrations/terraform-provider-github#612]
We would like to manage access for repository security alerts.

This feature is documented here https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/managing-security-and-analysis-settings-for-your-repository

A request for this feature was mentioned in the comments [here](https://github.com/terraform-providers/terraform-provider-github/issues/238) but never got implemented.

**Comment by shogo82148** [comment]
The issue link is now dead.
New URL is https://github.com/integrations/terraform-provider-github/issues/238

**Comment by EQemccudden** [comment]
Am I correct to say (based on #238) that https://github.com/integrations/terraform-provider-github/pull/444 only handles the boolean to enable vulnerability_alerts but not the team based access to those alerts?

**Comment by nickfloyd** [comment]
Hey @bsuv Thanks for reaching out.  I've labeled this as "up for grabs" to encourage anyone who might need this functionality and has the time to contribute can feel free to do so. ❤

**Comment by kfcampbell** [comment]
I'm not sure if this has API support to be actionable in the first place. The closest thing I can find is [here](https://docs.github.com/en/rest/dependabot/alerts?apiVersion=2022-11-28#update-a-dependabot-alert), which requires granting access first via the UI.

**Comment by nnellanspdl** [comment]
@nickfloyd Any chance this one could be resurrected?  It would be a nice feature to have and has a bunch of likes.

**Comment by deiga** [comment]
@nnellanspdl Have you been able to find an API for this functionality?

**Comment by nnellanspdl** [comment]
I just did some searching, and no, I wasn't able to find anything.

Based on [this discussion](https://github.com/orgs/community/discussions/14021), GitHub was planning to remove this feature, in favor of custom repository roles.  However, its still around for now, but I doubt we'll be getting an API anytime soon.

**Comment by hussein-mimi** [comment]
reopen please

**Comment by hussein-mimi** [comment]
i opened new issue for same https://github.com/integrations/terraform-provider-github/issues/3312
