### ISSUE TITLE
GitHub CLI authentication method

### ISSUE THREAD

**Issue by phillebaba** [integrations/terraform-provider-github#632]
The Github CLI is becoming more and more popular and has solved authentication for users towards the GitHub API. A nice feature to have would be for the provider to as a last resort fallback on using the oauth token managed by the CLI as an authentication method. This makes local development a lot easier and removes the need for users to create and store personal access tokens. This authentication method is similar to most other providers who also have CLIs that implement authentication.

I create an issue in the GitHub CLI project to expose the needed packages to read the config file containing the oauth token, but they are unwilling to expose it as it would introduce requirements of providing a stable API. It does not seem like they will budge on this opinion as they stated that the project is meant to be used by the CLI rather than a Go library that could be imported by other projects.
https://github.com/cli/cli/pull/2635

The other option which is not as nice would be to shell out and call the GitHub CLI to have it get the token for the provider. It introduces a requirement that the end user has the CLI installed on their computer but it could easily be disabled if it is not present.

**Comment by nfx** [comment]
@jcudit i wonder what's blocking it?... having CLI auth would simplify some of our pipelines tremendously

**Comment by nfx** [comment]
@phillebaba by the way, can you just call `gh auth status -h github.com --show-token` as subprocess? `azurerm` does that and it's fine.
