### ISSUE TITLE
can not upgrade v3.1.0 above

### ISSUE THREAD

**Issue by yuzujoe** [integrations/terraform-provider-github#634]
When I try to upgrade the Branch protection resources to 3.1.0 or higher, the plan fails with an error.

### Terraform Version

```
$ terraform version
Terraform v0.13.5
provider registry.terraform.io/hashicorp/github v3.1.0
```

### Affected Resource(s)

```
"github_branch_protection"
```

### Terraform Configuration Files
```hcl
resource "github_branch_protection" "server" {
  for_each = toset(local.server)

  repository     = each.value
  branch         = "master"
  enforce_admins = "true"

  required_status_checks {
    strict = "true"
  }
}
```

### Debug Output
```
terraform plan

Error: Missing required argument

  on server.tf line 1, in resource "github_branch_protection" "server":
   1: resource "github_branch_protection" "server" {

The argument "repository_id" is required, but no definition was found.


Error: Missing required argument

  on server.tf line 1, in resource "github_branch_protection" "server":
   1: resource "github_branch_protection" "server" {

The argument "pattern" is required, but no definition was found.


Error: Unsupported argument

  on server.tf line 4, in resource "github_branch_protection" "server":
   4:   repository     = each.value

An argument named "repository" is not expected here.


Error: Unsupported argument

  on server.tf line 5, in resource "github_branch_protection" "server":
   5:   branch         = "master"

```
### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
- [ ] Exactly what the plan goes through.

### Actual Behavior
- [ ] error occurred

### Important Factoids
- [ ] It worked fine up to 3.0.0.

### References
- https://github.com/terraform-providers/terraform-provider-github/issues/621

**Comment by jcudit** [comment]
This is likely due to breaking changes introduced in `v3.1.0` and later rebranded as `v4.0.0`.  See [here](https://github.com/terraform-providers/terraform-provider-github/blob/master/CHANGELOG.md#400-november-10-2020) for more details on the breaking changes.

**Comment by yuzujoe** [comment]
@jcudit 
Would this be a forceful rewrite of the state?
a few changes have come in.

**Comment by jcudit** [comment]
@yuzujoe I have not tested this upgrade path but can get this tracked to test out in the future.  🤔  you may have success with the following sequence:
- [move](https://www.terraform.io/docs/commands/state/mv.html) all `github_branch_protection` resources to a backup state file
- upgrade the provider and re-write the `github_branch_protection` blocks with the latest arguments
- try [importing](https://www.terraform.io/docs/providers/github/r/branch_protection.html#import) the moved resources
- if ☝🏾 failed, downgrade the provider and move the backup resources back into the original state file

If the upgrade still fails, let us know.  This is something that will have to be ironed out when https://github.com/terraform-providers/terraform-provider-github/pull/642 ships as well.

**Comment by yuzujoe** [comment]
@jcudit Hi

I tried upgrade github provider.
I was able to get the plan through, but there are some problems such as very slow plan speed.

Also, why did they change from repository to repository_id?

I'm not sure what the benefit of this is.

**Comment by jcudit** [comment]
The change to `repository_id` is documented [here](https://github.com/integrations/terraform-provider-github/blob/master/CHANGELOG.md#310-october-12-2020), but in short it was made to support switching to GraphQL-based queries.

 It sounds like you may have better results with the new `github_branch_protection_v3` resource instead of `github_branch_protection`.  See [here](https://github.com/integrations/terraform-provider-github/blob/master/CHANGELOG.md#430-january-14-2021) for further details.
