### ISSUE TITLE
Feature Request: Support automerge

### ISSUE THREAD

**Issue by mallyvai** [integrations/terraform-provider-github#649]
Github now supports auto-merge as a repository setting. Would be great to support it!

https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/automatically-merging-a-pull-request

**Comment by kpfleming** [comment]
As is often the case, this new GitHub feature is not exposed via the API (neither REST nor GraphQL). Once it is available in one of the APIs, then the Go client library for that API will need to have the new setting added... and after that, this provider can be updated. It's unfortunately a long cycle.

**Comment by entropitor** [comment]
The API is actually already setting the value to false when you call it 😭 Is it still not there, or just not documented?

(If you have a repository resource and you change anything else, and the toggle was true, it will be false after apply)

**Comment by emmekappa** [comment]
It's now exposed through a GraphQL mutation

https://github.community/t/enabling-auto-merge-on-a-pr-using-the-api/150797/5

**Comment by majormoses** [comment]
The next step is getting an issue and merged functionality into https://github.com/google/go-github so we can get ready to consume it.

**Comment by jcudit** [comment]
🤔 does `go-github` leverage the GraphQL API?  If not, we'd be able to use our GraphQL client to toggle this configuration directly.

**Comment by majormoses** [comment]
Oh I completely forgot we dont rely as heavily on that library anymore.

**Comment by RTodorov** [comment]
@jcudit apparently there is a lib for the graphql API already added to the project: github.com/shurcooL/githubv4

I noticed that the graphql lib (v4) is not used in the repository logic just yet. If one wants to suggest a PR for adding the auto-merge using v4, would that be ok?

**Comment by s4nji** [comment]
> It's now exposed through a GraphQL mutation
> 
> Github thread: https://github.community/t/enabling-auto-merge-on-a-pr-using-the-api/150797/5
> 
> GraphQL doc reference: https://docs.github.com/en/graphql/reference/mutations#enablepullrequestautomerge

This seems to just enable/disable automerge on specific PR; for this to work you have to [allow automerge at repository level](https://docs.github.com/en/github/administering-a-repository/managing-auto-merge-for-pull-requests-in-your-repository), and after a brief look at the graphql explorer, it does not seem to be exposed via the v4 API yet.

**Comment by jcudit** [comment]
@RTodorov yes! PRs are welcome in general.  However, as pointed out above, the v4 mutation does not apply to the repository level.  We will need to wait on better support.

**Comment by mungojam** [comment]
It's now available on the [GitHub REST API](https://github.blog/changelog/2021-08-17-maintainers-can-now-manage-the-availability-of-auto-merge-in-a-repository/) and the [GraphQL one](https://docs.github.com/en/graphql/reference/objects#repository)

**Comment by Richard-de-Vries** [comment]
Hello,
I'd like to have this functionality as well so i'm opening an issue with the go-github (and possibly implementing it as well). I hope this is okay :smile:

**Comment by Richard-de-Vries** [comment]
Okay, i've added the option to the library. Now in the upcoming release we can make use of this property.

**Comment by jcudit** [comment]
Lets focus on getting v39 added to the project first.  Aiming to land in the next release.

**Comment by usmonster** [comment]
In case it wasn't seen, #923 is waiting to be reviewed & hopefully merged. 👀

**Comment by servo1x** [comment]
This doesnt seem to be working for us, `allow_auto_merge` keeps getting changed back to `false`.
