### ISSUE TITLE
Branch protection documentation outdated

### ISSUE THREAD

**Issue by GaboFDC** [integrations/terraform-provider-github#650]
The github_branch_protection docs: https://github.com/terraform-providers/terraform-provider-github/blob/master/website/docs/r/branch_protection.html.markdown are not in sync with what is deployed at https://www.terraform.io/docs/providers/github/r/branch_protection.html

The deployed content is outdated and doesn't reflect the actual content in the source.

**Comment by justinmacleod** [comment]
Same for the new `github_branch_default` resource. That doesn't exist on the TF docs site but if you use the old method it throws a deprecation error.

**Comment by shogo82148** [comment]
there is duplicated issue https://github.com/terraform-providers/terraform-provider-github/issues/595
see it for details

**Comment by rngtng** [comment]
@shogo82148 above link reditrects to https://github.com/hashicorp/terraform-provider-github/issues/595 which is a 404 for me ;( guess the issues on the old repo got deactivated?

**Comment by shogo82148** [comment]
@rngtng oh, sorry. here you are https://github.com/integrations/terraform-provider-github/issues/595

**Comment by rngtng** [comment]
@shogo82148 thx. looks like the GH redirect is broken.... 

this worked for me: https://registry.terraform.io/providers/integrations/github/latest/docs

**Comment by jcudit** [comment]
I believe the documentation drift issue has been resolved now that we've migrated the project out of the previous organization and hooked into the Terraform Registry from our current repository.  Our release process is now aligned with best practices and documentation should be in sync because of this.  I think this can be closed?

**Comment by rngtng** [comment]
@jcudit yes. can confirm
