### ISSUE TITLE
Incompatibility from 4.1.0 to 4.2.0

### ISSUE THREAD

**Issue by colltoaction** [integrations/terraform-provider-github#651]
I get `Field 'allowsDeletions' doesn't exist on type 'BranchProtectionRule'`

1. patch
    ```diff
     terraform {
       required_providers {
         github = {
    -      version = "4.1.0"
    +      source = "integrations/github"
    +      version = "4.2.0"
         }
       }
     }
    ```
1. `terraform init`
1. `terraform plan`
1. output:
    > Error: Field 'allowsDeletions' doesn't exist on type 'BranchProtectionRule'

I'm glad to give more details if needed.

**Comment by docwhat** [comment]
I couldn't even get this far. See #652

**Comment by frbayart** [comment]
@colltoaction you have this error with only provider defined or do you have something on TF plan?

**Comment by colltoaction** [comment]
I am new to terraform so please excuse me if I'm not clear. I just use provider for a few automation tasks around a GHE org. I didn't know about `state replace-provider` so I assume I'm missing a few steps in my upgrade path.

By the way, I'm just upgrading to be up-to-date, and I'm happy to help iron out the project details while doing it.

**Comment by jcudit** [comment]
> happy to help iron out the project details while doing it.

❤️ 

---

As documented over [here](https://github.com/integrations/terraform-provider-github/issues/652#issuecomment-756921841), can we try running through the `state replace-provider` steps?  Post any friction you have here and I'll be able to point others to the fix via the CHANGELOG / README.

**Comment by colltoaction** [comment]
still seeing this error log once per `branch_protection`:

```
Error: Field 'allowsDeletions' doesn't exist on type 'BranchProtectionRule'
```

the protection rules look like:

```tf
resource "github_branch_protection" "bla" {
  repository_id  = "bla"
  pattern        = "main"
  enforce_admins = true

  required_status_checks {
    strict   = true
    contexts = ["bla"]
  }

  required_pull_request_reviews {
    require_code_owner_reviews      = true
    required_approving_review_count = 1
  }
}
```

**Comment by Polygens** [comment]
@colltoaction Are you using GitHub Enterprise? We are experiencing the same issue on our instances. It seems `allowsDeletions` was only added since GitHub Enterprise V3.0 which is still in release candidate.

**Comment by colltoaction** [comment]
Yes

> @colltoaction Are you using GitHub Enterprise?

**Comment by weijing24** [comment]
Any update？ I also have the same problem. I use github enterprise v.2.22.3. When I upgrade `version = "4.1.0" ` to `version = "4.2.0"`, I met the same error. 
> Error: Field 'allowsDeletions' doesn't exist on type 'BranchProtectionRule'

**Comment by docwhat** [comment]
The `allowsDeletions` is broken on 2.21.14 as well, which makes sense if it isn't added until v3.0

Can there be a check for the GitHub Enterprise version to prevent this breaking things?
