### ISSUE TITLE
Background on hashicorp/github to integrations/github transfer

### ISSUE THREAD

**Issue by ap0phi5** [integrations/terraform-provider-github#656]
Anyway we could put even a one-liner in the README on what happened?

Maybe we missed a blog post or something? On the outset, it sounds like a good thing for the TF provider to come under Github's umbrella, but this took us a bit by surprise!

TF gives a great approach to managing GitHub and it would be good to understand if there are any changes without us having to speculate. e.g. is GitHub now providing support for this?

**Comment by jcudit** [comment]
I've documented the transfer as a breaking change tied to v4.2.0 and have linked to some discussion around how to consume this change.

Happy to field questions here to provide more visibility to everyone around this transfer.  From a maintainership perspective, this transfer unblocked releasing using the Terraform Registry.  Other providers have also been moving away from the `terraform-providers` organization, which has been recommended by organizers of the Terraform ecosystem.  Look out for other providers to follow suit in time.

Apologies for the surprise!  I realize that this causes interrupt work for consumers of this project, but the benefit is we now have a faster release process and can recover quicker from breaking changes like this.

We'll continue to be community-supported, but are now plugged into the ecosystem from the angle desired by its organizers.  I'll continue to represent this community and seek out others that can help maintain a quality Terraform interface to GitHub resources.  But to be clear, GitHub is not providing support for this project.

**Comment by minamijoyo** [comment]
Hi, @jcudit Thank you for your explanation.

I noticed that https://github.com/terraform-providers/terraform-provider-github is now redirected to https://github.com/hashicorp/terraform-provider-github, not https://github.com/integrations/terraform-provider-github

```
$ curl -sI https://github.com/terraform-providers/terraform-provider-github | grep location
location: https://github.com/hashicorp/terraform-provider-github
```

This breaks many direct links. Is it possible to fix the redirect location?

**Comment by jcudit** [comment]
Yes, that is annoying consequence of the transfer. I've raised an issue with the team to investigate already, but will 🤔 what else could be done while we wait.

**Comment by minamijoyo** [comment]
Thanks!
