### ISSUE TITLE
Bug: vulnerability_alerts in archived repos

### ISSUE THREAD

**Issue by jspiro** [integrations/terraform-provider-github#665]
I am finding that vulnerability_alerts must be set to false when a repo is archived, regardless of the prior state of it, otherwise setting it to false has no effect, and the refresh always pulls in the wrong state (where it has been disabled by github), so it always shows up as needing to be set to false.

I unarchived the repo, did a refresh, and while TF wanted to archive it again, v_a was read as `true`. When archived, it read it as `false`.

I solved it in my module with `vulnerability_alerts = var.archived ? false : true`.

### Terraform Version
0.14.4

### Affected Resource(s)
- github_repository

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
This repo has `archived=false` set:
```hcl
  # module.repo.github_repository.this will be updated in-place
  ~ resource "github_repository" "this" {
        id                     = "Repo"
        name                   = "Repo"
      ~ vulnerability_alerts   = true -> false
        # (25 unchanged attributes hidden)
    }
```

### Expected Behavior
My suggestion is that either this value is ignored in plans against archived resources, or an error is given to the user.

### Actual Behavior
No error, plans that never resolve no matter how many times applied.

**Comment by majormoses** [comment]
This is also true if the repository is not initialized.

I had a successfully applied plan:
```
Apply complete! Resources: 8 added, 0 changed, 0 destroyed.
Releasing state lock. This may take a few moments...

```
However when I further plana/apply without any further code change I get a delta on this property. Here is the follow up plan:
```hcl
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.infra_security-repo-test-branches-fresh.github_repository.repo will be updated in-place
  ~ resource "github_repository" "repo" {
        allow_merge_commit     = false
        allow_rebase_merge     = true
        allow_squash_merge     = true
        archived               = false
        auto_init              = false
        default_branch         = "master"
        delete_branch_on_merge = true
        description            = "A repo for testing creating of branches in terraform workflows"
        etag                   = "W/\"58fa8a5886b295cdc05cb5dcb3ef337e44431b6bac1ae0f25911ed19a1bb87db\""
        full_name              = "REDACTED/test-branches-terraform-workflow-fresh"
        git_clone_url          = "git://github.com/REDACTED/test-branches-terraform-workflow-fresh.git"
        has_downloads          = true
        has_issues             = true
        has_projects           = false
        has_wiki               = false
        html_url               = "https://github.com/REDACTED/test-branches-terraform-workflow-fresh"
        http_clone_url         = "https://github.com/REDACTED/test-branches-terraform-workflow-fresh.git"
        id                     = "test-branches-terraform-workflow-fresh"
        is_template            = false
        name                   = "test-branches-terraform-workflow-fresh"
        node_id                = "REDACTED="
        private                = true
        repo_id                = REDACTED
        ssh_clone_url          = "git@github.com:REDACTED/test-branches-terraform-workflow-fresh.git"
        svn_url                = "https://github.com/REDACTED/test-branches-terraform-workflow-fresh"
        topics                 = [
            "github",
            "terraform",
        ]
        visibility             = "private"
      ~ vulnerability_alerts   = false -> true
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```
Which results in the following error
```hcl
$ aws-vault exec REDACTED -- terraform apply current.plan
module.infra_security-repo-test-branches-fresh.github_repository.repo: Modifying... [id=test-branches-terraform-workflow-fresh]

Error: PATCH https://api.github.com/repos/REDACTED/test-branches-terraform-workflow-fresh: 422 Validation Failed [{Resource:Repository Field:default_branch Code:invalid Message:Cannot update default branch for an empty repository. Please init the repository and push first.}]

  on ../../../../../modules/repository/repo.tf line 1, in resource "github_repository" "repo":
   1: resource "github_repository" "repo" {


Releasing state lock. This may take a few moments...

```

**Comment by czerasz** [comment]
@majormoses `auto_init = true` might help

**Comment by majormoses** [comment]
@czerasz yes we could do that but IMO its the responsibility of the provider to handle this properly. I already have this in my module:
```terraform
resource "github_repository" "this" {
  name                   = var.repo_name
  ...
  vulnerability_alerts   = var.repo_archived == false ? var.enable_vulnerability_alerts : false
```

I think having to have a bunch of logic for a bunch of specific properties is not ideal:
```terraform
resource "github_repository" "this" {
  name                   = var.repo_name
  ...
  vulnerability_alerts   = (var.repo_archived == false && var.auto_init == false) ? var.enable_vulnerability_alerts : false
  delete_branch_on_merge = (var.repo_archived == false && var.auto_init == false) ? var.delete_branch_on_merge : false
```

I suppose I could wrap these as a single local to at least save the additional lookups but IMO its dancing around rather than addressing the issue. To me spinning up a repository should not require a whack-a-mole style testing with every single option to be able to create a repository. If we know something is invalid lets do the right thing rather than expect the user has deep knowledge of a particular set of APIs especially when you consider that the behavior can simply change on you from an API perspective.

**Comment by jspiro** [comment]
@majormoses Agree agree. These are fundamentals of the provider. The provider could issue an error OR warning if your setting conflicts with the required/constrained value (as a result of archival). But the provider shouldn't let you get in a bad state, it knows best, it's the provider, and this is declarative.

**Comment by kfcampbell** [comment]
I believe this is still a valid issue; please correct me if I'm wrong.
