### ISSUE TITLE
Help doing local development of this provider

### ISSUE THREAD

**Issue by jspiro** [integrations/terraform-provider-github#677]
For those of us trying to contribute to this provider, could someone provide more details to https://github.com/integrations/terraform-provider-github/blob/master/CONTRIBUTING.md on how to actually USE the provider locally after building it?

E.g. suggestions on where to clone/build it, what to symlink, debugging tips, how to change required providers to refer to an unreleased local (or remote) branch/build. The new lockfiles have stymied my attempts to install the binary locally by overwriting or by bumping the version locally.

I spent hours trying to figure out how to run this locally, and I can't find any useful hashi docs. Thanks in advance!

**Comment by jcudit** [comment]
Raised ☝🏾 to get our contributing docs in a better place.  This documents the flow I use given my access rights to the project, but may not be suitable for other contributors.  Let me know if this helps and where these steps fall over if someone is working from a fork.

**Comment by jspiro** [comment]
This has been resolved!
