### ISSUE TITLE
v4.3.1 breaks owner provider configuration

### ISSUE THREAD

**Issue by sh0shin** [integrations/terraform-provider-github#678]
### Terraform Version
```
Terraform v0.14.5
+ provider registry.terraform.io/integrations/github v4.3.1
```

### Affected Resource(s)
 - github_repository
 - all

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    github = {
      source = "integrations/github"
    }
  }
}

provider "github" {
  owner = "sh0shin"
  # token is provided via GITHUB_TOKEN environment variable
}

resource "github_repository" "sick" {
  name        = "sick"
  description = "My sick git repository"
  visibility  = "public"
}
```

### Debug Output
https://gist.github.com/sh0shin/8faca30a9f162939fa50fcc097868112

### Expected Behavior
Repository `sick` should be created.

### Actual Behavior
```
Error: GET https://api.github.com/orgs/sh0shin: 404 Not Found []

  on main.tf line 11, in provider "github":
  11: provider "github" {
```

### Steps to Reproduce
 * `terraform apply`

**Comment by sh0shin** [comment]
It looks like the problem is in the config.go: [L100-L124](https://github.com/integrations/terraform-provider-github/blob/dec1456e4c1c612fec1ffee8335f89d6015a9a53/github/config.go#L100-L124) and/or [ L200-L220](https://github.com/integrations/terraform-provider-github/blob/dec1456e4c1c612fec1ffee8335f89d6015a9a53/github/config.go#L200-L220)

The owner is check as an organization and an error is returned: [L118-L120](https://github.com/integrations/terraform-provider-github/blob/dec1456e4c1c612fec1ffee8335f89d6015a9a53/github/config.go#L118-L120) and/or [L215-L217](https://github.com/integrations/terraform-provider-github/blob/dec1456e4c1c612fec1ffee8335f89d6015a9a53/github/config.go#L215-L217)

**Comment by sorensonpragmatics** [comment]
Hitting same issue.
