### ISSUE TITLE
github_actions_secret: support environment secrets

### ISSUE THREAD

**Issue by hoxu** [integrations/terraform-provider-github#681]
`github_actions_secret` does not seem to support [GitHub Actions' Environment Secrets](https://docs.github.com/en/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-an-environment). It would be very useful to have that support.

### Affected Resource(s)
- github_actions_secret

**Comment by dudicoco** [comment]
Are there any plans on implementing this? Standard actions secrets are not secure, the only way to secure secrets is by using environment secrets.

**Comment by crmitchelmore** [comment]
Would love to see this

**Comment by stevengonsalvez** [comment]
+1

**Comment by marcinwyszynski** [comment]
I need it. I'll take this.

**Comment by srgustafson8** [comment]
Thank you @marcinwyszynski - happy to contribute if I can. I think this links into #528, as my use case would be to allow  squads to define environments and environment secrets programatically to protect CD keys.

**Comment by marcinwyszynski** [comment]
I think @srgustafson8 the main difficulty here is that this resource depends on the environment resource which is still missing, and the API of that does not look terribly stable.

**Comment by marcinwyszynski** [comment]
My concept for now would be to just add a "stub" resource for the environment, without branch protection rules (reviewers, timer etc.)

**Comment by srgustafson8** [comment]
> I think @srgustafson8 the main difficulty here is that this resource depends on the environment resource which is still missing, and the API of that does not look terribly stable.

Understood - it looks like someone had a go at the environment resource here https://github.com/integrations/terraform-provider-github/pull/736 but then closed the PR.

**Comment by marcinwyszynski** [comment]
I'll see what I can reuse from #736 - I think if one simplifies it a bit to avoid using unstable parts of the API, future iterations can build on top of it.

**Comment by srgustafson8** [comment]
I just had a PR merged into the go-github module that provides the client for environments and environment secrets (https://github.com/google/go-github/pull/1847). Not sure how long this will take to make it's way here but it may help

**Comment by maxgr0** [comment]
+1
Would love to see this implemented!

**Comment by hoxu** [comment]
Please stop posting useless +1 comments that add nothing to the discussion. Upvoting the first comment is for showing you support the idea. People who are subscribed to the issue do not want emails of +1 comments. Thanks for understanding.

**Comment by nadenf** [comment]
For those interested I am currently working on this in conjunction wth #528.

**Comment by nadenf** [comment]
PR has been raised. Huge thank you to @srgustafson8 for adding support in go-github.

**Comment by kfcampbell** [comment]
Closing as #805 has been merged. Thanks again @nadenf!
