### ISSUE TITLE
Feature Request: Add github_app_installation_repository resource

### ISSUE THREAD

**Issue by k24dizzle** [integrations/terraform-provider-github#687]
I was wondering if we could create a new resource to help manage app installations to repositories in an organization.

It would be similar to `github_team_repository`, taking in an app `installation_id` and a `repository_id` to manage this relationship.

https://docs.github.com/en/rest/reference/apps#add-a-repository-to-an-app-installation

**Comment by k24dizzle** [comment]
Went ahead and gave it a shot in the PR above

**Comment by gmile** [comment]
PR above got merged. Shall this be closed now?
