### ISSUE TITLE
[Feature Request] Provide 'github_Releases' resource

### ISSUE THREAD

**Issue by Omarimcblack** [integrations/terraform-provider-github#692]
I would find it vary useful if there was a resource [`github_release`](https://docs.github.com/en/rest/reference/repos#create-a-release) that could be used to manage the creation an updating of a github release. There is already the accompanying [data source](https://github.com/integrations/terraform-provider-github/pull/356)

this could then spawn the creation of [`github_release_asset`](https://docs.github.com/en/rest/reference/repos#upload-a-release-asset)

**Comment by kfcampbell** [comment]
This is still a valid issue; API support exists [here](https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28).

**Comment by kfcampbell** [comment]
The linked PR (#1122) looks good and can be merged soon.
