### ISSUE TITLE
[Tracking] Provider compiled for darwin/arm64

### ISSUE THREAD

**Issue by skyzyx** [integrations/terraform-provider-github#695]
### Important Factoids

Apple M1 chip is here. Porting work is occurring for everyone. Opening a tracking ticket to provide public visibility on the work.

### References

Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:

* https://github.com/golang/go/issues/38485
* https://github.com/hashicorp/terraform/issues/27257
* https://github.com/hashicorp/terraform-provider-aws/issues/16948

**Comment by skyzyx** [comment]
**Status update:** Go 1.16 was released today with [non-prerelease, first-class support for `darwin/arm64`](https://golang.org/doc/go1.16#darwin).

**Comment by jcudit** [comment]
Is this in some way related to [this `goreleaser` failure](https://github.com/integrations/terraform-provider-github/runs/1923177876?check_suite_focus=true)?  I'm unable to cut new releases due to this failure, so any pointers are appreciated.

**Comment by jcudit** [comment]
Oh, I now see our options:

- Update the provider codebase and .github/workflows/release.yml to Go 1.16
- Pin the goreleaser version in your .github/workflows/release.yml to v0.155.0
- Ignore the new platform in .goreleaser.yml under builds

I'll ignore the new platform for the time being, but welcome more input from everyone on how best to proceed.

**Comment by verokarhu** [comment]
What's the status on this @jcudit? It seems like other providers haven't needed to do anything beyond upgrading to Go 1.16, e.g. [Google provider](https://github.com/hashicorp/terraform-provider-google/issues/8629) and there's already an open PR for this provider at #727.

**Comment by verokarhu** [comment]
I can verify that this works on Apple silicon with Terraform 0.15 with the provider version 4.9.2. 👍 

Thanks for the excellent provider!
