### ISSUE TITLE
Publish v2.4.1 to integrations/github registry

### ISSUE THREAD

**Issue by thirstydeveloper** [integrations/terraform-provider-github#700]
### Background

My team is stuck on an old version of GitHub enterprise (v2.19.4), for which the last supported provider version appears to be v2.4.1.

It seems many of the older provider versions were not migrated to the new integrations/github registry. If you are stuck on an old version, the result is you either get warnings for not having upgraded, or errors if you try to upgrade.

Would the maintainers be willing to publish at least this version, or alternatively all of the versions from the old registry to the new one?

### Expected Behavior

I should be able to run `terraform init` with the following `required_providers` block:

```hcl
terraform {
  required_providers {
    github = {
      source = "integrations/github"

      # NOTE: This appears to be the last provider version that supports our current GitHub enterprise version
      #       of 2.19.4
      #
      #       See: https://github.com/terraform-providers/terraform-provider-github/issues/539
      #            https://github.com/terraform-providers/terraform-provider-github/issues/404
      version = "~> 2.4.1"
    }
  }
}
```

### Actual Behavior

```
Initializing provider plugins...
- Finding hashicorp/tls versions matching "~> 3.0.0"...
- Finding hashicorp/aws versions matching "~> 3.27.0"...
- Finding integrations/github versions matching "~> 2.4.1"...
- Using hashicorp/tls v3.0.0 from the shared cache directory
- Using hashicorp/aws v3.27.0 from the shared cache directory

Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider
integrations/github: no available releases match the given constraints ~>
2.4.1
```

**Comment by jcudit** [comment]
This seems doable given the release tooling that is now available.  My only concern here is around what the "latest" release would end up being if we were to publish older versions.  I will test releasing `v2.4.1` before and alongside the next release to see if that helps this issue.  If all goes well, then another pass including other older releases should be possible.

Thanks for pointing out this flaw 🙇🏾

**Comment by jcudit** [comment]
@thirstydeveloper I attempted to release this version using the same process used for new releases, but the automation did not seem to trigger 🤔 .  I've manually created a release through the GitHub UI instead.  Can you confirm whether or not that solved the issue?

**Comment by thirstydeveloper** [comment]
Hi @jcudit - I'm afraid not. Running `terraform init` still fails and if I query the Terraform registry, it does not show v2.4.1 as being available.

```bash
➜ curl -s registry.terraform.io/v1/providers/integrations/github | jq '{ namespace, name, versions }'
{
  "namespace": "integrations",
  "name": "github",
  "versions": [
    "4.2.0",
    "4.3.0",
    "4.3.1",
    "4.3.2",
    "4.4.0",
    "4.5.0",
    "4.5.1"
  ]
}
```

**Comment by jcudit** [comment]
👋🏾  still alive over here.  Checking in with the registry support team on next steps.

**Comment by thirstydeveloper** [comment]
@jcudit  - any word from the registry support team?

**Comment by jcudit** [comment]
😓  @thirstydeveloper I wish I had better news.  I'll ping again and spend some time in the registry docs to see if anything can be done.

Alternatively, I'm interested in hearing more about what is incompatible with published versions and the version of GHES you're running.  Kind of a long shot as the overall fix, but I'm willing to work a few issues in case it helps get you all onto a more recent version!

**Comment by thirstydeveloper** [comment]
@jcudit - I wish I could get my organization to upgrade their GHE version and just make the problem go away :-(

I don't recall what the specific issues were. If we need to go down that path I'll try.

Is the issue just re-releasing old tags? If so, is it possible to branch off of the 2.4.1 tag and release a new 2.4.2 tag off it?

**Comment by jcudit** [comment]
> branch off of the 2.4.1 tag and release a new 2.4.2 tag off it

Great idea. Aiming to give this a shot alongside the next release.

**Comment by jcudit** [comment]
Gave this a shot with this branch: https://github.com/integrations/terraform-provider-github/tree/release-2.4.2

The workflow succeeded but the `curl` provided above is not reporting the new release 😕
