### ISSUE TITLE
[Feature Request] Use encrypted_value in github_actions_organization_secret and github_actions_secret

### ISSUE THREAD

**Issue by KMConner** [integrations/terraform-provider-github#704]
Hi there,

I use `github_actions_secret` resource to manage GitHub Actions Secret for my repositry.
But this resource stores `plaintext_value` in tfstate, which is not very safe.

So I suggest these resources should have ways to use [this api](https://docs.github.com/en/rest/reference/actions#create-or-update-an-organization-secret) with a parameter `encrypted_value`. This will store `encrypted_value` instead of `plaintext_value` which will be safer.

### Affected Resource(s)

- github_actions_organization_secret
- github_actions_secret

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-468 
- GH-362

**Comment by nadenf** [comment]
@KMConner  .. Pretty sure this should be closed. As per the [code](https://github.com/integrations/terraform-provider-github/blob/f8eeee871d6e0e08642512bb52e0be5a915f8ac6/github/resource_github_actions_organization_secret.go
) the plaintext value is encrypted using the Github public key.

**Comment by KMConner** [comment]
@ nadenf

I know that the plaintext value is encrypted using GitHub public key in the current version.

In my opinion, it is not very safe to store plaintext values in tfstate files. (I believe the current version will do so...)
Then, I would like to create a new option to specify encrypted values directly instead of encrypting inside GitHub provider.
Specifying this option will avoid saving plaintext values to tfstate files, and will save encrypted values to tfstate files.

**Comment by nadenf** [comment]
@KMConner .. Understand now. Have submitted a PR which adds encrypted_value for Actions, Environment and Organisation secrets.

**Comment by kfcampbell** [comment]
Closing as #807 has been merged and released.
