### ISSUE TITLE
Unable to specify deletion commit message

### ISSUE THREAD

**Issue by simontabor** [integrations/terraform-provider-github#706]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
0.14.6 / 4.4.0

### Affected Resource(s)

- github_repository_file

### Terraform Configuration Files
```hcl
resource "github_repository_file" "file" {
  repository          = github_repository.repo.name
  branch              = github_branch_default.default.branch
  file                = ".github/CODEOWNERS"
  content             = file(".github/CODEOWNERS")
  commit_message      = ".github/CODEOWNERS [skip ci]"
  commit_author       = "bot"
  commit_email        = "bot@user.com"
  overwrite_on_create = false

  lifecycle {
    // these change every time or unnecessarily
    ignore_changes = [commit_author, commit_email]
  }
}
```

### Expected Behavior
When I delete this resource, I should have control over the commit message

### Actual Behavior
Commit message is: "Delete .github/CODEOWNERS"

This removes the [skip ci] message and triggers pipelines

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create this resource then delete it

### Important Factoids
None

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- Similar issue with the provider creating lots of unnecessary commits (or even worse, choosing previous commit messages) https://github.com/integrations/terraform-provider-github/issues/689

**Comment by lrstanley** [comment]
Just ran into the same thing -- deleting files causes the `[skip ci]` portion of the commit I would normally add, to not be included, thus triggering a bunch of CI runs.

**Comment by FalconerTC** [comment]
+1 would like to see this fixed
