### ISSUE TITLE
Can't apply branch protection on github enterprise-server@2.21

### ISSUE THREAD

**Issue by jonesy1234** [integrations/terraform-provider-github#707]
### Terraform Version
```Terraform v0.14.7
+ provider registry.terraform.io/integrations/github v4.5.0
```

### Affected Resource(s)
- github_branch_protection

### Terraform Configuration Files
```hcl
data "github_repository" "example" {
  name = "module-azure-recovery-vault"
}

resource "github_branch_protection" "example" {

  repository_id = data.github_repository.example.node_id

  pattern          = "master"
  enforce_admins   = true
  allows_deletions = true

}
```

### Debug Output
```
github_branch_protection.example: Creating...

Error: Variable $input of type CreateBranchProtectionRuleInput! was provided invalid value for allowsForcePushes (Argument is not defined on CreateBranchProtectionRuleInput), allowsDeletions (Argument is not defined on CreateBranchProtectionRuleInput)
```

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
Apply the branch protection

### Actual Behavior
```
github_branch_protection.example: Creating...

Error: Variable $input of type CreateBranchProtectionRuleInput! was provided invalid value for allowsForcePushes (Argument is not defined on CreateBranchProtectionRuleInput), allowsDeletions (Argument is not defined on CreateBranchProtectionRuleInput)
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Have tried various different combinations of values without success 

### References
Can't find any

**Comment by jonesy1234** [comment]
Anyway I can bump this up the list of priorities to look into? Without being able to implement branch protection this provider is currently very limited for us. Many thanks

**Comment by jcudit** [comment]
The errors read like the version of GHES in use does not support receiving `allowsDeletions` and `allowsForcePushes`.  We may be able to optionally send these parameters to remain backwards compatible, but would need to experiment to confirm this is the case.  I can play around with this locally to see if this is a possible solution, but overall suspect an upgrade to a supported GHES version is warranted.

🤔  curious if this is an issue for others that are on more recent versions of GHES.  If anyone can confirm a working version, that would be helpful for documentation purposes!

**Comment by shivamsood** [comment]
This is an issue for me as well. i am on 2.22.7 version of GHE

**Comment by leighmhart** [comment]
Ditto, GitHub Enterprise Server 2.22.7

**Comment by seanorama** [comment]
Same problem on:
> GitHub Enterprise Server 3.6.3

**Comment by chamoisla** [comment]
> 

Same problem on `GitHub Enterprise Server 3.7.3`
```
Error: Variable $input of type CreateBranchProtectionRuleInput! was provided invalid value for requireLastPushApproval (Field is not defined on CreateBranchProtectionRuleInput), lockBranch (Field is not defined on CreateBranchProtectionRuleInput)
```
Provider version:
```
terraform {
  required_providers {
    github = {
      source  = "integrations/github"
      version = "~> 5.17.0"
    }
  }
}
```
Also reproducible on version `5.16.0`.

**Comment by dbg-raghulkrishna** [comment]
same issue for GHE 3.6

**Comment by chamoisla** [comment]
> same issue for GHE 3.6

I was able to work around this by downgrading the provider plugin version to `4.19.2`.

**Comment by vtavernier** [comment]
I can confirm the issue with:
- integrations/github: 5.18.0
- GHES: 3.7.6

**Comment by kfcampbell** [comment]
The provider isn't very good at handling GHES versions right now. Perhaps we could introduce a GHES_VERSION environment variable that each resource could check and handle appropriately. Thoughts?

**Comment by froblesmartin** [comment]
> The provider isn't very good at handling GHES versions right now. Perhaps we could introduce a GHES_VERSION environment variable that each resource could check and handle appropriately. Thoughts?

Hey! I am just starting to use the provider and just faced this issue as well.

Would that be similar to a feature flag but with checks, so that certain parts of the code would only be executed for certain versions? It will increase quite a bit the complexity, but then also it can be decided to only keep backwards compatibility with a limited number of versions 🤔

Also, checking the docs, GHES 3.8 will have at least the `requireLastPushApproval` and `lockBranch`
https://docs.github.com/en/enterprise-server@3.8/graphql/reference/input-objects#createbranchprotectionruleinput, so updating to that version should get it working.

**Comment by kfcampbell** [comment]
> Would that be similar to a feature flag but with checks, so that certain parts of the code would only be executed for certain versions? 

Yep, that's what I"m envisioning. We could also define some provider-level configuration that will allow us to specify the GHES version.

> It will increase quite a bit the complexity, but then also it can be decided to only keep backwards compatibility with a limited number of versions

Agreed!

**Comment by pascal-hofmann** [comment]
The REST API answers with this header:
```
X-Github-Enterprise-Version: 3.7.8
```

I guess this could be used when a non-default `base_url` is specified.
