### ISSUE TITLE
Attempts to set up a github_user_ssh_key results in a 404 error

### ISSUE THREAD

**Issue by cwinters8** [integrations/terraform-provider-github#711]
When I try to create a new github_user_ssh_key resource, I get a 404 error for the https://api.github.com/user/keys URL. I thought this was perhaps because I had the provider set to use an organization, but I also tried using an owner attribute and got the same error. As far as I can tell based on the documentation for this resource, I should be passing all the necessary information. Please let me know if there is a fix for this. Obviously I can workaround it for now but it would be a really nice feature for the infrastructure to be able to add the SSH key that the EC2 instance needs to Github as the environment is built.

### Terraform Version
Terraform v0.14.7
+ provider registry.terraform.io/hashicorp/aws v3.29.1
+ provider registry.terraform.io/hashicorp/http v2.1.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.0.2
+ provider registry.terraform.io/integrations/github v4.5.0
+ provider registry.terraform.io/mongodb/mongodbatlas v0.8.2

### Affected Resource(s)
Please list the resources as a list, for example:
- github_user_ssh_key

### Terraform Configuration Files
main.tf
```hcl
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.29"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.0"
    }
    github = {
      source  = "integrations/github"
      version = "~> 4.5"
    }
  }
  backend "s3" {
    bucket         = "tf-lgbtq-health-directory"
    key            = "terraform/state"
    region         = "us-west-2"
    dynamodb_table = "tf-lgbtq-health-directory"
  }
}

provider "aws" {
  profile = "obc"
  region  = "us-west-2"
}

provider "github" {
  token = var.github_token
  # organization = "OutBoulderCounty"
  owner = "cwinters8"
}
```
github.tf
```hcl
resource "github_actions_secret" "staging_ssh_host" {
  repository      = "lgbtq-health-directory-api"
  secret_name     = "STAGING_SSH_HOST"
  plaintext_value = aws_instance.api.public_ip
}

resource "github_actions_secret" "staging_ssh_user" {
  repository      = "lgbtq-health-directory-api"
  secret_name     = "STAGING_SSH_USER"
  plaintext_value = "ec2-user" # currently no way to get this from the instance dynamically
}

resource "github_actions_secret" "staging_ssh_key" {
  repository      = "lgbtq-health-directory-api"
  secret_name     = "STAGING_SSH_KEY"
  plaintext_value = file(var.ssh_private_key_path)
}

resource "github_user_ssh_key" "ec2_access" {
  title = "EC2 Access"
  key   = file(var.ssh_public_key_path) # have also tried passing the public key as a string directly with the same effects
}
```
variables.tf
```hcl
variable "api_public_key" {
  type = string
}

variable "github_token" {
  type = string
}

variable "ssh_private_key_path" {
  type = string
}

variable "ssh_public_key_path" {
  type = string
}
```

### Debug Output
https://gist.github.com/cwinters8/58371307ee7b9a538457fd30f78e5132

### Expected Behavior
A new SSH key should have been created for my Github account.

### Actual Behavior
The following 404 error:
```
github_user_ssh_key.ec2_access: Creating...

Error: POST https://api.github.com/user/keys: 404 Not Found []

  on github.tf line 19, in resource "github_user_ssh_key" "ec2_access":
  19: resource "github_user_ssh_key" "ec2_access" {

```

### Steps to Reproduce
1. `terraform apply`

**Comment by issyl0** [comment]
I can reproduce this behaviour if I remove `write:public_key` permissions from the GitHub token I am using with Terraform. Does your token have `write:public_key` permissions? You can check and edit the token's permissions at https://github.com/settings/tokens.

**Comment by cwinters8** [comment]
Hi @issyl0, thanks for the reply. You are correct - I was missing the `write:public_key` permission from the token I was using with Terraform. 🙄 I'm all set now!
