### ISSUE TITLE
github_team "Name must be unique for this org" when passing unique name

### ISSUE THREAD

**Issue by shermanericts** [integrations/terraform-provider-github#724]
### Terraform Version
```
Terraform v0.14.7
+ provider registry.terraform.io/hashicorp/github v4.4.0
```
### Affected Resource(s)
Please list the resources as a list, for example:

- github_team

### Terraform Configuration Files
```
resource "github_team" "engineering" {
  name        = "engineering-test"
  description = "engineering-test team"
}
```

### Debug Output
Please provide a link to a GitHub Gist containing the complete debug output:
https://gist.github.com/shermaneric/9e0ef9c3990c4f55be031787957d8af2

### Expected Behavior
Team of `engineering-test` should have been created in the organization. 

### Actual Behavior
Team was not created.  Validation failed - Error 422 Name must be unique for this org.
Specifically, I can verify that doing a 
`curl -H "Accept: application/vnd.github.v3+json"   https://api.github.com/orgs/<org>/teams` shows engineering-test not a team name.

### Steps to Reproduce
1. `GITHUB_TOKEN=<personal access token> GITHUB_ORGANIZATION=<github org> terraform apply`

**Comment by majormoses** [comment]
I will see if I can replicate this next week. Is this in a new existing setup? Were any plugins upgraded? If so do we know the last working version?

**Comment by shermanericts** [comment]
Thanks @majormoses !

1. This is a new setup applying this on my work Github Organization.
2. Full disclosure:  I couldn't recreate this on my personal organization.  I'm wondering if it's possible that I'm getting an error message that's not indicative or the root cause.

3. I verify using the Github [GET](https://docs.github.com/en/rest/reference/teams)  request that "engineering-test" is not a team.
4. We have these teams in the work organization (no 'engineering-test' team)
```
  UX
  Engineering
     <5 sub teams>
  then a test team i manually created through the github UI.
```
5. I'm using 
```
provider "registry.terraform.io/hashicorp/github" {
  version = "4.4.0"
```

6. Here are the rights I've given my Github Personal Access Token ( the same ones I give on my personal org).
```
admin:org, admin:org_hook, repo, user, workflow, write:discussion
```

I can give more Debugging information. I'm trying to marry what you need for troubleshooting vs. not divulging any pertinent information.

Thanks again! let me know how else I can help.  I'll investigate my side as well.

**Comment by majormoses** [comment]
@shermanericts thanks for the extra information, that will help me confirm if there was a regression or if this is a setup/access/permission type scenario.

> I can give more Debugging information. I'm trying to marry what you need for troubleshooting vs. not divulging any pertinent information.

As a security engineer, you have just described more than half my job: finding the balance in the chaos. I recommend scrubbing, redacting, or hashing any sensitive elements in logs/debug data as best as possible before sharing especially publicly. I [recently](https://github.com/integrations/terraform-provider-github/issues/621#issuecomment-786889425) did this myself. I generally redact the names of the organization, team, and repository (outside of the specific example if its relevant) names. In some cases it could be relevant (bad encoding, invalid characters, etc) but that information can often be extracted without giving away the original source data. Let's first see what we can get without the original data before I ask for it. If it would make you feel more comfortable you can send me an E2E encrypted message. I typically use PGP for these scenarios and publish my keys here (among other key servers):
- https://github.com/majormoses.gpg
- https://keybase.io/majormoses/pgp_keys.asc
- https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x96d0b48308b43174b8c654e99440eb5aaf298039

**Comment by shermanericts** [comment]
> @shermanericts thanks for the extra information, that will help me confirm if there was a regression or if this is a setup/access/permission type scenario.
> 
> > I can give more Debugging information. I'm trying to marry what you need for troubleshooting vs. not divulging any pertinent information.
> 
> As a security engineer, you have just described more than half my job: finding the balance in the chaos. I recommend scrubbing, redacting, or hashing any sensitive elements in logs/debug data as best as possible before sharing especially publicly. I [recently](https://github.com/integrations/terraform-provider-github/issues/621#issuecomment-786889425) did this myself. I generally redact the names of the organization, team, and repository (outside of the specific example if its relevant) names. In some cases it could be relevant (bad encoding, invalid characters, etc) but that information can often be extracted without giving away the original source data. Let's first see what we can get without the original data before I ask for it. If it would make you feel more comfortable you can send me an E2E encrypted message. I typically use PGP for these scenarios and publish my keys here (among other key servers):
> 
> * https://github.com/majormoses.gpg
> * https://keybase.io/majormoses/pgp_keys.asc
> * https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x96d0b48308b43174b8c654e99440eb5aaf298039
> 
> To confirm are you (or the users token who you are using) is an organizational admin? If not try with an admin. If it's not an admin then you can try verifying if this is enabled/disabled: https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/restricting-repository-creation-in-your-organization. If you are feeling queezy about running terraform with admin permissions see my stance [here](https://github.com/integrations/terraform-provider-github/issues/679#issuecomment-798967735)

The Github account running the tf automation was indeed not an admin.  I'll go back to my team and ask for that.  Strange that the error message isn't indicative of the problem in this case. (ah, that's on github :) ).  I'll take a look at the PGP links you sent and ready if you need more info.  Most likely it's the account type.

Thanks again!

**Comment by shermanericts** [comment]
Curious if you were able to repro @majormoses . I just tried a Personal Access token with an admin account.  Same issue:
The PAT has the following permissions:

<img width="911" alt="Screen Shot 2021-03-18 at 11 15 02 AM" src="https://user-images.githubusercontent.com/61428598/111676220-36170d00-87db-11eb-8955-bd5c815707d3.png">

**Comment by majormoses** [comment]
> The Github account running the tf automation was indeed not an admin. I can go back to my team and ask for that if that's what's needed.

Ah when I read this I figured there was nothing further to look at until you reported back. If you set the oauth scoped token if the user that runs it is not admin then that would occur.

> What's even stranger is that I can import an existing team and apply it back just fine :). I can just do that for now if you want to move on from this ticket.

Interesting, I think that actually does shed some light. It is expected that terraform does not auto import (though that would be a cool but potentially dangerous feature) resources that are defined. Terraform state does not know about the resources created outside of itself making it compatible with existing infrastructure. In this case it tries to create a new team with the same name which is refused by the API. Importing the manually created resources and then letting terraform mutate them going forward is the right solution. This is not specific to any particular provider or module. Depending on the size of you setup/migration you might consider scripting the import.

**Comment by majormoses** [comment]
Still wish there was a better error message, I'd report that to the github team.

**Comment by shermanericts** [comment]
Sounds good, thanks Ben!  I'll report back to github.  I'l close this issue. Thanks for all of your details!

**Comment by AdamSir2** [comment]
@shermanericts did you ever find a fix for this?

**Comment by AdamSir2** [comment]
@majormoses jsut an FYI - i read through your comment. So this may have been the case back then - but this definitely a persisting issue. I have run this directly from POSTMAN with the API I received noe rrors in the response.

This is only happening in the Terraform provider - I'm going to have a dive now into the code

**Comment by majormoses** [comment]
@AdamSir2 odd, it's got to be a very particular edge case as I have not experienced this having used this provider for many years across orgs. I hope you find something and I will try to respond in #1093.
