### ISSUE TITLE
[Feature Request] List all teams of an organization

### ISSUE THREAD

**Issue by reinoudk** [integrations/terraform-provider-github#726]
A lot of times it is beneficial to have a list of all teams in an organization, especially if they are not managed by Terraform or if this information is needed somewhere where there is no access to the particular Terraform state that contains this information.

I've created #725 to add a `github_teams` data source, which returns a list of all teams for an organization. The attributes of the teams are similar to that of `github_team`, with the exception of `permissions`, which I did not see in the GraphQL API.

Regarding the number of returned members of each team, I don't know if this is also affected by #701? This data source does not use the REST API.

**Comment by majormoses** [comment]
Here are some thoughts on some use cases we might want to consider:
- all / meta
- child teams, recursive?
- multiple teams

**Comment by reinoudk** [comment]
I like the idea of being able to fetch child teams. What about adding `parent_team` to the schema, which defaults to listing the teams in the organization itself?

I'm not sure about recursion, afaik it's not possible with [terraform-plugin-sdk](http://github.com/hashicorp/terraform-plugin-sdk) unless the result is flattened. (I think it should be possible using [terraform-plugin-go](https://github.com/hashicorp/terraform-plugin-go) but that's a whole other beast.)

What do you mean by multiple teams?

**Comment by majormoses** [comment]
I am not sure I fully fleshed these out but here is some chicken scratch of some early thoughts.

> I like the idea of being able to fetch child teams. What about adding `parent_team` to the schema, which defaults to listing the teams in the organization itself?

I think that could work, we need to handle the case of teams that are at the apex of the org as there is no parent. This may make more sense when you see how we are setup and some psuedo examples.

> What do you mean by multiple teams?

At my org we have the following structure:
```
org
|- bussiness_units
|-- bu1
|--- team1
|---- team1_reviewers
|-----team1_admins
...

|-- bu2
|--- team10
|---- team10_reviewers
|-----team10_admins
```
Get a list of all our various infra teams that could span multiple BUs to give them access to a repository
```terraform
# get a list of infra teams to grant to a repository
data "github_teams" "infra_all" {
  slugs = ["infra_1", "infra_2", "sre1", "sre2"]
  include_children = true # infra_1_(reviewers|admins), sre_(viewers|admins), ...
}

# dynamically grant access to these teams
resource "github_team_repository" "permission" {
  for_each = { for team in data.github_teams.infra_all.ids : team.id => team }

  team_id    = each.value.team
  repository = github_repository.repo.name
  permission = "pull"
}
```


The meta/all use case to grant all teams access to a repository:
```terraform
# get a list of all teams in the org to grant to a repository
data "github_teams" "org" {
  slugs = []
  all_teams = true
}

# dynamically grant access to these teams
resource "github_team_repository" "permission" {
  for_each = { for team in data.github_teams.org.ids : team.id => team }

  team_id    = each.value.team
  repository = github_repository.repo.name
  permission = "pull"
}

```

I think the interface is probably clunky and perhaps we should be looking at two different data sources for a better experience?

**Comment by reinoudk** [comment]
Sorry for the late reply, it was a bit of a hectic week here. 

Isn't this use case covered by inheritance of permissions by nested teams as described [here](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/about-teams#nested-teams)?

In any case I think that the `slugs` property can be handled by a `for_each` instead. (I don't think it is possible to query by multiple slugs in a single request, so the amount of request to the GitHub API would be the same.)

Adding `max_depth` should be possible by dynamically creating the query and flattening the results. For the root level this works a bit different in the GraphQL API though: is has a `rootTeamsOnly` option. To keep the resulting code clean I think that having two distinct data sources (like you mentioned in #725 @majormoses) makes sense:


```hcl
# all teams of the organization
data "github_organization_teams" "all" {}

# just the root teams of the organization
data "github_organization_teams" "root_teams" {
  root_teams_only = true # default = false
}

# child teams of a specific team
data "github_child_teams" {
  parent    = "slug-1"  # mandatory
  max_depth = 1         # value between 1 and x, though x might need to be limited to some sensible value
}

# child teams of multiple teams
data "github_child_teams" {
  for_each  = toset(["infra_1", "infra_2"])
  parent    = each.key
  max_depth = 2
}
```

If you need two levels down from the root teams, you can combine the two. This might not be ideal from an API call perspective, but as I said, it would keep the code clean.

```hcl
data "github_organization_teams" "root_teams" {
  root_teams_only = true # default = false
}

data "github_child_teams" {
  for_each  = data.github_organization_teams.root_teams
  parent    = each.value.slug
  max_depth = 2
}
```

What are your thoughts @jcudit? I'm not sure about the `parent` option, maybe this should be called `slug` or `parent_slug`?

**Comment by majormoses** [comment]
> Isn't this use case covered by inheritance of permissions by nested teams as described here?

Negatory ghost rider, as I indicated these may span multiple business units, umbrellas, teams subteams, and may not have a comment parent.

**Comment by reinoudk** [comment]
Having an `include_children` and `max_depth` option has no effect as nested children (regardless of depth) inherit the permissions of their parent team. The same permissions can be handed out as follows:

```hcl
data "github_team" "infra_all" {
  for_each = toset(["infra_1", "infra_2", "sre1", "sre2"])
  slug = each.key
}

# dynamically grant write access to infra_all teams
resource "github_team_repository" "infra_all_permission" {
  for_each = data.github_team.infra_all

  team_id    = each.value.id
  repository = github_repository.repo.name
  permission = "push"
}

data "github_team" "infra_admins" {
  for_each = toset(["infra_1_admins", "infra_2_admins", "sre1_admins", "sre2_admins"])
  slug = each.key
}

# dynamically grant write access to infra_admins teams
resource "github_team_repository" "infra_admins_permission" {
  for_each = data.github_team.infra_admins

  team_id    = each.value.id
  repository = github_repository.repo.name
  permission = "admin"
}
```
