### ISSUE TITLE
feature request: import github_organization_project

### ISSUE THREAD

**Issue by mfinelli** [integrations/terraform-provider-github#729]
Hi there,

It would be nice to be able to import existing projects both from the organization as well as a repository into the state to be managed by terraform. The documentation does not mention how to import these resources, so I'm assuming that it's not currently possible and needs to be added to the provider.

### Affected Resource(s)
Please list the resources as a list, for example:
- github_organization_project
- github_repository_project

**Comment by jcudit** [comment]
Looks like we have importing implemented for `github_repository_project`, so just docs needed here:

https://github.com/integrations/terraform-provider-github/blob/a4dc862435969c879fcc8b7b3a401f4ac19261f1/github/resource_github_repository_project.go#L21-L31

Nothing for `github_organization_project` though:

https://github.com/integrations/terraform-provider-github/blob/a4dc862435969c879fcc8b7b3a401f4ac19261f1/github/resource_github_organization_project.go#L20-L22

**Comment by dstrates** [comment]
+1 being able to import `github_organization_project` would be helpful 🙏

**Comment by fabn** [comment]
Why this has been closed, it would be very useful to have this feature, I tried to import a project with its id but it calls the wrong API:

```terraform
import {
  to = github_organization_project.next
  id = 3
}
# Generates this
resource "github_organization_project" "next" {
  body = "this is my project"
  name = "time to project 🐠🐟🌊"
}
```

It calls the following API `GET https://api.github.com/projects/3` that's of course not scoped to my organization/user.

Could you please reopen this?
