### ISSUE TITLE
feature request: manage project column automation

### ISSUE THREAD

**Issue by mfinelli** [integrations/terraform-provider-github#730]
Hi there,

It's currently only possible to create a column in a project but not manage any of the automation options. Ideally we could also control the automation for moving cards across columns via terraform.

### Affected Resource(s)
Please list the resources as a list, for example:
- github_project_column

**Comment by jcudit** [comment]
🤔 took a glance at the [docs](https://docs.github.com/en/graphql/reference/objects) and couldn't spot anything that'd help us get this automation configured through the v4 API.
