### ISSUE TITLE
Cannot import repository named, literally, ‘.terraform’

### ISSUE THREAD

**Issue by dato** [integrations/terraform-provider-github#731]
The following command fails for my github_org:

```bash
$ terraform import github_repository.terraform .terraform
                                               ^
```

### Debug Output
```
...
github_repository.terraform: Refreshing state... [id=.terraform]
                                                     ^
...
```
(Full log: https://gist.github.com/dato/fe79aaed096f7879494308f2159bd5e8)

### Terraform Version
```
Terraform v0.14.8
+ provider registry.terraform.io/integrations/github v4.2.0
```

### Terraform Configuration Files

```hcl
resource "github_repository" "terraform" {
  name        = ".terraform"
  description = "Terraform config files"
  visibility  = "private"

  auto_init = false
  allow_rebase_merge = false
  delete_branch_on_merge = true
}
```

### Affected Resource(s)

- github_repository

### Expected Behavior

I would like for the Github integration to recognize any repository name that is valid, and accepted by Github.

**Comment by tibbes** [comment]
@dato, importing a repository named `.terraform` works for me, with the following configuration:

```hcl
provider "github" {
  token        = "REDACTED"
  organization = "REDACTED"
}

terraform {
  required_providers {
    github = {
      source = "integrations/github"
      version = "4.2.0"
    }
  }
}

resource "github_repository" "terraform" {
  name        = ".terraform"
  description = "Terraform config files"
  visibility  = "private"

  auto_init              = false
  allow_rebase_merge     = false
  delete_branch_on_merge = true
}
```

The output is:

```
$ terraform import github_repository.terraform .terraform
github_repository.terraform: Importing from ID ".terraform"...
github_repository.terraform: Import prepared!
  Prepared github_repository for import
github_repository.terraform: Refreshing state... [id=.terraform]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```

However, if I remove `token` from provider configuration, then I do get the error message you see:

```
$ terraform import github_repository.terraform .terraform
github_repository.terraform: Importing from ID ".terraform"...
github_repository.terraform: Import prepared!
  Prepared github_repository for import
github_repository.terraform: Refreshing state... [id=.terraform]

Error: Cannot import non-existent remote object

While attempting to import an existing object to github_repository.terraform,
the provider detected that no object exists with the given id. Only
pre-existing objects can be imported; check that the id is correct and that it
is associated with the provider's configured region or endpoint, or use
"terraform apply" to create a new remote object for this resource.
```

This is because `.terraform` is a private repository, so if the GitHub provider is not authenticated to GitHub then it can't access the repository. Is it possible that your terraform configuration is not setting `token` or the environment variable `GITHUB_TOKEN`? If you do have a token, it's possible that the scopes associated with that token aren't sufficient (the token will need the `repo` scope).

**Comment by dato** [comment]
Could it be https://github.com/integrations/terraform-provider-github/issues/647 ?

When starting to use app.terraform.io, I found it impossible to import things, because the token was not shared back (of course). I did some dances of switching the backend from remote to local, then import, then back to remote.

Then, in some recent Terraform version, it seemed to work beautifully (at least, I'm pretty sure I've done successful imports with a remote backend).

Could this be a corner case of that functionality, that doesn't quite get it right here?

Many thanks for your response above btw, and care in showing a working example.

**Comment by aidan-mundy** [comment]
@dato Imports are not fully supported by the Terraform Cloud remote backend. The required environment variables (and terraform variables) must be set locally as well. If those variables were not set on your machine, it is possible that your successful import was related to a non-private resource or a provider that was capable of pulling authentication information from your machine automatically.
