### ISSUE TITLE
github_repository_file should create the branch

### ISSUE THREAD

**Issue by nikolay** [integrations/terraform-provider-github#738]
### Terraform Version
v0.13.6

### Affected Resource(s)
- `github_repository_file`

### Expected Behavior
If the branch does not exist, it should be created provided a `create_branch` `bool` attribute.

### Actual Behavior
It gets into a limbo requiring manual intervention as the file cannot be added when a new repository is created without any branches.

**Comment by kfcampbell** [comment]
I've run into this issue myself in Terraform and the API. I like the idea of fixing it; I think this issue is still relevant.
