### ISSUE TITLE
github_repository should have optional id field

### ISSUE THREAD

**Issue by nadenf** [integrations/terraform-provider-github#744]
### Affected Resource(s)
- github_repository

### Feature Request

It is common to want to rename Github repositories but doing so using this provider can often lead to data loss for associated data e.g. issues, projects, labels.

Having a user specify an optional id field for each repository (which could be stored as a Repository Secret e.g. Terraform ID) would ensure that renames and reorders (when you have a list of repositories) would not cause data loss.

Alternatively if the ID/NodeID attributes in the gitHub-go library can be used to track the repositories instead of the name.

### References
- https://github.com/integrations/terraform-provider-github/issues/55
- https://github.com/integrations/terraform-provider-github/issues/616

**Comment by shoddyguard** [comment]
I think this may no longer be needed due to #699 having been shipped?

**Comment by kfcampbell** [comment]
@shoddyguard you're right, thanks!
