### ISSUE TITLE
Unable to list the branches for a repository

### ISSUE THREAD

**Issue by nadenf** [integrations/terraform-provider-github#748]
### Affected Resource(s)
- github_branches
- github_repository

Feature request for either a: 
1) New data source called github_branches which lists all of the branches for a repository.
2) branches attribute for github_repository.

**Comment by lubo** [comment]
Although `branches` attribute has been added to `github_repository`, it does not work as expected as shown in https://github.com/integrations/terraform-provider-github/pull/892#issuecomment-947950349.
