### ISSUE TITLE
Not applying vulnerability_alerts = true on private repository creation

### ISSUE THREAD

**Issue by cgriego** [integrations/terraform-provider-github#754]
### Terraform Version
```
Terraform v0.13.6
+ provider registry.terraform.io/integrations/github v4.5.0
```

### Affected Resource(s)
- github_repository

### Terraform Configuration Files
```hcl
resource "github_repository" "simulator" {
  visibility = "private"
  name       = "simulator"

  delete_branch_on_merge = true
  has_issues             = false
  has_projects           = false
  has_wiki               = false
  vulnerability_alerts   = true
}
```

### Expected Behavior
When initially creating the resource, vulnerability alerts should be enabled.

### Actual Behavior
Repository is initially created with vulnerability alerts disabled, and running Terraform again enables the vulnerability alerts.

### Steps to Reproduce
1. `terraform apply`

**Comment by kfcampbell** [comment]
I've confirmed this behavior and drafted a [PR to fix it](https://github.com/integrations/terraform-provider-github/pull/768). I'll see about investigating any possible side effects more thoroughly and try to resolve the issue!

**Comment by PPFerrari** [comment]
Hi @kfcampbell,
will your fix help in some way with [this](https://github.com/integrations/terraform-provider-github/issues/588) too?

**Comment by kfcampbell** [comment]
@PPFerrari I don't believe so. I've asked around internally and it looks like that has a [separate API](https://docs.github.com/en/rest/reference/repos#enable-automated-security-fixes). I'll make a comment to that effect over there. If nobody beats me to it, I can take a peek at that issue once this fix is in.

**Comment by kfcampbell** [comment]
Closing as #768 has been merged. Please open a new issue if there's additional behavior around vulnerability alerts that should be changed!
