### ISSUE TITLE
Import of a github_branch uses default source_branch parameter and forces re-creation if the configuration specifies a different branch

### ISSUE THREAD

**Issue by alex-shafer-ceshop** [integrations/terraform-provider-github#759]
### Terraform Version
```
% terraform -v
Terraform v0.14.9
+ provider registry.terraform.io/hashicorp/aws v3.36.0
+ provider registry.terraform.io/integrations/github v4.8.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- `github_branch`

### Terraform Configuration Files
```hcl
resource "github_branch" "dev" {
  repository    = github_repository.project.name
  branch        = "dev"
  source_branch = "not-the-default"
}
```

### Debug Output
https://gist.github.com/alex-shafer-ceshop/cefd45c46c2e40f44175eb81149396fb

### Expected Behavior
The import should have found the source branch and stored that in the `source_branch` attribute, preventing a force re-creation.

### Actual Behavior
The `source_branch` attribute on the imported resource contains the default value of `main` (which is not the configured source branch)

### Steps to Reproduce
See the terraform code sample and [debugging information](https://gist.github.com/alex-shafer-ceshop/cefd45c46c2e40f44175eb81149396fb)

**Comment by dcfsc** [comment]
Same issue; based on the message when replace is forced I did not want to actually execute the apply, for fear it would delete the valuable branch.
```
  # module.repo_axisnow_serviceworker2_branches.github_branch.branches["master"] must be replaced
-/+ resource "github_branch" "branches" {
      ~ etag          = "W/\"1255b40d....b1\"" -> (known after apply)
      ~ id            = "reponame:master" -> (known after apply)
      ~ ref           = "refs/heads/master" -> (known after apply)
      ~ sha           = "97095...." -> (known after apply)
      ~ source_branch = "main" -> "master" # forces replacement
      + source_sha    = (known after apply)
        # (2 unchanged attributes hidden)
    }
```

I pulled the state file, edited the serial and `"source_branch": "main",`  to `"source_branch": "master",` and pushed it back. Not an efficient workflow.

This was the result of an import with the `source_branch="master"` specified, and there was no `main` branch. Not sure how it ended up with `main`.

**Comment by jcudit** [comment]
Does this work if we add the `source_branch` to the end of the `import` command?

> % terraform import module.test.github_branch.dev repo-name-redacted:dev

From the debug link, it looks like there are only two parts to the import argument.  Our docs state:

> Optionally, a source branch may be specified using an ID of `repository:branch:source_branch`.
This is useful for importing branches that do not branch directly ...

**Comment by jledoux-sonergia** [comment]
Hi there,

this issue still occurs with terraform 1.3.7 and github provider 5.16.0, somehow source_branch attribute always use main as its default value even if this branch never ever existed on the github repository.

```
resource "github_branch" "default" {
      ~ etag          = "W/\"f20be85cbbbfdc9a71447eae270229d77eb1effdb54d1010655348673d2b0786\"" -> (known after apply)
      ~ id            = "my-repository:delivery" -> (known after apply)
      ~ ref           = "refs/heads/delivery" -> (known after apply)
      ~ sha           = "6b5b59a145938fbe2b11da28008e7e605f919874" -> (known after apply)
      ~ source_branch = "main" -> "master" # forces replacement
      + source_sha    = (known after apply)
        # (2 unchanged attributes hidden)
    }
```
