### ISSUE TITLE
Provider always returns 403 Rate Limit Exceeded for github_team_repository even with /rate_limit showing thousands remaining

### ISSUE THREAD

**Issue by alex-shafer-ceshop** [integrations/terraform-provider-github#760]
### Terraform Version
```
Terraform v0.14.9
+ provider registry.terraform.io/hashicorp/aws v3.36.0
+ provider registry.terraform.io/integrations/github v4.8.0
```

### Affected Resource(s)
- `github_team_repository`

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    github = {
      source  = "integrations/github"
      version = "~> 4.8.0"
    }
  }
}

provider "github" {
  owner = "my-org"
}

resource "github_repository" "project" {
  name         = "test-repo"
  description  = "A repository for debugging terraform"
  visibility   = "private"
  has_projects = false
  has_wiki     = false
  auto_init    = true
}

data "github_team" "maintainers" {
  slug = "maintainer-team"
}

resource "github_team_repository" "project" {
  repository = github_repository.project.name
  permission = "maintain"
  team_id    = data.github_team.maintainers.id
}

```

### Debug Output
https://gist.github.com/alex-shafer-ceshop/f4bb3066c905102386bdd3060729b63b

### Expected Behavior
The resource should be created without error

### Actual Behavior
The resource is not created and a `403 Rate Limit Exceeded` error is returned during the apply consistently every time for this resource type, which seems like it must be incorrect.

### Steps to Reproduce
1. `terraform apply`

**Comment by alex-shafer-ceshop** [comment]
This is occurring with curl as well and therefore is not an issue with the terraform provider.

**Comment by alex-shafer-ceshop** [comment]
For anyone encountering this issue in the future, the issue was with the `maintain` permission; for some reason yet unknown, that permission seems unavailable for me, and the error message returned seems very incorrect.

**Comment by jcudit** [comment]
🙇🏾.appreciate the report, will keep an eye out for similar in the future.
