### ISSUE TITLE
Managing Github action workflow files

### ISSUE THREAD

**Issue by JamesWoolfenden** [integrations/terraform-provider-github#762]
### Terraform Version
Terraform v0.15.0

I'd like to be able to manage a repositories github action workflow via this provider (i got a lot of modules!) . I cant add then as a normal file content as they arent stored as content but as blobs?

```
│ Error: PUT https://api.github.com/repos/JamesWoolfenden/terraform-aws-dns/contents/.github/workflows/compare.yml: 404 Not Found []
```
And i think they really need to go
https://github.com/JamesWoolfenden/terraform-aws-dns/blob/main/.github/workflows/compare.yml

Happy to be wrong if there's already a terraform way of achieving this? Ty James

**Comment by jcudit** [comment]
Have you played with the `github_repository_file` resource this project offers?  I've seen this used successfully in the past if I'm understanding your use case correctly.

**Comment by JamesWoolfenden** [comment]
im using that resource for many other things, it just fails for files under .github paths

**Comment by jdyke** [comment]
I am also seeing this but it is only failing for `.github/workflows/` via a 404 error. I can create files under `.github/ISSUE_TEMPLATES/` or other test directories under `.github/` with no errors.

**Comment by daimon243** [comment]
Problem solved
Need add permission  
**workflow** (Update GitHub Action workflows)
 to Select scopes for used access token

**Comment by JamesWoolfenden** [comment]
Can confirm that you can add files to .github if you add the workflow permission.

**Comment by gmile** [comment]
I just [confirmed](https://github.community/t/failing-to-update-contents-under-github-using-an-api-call/190350/2?u=gmile) that this very issue is addressed by extending GH App's permission to read and write workflows.

**Comment by JamesWoolfenden** [comment]
Maybe a better error message that indicates this?
