### ISSUE TITLE
Changing + Renaming default branch impossible soley through provider?

### ISSUE THREAD

**Issue by mallyvai** [integrations/terraform-provider-github#765]
We were hoping to do all of our default branch renames through this wonderful terraform provider, but the resources and attributes I've tried all tell me that the new default branch has to exist already and we can't do the actual rename of the old branch through the provider. 

Can someone confirm there's no functionality in the provider to actually do a bulk rename through it? We're happy to hack together some shell scripts, but wanted to make sure we didn't miss some feature.

=============
What we're seeing currently?
```
  # module.repos.github_branch_default.driveway-default will be updated in-place
  ~ resource "github_branch_default" "driveway-default" {
      ~ branch     = "master" -> "randooom"
        id         = "driveway"
        # (1 unchanged attribute hidden)
    }
```

```
Error: PATCH https://api.github.com/repos/AfterpayTouch/driveway: 422 Validation Failed [{Resource:Repository Field:default_branch Code:invalid Message:The branch randooom was not found. Please push that ref first or create it via the Git Data API.}]

  on modules/repos/branch_default.tf line 1, in resource "github_branch_default" "driveway-default":
   1: resource "github_branch_default" "driveway-default" {

```

Thanks!
Vaibhav

**Comment by jcudit** [comment]
👋🏾  Vaibhav.  This is not something that I've seen accomplished through the provider previously.  

🤔  perhaps it makes sense to add a `rename = true` parameter here to signal to the provider that a rename operation is desired.  Logic to create the new branch would then be unlocked and we'd avoid the 422 from the API.

**Comment by rhughes1** [comment]
I'm suffering from the same issue. Fortunately, the repositories I need to manage are consistent with the name of the default branch. With that in mind, I'm thinking of just leveraging a GitHub template which has the default branch already renamed to what I want. This seems like a lot of overhead for something that should be handled within the resource.
