### ISSUE TITLE
Bump to `go-github` version 35.0.0

### ISSUE THREAD

**Issue by srgustafson8** [integrations/terraform-provider-github#766]
I recently had a PR merged into [the go-github library](https://github.com/google/go-github/pull/1847) to add repository environments and environment secrets endpoint support. I've referenced issues below that need this change to be implemented. 

I'm not 100% sure of the procedure here for bumping the version of this, but if it's as simple as raising a PR with the version changed and fixing the broken tests then i'm happy to give it a go myself. 

### References
This is required to implement #528 and #681.

**Comment by jcudit** [comment]
> raising a PR with the version changed and fixing the broken tests

That's about it!  PRs welcome if anyone wants to tackle this.  Looking forward to environment support 😄

**Comment by srgustafson8** [comment]
Looks like someone beat me to it! Thanks @jcudit
