### ISSUE TITLE
Provide a data source for GitHub SSH host keys

### ISSUE THREAD

**Issue by jbg** [integrations/terraform-provider-github#767]
If deploying something that interacts with GitHub over SSH (for example, a process that clones, pulls from, or pushes to, a repository), it's currently necessary to either **a)** deploy static SSH host keys for GitHub, which may become out of date and cause spurious failure, or **b)** run the equivalent of `ssh-keyscan github.com > ~/.ssh/known_hosts` at the beginning of the process, which blindly trusts whatever host keys are received, which could be the host keys of a MITM.

Providing a Terraform data source for GitHub's SSH host keys would allow populating `known_hosts` from a trusted source during deployment.

They're available from GitHub's [docs](https://docs.github.com/en/github/authenticating-to-github/githubs-ssh-key-fingerprints), but maybe - hopefully? - they're also available from their API.

**Comment by jbg** [comment]
SSH keys are indeed [available from the GitHub API](https://docs.github.com/en/rest/reference/meta#get-github-meta-information).

**Comment by kfcampbell** [comment]
This should stay pinned; it's still a useful feature request.

**Comment by nint8835** [comment]
This is functionality I'm looking for, I'll give implementing it a try

**Comment by jbg** [comment]
This would have been pretty handy recently 😉
