### ISSUE TITLE
Unable to create big_table_instance using terraform

### ISSUE THREAD

**Issue by charul97** [integrations/terraform-provider-github#787]
Using Terraform v0.14.10

Trying to create big_table_instance using terraform. Please see the code below:
resource "google_bigtable_instance" "bigtable_instance" {
  project = var.project
  name = var.name
  deletion_protection = false
  cluster {
    cluster_id = "${var.name}-cluster"
    num_nodes = var.num_nodes
    storage_type = var.storage_type
    zone = "us-central1-a"
  }
}

Getting the following error:
**module.bigtable_instance.google_bigtable_instance.bigtable_instance: Creating...

Error: Error creating instance. rpc error: code = Unavailable desc = connection closed

  on ..\bigtable_instance\main.tf line 1, in resource "google_bigtable_instance" "bigtable_instance":
   1: resource "google_bigtable_instance" "bigtable_instance" {**

**Comment by kpfleming** [comment]
This repository is for the GitHub provider, not the Google provider.
