### ISSUE TITLE
Content-type options not in org-level webhooks (docs)

### ISSUE THREAD

**Issue by tarfeef102** [integrations/terraform-provider-github#789]
### Affected Resource(s)
Please list the resources as a list, for example:
- github_organization_webhook

### Expected Behavior
Docs should specify valid values as they aren't directly what is in the console/UI.

### Actual Behavior
Users are left to guess, or maybe infer from the options in std webhooks. I used `application/json`, and my webhook is set to that in the UI, but requests are leaving as urlencoded, so... 🤷🏾 

### References
- #510 was the PR for std webhooks to add this info

**Comment by kfcampbell** [comment]
Hmm...I think this is still valid. @tarfeef102 do you have any interest in opening up a docs PR to fix this?

**Comment by vincentclee** [comment]
Setting content type to `json` worked for me


```hcl
resource "github_organization_webhook" "foo" {
  configuration {
    url          = "https://google.com"
    content_type = "json"
  }
}
```

https://github.com/integrations/terraform-provider-github/blob/0daadfa2449db5f1bd3dc5f9df9252e45521dcd1/github/schema_webhook_configuration.go#L21-L25
