### ISSUE TITLE
Bizarre behaviour when importing `github_repository_file`

### ISSUE THREAD

**Issue by DazKins** [integrations/terraform-provider-github#797]
### Terraform Version
```
Terraform v0.12.18
+ provider.aws v2.58.0
+ provider.github v4.5.0
+ provider.null v2.1.2
```

### Affected Resource(s)
- github_repository_file

### Bizarre Behavior
When importing a `github_repository_file` with `terraform import ...` terraform loads the most recent commit's author and message into the `commit_author` and `commit_message` fields if they are not specified in the resource definition. This means, that any subsequent `terraform apply`s that cause a change to that file will now take the author and commit message of the last commit that changed the file. This is behaviour that's bound to cause confusion.

There seem to be 2 possibilities to improve this in my mind:
- Make `commit_author` and `commit_message` non-optional fields on the `github_repository_file` resource
- Make some more sensible default for the `commit_author` and `commit_message` fields when they are not specified. The Github provider requires the token of a GitHub user, why not commit as that user?

### Steps to Reproduce
1. Import an existing `github_repository_file`
2. Make a change to that files contents in terraform config
3. Run `terraform apply`

**Comment by ezzatron** [comment]
I hit this issue, as well as some other bizarre behaviours surrounding committer details, especially in combination with `app_auth` provider authentication.

When using `app_auth`, if you create a completely new file, the initial commit will appear to be created by the app that the provider is authenticated as. Subsequent commits will appear to be created by `GitHub <noreply@github.com>`.

**Comment by ezzatron** [comment]
As far as I know, this problem still exists.

**Comment by kfcampbell** [comment]
@ezzatron please feel free to open up a new issue to track the app_auth committer details problem you've mentioned above. PRs are appreciated in both cases if anybody has the time and inclination to do so.
