### ISSUE TITLE
Allow GitHub App PEM data to be passed directly

### ISSUE THREAD

**Issue by gusnuf** [integrations/terraform-provider-github#803]
The new GitHub app authentication feature launched in 0.4.10 is fantastic (thanks @alloveras), but it forces the application's PEM data to be available to Terraform as a file, the path of which must be passed via the `GITHUB_APP_PEM_FILE` environment variable.  This makes it unusable where the execution environment is not under the user's control, notably Terraform Cloud and Terraform Enterprise.

`GITHUB_APP_PEM_FILE` is already marked as containing sensitive data, so the simplest option is to allow PEM data to be passed in via this same variable.  PEM data is easily detectable as it has `-----` as a standard preamble.  If this preamble is seen, just use the data directly and don't bother trying to open the file and read its contents.

**Comment by jspiro** [comment]
See #804!

**Comment by gusnuf** [comment]
Fixed by #804
