### ISSUE TITLE
5.0 release plan

### ISSUE THREAD

**Issue by jcudit** [integrations/terraform-provider-github#808]
Hey everyone!  Glad to have been getting regular contributions as of late.  There have been a few more GitHubbers getting involved with reviewing and we've been getting some enterprise customers helping guide feature prioritization as well.  With that background, I wanted to get some quick feedback on a possible 5.0 release.

At this point the only issues I think would be included are:
- https://github.com/integrations/terraform-provider-github/pull/804: changes the provider authentication interface, so seemingly a major bump is needed if enough of the community has already migrated to GitHub App authentication.
- https://github.com/integrations/terraform-provider-github/pull/735: follow through with deprecations around environment variable configuration of the provider.

Open to lumping in more if anyone can think of a change that gets the project in a better longer-term state.

The plan at this point is to **not** release a 5.0 and instead ship breaking changes in https://github.com/integrations/terraform-provider-github/pull/804 in the hopes that early adopters of the GitHub App authentication feature are 👌🏾 with reconfiguring.  Aiming to action this early next week if there are no objections raised here.  If this happens, we can still use this issue to track other items the community would like addressed.

**Comment by nadenf** [comment]
Would be nice to get some Github contributions as well.

Especially for some of the bigger changes e.g. referencing repositories using id instead of name.
