### ISSUE TITLE
github_team data resource does not inject organization id into call resulting in 404

### ISSUE THREAD

**Issue by hs-amartin** [integrations/terraform-provider-github#823]
### Terraform Version
```
Terraform v1.0.0
on darwin_amd64
```

### Affected Resource(s)
Please list the resources as a list, for example:
- github_team

### Terraform Configuration Files
```hcl
data "github_team" "parent_team" {
  count = var.parent_team_slug == "" ? 0 : 1
  slug  = var.parent_team_slug
}

resource "github_team" "team" {
  name        = var.name
  description = var.description

  create_default_maintainer = false
  parent_team_id            = try(data.github_team.parent_team[0].id, null)
  privacy                   = "closed"
}

```

### Debug Output
```
Error: GET https://api.github.com/orgs//teams/parent-team-name: 404 Not Found []
│ 
│   with module.teams["child-team-name"].data.github_team.parent_team[0],
│   on modules/team/main.tf line 1, in data "github_team" "parent_team":
│    1: data "github_team" "parent_team" {
```

### Expected Behavior
Retrieves the team.

### Actual Behavior
Fails to inject the organization id into the url, causing it to 404.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Have an organization with teams
1. `terraform apply`

### Important Factoids
This was working on the `hashicorp/github` provider, but is broken on all versions of `integrations/github` provider I tested (all the 4.x as of June 15 2021, some 3.x)

**Comment by gdlx** [comment]
I have the same issue with `github_repository_webhook` after migrating from `hashicorp/github` which was working fine except the deprecation:
```
module.app_env[0].github_repository_webhook.codepipeline: Creating...
╷
│ Error: POST https://api.github.com/repos//my-repo/hooks: 404 Not Found []
│
│   with module.app_env[0].github_repository_webhook.codepipeline,
│   on ../../modules/app_env/deploy_pipeline.tf line 235, in resource "github_repository_webhook" "codepipeline":
│  235: resource "github_repository_webhook" "codepipeline" {
```

Here is my provider requirement:
```hcl
  required_providers {
    aws = "~> 3.0"
    github = {
      version = "~> 4.0"
      source = "integrations/github"
    }
  }
```

In the config I've set the `token` and `owner`. I've tried adding the `organization` with no effect.

**Comment by braedongough** [comment]
I also experience a similar issue when using the integrations provider when trying to reference `github_actions_public_key`. For some reason it uses my GH username as the owner instead of the owner name I supply. Chaning my provider to use `hashicorp/github` resolved this. 

My requirements:
```tf
required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.28"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.0.2"
    }
    github = {
      source  = "integrations/github"
      version = "4.12.0"
    }
  }
}
```

Provider: 

```tf
provider "github" {
  owner = "pleo-io"
}
```

Error:
```sh
Error: GET https://api.github.com/repos/braedongough/<repo-name>/actions/secrets/public-key: 404 Not Found []

```

**Comment by hs-amartin** [comment]
Note this is likely the same bug as https://github.com/integrations/terraform-provider-github/issues/830 and https://github.com/integrations/terraform-provider-github/issues/846

**Comment by braedongough** [comment]
I was able to resolve this by exporting `GITHUB_OWNER` in my shell, however, it still seems to completely ignore the `owner` argument I'm supplying in the provider block.

**Comment by rjhornsby** [comment]
Not sure if I'm doing something stupid, but neither the provider setting nor the env var `GITHUB_OWNER` is working around this issue. It doesn't appear that the value I'm trying to use is wrong, but rather that it never makes it into the URL, resulting in `...orgs//teams...`

` Error: GET https://api.github.com/orgs//teams/<repo>: 404 Not Found []`

**Comment by hs-amartin** [comment]
@rjhornsby Export all the variables you set in the provider (GITHUB_OWNER, GITHUB_TOKEN, etc.)

**Comment by rjhornsby** [comment]
> @rjhornsby Export all the variables you set in the provider (GITHUB_OWNER, GITHUB_TOKEN, etc.)

@hs-amartin Good call. I forgot that I didn’t have a GITHUB_TOKEN set, having had incidental changes that eliminated my need for a personal token, and so the env var was removed. But, adding that env var back in fixed it. Everything else github worked as expected because of ssh keys in the background, so the token didn’t even occur to me.

While some internal validation/error handling and feedback to the user would be helpful, the provider works now. Thanks for the suggestion!
