### ISSUE TITLE
Only administrators can create internal repositories from templates in organizations that restrict changing repository visibility

### ISSUE THREAD

**Issue by pmjacinto** [integrations/terraform-provider-github#836]
### Terraform Version
Terraform v1.0.1
on darwin_amd64

### Affected Resource(s)

- github_repository

### Terraform Configuration Files
```hcl
resource "github_repository" "instance" {
  name                 = "test-repo"
  visibility             = "internal"
  template {
    owner      = "my-org"
    repository = "my-template-repo"
  }
}
```

### Debug Output

```
 Error: PATCH https://api.github.com/repos/<org>/<repo_name>: 422 Visibility can't be changed by this user. []

   with module.internal_repos.github_repository.test_repo,
   on internal-repos/test-repo.tf line 1, in resource "github_repository" "instance":
    1: resource "github_repository" "instance" {
```

### Panic Output

N/A

### Expected Behavior

Creating an internal repo from a template should create the repo as internal instead of creating it as private and later changing it to internal. 

This will make it possible to use the provider without admin privileges when the organization restricts changing the visibility of a repo to admins.

### Actual Behavior
Repo create uses the REST V3 [/repos/{template_owner}/{template_repo}/generate](https://docs.github.com/en/rest/reference/repos#create-a-repository-using-a-template) API method which does not support a visibility field.

### Steps to Reproduce
1. `terraform apply`

### Important Factoids

The equivalent method in the GraphQL API supports setting visibility to internal.

Ref: [cloneTemplateRepository mutation](https://docs.github.com/en/graphql/reference/mutations#clonetemplaterepository).

### References
- #788 addresses this issue for repos not created through a template
- #832 highlights that this is also a problem when using App authentication
- [resource_github_repository - creating repo from template](https://github.com/integrations/terraform-provider-github/blob/4e4522290b377aa8f12a222448a14b58404ce8fb/github/resource_github_repository.go#L330-L341)

**Comment by martinb3** [comment]
I've been seeing this on some internal organizations where we can no longer create repos from templates, that I think tracks back to this bug. I've been able to reproduce the error with a curl, if I omit `private: true` but including `private: true` against the `/generate` endpoint of a template repo. I'm also able to create internal-visible repos from the UI just fine.

**Comment by christophermancini** [comment]
Yes please, we are encountering this issue continuously, having to manually create repos then import them.
