### ISSUE TITLE
[Feature] IP Allowlist Resource

### ISSUE THREAD

**Issue by Kyle-Hughes-Imprivata** [integrations/terraform-provider-github#844]
Hi there,

For GitHub organizations that use the IP Allowlist, being able to use and update that in Terraform state would be incredible.  

Specifically, if there were a terraform resource that took in a list of strings that corresponded to individual CIDR blocks like so:

```
resource "github_ip_allowlist" "ip_allowlist" {
    ipAllowListEntries = ["1.2.3.4/32", "5.6.7.8/32"]
}
```

**Comment by joshuasimon-taulia** [comment]
is there an api endpoint for this? i [combed the docs real quick](https://docs.github.com/en/enterprise-cloud@latest/rest/orgs/orgs), but i'm not seeing one. adding these 1 by 1 is really painful.

**Comment by mattcocking** [comment]
Hi, +1 on this as it would be very useful. I think this is supported by the v4 graphql API (eg [create endpoint here](https://docs.github.com/en/graphql/reference/mutations#createipallowlistentry)) so it might be more achievable now than before.
