### ISSUE TITLE
Error on `terraform apply` 422 Validation Failed [] leaving tainted state

### ISSUE THREAD

**Issue by omgaz** [integrations/terraform-provider-github#850]
Hey folks, I'm running into an issue where I'm getting `Error: PATCH https://api.github.com/repos/omgaz/test-repo: 422 Validation Failed []` immediately after an apply.

This leaves my state file tainted and have to recreate the resource.

Thanks

### Terraform Version

```
Terraform v1.0.2
on darwin_amd64
+ provider registry.terraform.io/hashicorp/github v4.12.1
+ provider registry.terraform.io/integrations/github v4.12.1
```

### Affected Resource(s)

`github_repository`

### Terraform Configuration Files

main.tf
```hcl
terraform {
  required_providers {
    github = {
      source  = "integrations/github"
      version = ">= 4.0"
    }
  }

  required_version = ">= 1.0.0"
}

provider "github" {
  # owner set through GITHUB_OWNER environment variable
  # token set through GITHUB_TOKEN environment variable
}
```

modules/repo.tf
```hcl
resource "github_repository" "default" {
  name        = var.name
  description = var.description

  visibility  = var.public ? "public" : "private"
}

```

Minimum code example: https://github.com/omgaz/github-terraform

### Debug Output

https://gist.github.com/omgaz/aaf60b9b2ae78562ef57fcece7df3fda

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior

State should not be tainted and errors should not appear.

### Actual Behavior

```
module.test-repo.github_repository.default: Creating...
╷
│ Error: PATCH https://api.github.com/repos/omgaz/test-repo: 422 Validation Failed []
│ 
│   with module.test-repo.github_repository.default,
│   on modules/repo/main.tf line 1, in resource "github_repository" "default":
│    1: resource "github_repository" "default" {
│ 
╵
```

### Steps to Reproduce

1. Clone the attached repo https://github.com/omgaz/github-terraform
2. Create a personal access token with repo, delete_repo privileges and set the token to GITHUB_TOKEN environment variable along with GITHUB_OWNER to yourself e.g. omgaz.
3. Run `terraform init`
4. Run `terraform apply`

### Important Factoids

1. Noticed that terraform init is installing both old and new providers, and `terraform state replace-provider registry.terraform.io/hashicorp/github registry.terraform.io/integrations/github` doesn't seem to help.
2. I've an old project on github provider 2.9 that seems to run fine.
3. Looking in my GitHub security logs I notice another error appearing every time I try to run

```
@omgaz
omgaz – repo.change_merge_setting
Blocked a merge setting on the [unknown repo] repository 
```

### References

None that I can see

**Comment by omgaz** [comment]
I wonder if it has anything to do with `allow_auto_merge`. The option is disabled for private repos, so I wonder if even trying to set it to false is what's causing this validation issue?

**Comment by omgaz** [comment]
With a little more digging it looks as though it's because Terraform is sending the `name` through in the patch.

I looked at the request sent from the terraform apply to the patch route and mimiced in a curl

```
curl https://api.github.com/repos/omgaz/test-repo \
  -u username:${GITHUB_TOKEN} \
  -X PATCH \
  -H "Accept: application/vnd.github.v3+json" \
  -d '{
 "name": "test repo",
 "description": "",
 "homepage": "",
 "auto_init": false,
 "allow_rebase_merge": true,
 "allow_squash_merge": true,
 "allow_merge_commit": true,
 "allow_auto_merge": false,
 "delete_branch_on_merge": false,
 "archived": false,
 "has_issues": false,
 "has_wiki": false,
 "has_projects": false,
 "has_downloads": false,
 "is_template": false,
 "license_template": "",
 "gitignore_template": ""
}'
```

Same thing, getting a Validation failed error. But removing the name from the data of the request and we get a success.

```diff
curl https://api.github.com/repos/omgaz/test-repo \
  -u username:${GITHUB_TOKEN} \
  -X PATCH \
  -H "Accept: application/vnd.github.v3+json" \
  -d '{
- "name": "test repo",
 "description": "",
 "homepage": "",
 "auto_init": false,
 "allow_rebase_merge": true,
 "allow_squash_merge": true,
 "allow_merge_commit": true,
 "allow_auto_merge": false,
 "delete_branch_on_merge": false,
 "archived": false,
 "has_issues": false,
 "has_wiki": false,
 "has_projects": false,
 "has_downloads": false,
 "is_template": false,
 "license_template": "",
 "gitignore_template": ""
}'
```

Which is real odd because https://docs.github.com/en/rest/reference/repos#update-a-repository clearly accepts 'name' as a valid input of this endpoint.

**Comment by pndurette** [comment]
@omgaz Thanks for your research on that, it helped me debug and dig when I hit the issue. See #1215 I opened with more details. 

The workaround is to set a repository name that matches `^[a-zA-Z0-9_.]+$` (i.e. no spaces or special characters besides underscores and periods)

**Comment by omgaz** [comment]
Great sleuthing!
