### ISSUE TITLE
ability to turn off vulnerability alerts api completely

### ISSUE THREAD

**Issue by Gopikrishna19** [integrations/terraform-provider-github#852]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version

```
Terraform v0.15.3
on darwin_amd64
+ provider registry.terraform.io/hashicorp/github v4.12.2
+ provider registry.terraform.io/integrations/github v4.12.2
```

### Affected Resource(s)

- github_repository

### Terraform Configuration Files
```hcl
resource "github_repository" "repository" {
  name = var.repository_name

  allow_merge_commit = false
  allow_rebase_merge = false

  vulnerability_alerts = null
  topics = null
  is_template = false
  has_wiki = true
  has_projects = true
  has_issues = true
  has_downloads = true
}
```

### Expected Behavior
 - I should still be able to create a repository without vulnerability_alerts
 - I should be able to set vulnerability_alerts to null to completely turn off the feature

### Actual Behavior

We don't have vulnerability-alerts enabled in our enterprise github. Setting the field to `null` or `true` or `false` or just plainly ignoring it keeps resulting in following error:

```
// null or false or ignore
Error: DELETE https://github.example.com/api/v3/repos/<owner>/<repo>/vulnerability-alerts: 404 Not Found []

// true
Error: PUT https://github.example.com/api/v3/repos/<owner>/<repo>/vulnerability-alerts: 404 Not Found []
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

We don't have vulnerability-alerts enabled in our enterprise github.

**Comment by jonesy1234** [comment]
👍  to get this one fixed, we've gone from full repo creation automation to now having to fix every additional repo we add to our terraform code. Happy to assist with any testing our github enterprise instance.
