### ISSUE TITLE
Docs, observed behavior, and issue history inconsistent about whether `push_restrictions` supports mixed actor types

### ISSUE THREAD

**Issue by swu-etsy** [integrations/terraform-provider-github#853]
### Terraform Version
v1.0.0

### Affected Resource(s)
- github_branch_protection

### Terraform Configuration Files
```hcl
resource "github_branch_protection" "example" {
  repository_id = {node_id of github repository}

  pattern          = "main"
  enforce_admins   = true

  required_pull_request_reviews {
    require_code_owner_reviews = true
    dismiss_stale_reviews = true
  }

  push_restrictions = [
 {node_id of a user},
 {node_id of a team}
 ]

}
```

### Expected Behavior
The [documentation for github_branch_protection](https://registry.terraform.io/providers/integrations/github/latest/docs/resources/branch_protection) states that the `push_restrictions` argument is `# limited to a list of one type of restriction (user, team, app)`. Therefore, I would expect setting `push_restrictions` to a list that contains a user's node_id and a team's node_id would either:

1. Raise an error upon running `terraform plan` or
2. Cause `terraform apply` to unsuccessfully attempt to add both a user and a team to the branch protection's `push_restrictions` setting in the remote resource.

In addition, I noticed that the comment history in https://github.com/integrations/terraform-provider-github/issues/581 says that `push_restrictions` does support mixed types.

Is the comment in the documentation stale, or is it still unsafe to provide mixed actor types to the `push_restrictions` argument?

### Actual Behavior
Terraform successfully added both the user and the team to the `push_restrictions` list of my remote branch protection resource. 

### Steps to Reproduce
1.  Copy the above Terraform config block.
2. Fill in the placeholders with a test repo, user, and team.
3. `terraform apply`

### References
https://github.com/integrations/terraform-provider-github/issues/581

**Comment by jcudit** [comment]
We released a fix to this limitation in [`v4.12.0](https://github.com/integrations/terraform-provider-github/blob/main/CHANGELOG.md#4120-jun-18-2021) but failed to update docs around it.  Will get this cleared up in the next release.  Thanks for raising 🙇🏾

**Comment by swu-etsy** [comment]
Great to hear, thanks much for the clarification!

**Comment by jcudit** [comment]
I tried creating a `github_branch_protection` resource with mixed actor types configured but was unable to get the expected behaviour 😕.  

Can anyone else confirm being able to configure this scenario?

**Comment by pulkitanz** [comment]
Can confirm I've ran into the same issue. Can't configure mixed types.
