### ISSUE TITLE
Feature request: Provide membership status in the `github_membership` data source.

### ISSUE THREAD

**Issue by swu-etsy** [integrations/terraform-provider-github#862]
Hi there! This is a feature request.

Currently, the `github_membership` data source considers Github users with unaccepted invitations to join an organization to be full organization members. It would be helpful to be able to distinguish, when using `github_membership`, whether a user is a current organization member, or merely has a pending invitation. This information would be useful, for example, to ensure that only current organization members are added to a team via the `github_team_membership` resource or given certain repository protected branch permissions via the `github_branch_protection` resource.

Glancing at the code, implementing this feature might be as simple as getting the `state` field of the go-github client's [Membership object](https://github.com/integrations/terraform-provider-github/blob/35d075797439cabce358216d59a4ffd564a76fb1/vendor/github.com/google/go-github/v36/github/orgs_members.go#L19) when calling the go-github [GetOrgMembership](https://github.com/integrations/terraform-provider-github/blob/35d075797439cabce358216d59a4ffd564a76fb1/vendor/github.com/google/go-github/v36/github/orgs_members.go#L212) method in [github/data_source_github_membership.go](https://github.com/integrations/terraform-provider-github/blob/main/github/data_source_github_membership.go#L48), and adding a "state" property to the [github_membership schema](https://github.com/integrations/terraform-provider-github/blob/main/github/data_source_github_membership.go#L14).  `go-github`'s `Membership`'s `state` value should be `pending` if the user has an unaccepted invitation, or `active` if the user has successfully accepted the invitation.

**Comment by jcudit** [comment]
Sounds like a great addition to support this use case. PRs welcome!

**Comment by dgteixeira** [comment]
This feature would be awesome indeed.
It's very helpful to understand which requests are still pending whenever we alter our setup
