### ISSUE TITLE
Please add the possibility to get actions IP address in datasources

### ISSUE THREAD

**Issue by arsenhovhannisyan** [integrations/terraform-provider-github#866]
Hi there,

Please add the possibility to get actions IP address (curl https://api.github.com/meta | jq .actions) ranges in "github_ip_ranges" datasources.

**Comment by blesson3** [comment]
Looks like this [already exists in the code](https://github.com/integrations/terraform-provider-github/blob/main/github/data_source_github_ip_ranges.go#L70) as of [this PR](https://github.com/integrations/terraform-provider-github/pull/784) merged in May. So you can probably use `github_ip_ranges.actions` already. The documentation was not updated, but looks like it will be as of [this yet unmerged PR](https://github.com/integrations/terraform-provider-github/pull/857).
