### ISSUE TITLE
Manage Github organization

### ISSUE THREAD

**Issue by Olin-Vorechovsky** [integrations/terraform-provider-github#872]
Hi there,

I would like to manage Github organizations (creating, updating, deleting) by terraform.

I have created resource_github_organization resource to create/rename organization by terraform.

Here is GitHub API docs: https://docs.github.com/en/enterprise-server@3.1/rest/reference/enterprise-admin
It needs Enterprise Account with `site_admin` scope (in oposit of organization account used for most cases) making acceptance testing harder b/c this api is not available for public Github but only for Github Enterprise (GHE).

### Terraform Version
Terraform v1.0.1

### Affected Resource(s)
- resource_github_organization

### Terraform Configuration Files
```hcl
provider "github" {
  base_url = "https://enterprise.github.com/"
  // you don't need owner property here
}

resource "github_organization" "test" {
  login = "organization-name"
  // you need exported GITHUB_TOKEN Personal Token with site_admin scope of this user
  admin = "admin"
  // TODO: not set on creation
  // profile_name = "short name"
}
```

### Debug Output for creation
```
github_organization. test: Creating...
github_organization. test: Creation complete after 1s [id=2600]
```

### Debug output for updating (renaming only)
```
 # github_organization.create_new will be updated in-place
  ~ resource "github_organization" "test
        id           = "2600"
      + profile_name = "short name"
        # (2 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

github_organization.create_new: Modifying... [id=2600]
github_organization.create_new: Modifications complete after 1s [id=2600
```

### Actual Behavior
It works.

### Important Factoids
* unable to pass test b/c it needs to be run agains GHE
* to fully suport updating organization we need to add more than `profile_name` and we need to call different api than enterprise endpoints 
* cannot find api for organization delete

### References
Kick-off sources: https://github.com/integrations/terraform-provider-github/pull/864

**Comment by kfcampbell** [comment]
This is unfortunately limited by API support at the moment. We can't create or delete orgs from the API. [Reference here](https://docs.github.com/en/rest/orgs/orgs?apiVersion=2022-11-28).

**Comment by tjcorr** [comment]
Looks like this was initially added with #1478 to create/update organizations. #1669 will add delete.
