### ISSUE TITLE
[Feature] Add pattern matching when selecting custom branch policies in resource github_repository_environment

### ISSUE THREAD

**Issue by JustinYeoh93** [integrations/terraform-provider-github#874]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
v1.0.4

### Affected Resource(s)
- github_repository_environment

### Expected Behavior
When using the resource `github_repository_environment`, we are given the option to set the argument `custom branch policies` to `true` and with it, the pattern to match it.

### Actual Behavior
Currently we have the option to set the argument `custom branch policies` to the desired boolean, but no option to define the custom branch's matching pattern.

**Comment by jsnowfreedman** [comment]
So after doing a fair bit of research and spending way too long looking through this providers source, I realized that this is actually a problem with the GitHub API itself: https://docs.github.com/en/rest/reference/repos#create-or-update-an-environment

![image](https://user-images.githubusercontent.com/59654518/131405482-fc3d81d9-4492-4923-9689-38c1c6697693.png)


This has been a bit of a problem for my team, as we would like to be able to use these patterns through Terraform, but this feels like an issue that we will need to bring up to GitHub instead.

(Just as a note, I checked GitHub's GraphQL API, and it seems this is not possible to do using that either :/)

**Comment by JustinYeoh93** [comment]
Closed as its a limitation on GitHub's side.
