### ISSUE TITLE
github_repository_collaborator causing perpetual diff when roles overlap

### ISSUE THREAD

**Issue by lijok** [integrations/terraform-provider-github#881]
### Terraform Version
latest

### Affected Resource(s)
- github_repository_collaborator

### Terraform Configuration Files
```hcl
resource "github_repository_collaborator" "writers" {
  repository                  = github_repository.this.name
  username                    = each.value
  permission                  = "push"
  permission_diff_suppression = true
}
```

### Expected Behavior
Adding someone who is an admin in the org, as a writer to a repo, should just work

### Actual Behavior
Adding someone who is an admin in the org, as a reader or writer to a repo, causes perpetual diff

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. `terraform plan`

<img width="456" alt="image" src="https://user-images.githubusercontent.com/28689084/129799248-bde45f6f-634b-4504-bc8c-e0b4448add51.png">

```hcl
  # module.my_repository.github_repository_collaborator.readers["peter"] must be replaced
-/+ resource "github_repository_collaborator" "readers" {
      ~ id                          = "my_repository:peter" -> (known after apply)
      + invitation_id               = (known after apply)
      ~ permission                  = "admin" -> "pull" # forces replacement
        # (3 unchanged attributes hidden)
    }

  # module.my_repository.github_repository_collaborator.readers["will"] must be replaced
-/+ resource "github_repository_collaborator" "readers" {
      ~ id                          = "my_repository:will -> (known after apply)
      + invitation_id               = (known after apply)
      ~ permission                  = "push" -> "pull" # forces replacement
        # (3 unchanged attributes hidden)
    }
```

**Comment by mechastorm** [comment]
Also noticing the same issue in GitHub Enterprise Server 3.4.5

**Comment by slmg** [comment]
Still an issue, used the below workaround. Not ideal in the event permission really need to change, but it prevents the diff spam.
```tf
resource "github_repository_collaborator" "main" {
  # [...]

  lifecycle {
    ignore_changes = [permission]
  }
}
```

**Comment by macetw** [comment]
The terraform state is not saving the `permission` field. Like so:
 ```$ terraform state show  'module.testorg.github_repository_collaborator.this["myrepo.macetw"]'
# module.testorg.github_repository_collaborator.this["myrepo.macetw"]:
resource "github_repository_collaborator" "this" {
    id                          = "myrepo:macetw"
    permission_diff_suppression = false
    repository                  = "myrepo"
    username                    = "macetw"
}
```

`permission` field should be saved!

**Comment by macetw** [comment]
I suggest the problem is with this!

https://github.com/integrations/terraform-provider-github/blob/e83bb8d8ffd505d63d068527df25efcdccdfc7a0/github/resource_github_repository_collaborator.go#L47

**Comment by macetw** [comment]
I also have a problem if I use the "maintain" state, but it is in a different outcome:

```
│ Error: PUT https://my.github.host/api/v3/repos/testorg/myotherrepo/collaborators/macetw: 422 Validation Failed []    
│                                                                                                                                              
│   with module.testorg.github_repository_collaborator.this["myotherrepo.macetw"],                                                   
│   on  github_repository.tf line 48, in resource "github_repository_collaborator" "this":                                   
│   48: resource "github_repository_collaborator" "this" {                                                                                     
```

**Comment by posquit0** [comment]
There is still this problem. Please re-open this issue.

**Comment by deiga** [comment]
@lijok @posquit0 If you are still encountering this issue, please provide logs for runs with the latest provider version and TF config examples as well.
Otherwise we'll close this again

**Comment by lijok** [comment]
It's been 5 years. You want me to provide info on an issue I opened 5 years ago?

**Comment by deiga** [comment]
> It's been 5 years. You want me to provide info on an issue I opened 5 years ago?

@lijok I asked you to provide info IF you are still encountering this issue. You opened a duplicate issue on this 8 months ago without any actionable info. 

I don't know if the issue persists and don't know how to reproduce it.
