### ISSUE TITLE
CNAME for github pages seems to be broken

### ISSUE THREAD

**Issue by LilithWittmann** [integrations/terraform-provider-github#898]
I tried to set cnames for my managed repositories and it seems like that there is an issue with the gh API.

Code: https://github.com/bundesAPI/terraform/blob/main/main.tf#L255
Build: https://github.com/bundesAPI/terraform/runs/3523959929?check_suite_focus=true#step:10:267

Do I do anything wrong or is the API actually br0ken? Also, there seems to be no option to enable "enforce tls"? Thanks!

**Comment by pnancarrow** [comment]
Would like to see this resolved!

From a quick look and test, it appears the cname paramter is only available when [updating pages information](https://docs.github.com/en/rest/pages/pages?apiVersion=2022-11-28#update-information-about-a-github-pages-site) so the CNAME doesn't get added when initially configurating, but it does when updating.
