### ISSUE TITLE
'github_repository_file' overwriting existing files even after 'overwrite_on_create' is set to 'false'

### ISSUE THREAD

**Issue by parag-neve-db** [integrations/terraform-provider-github#906]
'github_repository_file' overwriting existing files even after 'overwrite_on_create' is set to 'false'

We are creating github repository and creating some files within the repository after the repo has been created. Some of the files we are creating like config should not be overwritten if it already exists and to achieve this we are using the `overwrite_on_create` attribute and set it to false. However, we are noticing that the `github_repository_file` is still overwriting the file on every terraform plan/apply.

### GitHub Provider Version
v4.12.0

### Terraform Version
v0.14.11

### Affected Resource(s)
Please list the resources as a list, for example:
- github_repository_file

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl

resource "github_repository" "repo" {
  name         = var.github_repo_name
  description  = var.github_repo_description
  homepage_url = var.homepage_url

  visibility = var.visibility

  has_issues             = var.has_issues
  has_projects           = var.has_projects
  has_wiki               = var.has_wiki
  is_template            = var.is_template
  allow_merge_commit     = var.allow_merge_commit
  allow_squash_merge     = var.allow_squash_merge
  allow_rebase_merge     = var.allow_rebase_merge
  delete_branch_on_merge = var.delete_branch_on_merge
  auto_init              = true

  archived           = false
  archive_on_destroy = true

  vulnerability_alerts = var.vulnerability_alerts
}

resource "github_repository_file" "epo_files" {
  for_each = { for plugin_repo_file in var.plugin_repo_files : plugin_repo_file.file_path => plugin_repo_file }

  repository          = github_repository.repo.name
  branch              = var.default_branch
  file                = each.value.file_path
  content             = each.value.file_content
  overwrite_on_create = each.value.overwrite_on_create

  commit_message = "<value-removed-as-its-sensitive>"
  commit_author  = "<value-removed-as-its-sensitive>"
  commit_email   = "<value-removed-as-its-sensitive>"

  lifecycle {
    ignore_changes = [
      commit_email,
      commit_author,
      branch
    ]
  }

  depends_on = [
    github_branch_default.plugin_default_branch
  ]
}

# Variable var.plugin_repo_files has following value set

plugin_repo_files = [
    {
      file_path           = "README.md"
      file_content        = file("./files/readme.md")
      overwrite_on_create = true
    },
    {
      file_path           = "config.yaml"
      file_content        = file("./files/config.yaml")
      overwrite_on_create = false
    }
  ]

```

### Expected Behavior
On subsequent runs the `config.yaml` file should **not** get overwritten as it has overwrite_on_create' is set to 'false'

### Actual Behavior
When we run the plan again, the `github_repository_file` is overwriting the config.yaml file in the repository 

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. Update the config.yaml file in the new repository
3. Run `terraform plan` again

### References
- https://github.com/integrations/terraform-provider-github/pull/459

**Comment by jcudit** [comment]
Any change we can get more debug output?  Adding `TF_LOG=DEBUG` ahead of any run would produce helpful logs to debug this further.

**Comment by arthur-rock** [comment]
Hi @jcudit !
I have the same problem and I try to reproduce it with the flag `TF_LOG=DEBUG` and I hope to help you to solve it.

[tf_plan.txt](https://github.com/integrations/terraform-provider-github/files/7508567/tf_plan.txt)

**Comment by marianobntz-silohub** [comment]
same thing here... anything else you need?

**Comment by andlucasamos** [comment]
@parag-neve-db @marianobntz-silohub This looks like the intended behaviour to me. I think you want to add this to your `github_repository_file` resource. This way the file will be created but any changes to its content will be ignored.

```
  lifecycle {
    ignore_changes = [
      content
    ]
  }
```

**Comment by marianobntz-silohub** [comment]
You are right @parag-neve-db , adding that does the trick, when I update the content the plan is not updated. THANKS!
PS: it should be documented in the github-file in terraform so we know how to handle this case that I think is common? 😄

**Comment by henryxuteck** [comment]
I got the same error, or maybe i misunderstood what does "overwrite_on_create" really do. @jcudit 

I want to add a file to all terraform managed repos, but there is already a file with the exact name/content in a number of repos. 

Can I use "overwrite_on_create" to ignore the file creation for the repos that have the file already (but not the others), so that I can have the file in state and manage it via terraform if content changes going forward?

**Comment by andlucasamos** [comment]
> I got below error when doing the following task.
> 
> Error: [ERROR] Refusing to overwrite existing file. Configure `overwrite_on_create` to `true` to override.
> 
> I want to add a file to all terraform managed repos, but there is already a file with the exact name/content in a number of repos.
> 
> I planned to have `"overwrite_on_create" = false` to ignore the file creation for the repos that have the file already (but not the others), so that I can have the file in state and manage it via terraform if content changes going forward?
> 
> Or what does "overwrite_on_create" really do? @jcudit

IIUC `overwrite_on_create` does the following
- If set to true it will overwrite an existing file with the same name
- If set to false it will fail if there is an existing file with the same name.

**Comment by henryxuteck** [comment]
> > I got below error when doing the following task.
> > Error: [ERROR] Refusing to overwrite existing file. Configure `overwrite_on_create` to `true` to override.
> > I want to add a file to all terraform managed repos, but there is already a file with the exact name/content in a number of repos.
> > I planned to have `"overwrite_on_create" = false` to ignore the file creation for the repos that have the file already (but not the others), so that I can have the file in state and manage it via terraform if content changes going forward?
> > Or what does "overwrite_on_create" really do? @jcudit
> 
> IIUC `overwrite_on_create` does the following
> 
> * If set to true it will overwrite an existing file with the same name
> * If set to false it will fail if there is an existing file with the same name.

gotcha, thanks for the reply
