### ISSUE TITLE
resource github_repository: etag: DiffSuppressFunc is for suppressing differences

### ISSUE THREAD

**Issue by eduardchai** [integrations/terraform-provider-github#910]
Error with `github_repository` in v4.15.0.

```
Error: Internal validation of the provider failed! This is always a bug
with the provider itself, and not a user issue. Please report
this bug:

1 error occurred:
	* resource github_repository: etag: DiffSuppressFunc is for suppressing differences between config and state representation. There is no config for computed-only field, nothing to compare.
```

### Provider Version
v4.15

### Terraform Version
v0.13.5

### Affected Resource(s)
- github_repository

### Expected Behavior
Run without error

### Actual Behavior
```
Error: Internal validation of the provider failed! This is always a bug
with the provider itself, and not a user issue. Please report
this bug:

1 error occurred:
	* resource github_repository: etag: DiffSuppressFunc is for suppressing differences between config and state representation. There is no config for computed-only field, nothing to compare.
```

**Comment by creack** [comment]
Getting the same error with v1.0.7, reverting the github provider to v4.14 "fixed" the issue.

**Comment by james-callahan** [comment]
Looks like this was https://github.com/integrations/terraform-provider-github/pull/909

**Comment by viniciusps** [comment]
We are also facing the same issue here:

```
Error: Internal validation of the provider failed! This is always a bug
with the provider itself, and not a user issue. Please report
this bug:

1 error occurred:
	* resource github_repository: etag: DiffSuppressFunc is for suppressing differences between config and state representation. There is no config for computed-only field, nothing to compare.
```

TF version: 0.14.9
Github provider version: v4.15.0

**Comment by paulalex** [comment]
My builds have been failing for this since this morning as well.

**Comment by fatbasstard** [comment]
Same error here since this morning

**Comment by hazcod** [comment]
Same issue.

**Comment by ChristophShyper** [comment]
Please add 👍  instead of purring pointless comments. It's obvious it breaks for everybody that uses newest provider version.

**Comment by husain-aljamri** [comment]
I just though I might add this comment: I don't actually manage any github resources in my TF config. The only thing I'm using the Github provider for is the datasource `github_ip_ranges`, and I still get this error on every `terraform plan` run. This only showed up this morning, I didn't have this issue earlier this week.

**Comment by w0rmr1d3r** [comment]
It's happening with the provider on other versions:
```
    github = {
      source  = "integrations/github"
      version = "~> 4.3"
    }
 ```

**Comment by ChristophShyper** [comment]
> It's happening with the provider on other versions:
> 
> ```
>     github = {
>       source  = "integrations/github"
>       version = "~> 4.3"
>     }
> ```

Please check your `terraform init` output and see which exactly version is being used.
`"~> 4.3" will point to `4.15`.

**Comment by w0rmr1d3r** [comment]
You are right @ChristophShyper !
It's pointing to `4.15`. 
Sorry for generating any noise :shame-on-me:

**Comment by leighmhart** [comment]
same with 4.15 - pinning to 4.14 for now.
```
Error: Internal validation of the provider failed! This is always a bug
with the provider itself, and not a user issue. Please report
this bug:

1 error occurred:
	* resource github_repository: etag: DiffSuppressFunc is for suppressing differences between config and state representation. There is no config for computed-only field, nothing to compare.
	```

**Comment by kanekotic** [comment]
I have pinned to 4.14
```HCL
required_providers {
    github = {
      source  = "integrations/github"
      version = "4.14"
    }
  }
```
nevertheless i am sill havew the same issue in my CI.
```
│ Error: Internal validation of the provider failed! This is always a bug
│ with the provider itself, and not a user issue. Please report
│ this bug:
│ 
│ 1 error occurred:
│ 	* resource github_repository: etag: DiffSuppressFunc is for suppressing differences between config and state representation. There is no config for computed-only field, nothing to compare.
```
noticed also in the module resulution in init is bringing 4.15 from terraform/github
```
Initializing provider plugins...
- Finding hashicorp/aws versions matching "3.58.0"...
- Finding integrations/github versions matching "4.14.0"...
- Finding latest version of hashicorp/github...
- Installing hashicorp/aws v3.58.0...
- Installed hashicorp/aws v3.58.0 (signed by HashiCorp)
- Installing integrations/github v4.14.0...
- Installed integrations/github v4.14.0 (signed by a HashiCorp partner, key ID 38027F80D7FD5FB2)
- Installing hashicorp/github v4.15.0...
- Installed hashicorp/github v4.15.0 (signed by HashiCorp)
```
Any thoughts why this is happening?

**Comment by nhumphreys** [comment]
> I have pinned to 4.14
> 
> ```terraform
> required_providers {
>     github = {
>       source  = "integrations/github"
>       version = "4.14"
>     }
>   }
> ```
> 
> nevertheless i am sill havew the same issue in my CI.
> 
> ```
> │ Error: Internal validation of the provider failed! This is always a bug
> │ with the provider itself, and not a user issue. Please report
> │ this bug:
> │ 
> │ 1 error occurred:
> │ 	* resource github_repository: etag: DiffSuppressFunc is for suppressing differences between config and state representation. There is no config for computed-only field, nothing to compare.
> ```
> 
> noticed also in the provider resulution in init is bringing 4.15 from terraform/github
> 
> ```
> Initializing provider plugins...
> - Finding hashicorp/aws versions matching "3.58.0"...
> - Finding integrations/github versions matching "4.14.0"...
> - Finding latest version of hashicorp/github...
> - Installing hashicorp/aws v3.58.0...
> - Installed hashicorp/aws v3.58.0 (signed by HashiCorp)
> - Installing integrations/github v4.14.0...
> - Installed integrations/github v4.14.0 (signed by a HashiCorp partner, key ID 38027F80D7FD5FB2)
> - Installing hashicorp/github v4.15.0...
> - Installed hashicorp/github v4.15.0 (signed by HashiCorp)
> ```
> 
> Any thoughts why this is happening?

Hi @kanekotic We've had the same problem, and perhaps the cause is the same for you...

If you have references to the `github` provider in modules those modules may also need pinning to the `4.14` version.

For us we had to add the following to all (well most) sub module usage to ensure the right version is used everywhere we need it.

```
terraform {
  required_providers {
    github = {
      source  = "integrations/github"
      version = "4.14.0"
    }
  }
}
```

The Terraform documentation mentions in a note the following:

> Note: Only provider configurations are inherited by child modules, not provider source or version requirements. Each module must declare its own provider requirements. This is especially important for non-HashiCorp providers.


ref that helped our discovery: 
https://github.com/integrations/terraform-provider-github/issues/696#issuecomment-804414088
