### ISSUE TITLE
Support for github_codespaces_secret and github_codespaces_organization_secret

### ISSUE THREAD

**Issue by ashwin153** [integrations/terraform-provider-github#915]
Currently, the provider supports github_actions_secret and github_actions_organization_secret, but does not support the corresponding resources for Codespaces. Would it be possible to add support for this?

**Comment by leszczynskimikolaj** [comment]
bump, it's been a year since that issue. @jcudit any update on this one?

**Comment by KenSpur** [comment]
bump, would very much love this feature!

**Comment by kfcampbell** [comment]
It does look like [API support](https://docs.github.com/en/rest/codespaces/secrets?apiVersion=2022-11-28#create-or-update-a-secret-for-the-authenticated-user) exists. PRs are appreciated!

**Comment by KenSpur** [comment]
@kfcampbell

Started looking in to it! Had to get my head around Go and Terraform provider development first ^^.

Meanwhile, the Codespaces support on the 'go-github' client is getting there as well to fully implement these features.
[go-github/issues/2362](https://github.com/google/go-github/issues/2362)

**Comment by KenSpur** [comment]
@kfcampbell 

[go-github/releases/tag/v53.2.0](https://github.com/google/go-github/releases/tag/v53.2.0) just got released, does the updating of the version need to happen separately?

**Comment by kfcampbell** [comment]
This is now complete! Sorry @KenSpur I neglected to respond here. I much prefer doing the google/go-github update in its own PR for what it's worth.
