### ISSUE TITLE
Unable to set branch names/patterns when `custom_branch_policies` is `true`.

### ISSUE THREAD

**Issue by Omicron7** [integrations/terraform-provider-github#922]
### Affected Resource(s)
- github_repository_environment

### Terraform Configuration Files
```hcl
resource "github_repository_environment" "environment" {
  repository  = "repository_name"
  environment = "testing"

  deployment_branch_policy {
    protected_branches     = false
    custom_branch_policies = true
  }
}
```
In the GitHub console, when `custom_branch_policies` is set to `true`, it allows setting one or more Branch names/patterns to match against. It doesn't seem like this is possible in Terraform. I'm unable to find any other GitHub resource that would allow managing that list per environment. Am I missing something?

**Comment by bishwash-delphix** [comment]
I was looking for the same feature... is it possible to "Add deployment branch rule"?

**Comment by gilfthde** [comment]
Same for me. I also need to set a branch name/pattern and don't now how to do it.

**Comment by figadore** [comment]
Agree, seems like there should be a way to specify the patterns that can deploy to the environment. Maybe something like

```hcl
resource "github_repository_environment" "default" {
  repository  = var.repo
  environment = "${var.env_id}"
  reviewers {
    teams = var.reviewers_team
    users = []
  }
  deployment_branch_policy {
    protected_branches          = false
    custom_branch_policies = true
    custom_branch_regex = ["main"]
  }
}
```
?

It doesn't look like the go-github package supports this at the moment 
https://github.com/google/go-github/blob/7add3a89d10dbdcbbfab71036aa9c12e5ee997c8/github/repos_environments.go#L42

**Comment by StephenWithPH** [comment]
I added a comment in GitHub's product discussions to try to elevate this to their PM team: https://github.com/github-community/community/discussions/14190#discussioncomment-3065590

**Comment by StephenWithPH** [comment]
https://github.com/orgs/community/discussions/14190#discussioncomment-3931426 points to https://docs.github.com/en/rest/deployments/branch-policies#create-a-deployment-branch-policy, which suggests that there is now an API endpoint for this.

**Comment by kfcampbell** [comment]
If that's true, that's great news. I'd be happy to review/test/merge a PR to cover this behavior!

**Comment by mBlomsterberg** [comment]
Would really like to see this implemented. Having a custom_branch_policies attribute feels a bit misleading since it's only a bool.

**Comment by romikoops** [comment]
Really disappointing that we still do not have it. If we automate something, it should have 100% automation, not 99 and etc.

**Comment by GMartinez-Sisti** [comment]
> Really disappointing that we still do not have it. If we automate something, it should have 100% automation, not 99 and etc.

@romikoops this is an on going project, as is the Github API, something will always be missing. This issue is "Up for grabs" if you want to contribute.

On the other hand, turn it around, it's great that we have 99% automation for Github using terraform 🥳 .

**Comment by ilmax** [comment]
Support in the go-github SDK has been merged recently [here](https://github.com/google/go-github/pull/2621), unfortunately is not part of the latest version of the SDK (49.1.0 at the moment) so we may probably wait until that's released.

Was also thinking if this should end up in a separate resource similar to the following:

```tf
resource "github_repository_environment_deployment_branch_policy" "default" {
  repository  = var.repo
  environment = "${var.env_id}"
  pattern = "main"
}
```
rather than the suggested 

```tf
resource "github_repository_environment" "default" {
  repository  = var.repo
  environment = "${var.env_id}"
  reviewers {
    teams = var.reviewers_team
    users = []
  }
  deployment_branch_policy {
    protected_branches          = false
    custom_branch_policies = true
    custom_branch_regex = ["main"]
  }
}
```
Due to the fact that's exposed via a different api than the repository environment.

**Comment by kfcampbell** [comment]
Thank you @GMartinez-Sisti and @ilmax! 

@ilmax I like your suggestion of the separate resource!

**Comment by ilmax** [comment]
@kfcampbell then I may give it a try as soon as the afk is released.

Disclaimer: I am not really expert in go though but with copy paste and some help from the PR review I should be able to land this

**Comment by justin-kidman-axomic** [comment]
Looks like the endpoint went out in v50.0.0 of the SDK

**Comment by ilmax** [comment]
Yes, wanted to write the same. @kfcampbell any objections about updating to v50?

**Comment by kfcampbell** [comment]
@ilmax My vote would be to do so in a separate PR than the feature one. I have no reservations about updating to the latest version though!
