### ISSUE TITLE
Error when `owner` isn't specified and using GitHub App authentication

### ISSUE THREAD

**Issue by dortort** [integrations/terraform-provider-github#929]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
```
Terraform v0.13.2
+ provider registry.terraform.io/integrations/github v4.16.0
```

### Affected Resource(s)
- provider

### Terraform Configuration Files
```hcl
provider "github" {
  app_auth {
    id              = var.github_app_id
    installation_id = var.github_app_installation_id
    pem_file        = var.github_app_pem_file
  }
}
```

### Debug Output
https://gist.github.com/dortort/010645cc4b3762fbccd12fb2dc7800a9

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
No error should occur as long as only [GitHub App accessible resources](https://docs.github.com/en/rest/overview/endpoints-available-for-github-apps) are used.

### Actual Behavior
Produced error:
```
Error: GET https://api.github.com/user: 403 Resource not accessible by integration []
```

### Steps to Reproduce
1. Create config with `github` provider and any resource or data bloc
2. Provide GitHub App auth details for provider and do _not_ specify `owner`
3. Run `terraform apply`

### Important Factoids
Possibly relevant: the GitHub App whose credentials were provided is _not_ configured to "Request user authorization (OAuth) during installation"
![image](https://user-images.githubusercontent.com/1169721/136274450-9ba2606b-6848-4862-b8ec-f2ebf02533c9.png)

Simply adding the [optional `owner` argument](https://registry.terraform.io/providers/integrations/github/latest/docs#owner) resolved the issue:
```hcl
provider "github" {
  owner = "MyOrg"
  app_auth {
    id              = var.github_app_id
    installation_id = var.github_app_installation_id
    pem_file        = var.github_app_pem_file
  }
}
```

**Comment by tekumara** [comment]
Adding `owner` when using a github app resolved this for me.
