### ISSUE TITLE
github_repository needs to not fail if repository doesn't exist

### ISSUE THREAD

**Issue by ronmpatel** [integrations/terraform-provider-github#933]
**Affected Resource(s)**
github_repository

For a new repository the following will fail the entire plan/apply. It would be nice if we return null so that we could use that to conditionally check if repository exist or not.

Our use case is to create the repository only if does not exist.

```
Terraform Configuration Files
data "github_repository" "existing_repository" {
  full_name   = "${var.github_org}/${var.repo}"
}
```
Error Output
GET https://api.github.com/repos/<org>/<repo> 404 Not Found []

Reference
[We have this for branch here](https://github.com/integrations/terraform-provider-github/issues/747)

**Comment by GauravJain98** [comment]
This is so different from the normal terraform standard! I have no clue why they did this actively!!!

**Comment by GauravJain98** [comment]
For anyone coming later with same issue i think this should help you 
https://developer.hashicorp.com/terraform/language/expressions/custom-conditions#usage
if i dont update then it works

**Comment by GauravJain98** [comment]
```terraform
data "github_repository" "repository" {
  name = coalesce(var.application.github_repo_name, var.name)
  lifecycle {
    postcondition {
      condition     = self.full_name != null
      error_message = "Repository does not exist for ${coalesce(var.application.github_repo_name, var.name)}"
    }
  }
}
```
