### ISSUE TITLE
Import github_repository_autolink_reference by key

### ISSUE THREAD

**Issue by entropitor** [integrations/terraform-provider-github#947]
### Affected Resource(s)
Please list the resources as a list, for example:
- github_repository_autolink_reference

### Feature request

Allow importing an autolink reference by key-prefix instead of only by id
That's gonna make it much easier to import... Now the API must be called to get the id while everyone will have the key-prefix probably

### References
- https://github.com/integrations/terraform-provider-github/pull/924

**Comment by marc-sensenich** [comment]
https://github.com/integrations/terraform-provider-github/pull/1218 has been opened to address this enhancement
