### ISSUE TITLE
Doc for repository_webhook fix-up

### ISSUE THREAD

**Issue by demarsdouglas** [integrations/terraform-provider-github#948]
Hello,

While working with the `repository_webhook` resource I found that giving it a value of `application/json` was not setting the correct content type. Upon reading the docs more carefully, I found out it wants a value of `json` instead. While this is questionable itself, I went ahead and updated the documentation so it follows the format for other provider docs when it comes to block configuration inside resource, as well as clearing up the wording around the `content_type` field and what values it can accept.

I think the `configuration` block isn't clear as is written today in the doc, also missing which values are required and optional, so I'm looking to get a maintainer to look at this change. PR below.

https://github.com/integrations/terraform-provider-github/pull/944

**Comment by jcudit** [comment]
@demarsdouglas can you confirm if #944 shipping has solved this issue?
