### ISSUE TITLE
github_issue or github_project_issue

### ISSUE THREAD

**Issue by farrukh90** [integrations/terraform-provider-github#958]
Hi, 

This is more like a suggestion. Can we get github_issue or github_repository_issue? It would help us create the issue as needed. As of now, I am using "github_project_card". But it is restricted. So having an issue type would be better so we can put it into a sprint

**Comment by ewilde** [comment]
I also have this requirement, @jcudit I see you've labelled it as an `enhancement`. I'll start working on adding this new resource https://github.com/ewilde/terraform-provider-github/tree/ewilde-github_issue and reference this issue as I progress.

**Comment by farrukh90** [comment]
Hi, Are we making any progress on this?

**Comment by ewilde** [comment]
@farrukh90 https://github.com/integrations/terraform-provider-github/pull/1047
