### ISSUE TITLE
Deprecate and then remove has_downloads attribute on github_repository

### ISSUE THREAD

**Issue by jtgrohn** [integrations/terraform-provider-github#966]
### Affected Resource(s)
- github_repository

I think `github_repository` should not have a `has_downloads` attribute since it appears to be a deprecated property. The API still returns it, but it does not allow the value to be changed `https://docs.github.com/en/rest/reference/repos#update-a-repository`. I suspect the backend just throws that value out. Since it appears it isn't used, it should be deprecated and/or removed from the resource since its presence is misleading. I realize full removal is a breaking change, so maybe deprecation is the way to go for now?

I cannot find an announcement or release notes about this property to fully confirm.

**Comment by kfcampbell** [comment]
@jtgrohn I've searched around internally a bit in both code and docs/communication, and I can't find anything about this changing recently either. 

I'm not quite convinced that the backend throws the value out; do you think you could come up with a repro case? Looking at the docs you linked, I see that the API accepts the value when [creating a repo](https://docs.github.com/en/rest/reference/repos#create-a-repository-for-the-authenticated-user) for an authenticated user, and returns it only after that. Perhaps the setting can only be set at creation time, and never altered?

**Comment by Centzilius** [comment]
Maybe its a left over from this deprecation (from 11 years ago...) https://github.blog/2012-12-12-goodbye-uploads/

**Comment by GMZwinge** [comment]
Thanks to @Centzilius, I started the discussion in [GitHub](https://github.com/orgs/community/discussions/102145).

**Comment by yktakaha4** [comment]
We use Terraform in our day-to-day operations, and we noticed that many developers were creating repositories with `has_downloads` set to true even though it was not necessary. As a result, we enforced `has_downloads = false` .

Based on comments in the issue, we initially expected that this would require configurations such as `ignore_changes` . However, since the internal state of the repository has been updated, the backend may no longer be discarding this value.

>  it does not allow the value to be changed https://docs.github.com/en/rest/reference/repos#update-a-repository. I suspect the backend just throws that value out.
