### ISSUE TITLE
restrict_dismissals doesn't apply

### ISSUE THREAD

**Issue by bmrec** [integrations/terraform-provider-github#973]
Hi. When I run `terraform apply` terraform tries to change this:
```
~ required_pull_request_reviews {
          - restrict_dismissals             = true -> null
```
After applying, terraform offers to apply it again.

### Terraform Version
Terraform v1.0.10
on linux_amd64
+ provider registry.terraform.io/hashicorp/github v4.12.0
+ provider registry.terraform.io/integrations/github v4.17.0

### Affected Resource(s)
resource "github_branch_protection" "repos"

### Expected Behavior
Apply the first time.

### Actual Behavior
Doesn't apply.

**Comment by thekbb** [comment]
This is still an issue with terraform `v1.1.2` in provider version `v4.19.0`

**Comment by srosell-uz** [comment]
I can confirm that this still happens with terraform `~>1.2` and provider version `v4.28.0`. There is any ETA for solving this? 🤔 
thanks 🙇

**Comment by ColinHarrington** [comment]
We still experienced this issue at `v5.28.1` It appears that the `restrict_dismissals` which is an optional field, is populated implicitly when you specify dismissal restrictions via other properties.  The provider could have handled this for us, but specifying `restrict_dismissals = true` prevented the persistent plan changes.
