### ISSUE TITLE
add a `required` option in `data "github_repository_file"`

### ISSUE THREAD

**Issue by nikophil** [integrations/terraform-provider-github#982]
Hi there,

is there a way to get a `required` option in the data `github_repository_file`?

Sometimes we may want to do some action when a file has changed, so I'd like to use `data "github_repository_file"` but if it does not exist at the first step, the data will create a 404 error. It would be nice to tell this data it should not fail in this case.

WDYT?

thanks for you work :)

**Comment by mcintyre321** [comment]
I too would like this. I am trying to model a gitops workflow. I need to test if a file exists on master, and if the content exist already on `main`, set the count for my branch, file and PR to 0. 

If it does not exist then I can raise a PR.

I cannot do this right now as I get 404 if the file does not exist
