### ISSUE TITLE
404 when trying to create github_branch_protection_v3 for newly created github_repository resource

### ISSUE THREAD

**Issue by dil-kpogany** [integrations/terraform-provider-github#983]
Hi there,

I'm trying to automate GitHub repository management with Terraform. My goal would be to create new repositories and set their permissions and branch protection rules via Terraform. Terraform plan runs perfectly, but when I try to do a terraform apply, the process fails with 404, when trying to create the branch protection rule with github_branch_protection_v3 at first. It creates the repository though. When re-trying terraform apply, it finishes successfully. I suspect that the github_repository resource still has some processes running in the background, when the github_branch_protection_v3 tries to access the resource that is not yet there. Please let me know if I missed to add something.
The terraform code looks like as follows:

```
terraform {
  required_providers {
    github = {
      source = "integrations/github"
    }
  }
}

locals {
  team_permissions = { for team_perm in var.team_permissions : replace(team_perm.name, " ", "_") => {
              name = team_perm.name
              perm = team_perm.permission
          }
    }
}

resource "github_repository" "repo" {
  name                   = var.repository_name
  description            = var.description
  visibility             = "internal"
  allow_squash_merge     = true
  delete_branch_on_merge = true
  auto_init              = true
}

resource "github_team_repository" "team_perms" {
  depends_on         = [ github_repository.repo ]
  for_each           = local.team_permissions
  repository         = var.repository_name
  team_id            = each.value.name
  permission         = each.value.perm
}

resource "github_branch_protection_v3" "branch_rule" {
  count          = var.enforce_branch_policies == true ? 1 : 0
  repository     = var.repository_name
  branch         = "master"
  enforce_admins = true
  depends_on     = [ github_repository.repo ]

  required_pull_request_reviews {
    dismiss_stale_reviews = true
    required_approving_review_count = 1
  }
}

```

**Variables passed in:**
```
variable "repository_name" {
  type = string
}

variable "description" {
  type = string
}

variable "enforce_branch_policies" {
    type = bool
    default = true
}

variable "team_permissions" {
   type = list(object({
       name = string,
       permission = string
   }))
}
```
**Example input values:**

```
    name                                     = "testrepo"
    description                            = "testrepo repository"
    github_skip_branch_policies = false
    github_team_permissions     = [
        { name = "security-team", permission = "pull" },                
        { name = "test-team1", permission = "pull" },
        { name = test-team2", permission = "admin" },
        { name = "owner-team", permission = "admin" }
    ]
```
 
**Output:**
The problematic part is in a module in the actual implementation, but I listed all necessary information for the reproduction.
```
│ Error: PUT https://api.github.com/repos/DiligentCorp/testrepo/branches/master/protection: 404 Branch not found []
│ 
│   with module.github["testrepo"].github_branch_protection_v3.branch_rule[0],
│   on modules/github/main.tf line 34, in resource "github_branch_protection_v3" "branch_rule":
│   34: resource "github_branch_protection_v3" "branch_rule" {
```

**Affected Resource(s)**
- github_branch_protection_v3 
- github_repository

**Steps to Reproduce**
1. Add a new repository with github_repository
2. Create team permissions with github_team_repository
3. Create branch protection rules for the newly created repo with github_branch_protection_v3
4. terraform apply

**Terraform version:**
- Terraform v1.0.3
- provider registry.terraform.io/integrations/github v4.18.0

**Comment by jtgrohn** [comment]
The error says the `master` branch is not found. Is the default branch actually `main`?

**Comment by dil-kpogany** [comment]
Thanks, we changed the structure and used other resources, so we managed to tackle the issue that way.
