### ISSUE TITLE
[feature request] Set Actions Permissions to "Disable Actions"

### ISSUE THREAD

**Issue by lopopolo** [integrations/terraform-provider-github#984]
### Terraform Version

```console
$ terraform -v
Terraform v1.0.11
on darwin_amd64
```

### Affected Resource(s)
Please list the resources as a list, for example:
- `github_repository`

### Feature Request

I would like to be able to set this setting for several repositories (mostly forks) in my organization:

<img width="771" alt="Screen Shot 2021-11-23 at 11 03 17 AM" src="https://user-images.githubusercontent.com/860434/143087745-542e4b44-77ef-4f42-9f26-9a9256fa0c12.png">

This setting can be found on `https://github.com/$org/$repo/settings/actions`.

**Comment by lubo** [comment]
`github_actions_repository_permissions` resource type should probably be added. It would be nice to also be able to set the default workflow permissions.

**Comment by StephenWithPH** [comment]
@lubo I made https://github.com/integrations/terraform-provider-github/issues/1008 to clearly state the need.

**Comment by nfcopier** [comment]
This issue was resolved with #1008.
https://registry.terraform.io/providers/integrations/github/latest/docs/resources/actions_repository_permissions#enabled
