### ISSUE TITLE
Add support for configuring checks to branch protection

### ISSUE THREAD

**Issue by jtgrohn** [integrations/terraform-provider-github#985]
### Affected Resource(s)
Please list the resources as a list, for example:
- github_branch_protection
- github_branch_protection_v3

### Description

The [GitHub API](https://docs.github.com/en/rest/reference/repos#update-branch-protection) supports setting up `checks` as well as `contexts` for branch protection. `checks` provide a few more configuration options (like enforcing that a check is set by a specific app)

![image](https://user-images.githubusercontent.com/14808144/143277221-e84b5e68-7105-4fa9-b5b0-56b6bbcc5391.png)

Could you add support to the `github_branch_protection` and `github_branch_protection_v3` resources to configure `checks`?  Currently they only support `contexts`

Thanks

**Comment by k24dizzle** [comment]
I took a look at this and I believe `go-github` doesn't support this field yet either. So we'd have to wait for them to implement it first before we can add this to terraform provider. Created an issue in the `go-github` repo for this here: 
https://github.com/google/go-github/issues/2274

**Comment by zacharymelancon** [comment]
https://github.com/google/go-github/pull/2276 @k24dizzle It looks like checks was add to go-github since your last comment.

**Comment by k24dizzle** [comment]
Yeah so this is where I left off with this: https://github.com/integrations/terraform-provider-github/pull/1051
Now that it is in go-github, we could pick this work up again

**Comment by TheQueenIsDead** [comment]
I have tried to kick a PR off to support this in #1415, though it looks like Github does some interesting things in the back-end (Returning a list of contexts when only checks were provided). If anyone with more experience developing plugins would like to chime in / extend this work I'd be more than happy for the help :pray: 

Just want to be able to define protections again :smiling_face_with_tear:
