### ISSUE TITLE
Allow custom role names for permission argument

### ISSUE THREAD

**Issue by emtunc** [integrations/terraform-provider-github#988]
As per https://docs.github.com/en/rest/reference/teams#add-or-update-team-repository-permissions - custom role names (https://docs.github.com/en/enterprise-cloud@latest/organizations/managing-peoples-access-to-your-organization-with-roles/managing-custom-repository-roles-for-an-organization) are now permitted when adding/updating permissions for teams.

The Terraform provider still only expects _pull, triage, push, maintain, or admin_

For the avoidance of doubt, I have tested setting permissions with a custom role name (it seems to be case sensitive) via the GH API and it works.

Would someone be so kind as to allow string values for the permission argument please?

**Comment by joshuahancox** [comment]
I raised a PR here, based on another - could anyone help in getting this reviewed/merged? 😃 

https://github.com/integrations/terraform-provider-github/pull/1113

**Comment by joshuahancox** [comment]
@kfcampbell could we merge/release this?

**Comment by grant-adarga** [comment]
Both of the linked PRs are ready to go :shipit: (sorry about the delay in updating mine @joshuahancox)
