### ISSUE TITLE
v4.18.1 is not available on the registry

### ISSUE THREAD

**Issue by shogo82148** [integrations/terraform-provider-github#989]
[v4.18.1](https://github.com/integrations/terraform-provider-github/releases/tag/v4.18.1) is released on the GitHub Releases, however [the latest version on the registry](https://registry.terraform.io/providers/integrations/github/latest) still points v4.18.0.

![image](https://user-images.githubusercontent.com/1157344/143668100-be924174-72f7-4a35-85c7-b10afb5b72fa.png)

### Terraform Version

```
Terraform v1.0.11
on darwin_amd64
+ provider registry.terraform.io/hashicorp/github v4.1.0
+ provider registry.terraform.io/integrations/github v4.18.0
```

### Terraform Configuration Files

```hcl
terraform {
  required_version = ">= 1.0"
  required_providers {
    github = {
      source = "integrations/github"
      version = "~> 4.18.1"
    }
  }
}
```

### Expected Behavior

`terraform init --upgrade` should succeed.

### Actual Behavior

```
% terraform init --upgrade

Initializing the backend...

Initializing provider plugins...
- Finding integrations/github versions matching "~> 4.18.1"...
╷
│ Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider integrations/github: no available releases match the given constraints ~> 4.18.1
╵
```

### Steps to Reproduce

1. bump the provider version to v4.18.1.
2. run `terraform init --upgrade`

### References

I have the problem on branch protection rules that issued as https://github.com/integrations/terraform-provider-github/issues/908.
The CHANGELOG says that it is fixed on https://github.com/integrations/terraform-provider-github/pull/914 and v4.18.1 includes the fix.

https://github.com/integrations/terraform-provider-github/blob/01d92de30bd7eca8af0a9e2013e9eff447ecadea/CHANGELOG.md?plain=1#L1-L7

> ## 4.18.1 (Nov 22, 2021)
> 
> BUG FIXES:
> 
> - Add length requirement to `topics` option for `github_repository` ([[#951](https://github.com/integrations/terraform-provider-github/pull/951)])
> - Add pagination to `selected_repositories` option for `github_actions_runner_group` ([[#970](https://github.com/integrations/terraform-provider-github/pull/970)])
> - Add handling for new `node_id` format introduced to the GitHub GraphQL API (`github_repository`) ([[#914](https://github.com/integrations/terraform-provider-github/pull/914)])
> 

This is why I want to use v4.18.1.
Thanks.

**Comment by bateller** [comment]
I've had terraform registry issues in the past (providers not updating). Just in case, I went ahead and opened a ticket with Hashicorp too. I'll update with any response on their end.

**Comment by petracvv** [comment]
FYI it looks like the `v4.18.2` release they tagged on GitHub yesterday did get pushed to the registry.

**Comment by shogo82148** [comment]
Thank you for your information.
That's right. The latest version on the registry now points `v4.18.2`.

![image](https://user-images.githubusercontent.com/1157344/144427855-a854d0a1-6a68-4c31-bdc7-c8dac1542576.png)

and v4.18.1 is also available. (why...?)

- https://registry.terraform.io/providers/integrations/github/4.18.1

I'm going to close the issue, because it looks a terraform registry issue, and I get the latest version now.
Thanks again!

**Comment by jcudit** [comment]
🙇🏾 for raising this and glad it has auto-resolved.
