### ISSUE TITLE
Improvement - Operability - Logging - At least one permission expected from permissions map

### ISSUE THREAD

**Issue by njgibbon** [integrations/terraform-provider-github#992]
Hello,

I've recently had a problem where a terraform plan could not complete (failing with errors - see logs / output).

(When increasing log verbosity)
## Logs
```
2021/11/24 15:31:41 [ERROR] eval: *terraform.EvalRefresh, err: At least one permission expected from permissions map.
2021/11/24 15:31:41 [ERROR] eval: *terraform.EvalSequence, err: At least one permission expected from permissions map.
```

## CLI Output
```
Error: At least one permission expected from permissions map.

# x6
```

## Root cause
The root cause of the problem is where terraform is managing the team permissions on a repository and a permission that should exist has been removed outside of terraform.

I managed to look around with API calls and scripts and so on to ultimately find where the issue lay.

So the error is a valid error. No complaints about that.

## Minor Ops feature request
But I think that it would be good if you could somehow log the affected repository as well as the above output. This would massively help operators who are debugging this problem. It is currently very difficult to find where to fix when this error is output.

The error occurs here in `util_permissions.go`:
* https://github.com/integrations/terraform-provider-github/blob/main/github/util_permissions.go

`getRepoPermission` seems to be a pure function that find if all `permissions` given are false.

But it would be good if somewhere up the stack that another log could be made with the repo name where this function has returned an error further down.

## Somewhat related issue
* https://github.com/integrations/terraform-provider-github/issues/131

**Comment by augustingombault** [comment]
👋  I have the same issue when refreshing on ~250 github_team_repository items without any changes on my code.

**Comment by augustingombault** [comment]
🥳  I don't have the error anymore since today. I think it must have been an error in the API on the Github side since I haven't changed the github provider version since. What do you think about it?

**Comment by vin01** [comment]
I am also no longer encountering this error. It was occurring pretty consistently towards end of November and first couple of weeks in December. Most likely an API issue on Github's end.

**Comment by kfcampbell** [comment]
Closing for now with the understanding that it was an API error. If it crops up again, we can open a new issue and link it to this one.
