### ISSUE TITLE
Removing repo team resource issue for the team which has assigned the security manager role

### ISSUE THREAD

**Issue by ViacheslavKudinov** [integrations/terraform-provider-github#997]
Hi there,
we are experinsing issue when try to remove resource `teams_permissions` for team which has on Enterprise org level  `security manager role`. 

### Terraform Version
Terraform v1.0.11

- integrations/github 4.18.2

### Affected Resource(s)
- github_team_repository

### Terraform Configuration Files
```hcl
variable "teams_permissions" {
  teams_permissions = {
    "${github_team.SOME_TEAM.id}"                                                       = "admin" # Line witch wanna be deleted 
    "${data.terraform_remote_state.OTHER_TEAM.outputs.team_id}" = "pull"
  }
}

locals {
  default_team_permission = {
    "${data.terraform_remote_state.OTHER_TEAM.outputs.team_id}" = "push"
  }
  teams_permissions  = length(var.teams_permissions) != 0 ? var.teams_permissions : local.default_team_permission
}

resource "github_team_repository" "this" {
  for_each = local.teams_permissions

  repository   = github_repository.this.name
  team_id      = each.key
  permission = each.value
}
```

### Expected Behavior
Resource was successfully deleted 

### Actual Behavior
Error: DELETE https://api.github.com/organizations/CENSORED/team/CENSORED/repos/CENSORED/maven-microservice-workflow: 403 You cannot remove repositories from a security manager team. []

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
Team which was set as admin via "github_team_repository" at the same time has assigned `security manager role` on our GitHub org.

**Comment by rngtng** [comment]
Same problem here. Did you found any solution so far?

**Comment by robert-spring** [comment]
so from what i found no one can delete a team from a repo that has the "security manager" role.  you need to remove them from the security managers in the org settings, do what you have to, then add them back.

**Comment by devopsrick** [comment]
This issue is definitely still a bug. The provider should at least handle the error that it cannot be removed and move on gracefully.
